- monkey/monkey_island/cc/ui/src/components/map/MapOptions.js
- monkey/monkey_island/cc/ui/src/components/pages/MapPage.js
- monkey/monkey_island/cc/ui/src/components/reactive-graph/ReactiveGraph.js
- monkey/monkey_island/cc/ui/src/components/types/MapNode.tsx
Fixes part of #2334
Update ReactiveGraph.js to draw the graph from `MapNode`s
> Tested by running the UI. The map is using dummy MapNode data.
> ![Screen Shot 2022-10-18 at 9 16 14 AM](https://user-images.githubusercontent.com/11077625/196440159-5110a7e9-65fe-4486-baa1-35249ebf99df.jpg)
> 2334 draw the graph

- monkey/monkey_island/cc/ui/src/components/map/MapPageWrapper.tsx
- monkey/monkey_island/cc/ui/src/components/map/preview-pane/PreviewPane.js
- monkey/monkey_island/cc/ui/src/components/types/MapNode.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/LogDownloadButtons.tsx
> Updated agent log download URL

- monkey/monkey_island/cc/ui/src/components/map/MapPageWrapper.tsx
- monkey/monkey_island/cc/ui/src/components/map/preview-pane/NodePreviewPane.tsx
Fixes #2334 
> Tested by running the agent multiple times, downloading logs,checking the order of sort
> UI: Fix log download in the map

- monkey/monkey_island/cc/ui/src/components/IslandHttpClient.tsx
- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/AttackSection.tsx
- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/BreachSection.tsx
- monkey/monkey_island/cc/ui/src/components/report-components/security/BreachedServers.tsx
Adds three missing endpoints to the `APIEndpoint`:
1. `/api/telemetry`
2. `/api/exploitatons/manual`
3. `/api/exploitations/monkey`
> Tested by building and running Monkey Island
> Adds missing endpoints in the UI

- monkey/monkey_island/cc/ui/src/styles/App.css
Fixes alignment of sidenav arrows and manual run clipboard icon
> UI: Fix alignment of sidenav arrows and manual run clipboard copy

- monkey/infection_monkey/monkey.py
Fixes depth4 blackbox tests by separating the setup of agent event forwarder and subscription of events in the agent.
> Tested by running Depth4 black box tests
> Fix order when setting up agent event forwarder and subscribing events

- monkey/monkey_island/cc/ui/src/components/map/preview-pane/NodePreviewPane.tsx
- monkey/monkey_island/cc/ui/src/components/types/MapNode.tsx
Fixes #2495 .
> Tested by running the UI and check an unknown system
> 2495 fix unknown node os

- envs/monkey_zoo/terraform/firewalls.tf
- envs/monkey_zoo/terraform/monkey_zoo.tf
- envs/monkey_zoo/terraform/templates.tf
> 2372 terraform instance resources

- monkey/monkey_island/cc/ui/src/components/report-components/credentialParsing.js
Fixes a part of #2288 
> Tested by running the agent and checking the report in the UI
(ignore the "???"s, I replaced some stuff which was causing the report to crash due to telemetry changes)
> Fix list inconsistency in security report

- docs/content/setup/aws.md
- docs/content/usage/integrations/aws-run-on-ec2-machine.md
Fixes #2492
> Tested by running docs manually, checking that hte links are valid
> Docs: Small fixups related to running agents in AWS

- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/AttackSection.tsx
Fixes a part of #2496 
> Tested by checking the ransomware report with (1) a local run, (2) dummy events/agents/machines data
> Use events in ransomware report

- monkey/monkey_island/cc/ui/src/components/ui-components/EventsTable.js
Fixes a part of #2501
> There is duplication which needs to be refactored
> Tested by running the Island with different dummy events
> Use agent events in events table

- monkey/monkey_island/cc/ui/src/components/ui-components/EventsTable.js
Fixes part of #2501 .
> Tested by locally
https://user-images.githubusercontent.com/15820737/199292213-8dfbd2f5-8489-4a21-bb8a-ec83cd57afa8.mov
> UI: Add LoadingIcon to EventsTable

- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/AttackSection.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/EventsTable.js
- monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx
> 2501 fix UI code duplication

- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/services/reporting/report.py
> Remove aws_instance_id from report generation

- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx
- monkey/tests/unit_tests/monkey_island/cc/services/reporting/test_report.py
> 2507 refactor report manual monkeys UI

- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js
- monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx
Fixes #2507
> Tested by running the Island and checking the report with dummy data
> Refactor tunnel issue in UI

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/utils/commands.py
- monkey/tests/unit_tests/infection_monkey/utils/test_commands.py
Fixes #2530 
**Still needs to be tested!**
> Pass parent Agent's ID to child agents

- monkey/monkey_island/cc/repository/mongo_agent_event_repository.py
Fixes #2545.
Request timing on develop:
No. of events: 5573
Generating report:
Cached report:
Request timings on this branch:
No. of events: 7343
Generating report:
Cached report:
> Island: Skip encryption/decryption on a whitelist events type

- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js
> Malformed issues in report

- monkey/monkey_island/cc/agent_event_handlers/__init__.py
- monkey/monkey_island/cc/agent_event_handlers/update_machine_hostname.py
- monkey/monkey_island/cc/setup/agent_event_handlers.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_update_machine_hostname.py
Fixes a part of #2569 
> UTs pass
> Add hostname discovery event handler

- envs/monkey_zoo/docs/zoo_network.md
- monkey/common/network/network_range.py
- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/ui/src/components/report-components/security/issues/CrossSegmentIssue.js
Fixes segmentation report bugs
> Tested by setting up segmentation tests
> Segmentation report fix

- monkey/tests/unit_tests/common/event_queue/test_pypubsub_agent_event_queue.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_network_model_update_facade.py
> UT: Rename TestEvent to FalseEvent

- pyproject.toml
> Project: Add filterwarnings for flask's propagate_exceptions deprecation

- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/monkey.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/master/test_automated_master.py
Mitigates  #2596
And adds logging
> Tested by running it on the zoo
> Fix cleanup bugs

- monkey/infection_monkey/exploit/sshexec.py
Fixes #2589 
> AppImage EtE tests pass
> Don't use ssh-agent in paramiko for SSH exploiter

- monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/PropagationConfig.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/ReformatHook.js
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/propagation.js
Fixes #2585.
https://user-images.githubusercontent.com/15820737/203317004-e29453fc-5bf2-4e6a-be51-4ae683614106.mov
> 2585 fix max scan depth UI value

- monkey/common/types.py
- monkey/infection_monkey/i_puppet/__init__.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/i_puppet/plugin_type.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/puppet/plugin_registry.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
- vulture_allowlist.py
Addresses part of  #2579
Improves code in `http_island_api_client.py`
> Tested by running the agent, making sure that UT's don't break
> 2579 fetch plugins

- monkey/monkey_island/cc/resources/security_report.py
- monkey/monkey_island/cc/services/infection_lifecycle.py
- monkey/monkey_island/cc/services/reporting/report.py
- monkey/tests/unit_tests/monkey_island/cc/services/reporting/test_report.py
> Add `ReportService.update_report`

- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
Updates the security report to point the user to the correct configuration sections if no machines were exploited.
> Update security report with accurate configuration information

- monkey/monkey_island/cc/services/authentication_service.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_authentication_service.py
Fixes #2584.
https://user-images.githubusercontent.com/15820737/203600318-f0615cdc-aa00-413f-8f6f-ce674926c19d.mov
> Publish event topic when registering a new user

- monkey/monkey_island/cc/services/reporting/issue_processing/exploit_processing/exploiter_report_info.py
- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js
- monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx
Fixes #2588 
> Tested by on GCP, see screenshot
> Use machine ID for machine recommendations in security report

- envs/monkey_zoo/docs/zoo_network.md
- envs/monkey_zoo/terraform/firewalls.tf
Fixes part of #2597 .
> Tested by  running depth 3 tests
https://github.com/guardicore/monkey/issues/2597#issuecomment-1326325168
> 2597 add firewall rule to speed up depth3

- monkey/infection_monkey/island_api_client/http_client.py
- monkey/infection_monkey/network/relay/sockets_pipe.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
> 2613 fix tunneling

- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/ui/src/components/pages/ReportPage.js
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx
- monkey/tests/unit_tests/monkey_island/cc/services/reporting/test_report.py
Fixes #2600 
https://user-images.githubusercontent.com/44770317/204231467-6c1d29bc-ae19-4b7c-8188-817d199a3b3a.mp4
> Security report crash bugfix

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/event_queue/i_island_event_queue.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/monkey_island/cc/resources/agent_heartbeat.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_heartbeat.py
- vulture_allowlist.py
> Add AgentHeartbeat event and resource

- monkey/infection_monkey/heart.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/island_api_client/i_island_api_client.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/monkey.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
Fixes a part of #2518
> Tested by running the Agent and checking the logs
> AgentHeartbeat thread

- monkey/infection_monkey/heart.py
Issue #2518
Refactor's the Agent's `Heart` to use `PeriodidCaller`
* [ x Have you checked that you haven't introduced any duplicate code?
> Tested by running an agent from source
> Agent: Use PeriodicCaller to implement Heart

- monkey/infection_monkey/agent_event_handlers/agent_event_forwarder.py
- monkey/tests/unit_tests/infection_monkey/agent_event_handlers/test_agent_event_forwarder.py
Simplifies `AgentEventForwarder` by using `PeriodicCaller`
Benefits:
1. Simpler code
2. More reliable (less racey) tests.
3. The component will shutdown faster (the sleep() was removed)
> Tested by running an agent from source
> Use periodic caller for agent event forwarder

- monkey/infection_monkey/exploit/smbexec.py
> Fix SMB exploiter if no credentials

- monkey/monkey_island/cc/services/agent_signals_service.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_agent_signals_service.py
Fixes a part of #2518
> Tested by running the Island and manually changing the running Agent's stop time
> Modify AgentSignalsService to check for Agent stop time

- monkey/common/event_queue/__init__.py
- monkey/common/event_queue/queued_agent_event_publisher.py
- monkey/tests/unit_tests/common/event_queue/test_queued_agent_event_publisher.py
- vulture_allowlist.py
> 2640 queued agent event publisher

- monkey/common/agent_plugins/__init__.py
- monkey/common/agent_plugins/agent_plugin.py
- monkey/common/agent_plugins/agent_plugin_manifest.py
- monkey/common/agent_plugins/plugin_manifest.py
- monkey/tests/unit_tests/common/agent_plugins/test_agent_plugin.py
- monkey/tests/unit_tests/common/agent_plugins/test_agent_plugin_manifest.py
- vulture_allowlist.py
Fixes part of  #2638
> Tested by running the unit tests created
> 2638 plugin classes

- monkey/monkey_island/cc/repositories/i_agent_plugin_repository.py
- vulture_allowlist.py
> Island: Define AgentPluginRepository interface

- monkey/monkey_island/cc/repositories/__init__.py
- monkey/monkey_island/cc/repositories/agent_plugin_repository_logging_decorator.py
- vulture_allowlist.py
> Island: Implement AgentPluginRepositoryLoggingDecorator

- monkey/infection_monkey/monkey.py
- vulture_allowlist.py
Fixes #2640.
> Tested by running the agent
> Agent: Start PluginEventForwarder thread

- monkey/monkey_island/cc/ui/src/components/map/MapPageWrapper.tsx
Fixes #2591
> Tested by running some agents, navigating to the map
> 2591 map page delay

- monkey/monkey_island/cc/services/initialize.py
> Island: Add plugin file repository convention

- monkey/monkey_island/cc/repositories/file_agent_plugin_repository.py
- monkey/monkey_island/cc/services/initialize.py
> Island: Register IAgentPluginRepository

- monkey/tests/data_for_tests/agent_plugin/config-schema.json
Fixes part of #2675.
Adds the JSON schema for plugin configuration.
> UT: Add config schema for Mock plugin

- monkey/common/event_queue/locking_agent_event_queue_decorator.py
- monkey/common/types/concurrency.py
- monkey/monkey_island/cc/event_queue/locking_island_event_queue_decorator.py
- monkey/monkey_island/cc/services/initialize.py
Fixes #2653.
Updates the queues to use an RLock
> 2653 use rlock on event publish

- monkey/common/event_queue/locking_agent_event_queue_decorator.py
- monkey/common/types/concurrency.py
- monkey/monkey_island/cc/services/initialize.py
Adds BasicLock and fixes some type hinting.
> Tested by running mypy
> Tested by starting the Island
> 2653 basic lock

- monkey/monkey_island/cc/ui/src/components/ui-components/Error404Modal.js
- monkey/monkey_island/cc/ui/src/components/ui-components/ErrorModal.js
- monkey/monkey_island/cc/ui/src/components/ui-components/LogDownloadButtons.tsx
> Fix empty log file download bug

- monkey/monkey_island/cc/ui/src/components/map/preview-pane/NodePreviewPane.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/LogDownloadButtons.tsx
Fixes part of #2595 .
> Tested by running twice and downloading two files.
> 2595 download all agents logs in preview pane

- monkey/monkey_island/cc/ui/src/components/map/MapPageWrapper.tsx
- monkey/monkey_island/cc/ui/src/components/map/preview-pane/NodePreviewPane.tsx
- monkey/monkey_island/cc/ui/src/components/types/MapNode.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/LogDownloadButtons.tsx
> 2595 fix agent log filenames

- monkey/monkey_island/cc/repositories/file_repository_caching_decorator.py
- monkey/monkey_island/cc/repositories/file_repository_locking_decorator.py
- monkey/monkey_island/cc/repositories/file_repository_logging_decorator.py
- monkey/monkey_island/cc/repositories/i_file_repository.py
- monkey/monkey_island/cc/repositories/local_storage_file_repository.py
- monkey/tests/monkey_island/in_memory_file_repository.py
- monkey/tests/monkey_island/mock_file_repository.py
- monkey/tests/monkey_island/single_file_repository.py
- vulture_allowlist.py
Issue #2710
Add IFileRepository.get_all_file_names()
> Island: Add IFileRepository.get_all_file_names()

- monkey/monkey_island/cc/ui/src/components/ui-components/LogDownloadButtons.tsx
Fixes #2595.
> Tested by running bunch of times, deleting and checking error modal
> 2595 add missing log filenames in error modal

- monkey/monkey_island/cc/repositories/agent_plugin_repository_caching_decorator.py
- monkey/monkey_island/cc/repositories/agent_plugin_repository_logging_decorator.py
- monkey/monkey_island/cc/repositories/file_agent_plugin_repository.py
- monkey/monkey_island/cc/repositories/i_agent_plugin_repository.py
- monkey/tests/monkey_island/in_memory_agent_plugin_repository.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_agent_plugin_repository_caching_decorator.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_file_agent_plugin_repository.py
- vulture_allowlist.py
> 2710 agent plugin repository get plugin catalog

- monkey/monkey_island/cc/repositories/file_repository_caching_decorator.py
- monkey/monkey_island/cc/repositories/local_storage_file_repository.py
- monkey/tests/monkey_island/in_memory_file_repository.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_file_repository_caching_decorator.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_local_storage_file_repository.py
Implements `get_all_file_names()` for:
- `FileRepositoryCachingDecorator`
- `LocalStorageFileRepository`
> 2710 implement get all file names

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/monkey_island/cc/resources/agent_configuration_schema.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_configuration_schema.py
Fixes a part of #2710 
Merge after #2717 
> AgentConfigurationSchema endpoint

- monkey/monkey_island/cc/ui/package-lock.json
- monkey/monkey_island/cc/ui/package.json
- monkey/monkey_island/cc/ui/src/components/configuration-components/CredentialsConfig.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/PropagationConfig.tsx
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/components/ui-components/AdvancedMultiSelect.js
- monkey/monkey_island/cc/ui/src/components/utils/SafeOptionValidator.js
- monkey/monkey_island/cc/ui/src/services/configuration/credentialCollectors.js
- monkey/monkey_island/cc/ui/src/services/configuration/exploiterClasses.js
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/fingerprinterClasses.js
- monkey/monkey_island/cc/ui/src/styles/pages/ConfigurationPage.scss
> 2694 migrate rjsf

- monkey/monkey_island/cc/ui/src/styles/components/AdvancedMultiSelect.scss
- monkey/monkey_island/cc/ui/src/styles/pages/ConfigurationPage.scss
Improves configuration page style as part of #2694
> Tested by running manually
> Fixup styles in configuration page

- monkey/monkey_island/cc/ui/src/styles/pages/ConfigurationPage.scss
Fixes #2694
Finishes up the #2694 by removing unused style rules
> Tested by running the configuration page, trying out different inputs
> 2694 remove unused css

- monkey/infection_monkey/exploit/HostExploiter.py
- monkey/infection_monkey/exploit/exploiter_wrapper.py
- monkey/infection_monkey/exploit/log4shell_utils/service_exploiters/i_service_exploiter.py
- monkey/infection_monkey/exploit/log4shell_utils/service_exploiters/logstash.py
- monkey/infection_monkey/exploit/log4shell_utils/service_exploiters/solr.py
- monkey/infection_monkey/exploit/log4shell_utils/service_exploiters/tomcat.py
- monkey/infection_monkey/exploit/powershell_utils/auth_options.py
- monkey/infection_monkey/exploit/tools/helpers.py
- monkey/infection_monkey/exploit/web_rce.py
- monkey/infection_monkey/exploit/zerologon_utils/dc_utils.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/master/exploiter.py
- monkey/infection_monkey/master/propagator.py
- monkey/infection_monkey/model/__init__.py
- monkey/infection_monkey/model/host.py
- monkey/infection_monkey/model/target_host_factory.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/data_for_tests/agent_plugin/src/plugin.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_zerologon.py
- monkey/tests/unit_tests/infection_monkey/exploit/zerologon_utils/test_dc_utils.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/infection_monkey/model/test_victim_host_factory.py
Fixes part of #2707.
> Tested by unit tests.
> Rename VictimHost to TargetHost

- monkey/infection_monkey/exploit/HostExploiter.py
- monkey/infection_monkey/exploit/exploiter_wrapper.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/master/exploiter.py
- monkey/infection_monkey/master/ip_scanner.py
- monkey/infection_monkey/master/propagator.py
- monkey/infection_monkey/payload/i_payload.py
- monkey/infection_monkey/payload/ransomware/ransomware_payload.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/infection_monkey/utils/threading.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
Fixes a part of #2692
> Tested by running an agent and killing all agents from the map page
> 2692 multiprocessing event

- monkey/infection_monkey/exploit/exploiter_wrapper.py
- monkey/infection_monkey/puppet/puppet.py
Fixes a part of #2692 
> UTs pass
> Rename ExploiterWrapper's exploit_host() to run()

- monkey/infection_monkey/model/host.py
- monkey/infection_monkey/model/target_host_factory.py
- monkey/tests/unit_tests/infection_monkey/exploit/zerologon_utils/test_dc_utils.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/infection_monkey/model/test_victim_host_factory.py
> Remove TargetHost domain_name

- monkey/infection_monkey/i_puppet/__init__.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/i_puppet/port_scan_data.py
- monkey/infection_monkey/network_scanning/tcp_scanner.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_http_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_mssql_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ssh_fingerprinter.py
> 2707 pydantic port scan data

- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/puppet/plugin_registry.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_registry.py
Extract and load plugins in `PluginRegistry`
Issue #2692
> 2692 load plugin

- monkey/common/types/__init__.py
- monkey/common/types/networking.py
- monkey/infection_monkey/i_puppet/__init__.py
- monkey/infection_monkey/i_puppet/i_fingerprinter.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/i_puppet/ping_scan_data.py
- monkey/infection_monkey/master/ip_scan_results.py
- monkey/infection_monkey/master/ip_scanner.py
- monkey/infection_monkey/master/propagator.py
- monkey/infection_monkey/network_scanning/http_fingerprinter.py
- monkey/infection_monkey/network_scanning/mssql_fingerprinter.py
- monkey/infection_monkey/network_scanning/ping_scanner.py
- monkey/infection_monkey/network_scanning/smb_fingerprinter.py
- monkey/infection_monkey/network_scanning/ssh_fingerprinter.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ping_scanner.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Fixes a part of #2707 
> UTs pass
> PingScanData pydantic

- monkey/common/agent_configuration/agent_configuration.py
- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/icmpScan.js
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/tcpScan.js
- monkey/tests/unit_tests/common/agent_configuration/test_agent_sub_configurations.py
Titles, descriptions and defaults are required for conversion to jsonschema
Addresses part of #2710
> Investigating how schema is getting generated and if it will be displayed by rjsf
> Island: Add titles, descriptions and defaults to configuration

- monkey/infection_monkey/exploit/HostExploiter.py
- monkey/infection_monkey/exploit/hadoop.py
- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/log4shell_utils/service_exploiters/logstash.py
- monkey/infection_monkey/exploit/log4shell_utils/service_exploiters/solr.py
- monkey/infection_monkey/exploit/log4shell_utils/service_exploiters/tomcat.py
- monkey/infection_monkey/exploit/mssqlexec.py
- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/smbexec.py
- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/exploit/tools/helpers.py
- monkey/infection_monkey/exploit/tools/http_tools.py
- monkey/infection_monkey/exploit/tools/smb_tools.py
- monkey/infection_monkey/exploit/tools/wmi_tools.py
- monkey/infection_monkey/exploit/web_rce.py
- monkey/infection_monkey/exploit/wmiexec.py
- monkey/infection_monkey/exploit/zerologon.py
- monkey/infection_monkey/exploit/zerologon_utils/dc_utils.py
- monkey/infection_monkey/master/exploiter.py
- monkey/infection_monkey/master/propagator.py
- monkey/infection_monkey/model/__init__.py
- monkey/infection_monkey/model/host.py
- monkey/tests/data_for_tests/agent_plugin/src/plugin.py
- monkey/tests/unit_tests/infection_monkey/exploit/conftest.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_zerologon.py
- monkey/tests/unit_tests/infection_monkey/exploit/tools/test_helpers.py
- monkey/tests/unit_tests/infection_monkey/exploit/zerologon_utils/test_dc_utils.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
Fixes #2707.
> Tested by running AppImage and MSI EtE
> 2707 redefine target host

- monkey/tests/unit_tests/common/agent_configuration/test_agent_sub_configurations.py
Fixes a UT that was failing; see https://app.travis-ci.com/github/guardicore/monkey/jobs/591784600
> UTs pass
> Fix expected output in test_agent_sub_configurations.py

- monkey/infection_monkey/puppet/plugin_registry.py
> Set main_thread_name when loading plugin

- monkey/tests/monkey_island/in_memory_agent_plugin_repository.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_agent_plugin_repository_caching_decorator.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_plugins.py
We save plugins based on plugin_manifest.name
> UT: Remove name from InMemoryAgentPluginRepository.save_plugin

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
- monkey/infection_monkey/exploit/caching_agent_binary_repository.py
- monkey/infection_monkey/master/exploiter.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/puppet/plugin_registry.py
- monkey/tests/data_for_tests/agent_plugin/src/plugin.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_registry.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Issue #2692
Modifies the Agent and the plugin code to run successfully.
> Tested by running the Agent from source
* ['x] If applicable, add screenshots or log transcripts of the feature working
> 2692 fix run plugin bugs

- monkey/tests/data_for_tests/agent_plugin/config-schema.json
- monkey/tests/data_for_tests/agent_plugin/src/plugin.py
> Extend plugin options

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
- monkey/infection_monkey/puppet/plugin_registry.py
- monkey/tests/data_for_tests/agent_plugin/src/plugin.py
Issue #2692
Set's a plugin's main thread name to match the calling thread's name
> Tested by running a plugin and verifying it's thread name
> 2692 set main thread name

- CHANGELOG.md
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/monkey_island/cc/resources/agent_configuration_schema.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_configuration_schema.py
- vulture_allowlist.py
Issue #2710
Adds `/api/agent-configuration-schema`
> 2710 config schema endpoint

- build_scripts/docker/Dockerfile
- docs/content/setup/aws.md
- docs/content/setup/azure.md
> Remove reference to port 5001

- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/styles/pages/ConfigurationPage.scss
> UI: Remove tab-primary style from configuration page

- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/log_handlers/monkey_logs_downloader.py
Fixes #1057
> Tested by running BB tests, seeing the logs getting downloaded
> BB: Add island log download

- monkey/common/agent_plugins/agent_plugin_manifest.py
- monkey/common/types/__init__.py
- monkey/common/types/plugin_name.py
- monkey/tests/unit_tests/common/agent_plugins/test_agent_plugin_manifest.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_source_extractor.py
- vulture_allowlist.py
> Validate name in AgentPluginManifest

- envs/monkey_zoo/blackbox/log_handlers/island_log_parser.py
- envs/monkey_zoo/blackbox/log_handlers/monkey_logs_downloader.py
- envs/monkey_zoo/blackbox/tests/exploitation.py
- envs/monkey_zoo/blackbox/utils/bb_singleton.py
Fixes #2764
> Tested by running the BB tests, verifying the island doesn't contain logs from previous tests
> 2764 truncate bb island logs

- monkey/infection_monkey/puppet/plugin_registry.py
If two threads call get_plugin() or load_plugin() concurrently, the plugin may be downloaded multiple times or plugins may be erased from the registry. Adding a lock avoids such race conditions.
Makes plugin loading thread-safe
If two threads call get_plugin() or load_plugin() concurrently, the plugin may be downloaded multiple times or plugins may be erased from the registry. Adding a lock avoids such race conditions.
> Agent: Make plugin loading thread-safe

- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/puppet/plugin_registry.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_registry.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
> 2767 swap plugin registry parameters

- monkey/infection_monkey/monkey.py
Fixes #2768.
> Tested by running in the zoo environment and verifying that the directory is removed when the agent exits.
> 2768 remove plugin dir on exit

- monkey/infection_monkey/main.py
> Agent: Configure IPC logging in main

- monkey/infection_monkey/dropper.py
- monkey/infection_monkey/main.py
- monkey/infection_monkey/monkey.py
Fixes #2703 .
Configures plugin logging.
[infection-monkey-agent-2023-01-04-16-45-54-i5g_z64t.log](https://github.com/guardicore/monkey/files/10345934/infection-monkey-agent-2023-01-04-16-45-54-i5g_z64t.log)
> 2703 configure plugin logging

- monkey/infection_monkey/agent_event_handlers/add_stolen_credentials_to_repository.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/propagation_credentials_repository/__init__.py
- monkey/infection_monkey/propagation_credentials_repository/aggregating_propagation_credentials_repository.py
- monkey/infection_monkey/propagation_credentials_repository/i_legacy_propagation_credentials_repository.py
- monkey/tests/unit_tests/infection_monkey/credential_store/test_add_credentials_from_event.py
Fixes part of #2773. Merge after #2780
> 2773 rename legacy propagation credentials repository

- monkey/infection_monkey/propagation_credentials_repository/__init__.py
- monkey/infection_monkey/propagation_credentials_repository/i_propagation_credentials_repository.py
> 2773 add i propagation credentials repository

- monkey/infection_monkey/exploit/caching_agent_binary_repository.py
- monkey/tests/unit_tests/infection_monkey/base_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_caching_agent_binary_repository.py
> 2771 multiprocess safe caching agent binary repository

- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/common/agent_configuration/default_agent_configuration.py
- monkey/tests/common/example_agent_configuration.py
Merge "brute_force" and "vulnerability" into "exploiters"
Issue #2787
> Agent: Merge "brute_force" and "vulnerability" into "exploiters"

- monkey/infection_monkey/master/exploiter.py
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
Modifies the `master.exploiter` to use "exploiters" instead of "brute_force" and "vulnerability"
Issue #2787
Merge after #2789
> Tested by running the agent from source and inspecting the logs
> 2787 modify master exploiter logic

- monkey/monkey_island/cc/repositories/utils/__init__.py
- monkey/monkey_island/cc/repositories/utils/machine_repository_init.py
- monkey/monkey_island/cc/repositories/utils/mongo_encoder.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/utils/test_mongo_encoder.py
Splits up utilities in repositories package
> Island: Split up utils in repository

- monkey/monkey_island/cc/repositories/utils/__init__.py
- monkey/monkey_island/cc/repositories/utils/agent_configuration_schema_parser.py
- monkey/monkey_island/cc/services/agent_configuration_schema_service.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_agent_configuration_schema_service.py
Fixes part of #2783
> Tested by running the island, unit tests
> Island: Move schema parsing to repository utils

- monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js
- monkey/monkey_island/cc/ui/src/components/utils/SafeOptionValidator.js
- monkey/monkey_island/cc/ui/src/services/configuration/exploiterClasses.js
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/exploitation.js
Fixes part of #2787 .
> Tested by running island and agent
> 2787 modify UI with merged exploiters

- monkey/monkey_island/cc/services/reporting/report.py
Fixes part of #2787 .
Merge after #2794 
> Tested by running the Island and Agent and generating a report.
> Island: Modify report generation to work with merged exploiters

- envs/monkey_zoo/blackbox/test_configurations/credentials_reuse_ssh_key.py
- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_3_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_4_a.py
- envs/monkey_zoo/blackbox/test_configurations/noop.py
- envs/monkey_zoo/blackbox/test_configurations/smb_pth.py
- envs/monkey_zoo/blackbox/test_configurations/utils.py
- envs/monkey_zoo/blackbox/test_configurations/wmi_mimikatz.py
- envs/monkey_zoo/blackbox/test_configurations/zerologon.py
Fixes part of #2787 .
> Tested by running EtE
> BB: Modify test configuration with merged exploiters

- monkey/monkey_island/cc/repositories/i_agent_configuration_repository.py
- vulture_allowlist.py
> Island: Add PluginConfigurationValidationError

- monkey/common/credentials/credentials.py
- monkey/common/credentials/lm_hash.py
- monkey/common/credentials/nt_hash.py
- monkey/common/credentials/password.py
- monkey/common/credentials/ssh_keypair.py
- monkey/common/credentials/username.py
- monkey/infection_monkey/propagation_credentials_repository/__init__.py
- monkey/infection_monkey/propagation_credentials_repository/propagation_credentials_repository.py
- monkey/tests/unit_tests/infection_monkey/credential_store/test_propagation_credentials_repository.py
- vulture_allowlist.py
> 2773 propagation credentials repository

- monkey/infection_monkey/monkey.py
> 2773 construct propagation credentials repository

- monkey/infection_monkey/agent_event_handlers/add_stolen_credentials_to_repository.py
- monkey/infection_monkey/monkey.py
- monkey/tests/unit_tests/infection_monkey/credential_store/test_add_credentials_from_event.py
Merge after #2800.
> Tested by running the unit tests and verifying that they pass
> 2773 modify add stolen credentials to repository

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/puppet/plugin_registry.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_registry.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
> 2773 pass repository to plugin registry

- monkey/common/agent_configuration/default_agent_configuration.py
- monkey/monkey_island/cc/repositories/utils/hard_coded_exploiters.py
- monkey/tests/common/example_agent_configuration.py
Fixes part of #2785 (Adds hard-coded exploiter plugin schemas and configurations)
> Tested by running unit tests, seeing relevant fails and successes
> 2785 add hardcoded exploiter schemas

- monkey/monkey_island/cc/services/reporting/report.py
Fixes report to address the changes in #2785
> 2785 fixup report to use changed config format

- envs/monkey_zoo/blackbox/test_configurations/credentials_reuse_ssh_key.py
- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_3_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_4_a.py
- envs/monkey_zoo/blackbox/test_configurations/smb_pth.py
- envs/monkey_zoo/blackbox/test_configurations/utils.py
- envs/monkey_zoo/blackbox/test_configurations/wmi_mimikatz.py
- envs/monkey_zoo/blackbox/test_configurations/zerologon.py
Fixes the last part of #2785
> Tested by running BB test, making sure the config changed
> BB: Change exploiter configurations from list to dict

- CHANGELOG.md
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/monkey_island/cc/resources/agent_plugins_manifest.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_plugins_manifest.py
> 2786 plugin manifest endpoint

- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/island_api_client/i_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/base_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
- vulture_allowlist.py
> Add get_agent_configuration_schema() to Island API client

- CHANGELOG.md
- envs/monkey_zoo/blackbox/test_configurations/credentials_reuse_ssh_key.py
- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_3_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_4_a.py
- envs/monkey_zoo/blackbox/test_configurations/smb_pth.py
- envs/monkey_zoo/blackbox/test_configurations/utils.py
- envs/monkey_zoo/blackbox/test_configurations/wmi_mimikatz.py
- envs/monkey_zoo/blackbox/test_configurations/zerologon.py
- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/common/agent_configuration/default_agent_configuration.py
- monkey/infection_monkey/master/exploiter.py
- monkey/monkey_island/cc/repositories/utils/agent_configuration_schema_compiler.py
- monkey/monkey_island/cc/repositories/utils/hard_coded_exploiters.py
- monkey/monkey_island/cc/services/reporting/report.py
- monkey/tests/common/example_agent_configuration.py
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_agent_configuration_schema_service.py
Fixes #2785
Does all changes required to switch exploiters in the configuration from `Sequence[PluginConfiguration]` to `Dict[str, Mapping]`
> Tested by running unit tests, other relevant tests
> 2785 plugins in schema

- monkey/infection_monkey/exploit/caching_agent_binary_repository.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/propagation_credentials_repository/propagation_credentials_repository.py
- monkey/tests/unit_tests/infection_monkey/credential_store/test_propagation_credentials_repository.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_caching_agent_binary_repository.py
Fixes #2773.
Make the Manager a member of the InfectionMonkey class, and inject that into the objects that need a Manager.
> Tested by running agains the x.x.3.51 log2j machine
> Fix managers

- monkey/monkey_island/cc/resources/agent_configuration.py
- monkey/tests/common/example_agent_configuration.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_configuration.py
> 2783 valid agent configuration endpoint

- monkey/common/operating_system.py
Fixes the first task of #2811; ~the second subtask still needs to be done~ modified the issue to make it a separate task
> Common: Add OperatingSystem.ANY

- monkey/common/agent_plugins/agent_plugin.py
- monkey/monkey_island/cc/repositories/plugin_archive_parser.py
- monkey/tests/unit_tests/common/agent_plugins/test_agent_plugin.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_registry.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_source_extractor.py
- monkey/tests/unit_tests/monkey_island/cc/fake_agent_plugin_data.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_agent_plugin_repository_caching_decorator.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_plugins.py
- vulture_allowlist.py
Fixes the second task of #2811 
Merge after #2827
> UTs pass
> Add AgentPlugin.host_operating_system

- monkey/monkey_island/cc/repositories/utils/hard_coded_exploiters.py
- monkey/monkey_island/cc/ui/src/services/configuration/configSchema.js
- monkey/monkey_island/cc/ui/src/services/configuration/credentialCollectors.js
- monkey/monkey_island/cc/ui/src/services/configuration/exploitationOptions.js
- monkey/monkey_island/cc/ui/src/services/configuration/ransomware.js
Improves text in configuration, based on work of @ybasford
> UI: Improve various descriptions in configuration

- monkey/common/utils/code_utils.py
- monkey/tests/unit_tests/common/utils/test_code_utils.py
Issue #2825 
Adds random string generation functions.
> 2825 add random string generation functions

- monkey/common/utils/file_utils/__init__.py
- monkey/common/utils/file_utils/file_utils.py
- monkey/infection_monkey/exploit/hadoop.py
- monkey/infection_monkey/exploit/tools/helpers.py
- monkey/infection_monkey/monkey.py
- monkey/tests/unit_tests/common/utils/test_common_file_utils.py
#2825
Merge after #2831
Keep code DRY by using common random string generation functions.
> Tested by running BB tests
> 2825 use common random string generators

- vulture_allowlist.py
> Project: Clear out forgotten vulture entries

- monkey/infection_monkey/i_puppet/i_puppet.py
> Add IncompatibleOperatingSystemError(RejectedRequestError) exceptions

- monkey/common/__init__.py
- monkey/common/hard_coded_exploiter_manifests.py
> Common: Add hard coded agent plugins manifests for exploiters

- monkey/infection_monkey/island_api_client/configuration_validator_decorator.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/island_api_client/i_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/base_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
> 2788 add get agent plugin manifest i island api client

- monkey/monkey_island/cc/ui/src/components/utils/SafeOptionValidator.js
Fixes part of  #2698
> Tested by looking for safe options prompt on new/legacy plugins and safety being true/false/undefined
> UI: Adjust safe options validation to validate plugins

- monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
Fixes a bunch of bugs in plugin selector. 
With these bugs out of the way we can select, configure and submit plugins.
> Tested by clicking various components, submitting, refreshing, etc.
> 2698 plugin selector bugfixes

- monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx
Fixes part of  #2700
Adds a pane and link to plugin selector
cudos to @ilija-lazoroski
> 2700 options in pane

- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
> 2788 modify puppet to verify compatability

- monkey/monkey_island/cc/repositories/agent_plugin_repository_caching_decorator.py
- monkey/monkey_island/cc/repositories/agent_plugin_repository_logging_decorator.py
- monkey/monkey_island/cc/repositories/file_agent_plugin_repository.py
- monkey/monkey_island/cc/repositories/i_agent_plugin_repository.py
- monkey/monkey_island/cc/repositories/utils/agent_configuration_schema_compiler.py
- monkey/monkey_island/cc/resources/agent_plugins_manifest.py
- monkey/tests/monkey_island/in_memory_agent_plugin_repository.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_agent_plugin_repository_caching_decorator.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_file_agent_plugin_repository.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_plugins_manifest.py
- vulture_allowlist.py
Fixes part of #2811. Merge after #2835
Updates the plugin repository to get plugins filtered by operating system
> 2811 update agent repository get plugin

- CHANGELOG.md
- monkey/monkey_island/cc/resources/agent_plugins.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_plugins.py
Fixes part of #2811. Merge after #2836 
Add host_os to the `agent-plugins` endpoint
> 2811 add os to agent plugins endpoint

- monkey/infection_monkey/island_api_client/configuration_validator_decorator.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/island_api_client/i_island_api_client.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/puppet/plugin_registry.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_registry.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Merge after #2837.
Puppet requests plugins for its OS.
> Smoke tested the agent
> 2811 agent requests plugins with os

- monkey/infection_monkey/i_puppet/__init__.py
- monkey/infection_monkey/master/exploiter.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
> Tested by existing unit tests
> 2788 modify master exploiter to handle os compatibility

- monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/AdvancedMultiSelect.js
Fixes #2698 .
https://user-images.githubusercontent.com/15820737/213185600-a6f3d272-b83e-4d3b-82d5-af3c1eb964df.mov
> 2698 fix safe options reset button UI

- monkey/monkey_island/cc/repositories/file_agent_plugin_repository.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_file_agent_plugin_repository.py
Fixes a part of #2811 
> UTs pass
> Return OS-specific plugin in FileAgentPluginRepository

- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx
> 2700 add default info pane text

- monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/ChildCheckbox.js
- monkey/monkey_island/cc/ui/src/styles/_variables.scss
- monkey/monkey_island/cc/ui/src/styles/components/AdvancedMultiSelect.scss
Fixes part of #2700 .
https://user-images.githubusercontent.com/15820737/213244386-7435bdf8-af68-479b-a814-dd5111d367e7.mov
> 2700 highlight selected plugin

- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/master/exploiter.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
> 2830 pass legacy credentials to legacy exploiters

- monkey/agent_plugins/exploiters/hadoop/manifest.yaml
Fixes a part of #2826 
([Multiline strings in YAML](https://yaml-multiline.info/))
> Hadoop exploiter manifest file

- monkey/agent_plugins/exploiters/hadoop/config-schema.json
> Add config-schema.json for Hadoop Plugin Exploiter

- monkey/agent_plugins/runner/plugin_runner.py
- monkey/tests/plugins/exploiter_plugin_runner.py
Simple script that actually runs the plugin and tries to exploit
> 2826 exploiter runner

- monkey/common/agent_plugins/agent_plugin_manifest.py
- monkey/tests/unit_tests/common/agent_plugins/test_agent_plugin_manifest.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_plugins.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_plugins_manifest.py
- vulture_allowlist.py
Adds `remediation_suggestion` to the plugin manifest
*[x] Have you checked that you haven't introduced any duplicate code?
> Common: Add AgentPluginManifest.remediation_suggestion

- monkey/agent_plugins/exploiters/hadoop/build.sh
> Hadoop: Add build.sh script that outputs tar archive

- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop.py
Extends and improve unit tests for Hadoop exploiter
> Hadoop: Extend hadoop unit tests

- monkey/common/hard_coded_exploiter_manifests.py
Fixes a part of #2857
> UTs pass
> Add remediation_suggestion to hard-coded exploiters

- monkey/monkey_island/cc/services/reporting/issue_processing/exploit_processing/exploiter_descriptor_enum.py
- monkey/monkey_island/cc/services/reporting/report.py
Fixes a part of #2857 
> UTs pass
> Modify ReportService's get_config_exploits() to use plugin repository

- monkey/agent_plugins/exploiters/hadoop/src/hadoop.py
- monkey/agent_plugins/exploiters/hadoop/src/plugin.py
- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/mssqlexec.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop.py
> Tested by running the Hadoop plugin in the zoo environment
> 2826 refactor hadoop

- monkey/infection_monkey/exploit/log4shell_utils/exploit_class_http_server.py
- monkey/infection_monkey/exploit/tools/__init__.py
- monkey/infection_monkey/exploit/tools/http_agent_binary_server.py
- monkey/infection_monkey/exploit/tools/http_bytes_server.py
- monkey/infection_monkey/network/__init__.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_http_bytes_server.py
> 2826 new http agent binary server utilities

- monkey/agent_plugins/exploiters/hadoop/src/hadoop.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop.py
Fixes part of #2826.
Adds further unit tests for Hadoop.
> 2826 test exploit urls

- monkey/agent_plugins/exploiters/hadoop/src/plugin.py
- monkey/tests/data_for_tests/agent_plugin/mock1/src/plugin.py
- monkey/tests/data_for_tests/agent_plugin/mock2/src/plugin.py
- monkey/tests/data_for_tests/agent_plugin/mock_multiple_vendors/src/plugin.py
Allows exploiter plugins to handle the interface being extended with kwargs.
> 2826 plugin kwargs

- monkey/infection_monkey/exploit/HostExploiter.py
- monkey/infection_monkey/exploit/exploiter_wrapper.py
- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/mssqlexec.py
- monkey/infection_monkey/exploit/tools/http_tools.py
- monkey/infection_monkey/exploit/web_rce.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/info.py
- monkey/tests/unit_tests/infection_monkey/exploit/log4shell_utils/test_exploit_class_http_server.py
- monkey/tests/unit_tests/infection_monkey/exploit/log4shell_utils/test_ldap_server.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_http_bytes_server.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py
- monkey/tests/unit_tests/infection_monkey/network/test_info.py
> 2826 modify tcp port selector

- monkey/agent_plugins/exploiters/hadoop/src/hadoop.py
- monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py
- monkey/agent_plugins/exploiters/hadoop/src/plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_plugin.py
Fixes part of #2826 
- Updates the Hadoop plugin to use the HTTPBytesServer
- Adds tests for the Hadoop exploiter's Plugin class
> 2826 use http bytes server

- monkey/monkey_island/cc/services/reporting/report.py
- monkey/tests/data_for_tests/agent_plugin/manifests.py
- monkey/tests/unit_tests/monkey_island/cc/services/reporting/exploitations/test_monkey_exploitation.py
- monkey/tests/unit_tests/monkey_island/cc/services/reporting/test_report.py
Fixes part of #2857 .
> Tested by UTs
> Modify backend report to send remediation suggestions

- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
Safe and link are part of the plugin manifest. Therefore, the manifest must be obtained for each plugin, and merged into the UI schema.
Fixes #2850
> Tested by running the Island with the mock plugins, and viewing the configuration page
> https://user-images.githubusercontent.com/11077625/214933299-455567ec-c93b-43e5-b155-ceb2d3264dcd.mov
> UI: Fix safe, link for plugin configuration

- monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploit_client.py
- monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploiter.py
- monkey/agent_plugins/exploiters/hadoop/src/plugin.py
> Hadoop: Add more logging to hadoop exploiter

- monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploit_client.py
- monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploiter.py
- monkey/agent_plugins/exploiters/hadoop/src/hadoop_options.py
- monkey/infection_monkey/exploit/tools/http_bytes_server.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_exploit_client.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_options.py
- monkey/tests/unit_tests/infection_monkey/exploit/tools/test_http_bytes_server.py
Fixes agent binary download race condition
Improves code quality
> 2826 fix agent binary download race condition

- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/components/report-components/common/MonkeysStillAliveWarning.js
- monkey/monkey_island/cc/ui/src/components/report-components/common/MustRunMonkeyWarning.js
- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/BreachSection.tsx
- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/LateralMovement.tsx
- monkey/monkey_island/cc/ui/src/components/report-components/security/ScannedServers.js
Minor changes to wording in reports. Updates support email link in report footer.
> Fix report grammar and support email in UI

- monkey/monkey_island/cc/ui/src/components/SideNavComponent.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/IslandResetModal.tsx
> Fix Island reset delay

- docs/content/setup/linux.md
Fixes #2907 
> Tested by running the documentation server:
> Docs: Add suggestions about fixing Fuse errors for AppImage setup

- monkey/infection_monkey/puppet/plugin_registry.py
See https://github.com/pyinstaller/pyinstaller/issues/7410 for more details.
Fixes a race condition with pyinstaller, "spawn", and multiprocessing.
> Agent: Fix multiprocessing race condition with "spawn" and pyinstaller

- README.md
- build_scripts/docker/DOCKER_README.md
- docs/content/development/adding-exploits.md
- monkey/common/hard_coded_exploiter_manifests.py
- monkey/infection_monkey/payload/ransomware/ransomware_readme.txt
- monkey/monkey_island/cc/repositories/utils/hard_coded_exploiters.py
- monkey/monkey_island/cc/setup/data_dir.py
- monkey/monkey_island/cc/ui/src/components/logo/LogoComponent.js
- monkey/monkey_island/cc/ui/src/components/pages/LandingPage.tsx
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOnAWS/AWSRunButton.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOnAWS/AWSRunOptions.js
- monkey/tests/unit_tests/infection_monkey/island_api_client/configuration_validation_constants.py
> Fix guardicore redirection links

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/pages/MapPage.js
Fixes #2914
> Tested by manual run, clicking, dragging, etc.
> 2914 map sidepane fix

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/pages/RegisterPage.js
Fixes #2916
> Tested by running the island, trying to register with errors
> 2916 registration button bug

- monkey/monkey_island/cc/ui/src/components/ui-components/EventsTable.js
> Redact credentials in events page

- monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx
Fixes #2923
> Tested by switching tabs, making sure it remains up to date
https://user-images.githubusercontent.com/15820737/216594086-acb0a179-8663-449f-98a5-385814bda066.mov
> UI: Fix a bug in StolenCredentialsTable.tsx in the report

- monkey/infection_monkey/pyinstaller_hooks/hook-infection_monkey.payload.ransomware.py
- monkey/infection_monkey/pyinstaller_hooks/hook-infection_monkey.ransomware.py
> Agent: Add correct pyinstaller hook for ransowamre payload

- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx
Fixes #2923 
https://user-images.githubusercontent.com/44770317/216921902-2af33d1e-8d3b-44ee-9eec-43c62c10322b.mp4
> Fix StolenCredentialsTable bug

- docs/content/reports/_index.md
> Documentation changes

- monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx
Fixes #2920
> Tested by manually trying different malformed/outdated configs
> UI: Fix error handling in configuration import

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/map/MapOptions.js
> 2939 map drift fix

- monkey/monkey_island/cc/ui/src/services/configuration/configSchema.js
- monkey/monkey_island/cc/ui/src/services/configuration/exploitationOptions.js
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/icmpScan.js
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/tcpScan.js
> UI: Fix ranges in configuration schema

- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
Fixes #2956 
> Tested by hardcoding a timestamp and making sure it's shown in my browser's timezone on the Island
> Fix timezone bug in report

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
> Fix exploit percentage in security report

- monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js
> UI: Fix duplicate tunnels in report

- CHANGELOG.md
- monkey/infection_monkey/payload/ransomware/readme_dropper.py
- monkey/tests/data_for_tests/test_readme_windows.txt
- monkey/tests/unit_tests/infection_monkey/payload/ransomware/test_readme_dropper.py
> Fix readme line ending

- monkey/monkey_island/cc/ui/src/components/configuration-components/PropagationConfig.tsx
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> UI: Fix custom validation formats

- monkey/common/agent_plugins/agent_plugin_manifest.py
- monkey/common/types/__init__.py
- monkey/common/types/int_range.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/island_api_client/configuration_validator_decorator.py
- monkey/infection_monkey/island_api_client/i_island_api_client.py
- monkey/infection_monkey/master/control_channel.py
- monkey/infection_monkey/master/ip_scanner.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/info.py
- monkey/infection_monkey/network/ports.py
- monkey/infection_monkey/network/relay/tcp_connection_handler.py
- monkey/infection_monkey/network/relay/tcp_relay.py
- monkey/infection_monkey/network_scanning/tcp_scanner.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/infection_monkey/utils/signal_handler.py
- monkey/tests/unit_tests/common/types/test_int_range.py
- monkey/tests/unit_tests/infection_monkey/exploit/log4shell_utils/test_ldap_server.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
Fixes some mypy errors in the agent
> Tested by running the unit tests, ETE tests
> Fix agent mypy errors

- CHANGELOG.md
- monkey/monkey_island/linux/install_mongo.sh
Updates `install_mongo.sh` to use 6.0.4
Issue #2706
> Tested by running ETE tests for AppImage
> Upgrade mongo to 6.0.4 for appimage/linux deployment script

- docs/content/setup/docker.md
Update docker setup instructions to use MongoDB 6.0
Issue #2706
> Tested by running locally and copy/pasting new commands from documentation
> Docs: Update docker setup instructions to use MongoDB 6.0

- monkey/monkey_island/readme.md
- monkey/monkey_island/windows/install_mongo.ps1
Upgrades MongoDB to 6.0.4 for the MSI build
Merge after #2981
Issue #2706
* [ x Was the CHANGELOG.md updated to reflect the changes?
> 2706 upgrade mongo to 6.0.4 for msi

- monkey/common/types/networking.py
- monkey/infection_monkey/i_puppet/__init__.py
- monkey/infection_monkey/i_puppet/exploiter_result_data.py
- monkey/infection_monkey/i_puppet/fingerprint_data.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/i_puppet/test_fingerprint_data.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
Fixes part of #2136 .
It needs small manual test. Travis will fail but it will be fixed in next PRs
And it needs unit tests for the pydantic models itself
> 2136 redefine fingerprinterdata

- CHANGELOG.md
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
> Agent: Handle `None` returned from exploiter

- monkey/common/types/networking.py
- monkey/infection_monkey/i_puppet/fingerprint_data.py
- monkey/infection_monkey/network_scanning/http_fingerprinter.py
- monkey/infection_monkey/network_scanning/mssql_fingerprinter.py
- monkey/infection_monkey/network_scanning/smb_fingerprinter.py
- monkey/infection_monkey/network_scanning/ssh_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/i_puppet/test_fingerprint_data.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_http_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_mssql_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ssh_fingerprinter.py
> Update fingerprinters to use updated fingerprintdata

- monkey/infection_monkey/i_puppet/target_host.py
- monkey/infection_monkey/master/propagator.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
> Modify `master.propagator`

- monkey/agent_plugins/exploiters/hadoop/config-schema.json
- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/powershell_utils/auth_options.py
- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/exploit/web_rce.py
- monkey/infection_monkey/i_puppet/target_host.py
- monkey/infection_monkey/master/propagator.py
- monkey/tests/unit_tests/infection_monkey/exploit/conftest.py
Fixes part of #2136.
Replaces `TargetHost.services`
> 2136 replace targethost services

- monkey/common/hard_coded_manifests/__init__.py
- monkey/common/hard_coded_manifests/hard_coded_payloads_manifests.py
- monkey/monkey_island/cc/repositories/utils/hard_coded_payloads_schemas.py
- vulture_allowlist.py
> 2750 add hard coded paylods schemas

- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/monkey_island/cc/models/__init__.py
- monkey/monkey_island/cc/models/role.py
- monkey/monkey_island/cc/models/user.py
- vulture_allowlist.py
> 2157 define user role models

- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/models/role.py
- monkey/monkey_island/cc/resources/auth/__init__.py
- monkey/monkey_island/cc/resources/auth/authenticate.py
- monkey/monkey_island/cc/server_setup.py
- monkey/monkey_island/cc/server_utils/__init__.py
- monkey/monkey_island/cc/server_utils/setup_flask.py
- vulture_allowlist.py
> 2157 setup flask security

- build_scripts/.gitignore
- build_scripts/build_agent_linux.sh
- monkey/infection_monkey/build_linux.sh
- monkey/infection_monkey/readme.md
Issue #2705
Add a build script that builds agents in the official docker container for building agents.
> Tested by building and smoke testing an agent on Linux
> 2705 agent build script

- monkey/monkey_island/cc/repositories/utils/agent_configuration_schema_compiler.py
- monkey/monkey_island/cc/resources/agent_plugins_manifest.py
- monkey/monkey_island/cc/ui/package-lock.json
- monkey/monkey_island/cc/ui/package.json
- monkey/monkey_island/cc/ui/src/components/configuration-components/PropagationConfig.tsx
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/components/ui-components/AdvancedMultiSelect.js
- monkey/monkey_island/cc/ui/src/components/ui-components/JsonSchemaHelpers.js
- monkey/monkey_island/cc/ui/webpack.config.js
- monkey/tests/unit_tests/monkey_island/cc/services/test_agent_configuration_schema_service.py
- vulture_allowlist.py
Fixes part of #2750
> Tested by going to the configuration page, navigating to plugin selectors/advanced select
> 2750 render config with backend schema

- .pre-commit-config.yaml
The gitlab mirror no longer exists, so update the link to point to the github repository
> Project: Update flake8 pre-commit repo link

- CHANGELOG.md
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/tests/unit_tests/common/agent_configuration/test_agent_sub_configurations.py
Fixes #2860
> Tested by running the agent
> 2860 preserve exploit order

- envs/monkey_zoo/blackbox/test_configurations/noop.py
- monkey/common/agent_configuration/agent_configuration.py
- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/common/agent_configuration/default_agent_configuration.py
- monkey/common/hard_coded_manifests/hard_coded_payloads_manifests.py
- monkey/infection_monkey/master/automated_master.py
- monkey/monkey_island/cc/repositories/utils/agent_configuration_schema_compiler.py
- monkey/monkey_island/cc/repositories/utils/hard_coded_payloads_schemas.py
- monkey/monkey_island/cc/ui/src/components/configuration-components/PropagationConfig.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/ReformatHook.js
- monkey/monkey_island/cc/ui/src/components/configuration-components/UISchemaManipulators.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/components/ui-components/InfoPane.js
- monkey/monkey_island/cc/ui/src/components/utils/SafeOptionValidator.js
- monkey/tests/common/example_agent_configuration.py
- monkey/tests/unit_tests/common/agent_configuration/test_agent_configuration.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/configuration_validation_constants.py
Fixes part of #2750
Changes the payloads from sequence of PluginConfiguration to a Dict in pydantic models
Fixes remaining parts in configuration UI
> Tested by manually fiddling with the configuration UI
> 2750 plugin configuration

- monkey/common/agent_configuration/agent_configuration.py
- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/monkey_island/cc/repositories/utils/agent_configuration_schema_compiler.py
Fixes part of #2750
Specify descriptions to all fields missing one instead of overriding pydantic methods
> Tested by glossing over the UI, making sure those descriptions appear
> 2750 schema descriptions

- vulture_allowlist.py
> Remove stale entries in Vulture allowlist

- deployment_scripts/deploy_linux.sh
Fixes part of #2705.
> Tested by manually running the deployment script
> Project: Use python 3.11 for linux deployment script

- build_scripts/appimage/AppRun
- build_scripts/appimage/appimage.sh
- build_scripts/docker/Dockerfile
- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/monkey_island/windows/create_certificate.bat
Issue #2705
Upgrades the Island Python version to 3.11.2
> 2705 upgrade island python version

- deployment_scripts/config.ps1
- deployment_scripts/deploy_windows.ps1
Fixes part of #2705.
Updates the windows deployment script to install Python 3.11.2.
> 2705 windows deployment script

- monkey/common/utils/exceptions.py
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/auth/__init__.py
- monkey/monkey_island/cc/resources/auth/authenticate.py
- monkey/monkey_island/cc/resources/auth/login.py
- monkey/monkey_island/cc/services/authentication_service.py
- monkey/monkey_island/cc/ui/src/services/AuthService.js
- monkey/tests/unit_tests/monkey_island/cc/resources/auth/conftest.py
- monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_authenticate.py
- monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_login.py
- monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_register.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_authentication_service.py
> Island: Implement login using flask-security

- monkey/common/types/concurrency.py
- monkey/common/types/ids.py
- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
- monkey/infection_monkey/exploit/powershell_utils/powershell_client.py
- monkey/monkey_island/cc/models/machine.py
- monkey/monkey_island/cc/models/node.py
Fixes a part of #2971 
> UTs pass
> Remove typing_extensions

- monkey/monkey_island/cc/resources/auth/credential_utils.py
- monkey/monkey_island/cc/resources/auth/login.py
- monkey/monkey_island/cc/resources/auth/register.py
- monkey/monkey_island/cc/server_utils/response_utils.py
- monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_login.py
- monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_register.py
> 2157 wrap login and registration

- monkey/monkey_island/cc/app.py
- vulture_allowlist.py
> Island: Disable session-based cookies in Flask

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/auth/__init__.py
- monkey/monkey_island/cc/resources/auth/logout.py
- monkey/monkey_island/cc/services/authentication_service.py
- monkey/monkey_island/cc/ui/src/components/Main.tsx
- monkey/monkey_island/cc/ui/src/services/AuthService.js
- monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_logout.py
Fixes #2157
> Sending requests
> 2157 implement logout

- monkey/common/credentials/__init__.py
- monkey/infection_monkey/exploit/tools/__init__.py
- monkey/infection_monkey/exploit/tools/brute_force_credentials_generator.py
- monkey/tests/unit_tests/infection_monkey/exploit/tools/test_brute_force_credentials_generator.py
- vulture_allowlist.py
Fixes #3039
Add function for smarter brute force credentials generation
> 3039 smarter brute force credentials generator

- monkey/infection_monkey/exploit/tools/__init__.py
- monkey/infection_monkey/exploit/tools/brute_force_credentials_generator.py
- monkey/tests/unit_tests/infection_monkey/exploit/tools/test_brute_force_credentials_generator.py
- vulture_allowlist.py
Add a useful/reusable secret type filter for filtering brute-force credentials
Issue #3039
> Agent: Add secret_type_filter callable

- envs/monkey_zoo/blackbox/island_client/monkey_island_requests.py
- monkey/monkey_island/cc/app.py
- vulture_allowlist.py
Fixes BB test part of 2157
> Tested by running BB tests, invalidating the token
> 2157 fix bb authentication

- monkey/common/di_container.py
- monkey/tests/unit_tests/common/test_di_container.py
Adds the ability to handle default values in `DIContainer`
> Tested by starting the Island
> Handle defaults in `DIContainer`

- monkey/monkey_island/cc/services/agent_signals_service.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_agent_signals_service.py
> Island: Fix logic error in AgentSignalsService

- monkey/monkey_island/cc/resources/auth/register.py
- monkey/monkey_island/cc/ui/src/components/pages/RegisterPage.js
- monkey/monkey_island/cc/ui/src/services/AuthService.js
- monkey/monkey_island/cc/ui/src/styles/pages/AuthPage.scss
Fixes the registration errors so that they display in the UI.
> Tested by running the island
> ![Screenshot 2023-03-07 at 2 43 57 PM](https://user-images.githubusercontent.com/11077625/223563070-21d4b47c-bb3e-4624-b8cb-25e2f06b109a.jpg)
> https://user-images.githubusercontent.com/11077625/223563001-8bbe338e-bc87-4203-95a0-0867e6af5e64.mov
> UI: Parse authentication errors from flask-security

- monkey/monkey_island/cc/ui/src/components/pages/LoginPage.js
- monkey/monkey_island/cc/ui/src/components/pages/RegisterPage.js
- monkey/monkey_island/cc/ui/src/services/AuthService.js
Display login errors from failed authentication.
> Tested by running the island
> 2157 display login errors

- monkey/monkey_island/cc/app.py
Related to #2157
> Changed the expiration time to 1 minute, registered on the Island, waited a minute, got redirected to the login page
> Set auth expiration time in Flask

- monkey/monkey_island/cc/app.py
> Don't register /verify endpoint

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/auth/__init__.py
- monkey/monkey_island/cc/resources/auth/login.py
- monkey/monkey_island/cc/resources/auth/logout.py
- monkey/monkey_island/cc/resources/auth/register.py
Fixes a bug caused by `flask-security-too` endpoints overriding our auth endpoints
> Tested by running AppImage tests
> Tested by running manual tests
> Unregister flask security endpoints

- monkey/monkey_island/cc/services/authentication_service/configure_flask_security.py
- vulture_allowlist.py
Fixes security configuration tasks in #2157
Rebase and merge after #3085
> Tested by running the island, logging in
> 2157 improve security configuration

- monkey/agent_plugins/exploiters/smb/manifest.yml
Fixes part of #2952.
Add plugin manifest for SMB exploiter plugin
> SMB: Add plugin manifest

- monkey/agent_plugins/exploiters/smb/src/plugin.py
- monkey/agent_plugins/exploiters/smb/src/smb_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/smb/test_smb_plugin.py
> 2952 smb exploiter

- monkey/agent_plugins/exploiters/smb/src/smb_command_builder.py
- monkey/infection_monkey/model/__init__.py
> SMB command builder

- monkey/infection_monkey/island_api_client/island_api_client_errors.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
Follow up on #3101 that improves the unit test code
> Improve island api client tests

- monkey/common/hard_coded_manifests/hard_coded_fingerprinter_manifests.py
> Fix duplicate fingerprinter in configuration

- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/blackbox/test_configurations/smb_pth.py
- envs/monkey_zoo/blackbox/test_configurations/zerologon.py
> Update BB configurations for SMB

- monkey/infection_monkey/exploit/i_agent_otp_provider.py
- monkey/infection_monkey/exploit/i_otp_provider.py
- vulture_allowlist.py
> Add IOTPProvider

- build_scripts/README.md
- build_scripts/docker/DOCKER_README.md
- build_scripts/docker/docker.sh
- docs/content/FAQ/_index.md
- docs/content/setup/docker.md
> 3013 monkey island docker hub

- monkey/infection_monkey/exploit/__init__.py
- monkey/infection_monkey/exploit/agent_otp_provider.py
- monkey/infection_monkey/exploit/island_api_agent_otp_provider.py
- vulture_allowlist.py
> AgentOTPProvider

- CHANGELOG.md
- monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py
- monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploit_client.py
Fixes #2758
Fully fixes #655
Related: #1781, #1782
> Tested by running hadoop exploiter in the monkey zoo and verifying that only one new log appears
> 2758 disable hadoop speculative execution

- monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx
Configuration export already reformats config into it's "true" state (one that the back end expects). We don't need to do any more reformatting before submitting it
Fixes #3056
> Tested manually (import/export/submit, etc)
> UI: Fix configuration import bug

- monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx
> UI: Fix green question mark for plugin documentation

- monkey/infection_monkey/island_api_client/abstract_island_api_client_factory.py
- monkey/infection_monkey/island_api_client/configuration_validator_decorator.py
- monkey/infection_monkey/island_api_client/http_client.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/island_api_client/http_island_api_client_factory.py
- monkey/infection_monkey/island_api_client/i_island_api_client.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/relay/utils.py
- monkey/tests/unit_tests/infection_monkey/base_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_client.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/network/relay/test_utils.py
Fixes #3117 
> Tested by running the Agent locally
> Fix Island connection retries

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/Main.tsx
- monkey/monkey_island/cc/ui/src/components/SideNavComponent.tsx
- monkey/monkey_island/cc/ui/src/components/layouts/SidebarLayoutComponent.tsx
- monkey/monkey_island/cc/ui/src/styles/components/SideNav.scss
> UI: Add a logout button

- monkey/tests/unit_tests/infection_monkey/network/relay/test_relay_user_handler.py
Reducing the new client timeout and increasing the sleep time made test more reliable
Issue: #3096
Fixes unreliable relay unit test
> Tested by running the test manually like 20 times - 0 failures
> UT: Fix relay user connection timeouts

- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
Fixes part of #3069
> Tested by running island unit tests with `-n auto`
> Island: Add pytest-xdist package

- monkey/tests/unit_tests/infection_monkey/network/test_info.py
> UT: Choose only RANDOM_PORTS_NUMBER in testing common ports

- vulture_allowlist.py
Removes vulture entries related to #2952.
> Project: Remove SMB-related vulture entries

- monkey/tests/unit_tests/infection_monkey/network/relay/test_relay_user_handler.py
Fixes unaddressed windows timeout (#3096)
> Tested by running the unit tests 5 times, making sure it's didn't reproduce with the adjusted timeouts
> UT: Adjust timeouts in test_relay_users_time_out

- monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py
- monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploiter.py
- monkey/agent_plugins/exploiters/hadoop/src/plugin.py
- monkey/agent_plugins/exploiters/smb/src/plugin.py
- monkey/agent_plugins/exploiters/smb/src/smb_command_builder.py
- monkey/infection_monkey/exploit/HostExploiter.py
- monkey/infection_monkey/exploit/exploiter_wrapper.py
- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/mssqlexec.py
- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/exploit/web_rce.py
- monkey/infection_monkey/exploit/wmiexec.py
- monkey/infection_monkey/exploit/zerologon.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/utils/commands.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/smb/test_smb_command_builder.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_zerologon.py
- monkey/tests/unit_tests/infection_monkey/utils/test_commands.py
> Pass Agent ID to exploiters

- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/utils/CommandDisplay.js
Related to #3115.
Changed the code block CSS
> UI: Override the context menu's copy option to copy a command

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/payload/ransomware/ransomware.py
- monkey/infection_monkey/payload/ransomware/ransomware_builder.py
- monkey/infection_monkey/payload/ransomware/ransomware_payload.py
- monkey/tests/integration_tests/infection_monkey/payload/ransomware/test_integrated_ransomware.py
- monkey/tests/unit_tests/infection_monkey/payload/ransomware/test_ransomware.py
Fixes part of #3119 by passing Agent ID to the ransomware payload.
> Agent: Pass Agent ID to Ransomware

- monkey/common/utils/environment.py
- monkey/infection_monkey/utils/ids.py
- monkey/monkey_island/cc/repositories/utils/machine_repository_init.py
Fixes #3176
> Manual test on Ubuntu Jammy to verify that the Island and Agent detect the same machine ID
> 3176 fix hardware id mismatch

- envs/monkey_zoo/blackbox/gcp_test_machine_list.py
- envs/monkey_zoo/blackbox/island_client/i_monkey_island_requests.py
- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/island_client/monkey_island_requests.py
- envs/monkey_zoo/blackbox/island_client/reauthorizing_monkey_island_requests.py
- envs/monkey_zoo/blackbox/test_blackbox.py
Fixes part of #3122.
Add a BB test for island logout
> Tested by running the new BB test
> 3122 test island logout

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/services/authentication_service/setup.py
- monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/test_authentication_service.py
> 3122 test logout on restart

- envs/monkey_zoo/blackbox/conftest.py
- envs/monkey_zoo/blackbox/gcp_test_machine_list.py
- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/island_client/monkey_island_requests.py
- envs/monkey_zoo/blackbox/island_client/reauthorizing_monkey_island_requests.py
- envs/monkey_zoo/blackbox/test_blackbox.py
> Fix bb logout tests

- monkey/common/common_consts/token_keys.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/monkey_island/cc/services/authentication_service/flask_resources/agent_otp_login.py
- monkey/monkey_island/cc/services/authentication_service/flask_resources/refresh_authentication_token.py
- monkey/monkey_island/cc/services/authentication_service/flask_resources/register_resources.py
- monkey/monkey_island/cc/services/authentication_service/flask_resources/utils.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
- monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_login.py
- monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_otp_login.py
- monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_refresh_authentication_token.py
- monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_register.py
Fixes a part of #3137 
> It's hard to test it completely until Agent login is implemented but I tested manually by modifying the code as well as I could.
> Use refresh token in Agent

- monkey/infection_monkey/island_api_client/http_island_api_client.py
> Agent: Fix refresh authentication token url

- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunManually/LocalManualRunOptions.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/utils/CommandDisplay.js
Fixes part of #3078 by refreshing the OTP when the command is copied.
- Refreshes the command if the copy button is pressed
- Refreshes the command if `ctrl+c` is pressed
> 3078 refresh on copy

- monkey/common/types/__init__.py
- monkey/common/types/secrets.py
- monkey/common/types/token.py
- monkey/monkey_island/cc/services/authentication_service/authentication_facade.py
- monkey/monkey_island/cc/services/authentication_service/flask_resources/refresh_authentication_token.py
- monkey/monkey_island/cc/services/authentication_service/types.py
- monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_refresh_authentication_token.py
- monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/test_authentication_service.py
Fixes part of #3078 by changing Token to a SecretStr.
> Tested by running the agent from source, as well as running the BB logout test
> Island: Change Token to a SecretStr

- monkey/monkey_island/cc/ui/src/components/Main.tsx
> Fix 404 page in UI

- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/credentials.js
> Reorder configuration schema

- monkey/monkey_island/cc/ui/package-lock.json
- monkey/monkey_island/cc/ui/package.json
- monkey/monkey_island/cc/ui/src/components/IslandHttpClient.tsx
- monkey/monkey_island/cc/ui/src/components/Main.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx
- monkey/monkey_island/cc/ui/src/components/logo/VersionComponent.js
- monkey/monkey_island/cc/ui/src/components/map/MapPageWrapper.tsx
- monkey/monkey_island/cc/ui/src/components/map/preview-pane/ExploitationTimeline.tsx
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/components/pages/LandingPage.tsx
- monkey/monkey_island/cc/ui/src/components/pages/MapPage.js
- monkey/monkey_island/cc/ui/src/components/pages/ReportPage.tsx
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunManually/LocalManualRunOptions.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOnAWS/AWSRunButton.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOnAWS/AWSRunOptions.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOnIslandButton.js
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/AttackSection.tsx
- monkey/monkey_island/cc/ui/src/components/report-components/security/BreachedServers.tsx
- monkey/monkey_island/cc/ui/src/components/report-components/security/ScannedServers.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/EventsTable.js
- monkey/monkey_island/cc/ui/src/components/ui-components/LogDownloadButtons.tsx
- monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx
- monkey/monkey_island/cc/ui/src/services/AuthService.js
> 3137 refresh token timer UI

- vulture_allowlist.py
> Project: Clean vulture allowlist

- monkey/monkey_island/cc/resources/remote_run.py
- monkey/monkey_island/cc/services/aws/aws_command_runner.py
- monkey/monkey_island/cc/services/aws/aws_service.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_remote_run.py
- monkey/tests/unit_tests/monkey_island/cc/services/aws/test_aws_command_runner.py
> Fix aws ssm run

- monkey/monkey_island/cc/services/agent_binary_service/masquerade_agent_binary_repository_decorator.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/test_masquerade_agent_binary_repository_decorator.py
- vulture_allowlist.py
> 3241 masquerade agent binary repository decorator

- monkey/monkey_island/cc/services/agent_binary_service/agent_binary_service.py
- monkey/monkey_island/cc/services/agent_binary_service/i_agent_binary_service.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/test_agent_binary_service.py
- vulture_allowlist.py
> 3241 add os specific masque methods

- monkey/monkey_island/cc/services/agent_binary_service/agent_binary_service.py
- monkey/monkey_island/cc/services/agent_binary_service/masquerade_agent_binary_repository_decorator.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/test_agent_binary_service.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/test_masquerade_agent_binary_repository_decorator.py
Issue #324
Implement `AgentBinaryService.set_masque()`
> 3241 implement set masque

- CHANGELOG.md
- monkey/monkey_island/cc/services/agent_binary_service/flask_resources/agent_binaries_masque.py
- monkey/monkey_island/cc/services/agent_binary_service/flask_resources/register.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/flask_resources/test_agent_binaries_masque.py
- vulture_allowlist.py
Fixes a part of #3241 
> Tested endpoints with Postman
> Agent binary masque resource

- monkey/common/utils/file_utils/__init__.py
- monkey/common/utils/file_utils/file_utils.py
- monkey/monkey_island/cc/repositories/file_repository_caching_decorator.py
- monkey/monkey_island/cc/services/agent_binary_service/masquerade_agent_binary_repository_decorator.py
- monkey/tests/unit_tests/common/utils/test_file_utils.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/test_masquerade_agent_binary_repository_decorator.py
Fixes a caching issue in the `MasqueradeAgentBinaryRepositoryDecorator`
> Manual testing performed
> 3241 fix masque caching

- monkey/monkey_island/cc/services/agent_binary_service/build.py
- monkey/monkey_island/cc/services/agent_binary_service/event_handlers.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/test_event_handlers.py
Issue #3241
Subscribe to `SET_ISLAND_MODE` events and reset the masque
> Tested by running manually
> 3241 reset masque on mode change

- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/tests/exploitation.py
> Set masque in depth_1_a and depth_4_a tests

- monkey/agent_plugins/exploiters/wmi/Pipfile
- monkey/agent_plugins/exploiters/wmi/Pipfile.lock
> WMI Pipfile

- monkey/agent_plugins/exploiters/wmi/manifest.yaml
> WMI manifest

- monkey/agent_plugins/exploiters/wmi/config-schema.json
> WMI config-schema.json

- monkey/agent_plugins/exploiters/wmi/src/wmi_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_options.py
- vulture_allowlist.py
> WMIOptions pydantic model

- monkey/infection_monkey/credential_collectors/mimikatz_collector/mimikatz_credential_collector.py
- monkey/infection_monkey/credential_collectors/ssh_collector/ssh_credential_collector.py
- monkey/infection_monkey/i_puppet/i_credentials_collector.py
- monkey/infection_monkey/master/automated_master.py
- monkey/tests/unit_tests/infection_monkey/credential_collectors/test_mimikatz_collector.py
- monkey/tests/unit_tests/infection_monkey/credential_collectors/test_ssh_credentials_collector.py
> 3167 run credentials collectors as plugins

- monkey/agent_plugins/exploiters/wmi/src/wmi_command_builder.py
- monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_command_builder.py
- vulture_allowlist.py
> WMI command builder

- monkey/agent_plugins/exploiters/smb/src/plugin.py
- monkey/agent_plugins/exploiters/wmi/src/plugin.py
- monkey/infection_monkey/exploit/tools/__init__.py
- monkey/infection_monkey/exploit/tools/utils.py
- monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_plugin.py
- monkey/tests/unit_tests/infection_monkey/exploit/tools/test_exploit_tools_utils.py
> WMI plugin.py

- monkey/agent_plugins/credentials_collectors/mimikatz/Pipfile
- monkey/agent_plugins/credentials_collectors/mimikatz/Pipfile.lock
- monkey/agent_plugins/credentials_collectors/mimikatz/manifest.yaml
- monkey/agent_plugins/credentials_collectors/mimikatz/src/mimikatz_options.py
> 3168 mimikatz pipfile

- envs/monkey_zoo/blackbox/test_configurations/depth_3_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_4_a.py
Merge after the plugin is complete
> Update BB test configurations for WMI

- monkey/agent_plugins/exploiters/wmi/src/plugin.py
> WMI: Use AgentID type for agent ID

- monkey/agent_plugins/exploiters/wmi/src/wmi_client.py
- vulture_allowlist.py
Issue #3163
> Tested by running the depth_3 and depth_4 tests in the zoo
> Project: Fix vulture issues

- monkey/agent_plugins/exploiters/hadoop/manifest.yaml
- monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploit_client.py
- monkey/agent_plugins/exploiters/hadoop/src/plugin.py
- monkey/agent_plugins/exploiters/smb/manifest.yaml
- monkey/agent_plugins/exploiters/smb/src/plugin.py
Fixes AgentID type hint in SMB and Hadoop exploiters
> Agent id type in plugins

- monkey/agent_plugins/credentials_collectors/mimikatz/src/plugin.py
- monkey/agent_plugins/credentials_collectors/mimikatz/src/windows_credentials.py
- monkey/tests/unit_tests/agent_plugins/credentials_collectors/mimikatz/test_plugin.py
> Mimikatz: Fix duplication of mimikatz credentials

- monkey/agent_plugins/build_plugin.sh
- monkey/agent_plugins/build_windows_vendor_directory.ps1
> 3168 vendor windows directory

- monkey/agent_plugins/credentials_collectors/mimikatz/src/plugin.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/model/__init__.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/agent_plugins/credentials_collectors/mimikatz/test_plugin.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- vulture_allowlist.py
Issue #3168
Implements the logic for handling "MimikatzOptions.excluded_username_prefixes"
> 3168 exclude usernames

- CHANGELOG.md
- monkey/agent_plugins/build_windows_vendor_directory.ps1
- monkey/agent_plugins/exploiters/zerologon/Pipfile
- monkey/agent_plugins/exploiters/zerologon/Pipfile.lock
- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
Fixes #3164 
> Tested Zerologon manually in the Zoo
> Fix Zerologon plugin

- CHANGELOG.md
- monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploit_client.py
- monkey/infection_monkey/main.py
Fixes #3296
> Tested by running the hadoop exploiter and checking the logs
> 3296 fix hadoop otp leak

- monkey/agent_plugins/exploiters/snmp/Pipfile
- monkey/agent_plugins/exploiters/snmp/Pipfile.lock
> SNMP: Add pipfile

- monkey/monkey_island/cc/ui/src/components/IslandHttpClient.tsx
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/services/configuration/masquerade.js
> 3242 masquerade popluate UI

- monkey/agent_plugins/exploiters/smb/src/plugin.py
- monkey/agent_plugins/exploiters/wmi/src/plugin.py
- monkey/infection_monkey/exploit/tools/__init__.py
- monkey/infection_monkey/exploit/tools/utils.py
- monkey/tests/unit_tests/infection_monkey/exploit/tools/test_exploit_tools_utils.py
Renames `all_{exploitation,tcp}_ports_are_closed()`
> Rename all exploitation ports are closed

- monkey/agent_plugins/exploiters/snmp/src/snmp_command_builder.py
- monkey/tests/unit_tests/agent_plugins/exploiters/snmp/test_snmp_command_builder.py
Adds a command builder for the SNMP exploiter
> SNMP: Add command builder

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/UISchemaManipulators.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/UISchemaPluginsManipulator.js
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
Fixes #3297 
> Tested the UI manually with plugins
https://user-images.githubusercontent.com/44770317/236776338-18135e13-904c-4215-8db9-41025e3a57c4.mp4
> Placeholder in configuration UI

- monkey/common/credentials/ssh_keypair.py
- monkey/infection_monkey/credential_collectors/ssh_collector/ssh_handler.py
- monkey/monkey_island/cc/repositories/mongo_credentials_repository.py
- monkey/monkey_island/cc/ui/src/components/configuration-components/ReformatHook.js
- monkey/tests/data_for_tests/propagation_credentials.py
- monkey/tests/unit_tests/common/agent_events/test_credentials_stolen_events.py
- monkey/tests/unit_tests/common/credentials/test_credentials.py
- monkey/tests/unit_tests/infection_monkey/credential_collectors/test_ssh_credentials_collector.py
- monkey/tests/unit_tests/infection_monkey/credential_store/test_aggregating_propagation_credentials_repository.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_mongo_credentials_repository.py
> 3169 ssh keypair publi key optional

- monkey/infection_monkey/island_api_client/http_client.py
> Refactor http_client.py

- monkey/monkey_island/cc/services/agent_binary_service/agent_binary_service.py
- monkey/monkey_island/cc/services/agent_binary_service/build.py
- monkey/monkey_island/cc/services/agent_binary_service/masquerade_agent_binary_repository_decorator.py
- monkey/tests/monkey_island/in_memory_masquerade_repository.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/test_agent_binary_service.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/test_masquerade_agent_binary_repository_decorator.py
Fixes #3309 
> Tested manually, state is saved between Island runs
> Use masquerade repository in AgentBinaryService

- monkey/infection_monkey/network/info.py
> Agent: Refactor get_routes to resolve C901

- monkey/infection_monkey/dropper.py
Fixes part of #1076.
Refactors the dropper code to reduce complexity.
> 1076 dropper

- monkey/infection_monkey/network_scanning/tcp_scanner.py
> Agent: Refactor _check_tcp_ports to resolve C901

- monkey/monkey_island/cc/services/agent_binary_service/agent_binary_service.py
- monkey/monkey_island/cc/ui/package-lock.json
- monkey/monkey_island/cc/ui/package.json
- monkey/monkey_island/cc/ui/src/components/configuration-components/ExportConfigModal.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/MasqueradeConfig.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/ReformatHook.js
- monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js
- monkey/monkey_island/cc/ui/src/components/configuration-components/ValidationErrorMessages.js
- monkey/monkey_island/cc/ui/src/components/configuration-components/ValidationFormats.js
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/components/utils/MasqueradeUtils.js
- monkey/monkey_island/cc/ui/src/services/configuration/configSchema.js
- monkey/monkey_island/cc/ui/src/services/configuration/masquerade.js
> 3243 arbitrary bytes

- CHANGELOG.md
Calculates agent sha256
> Tested by running the agent from source and from a binary and inspecting the Island and Agent logs
> 3244 calculate agent sha256

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx
Fixes #3341
> Tested manually by importing configurations
> Fix configuration import bug

- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_3_a.py
- envs/monkey_zoo/blackbox/test_configurations/utils.py
- envs/monkey_zoo/blackbox/tests/exploitation.py
Issue #3244
Adds ETE test for randomized agent hashes
> BB: Test unique agent hashes (polymorphism)

- CHANGELOG.md
- monkey/common/network/network_range.py
- monkey/tests/unit_tests/common/network/test_network_range.py
> 3231 resolve hostname with dashes

- monkey/agent_plugins/exploiters/mssql/manifest.yaml
> MSSQL: Add Manifest.yaml for MSSQL exploiter

- monkey/agent_plugins/exploiters/mssql/Pipfile
- monkey/agent_plugins/exploiters/mssql/Pipfile.lock
Issue #3171
Add Pipfile{.lock} for mssql exploiter
> MSSQL: Add Pipfile

- monkey/agent_plugins/exploiters/mssql/src/mssql_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_options.py
- vulture_allowlist.py
> MSSQL: Add MSSQLOptions

- monkey/agent_plugins/exploiters/mssql/config-schema.json
> MSSQL: Add configuration schema for MSSQL exploiter

- monkey/agent_plugins/exploiters/mssql/src/mssql_command_builder.py
- monkey/infection_monkey/utils/commands.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_command_builder.py
- vulture_allowlist.py
> Add MSSQL command builder

- monkey/agent_plugins/exploiters/powershell/Pipfile
- monkey/agent_plugins/exploiters/powershell/Pipfile.lock
- monkey/agent_plugins/exploiters/powershell/config-schema.json
- monkey/agent_plugins/exploiters/powershell/manifest.yaml
- monkey/agent_plugins/exploiters/powershell/src/powershell_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/powershell/test_powershell_options.py
> PowerShell exploiter plugin skeleton

- monkey/agent_plugins/exploiters/powershell/src/powershell_command_builder.py
- monkey/tests/unit_tests/agent_plugins/exploiters/powershell/test_powershell_command_builder.py
> Powershell: Add powershell_command_builder

- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
Fixes a part of #3171
Merge after #3363
> Update MSSQL exploiter configuration in depth_1_a

- monkey/infection_monkey/monkey.spec
Fixes dependency issues with the PowerShell exploiter plugin.
> Powershell std deps

- monkey/common/types/__init__.py
- monkey/common/types/file_extension.py
- monkey/infection_monkey/payload/ransomware/in_place_file_encryptor.py
- monkey/infection_monkey/payload/ransomware/ransomware_options.py
- monkey/tests/integration_tests/infection_monkey/payload/ransomware/test_integrated_ransomware.py
- monkey/tests/unit_tests/common/types/test_file_extension.py
- monkey/tests/unit_tests/infection_monkey/payload/ransomware/test_in_place_file_encryptor.py
- monkey/tests/unit_tests/infection_monkey/payload/ransomware/test_ransomware_options.py
Makes some minor improvements to how Ransomware handles file extensions.
> Ransomware file extension improvements

- monkey/common/agent_configuration/default_agent_configuration.py
- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
- monkey/infection_monkey/payload/ransomware/aes_256_file_encryptor.py
- monkey/infection_monkey/payload/ransomware/ransomware_builder.py
- monkey/infection_monkey/payload/ransomware/ransomware_options.py
- monkey/monkey_island/cc/services/agent_configuration_service/hard_coded_schemas/hard_coded_payloads_schemas.py
- monkey/tests/integration_tests/infection_monkey/payload/ransomware/test_integrated_ransomware.py
- monkey/tests/unit_tests/infection_monkey/payload/ransomware/test_aes256_file_encryptor.py
- monkey/tests/unit_tests/infection_monkey/payload/ransomware/test_ransomware_options.py
> 3379 ransomware aes256

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
- monkey/infection_monkey/payload/ransomware/ransomware_builder.py
- monkey/infection_monkey/payload/ransomware/ransomware_options.py
- monkey/infection_monkey/payload/ransomware/stealth_aes_256_bit_manipulator.py
- monkey/monkey_island/cc/services/agent_configuration_service/hard_coded_schemas/hard_coded_payloads_schemas.py
- monkey/tests/integration_tests/infection_monkey/payload/ransomware/test_integrated_ransomware.py
- monkey/tests/unit_tests/infection_monkey/payload/ransomware/test_stealth_aes_256_bit_manipulator.py
> 3381 ransomware stealth aes256

- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/test_blackbox.py
- monkey/monkey_island/cc/services/agent_binary_service/masquerade_agent_binary_repository_decorator.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/test_masquerade_agent_binary_repository_decorator.py
Fixes a bug where masquerade caching caused incorrect masques to be returned
Adds a BB test for malware masquerading
> 3309 fix masquerade caching

- build_scripts/build_agent_linux.sh
Fixes a part of #3395 
> The Linux Agent binary built on Jenkins from this branch is 2 MB smaller.
> Use uncompiled pydantic in Linux Agent build script

- envs/monkey_zoo/blackbox/test_blackbox.py
- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
> Add depth limit assertion to BB tests

- monkey/agent_plugins/exploiters/log4shell/Pipfile
- monkey/agent_plugins/exploiters/log4shell/Pipfile.lock
> Log4Shell: Add Pipfile to Log4Shell

- monkey/agent_plugins/exploiters/log4shell/src/ldap_server.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_ldap_server.py
Fixes a part of #3388 
> Tested by running Log4Shell (logstash on linux, solr on windows)
[2023-06-23T11.53.58.490Z-island-linux-250.log](https://github.com/guardicore/monkey/files/11848176/2023-06-23T11.53.58.490Z-island-linux-250.log)
[2023-06-23T11.54.20.166Z-log4j-solr-50.log](https://github.com/guardicore/monkey/files/11848178/2023-06-23T11.54.20.166Z-log4j-solr-50.log)
[2023-06-23T11.55.02.640Z-log4j-logstash-55.log](https://github.com/guardicore/monkey/files/11848175/2023-06-23T11.55.02.640Z-log4j-logstash-55.log)
> Migrate LDAPExploitServer from processes to threads

- CHANGELOG.md
- monkey/common/agent_events/__init__.py
- monkey/common/agent_events/abstract_agent_event.py
- monkey/tests/unit_tests/common/event_queue/test_pypubsub_agent_event_queue.py
- monkey/tests/unit_tests/infection_monkey/credential_store/test_add_credentials_from_event.py
> Constrain Agent event tags

- monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
- monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploiter.py
- monkey/agent_plugins/exploiters/log4shell/src/plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_exploit_client.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_exploiter.py
> 3388 log4shell exploit client

- monkey/agent_plugins/exploiters/ssh/Pipfile
- monkey/agent_plugins/exploiters/ssh/Pipfile.lock
- monkey/agent_plugins/exploiters/ssh/config-schema.json
- monkey/agent_plugins/exploiters/ssh/manifest.yaml
- monkey/agent_plugins/exploiters/ssh/src/ssh_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/ssh/test_ssh_options.py
- vulture_allowlist.py
> SSH exploiter plugin skeleton

- monkey/agent_plugins/exploiters/ssh/src/ssh_command_builder.py
- monkey/tests/unit_tests/agent_plugins/exploiters/ssh/test_ssh_command_builder.py
- vulture_allowlist.py
> SSH exploiter command builder

- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py
> Update Log4Shell EtE test configurations

- monkey/agent_plugins/exploiters/log4shell/src/ldap_server.py
> Log4Shell: Import twisted reactor at top level

- envs/monkey_zoo/blackbox/test_configurations/depth_3_a.py
> BB: Change depth_3_a credentials configuration

- monkey/monkey_island/cc/ui/src/components/pages/RegisterPage.js
* [] Is the TravisCI build passing?
* []Was the CHANGELOG.md updated to reflect the changes?
* ~Was the documentation framework updated to reflect the changes?
* ~Have you checked that you haven't introduced any duplicate code?~
* ~Added relevant unit tests?~
* ~Do all unit tests pass?~
* ~Do all end-to-end tests pass?~
* ~Any other testing performed?~
> 1984 Update the registration page texts

- monkey/infection_monkey/monkey.spec
> Agent: Update comment in monkey.spec about `cryptography`

- monkey/agent_plugins/exploiters/ssh/src/plugin.py
- monkey/agent_plugins/exploiters/ssh/src/ssh_client.py
- monkey/agent_plugins/exploiters/ssh/src/ssh_remote_access_client.py
- monkey/tests/unit_tests/agent_plugins/exploiters/ssh/test_ssh_client.py
- monkey/tests/unit_tests/agent_plugins/exploiters/ssh/test_ssh_remote_access_client.py
Fixes part of #3170 .
Adds unit tests and fixes issues in the SSHClient.
> Tested by running the SSH exploiter plugin in the zoo
> 3170 ssh client

- monkey/monkey_island/cc/repositories/i_agent_event_repository.py
- monkey/monkey_island/cc/repositories/mongo_agent_event_repository.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_mongo_agent_event_repository.py
> Return events by ascending timestamp in Agent events repository

- CHANGELOG.md
- monkey/monkey_island/cc/resources/agent_events.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_events.py
Fixes #3397
> Tested by running the Island and querying the endpoint
> Filter events by timestamp in AgentEvents resource

- monkey/monkey_island/cc/ui/src/components/ui-components/credential-pairs/credentialPairsHelper.js
> Fix enter key behavior in credentials configuration table

- monkey/infection_monkey/exploit/http_agent_binary_server_registrar.py
- monkey/infection_monkey/exploit/i_http_agent_binary_server_registrar.py
> Agent: Add HTTPAgentBinaryServerRegistrar

- monkey/monkey_island/cc/ui/src/components/configuration-components/ReformatHook.js
- monkey/monkey_island/cc/ui/src/components/configuration-components/UISchemaPluginsManipulator.js
- monkey/monkey_island/cc/ui/src/components/ui-components/credential-pairs/CredentialPairs.js
- monkey/monkey_island/cc/ui/src/components/ui-components/credential-pairs/credentialPairsHelper.js
Fix a bug that caused to unnecessary pair to be created.
Fixes #3481
> 3478 Fix a bug in Credential Pairs

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/plugin/exploiter_plugin_factory.py
> Agent: Pass IHTTPAgentBinaryServerRegistrar to exploiter plugins

- monkey/agent_plugins/exploiters/powershell/manifest.yaml
- monkey/agent_plugins/exploiters/powershell/src/powershell_command_builder.py
- monkey/agent_plugins/exploiters/powershell/src/powershell_remote_access_client.py
- monkey/agent_plugins/exploiters/powershell/src/powershell_remote_access_client_factory.py
- monkey/tests/unit_tests/agent_plugins/exploiters/powershell/test_powershell_command_builder.py
> Remove OS check from PowerShell command builder

- monkey/agent_plugins/exploiters/smb/manifest.yaml
- monkey/agent_plugins/exploiters/smb/src/smb_command_builder.py
- monkey/agent_plugins/exploiters/smb/src/smb_remote_access_client.py
- monkey/agent_plugins/exploiters/smb/src/smb_remote_access_client_factory.py
- monkey/tests/unit_tests/agent_plugins/exploiters/smb/test_smb_command_builder.py
> Remove OS check from SMB command builder

- monkey/agent_plugins/exploiters/wmi/manifest.yaml
- monkey/agent_plugins/exploiters/wmi/src/wmi_command_builder.py
- monkey/agent_plugins/exploiters/wmi/src/wmi_remote_access_client.py
- monkey/agent_plugins/exploiters/wmi/src/wmi_remote_access_client_factory.py
- monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_command_builder.py
> Remove OS check from WMI command builder

- monkey/agent_plugins/exploiters/snmp/manifest.yaml
- monkey/agent_plugins/exploiters/snmp/src/snmp_command_builder.py
- monkey/tests/unit_tests/agent_plugins/exploiters/snmp/test_snmp_command_builder.py
> Remove OS check from SNMP command builder

- monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_command_builder.py
> Default to Windows in Hadoop

- CHANGELOG.md
- monkey/common/agent_events/__init__.py
- monkey/monkey_island/cc/resources/agent_events.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_events.py
Fixes #3396
> Tested by running Island and querying endpoints manually
> Filter Agent events by tag

- monkey/monkey_island/cc/services/__init__.py
- monkey/monkey_island/cc/services/agent_plugin_service/__init__.py
- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_service.py
- monkey/monkey_island/cc/services/initialize.py
> Add AgentPluginService

- monkey/agent_plugins/exploiters/mssql/manifest.yaml
- monkey/agent_plugins/exploiters/mssql/src/mssql_exploiter.py
- monkey/agent_plugins/exploiters/mssql/src/plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_plugin.py
> 3410 use shared http server mssql

- monkey/agent_plugins/exploiters/hadoop/manifest.yml
- monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py
- monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploiter.py
- monkey/agent_plugins/exploiters/hadoop/src/plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_command_builder.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_plugin.py
> Use shared HTTP server in Hadoop

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/plugin/payload_plugin_factory.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_registry.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
- vulture_allowlist.py
> Modifications to load payload plugins

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/puppet/plugin_compatibility_verifier.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_compatibility_verifier.py
> Remove PluginCompatibilityVerifier dead code

- monkey/agent_plugins/exploiters/rdp/manifest.yaml
Fixes part of #3425.
Add plugin manifest for the RDP exploiter
> 3425 manifest

- monkey/agent_plugins/exploiters/rdp/Pipfile
- monkey/agent_plugins/exploiters/rdp/Pipfile.lock
Fixes part of #3425.
Add Pipfile for the RDP exploiter
> 3425 pipfile

- monkey/common/agent_event_serializers/__init__.py
- monkey/common/agent_event_serializers/consts.py
- monkey/common/agent_events/abstract_agent_event.py
- monkey/monkey_island/cc/repositories/mongo_agent_event_repository.py
- monkey/monkey_island/cc/resources/agent_events.py
Improves the performance of event filtering.
Fixes #3521
> 3521 improve event filtering performance

- envs/monkey_zoo/packer/setup_rdp_64.yml
- envs/monkey_zoo/packer/setup_rdp_65.yml
> BB: Set hostname in RDP packer script

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/plugin/payload_plugin_factory.py
Pass Island server's address to payload plugins
Issue #3411
> Pass Island address to payload plugins

- monkey/agent_plugins/payloads/ransomware/src/ransomware.py
- monkey/agent_plugins/payloads/ransomware/src/ransomware_builder.py
- monkey/tests/unit_tests/agent_plugins/payloads/ransomware/test_integrated_ransomware.py
- monkey/tests/unit_tests/agent_plugins/payloads/ransomware/test_ransomware.py
> Ransomware: Rename IAgentEventQueue to IAgentEventPublisher

- envs/monkey_zoo/packer/setup_mimikatz_15.yml
- envs/monkey_zoo/packer/smb.pkr.hcl
- envs/monkey_zoo/terraform/firewalls.tf
> 3577 smb packer scripts

- monkey/agent_plugins/exploiters/smb/manifest.yaml
- monkey/agent_plugins/exploiters/smb/src/smb_client.py
- monkey/agent_plugins/exploiters/wmi/manifest.yaml
- monkey/agent_plugins/exploiters/wmi/src/smb_client.py
> 3577 smb fix

- .pre-commit-config.yaml
- envs/monkey_zoo/blackbox/analyzers/stolen_credentials_analyzer.py
- envs/monkey_zoo/blackbox/expected_credentials.py
- envs/monkey_zoo/blackbox/gcp_test_machine_list.py
- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/island_client/monkey_island_requests.py
- envs/monkey_zoo/blackbox/log_handlers/island_log_parser.py
- envs/monkey_zoo/blackbox/log_handlers/monkey_log_parser.py
- envs/monkey_zoo/blackbox/log_handlers/monkey_logs_downloader.py
- envs/monkey_zoo/blackbox/log_handlers/test_logs_handler.py
- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_3_a.py
- envs/monkey_zoo/blackbox/test_configurations/smb_pth.py
- envs/monkey_zoo/blackbox/tests/exploitation.py
- envs/monkey_zoo/blackbox/utils/gcp_machine_handlers.py
Fixes #3579
Adds SSH credential stealing test
> 3579 smb pth fix

- envs/monkey_zoo/packer/setup_mimikatz_15.yml
- monkey/agent_plugins/exploiters/wmi/src/wmi_client.py
- monkey/agent_plugins/exploiters/wmi/src/wmi_remote_access_client.py
> 3543 wmi hanging

- envs/monkey_zoo/packer/setup_rdp_64.yml
Fixes failing rdp-64 exploitation
> BB: Disable Windows Defender on rdp-64

- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_repository_caching_decorator.py
- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_repository_logging_decorator.py
- monkey/monkey_island/cc/services/agent_plugin_service/file_agent_plugin_repository.py
- monkey/monkey_island/cc/services/agent_plugin_service/i_agent_plugin_repository.py
- monkey/tests/monkey_island/in_memory_agent_plugin_repository.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_configuration_service/test_agent_configuration_schema_compiler.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/flask_resources/test_agent_plugins.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/flask_resources/test_agent_plugins_manifest.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/test_agent_plugin_repository_caching_decorator.py
Adds `IAgentRepository.store_agent_plugin()`
Issue #3417
> 3417 add store agent plugin

- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_repository_caching_decorator.py
- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_repository_logging_decorator.py
- monkey/monkey_island/cc/services/agent_plugin_service/file_agent_plugin_repository.py
- monkey/monkey_island/cc/services/agent_plugin_service/i_agent_plugin_repository.py
- monkey/tests/monkey_island/in_memory_agent_plugin_repository.py
Adds `IAgentPluginRepository.remove_agent_plugin()`
Issue #3417
> 3417 add remove agent plugin

- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_repository_caching_decorator.py
- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_repository_logging_decorator.py
- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_service.py
- monkey/monkey_island/cc/services/agent_plugin_service/i_agent_plugin_repository.py
- monkey/monkey_island/cc/services/agent_plugin_service/i_agent_plugin_service.py
- monkey/tests/monkey_island/in_memory_agent_plugin_repository.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/conftest.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/test_agent_plugin_service.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/test_plugin_archive_parser.py
Fixes part of #3417 .
Adds `IAgentPluginService.install_agent_plugin_archice`
> 3417 add install agent plugin archive

- CHANGELOG.md
- monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/__init__.py
- monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/installed_agent_plugins_manifests.py
- monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/register.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/flask_resources/test_installed_agent_plugins_manifests.py
Adds an endpoint to get manifests of all installed plugins
Fixes #3424
> Installed plugins manifests endpoint

- docs/content/development/setup-development-environment.md
This PR fixes some broken links and outdated installation guide in documentation
> [RFR] Changes in documentation

- monkey/monkey_island/cc/services/agent_plugin_service/i_agent_plugin_service.py
Adds an abstract method to IAgentPluginService, prerequisite for tasks of #3421
> Add IAgentPluginService.install_agent_plugin_from_respository()

- monkey/common/agent_plugins/agent_plugin_metadata.py
- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_service.py
- monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/agent_plugins.py
- monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/install_agent_plugin.py
- monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/uninstall_agent_plugin.py
- monkey/monkey_island/cc/services/agent_plugin_service/i_agent_plugin_service.py
- monkey/tests/data_for_tests/agent_plugin/agent_plugin_repository_index.yml
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/flask_resources/test_agent_plugins.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/flask_resources/test_install_agent_plugin.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/flask_resources/test_uninstall_agent_plugin.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/test_agent_plugin_service.py
Adds `AgentPluginService.install_agent_plugin_from_repository()`
Fixes a part of #3421 
UTs left
> Install plugin from repository

- monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/install_agent_plugin.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/flask_resources/test_install_agent_plugin.py
Fixes #3421
Adds json content type to `InstallAgentPlugin`
> 3421 install repository agent plugin

- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_repository_caching_decorator.py
- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_repository_logging_decorator.py
- monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_service.py
- monkey/monkey_island/cc/services/agent_plugin_service/file_agent_plugin_repository.py
- monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/agent_plugins.py
- monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/agent_plugins_manifest.py
- monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/installed_agent_plugins_manifests.py
- monkey/monkey_island/cc/services/agent_plugin_service/i_agent_plugin_repository.py
- monkey/monkey_island/cc/services/agent_plugin_service/i_agent_plugin_service.py
- monkey/monkey_island/cc/services/agent_plugin_service/mongo_agent_plugin_repository.py
- monkey/tests/data_for_tests/agent_plugin/manifests.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/test_mongo_agent_plugin_repository.py
Fixes part of #3416.
Implements IAgentPluginRepository for MongoDB
> 3416 mongo agent plugin repository

- monkey/monkey_island/cc/server_setup.py
- monkey/monkey_island/cc/services/agent_plugin_service/mongo_agent_plugin_repository.py
- monkey/monkey_island/cc/setup/__init__.py
- monkey/monkey_island/cc/setup/plugin_installation.py
Installs plugins present in the data dir to the Island during setup
Fixes a part of #3416
**Merge this after #3601.**
> Tested that the Island attempts to install a plugin present in the data directory
> Install plugins on server setup

- monkey/monkey_island/cc/ui/src/components/Main.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx
- monkey/monkey_island/cc/ui/src/styles/components/AdvancedMultiSelect.scss
Adds a link to the Plugins page if no plugins are available in the configuration
Issue #3418 
> Tested UI
> Link to Plugins page in configuration

- monkey/monkey_island/cc/ui/src/components/ui-components/MonkeyTooltip.js
- monkey/monkey_island/cc/ui/src/styles/App.css
> 3418 tooltip component

- monkey/monkey_island/cc/ui/src/components/ui-components/XDataGrid.js
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/mocksHelper.js
- Integrate XDataGrid with MonkeyTooltip component
> UI xdatagrid tooltip integration

- monkey/monkey_island/cc/ui/src/components/ui-components/SearchBar.js
> UI Add SearchBar component

- monkey/monkey_island/cc/ui/src/components/ui-components/LoadingIconMUI.js
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.tsx
> 3418 fix plugin download icon

- monkey/monkey_island/cc/ui/src/components/ui-components/XDataGrid.js
Fixes part of #3418 
- Fix the tooltip in the datagrid
> UI fix xdatagrid tooltip integration

- monkey/monkey_island/cc/ui/src/components/ui-components/Select.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/TypeFilter.tsx
1. Adds filter and filtering logic
2. Moves mock plugin state higher up in the component hierarchy so other components can reuse it
> 3418 type dropdown

- monkey/common/agent_events/__init__.py
- monkey/common/agent_events/fingerprinting_event.py
- monkey/common/types/__init__.py
- monkey/common/types/networking.py
- monkey/infection_monkey/i_puppet/__init__.py
- monkey/infection_monkey/i_puppet/fingerprint_data.py
- monkey/infection_monkey/master/propagator.py
- monkey/infection_monkey/network_scanning/http_fingerprinter.py
- monkey/infection_monkey/network_scanning/mssql_fingerprinter.py
- monkey/infection_monkey/network_scanning/smb_fingerprinter.py
- monkey/infection_monkey/network_scanning/ssh_fingerprinter.py
- monkey/tests/unit_tests/common/agent_events/test_fingerprinting_event.py
- monkey/tests/unit_tests/infection_monkey/i_puppet/test_fingerprint_data.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_mssql_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ssh_fingerprinter.py
Adds FingerprintingEvent
Issue #3000
> 3000 fingerprinting event

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network_scanning/http_fingerprinter.py
- monkey/infection_monkey/network_scanning/mssql_fingerprinter.py
- monkey/infection_monkey/network_scanning/smb_fingerprinter.py
- monkey/infection_monkey/network_scanning/ssh_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_http_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_mssql_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ssh_fingerprinter.py
Pass IAgentEventPublisher to fingerprinters
Merge after https://github.com/guardicore/monkey/pull/3636
> 3000 pass event publisher

- monkey/monkey_island/cc/ui/src/components/pages/MarketplacePage.js
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.js
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/InstalledPlugins.tsx
Fixes part of #3418.
Implements the "Install All Safe" button.
> 3418 install all safe

- monkey/monkey_island/cc/ui/src/components/contexts/plugins/PluginsContext.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.js
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/BasePlugins.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/InstalledPlugins.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/TypeFilter.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/utils.js
Improves code quality and fixes various things in plugin UI.
> 3418 define plugin types

- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/BasePlugins.tsx
> 3418 add safe column

- monkey/monkey_island/cc/ui/src/components/pages/MarketplacePage.js
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/BasePlugins.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/InstalledPlugins.tsx
Fixes part of #3418.
Updates the plugins grids to use the available screen's height
> UI: Modify layout so that grid fills the viewport height

- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.tsx
- monkey/monkey_island/cc/ui/src/styles/components/plugins-marketplace/AvailablePlugins.module.scss
- monkey/monkey_island/cc/ui/src/styles/components/plugins-marketplace/AvailablePlugins.scss
Fixes part of #3418 .
Adds animation to the refresh button
> UI: Spin refresh button when refreshing available plugins

- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/InstalledPlugins.tsx
Adds loading icon when updating/deleting.
> UI: Use loading icon for update/delete

- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py
- monkey/common/agent_event_serializers/register.py
- monkey/common/agent_events/register.py
- monkey/infection_monkey/network_scanning/mssql_fingerprinter.py
- monkey/infection_monkey/network_scanning/smb_fingerprinter.py
- monkey/infection_monkey/network_scanning/ssh_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_mssql_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ssh_fingerprinter.py
Modifies MSSQL, SSH, SMB fingerprinters to publish FingerprintingEvent
Issue #3000
- ~UTs and manual testing left~
> Checked logs from EtE test and made sure events are sent with no hiccups
> Publish FingerprintingEvent from fingerprinters

- monkey/monkey_island/cc/ui/src/components/ui-components/SearchBar.js
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/InstalledPlugins.tsx
Removes redundant search bar label
#3418 
> Tested by building UI
> Remove search bar label

- monkey/monkey_island/cc/agent_event_handlers/__init__.py
- monkey/monkey_island/cc/agent_event_handlers/fingerprinting_event_handler.py
- monkey/monkey_island/cc/repositories/network_model_update_facade.py
- monkey/monkey_island/cc/setup/agent_event_handlers.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_fingerprinting_event_handler.py
Add FingerprintingEventHandler to Island, to update machines when network services' data is obtained
Fixes #3000
> Checked EtE test logs to make sure there are no errors, tested manually and checked report
Tested by Ilija:
> Fingerprinting event handler

- monkey/common/agent_plugins/agent_plugin_metadata.py
- monkey/tests/data_for_tests/agent_plugin/agent_plugin_repository_index.yml
- monkey/tests/data_for_tests/agent_plugin/agent_plugin_repository_index_simple.yml
- monkey/tests/unit_tests/common/agent_plugins/test_agent_plugin_metadata.py
- monkey/tests/unit_tests/common/agent_plugins/test_agent_plugin_repository_index.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/flask_resources/test_available_agent_plugins_index.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/test_agent_plugin_service.py
> AgentPluginMetadata.type_ -> AgentPluginMetadata.plugin_type

- monkey/tests/unit_tests/agent_plugins/credentials_collectors/chrome/test_chrome_plugin.py
> Improve tests for Chrome credentials collector

- monkey/monkey_island/cc/ui/src/components/pages/MarketplacePage.js
- monkey/monkey_island/cc/ui/src/components/ui-components/MonkeyButton.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/base-components/Color.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/InstallAllSafePluginsButton.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/InstalledPlugins.tsx
- monkey/monkey_island/cc/ui/src/styles/MUITheme.js
Fixes numerous bugs, improves the code state and looks of the button
> 3418 fix install all plugins button

- monkey/monkey_island/cc/ui/src/components/ui-components/MonkeySelect.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/TypeFilter.tsx
> 3418 monkey select styling

- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/InstalledPlugins.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/PluginTable.tsx
> 3418 table improvements

- monkey/agent_plugins/credentials_collectors/chrome/src/chrome_credentials_collector_builder.py
- monkey/tests/agent_plugins/credentials_collector_plugin_runner.py
> Prepare Chrome credentials collector for testing

- monkey/agent_plugins/credentials_collectors/chrome/src/chrome_credentials_collector_builder.py
- monkey/agent_plugins/credentials_collectors/chrome/src/plugin.py
- monkey/tests/unit_tests/agent_plugins/credentials_collectors/chrome/test_chrome_plugin.py
Issue #3426
> Tested by rebasing #3669 on this branch and testing the plugin
> Remove `host` argument from Chrome credentials collector

- CHANGELOG.md
- docs/content/reference/credentials_collectors/_index.md
- docs/content/reference/credentials_collectors/chrome.md
- docs/content/reference/credentials_collectors/mimikatz.md
- docs/content/reference/credentials_collectors/ssh.md
Adds documentation for all 3 credentials collectors
Issue #3426 
> Tested by running Hugo
> Credentials collector docs

- monkey/agent_plugins/credentials_collectors/chrome/src/chrome_credentials_collector.py
- monkey/agent_plugins/credentials_collectors/chrome/src/chrome_credentials_collector_builder.py
- monkey/agent_plugins/credentials_collectors/chrome/src/database_reader.py
- monkey/agent_plugins/credentials_collectors/chrome/src/decrypt.py
- monkey/agent_plugins/credentials_collectors/chrome/src/linux_credentials_database_processor.py
- monkey/agent_plugins/credentials_collectors/chrome/src/windows_credentials_database_processor.py
- monkey/tests/unit_tests/agent_plugins/credentials_collectors/chrome/test_chrome_plugin.py
- monkey/tests/unit_tests/agent_plugins/credentials_collectors/chrome/test_windows_credentials_database_processor.py
- monkey/tests/unit_tests/agent_plugins/credentials_collectors/chrome/test_windows_credentials_database_selector.py
- monkey/tests/utils.py
Adds the `WindowsCredentialsDatabaseProcessor` component for #3426 
> Tested by running with the plugin runner script and verifying the output
Tested by building the plugin and running it (screenshot of report below)
> Implement WindowsCredentialsDatabaseProcessor

- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/PluginTable.tsx
> UI: Fix description dropdown to increase plugin row height

- monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/SearchFilter.tsx
> UI: Fix plugins search

- monkey/agent_plugins/payloads/ransomware/src/ransomware_builder.py
- monkey/agent_plugins/payloads/ransomware/src/readme_dropper.py
- monkey/tests/data_for_tests/test_readme.txt
- monkey/tests/unit_tests/agent_plugins/payloads/ransomware/test_readme_dropper.py
- pyproject.toml
Fixes line endings in Ransomware README in Windows.
> Pending manual tests by @cakekoa
> Fix windows ransomware readme

- monkey/monkey_island/cc/ui/src/components/report-components/security/ScannedServers.js
> 3701 fix services count

- envs/monkey_zoo/blackbox/expected_credentials.py
- envs/monkey_zoo/blackbox/gcp_test_machine_list.py
- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py
Modifies depth_2_a BB test to verify expected credentials are stolen by Chrome credentials collector
> Chrome credentials collector BB modifications

- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_windows_powershell.js
> UI: Fix the manual run powershell command

- docs/content/development/setup-development-environment.md
- docs/content/usage/ransomware-simulation.md
> Docs: direct Github links to master

- monkey/monkey_island/cc/ui/package-lock.json
> UI: Add missing package-lock.json

- monkey/agent_plugins/exploiters/rdp/src/rdp_command_builder.py
- monkey/tests/unit_tests/common/test_decorators.py
> Fix flake8 issues

- .flake8
- .pre-commit-config.yaml
- monkey/infection_monkey/network_scanning/scan_target_generator.py
- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/monkey_island/cc/server_utils/encryption/password_based_bytes_encryptor.py
- monkey/tests/unit_tests/common/agent_event_serializers/test_pydantic_agent_event_serializer.py
- monkey/tests/unit_tests/infection_monkey/exploit/tools/test_brute_force_exploiter.py
- monkey/tests/unit_tests/infection_monkey/test_plugin_event_forwarder.py
- monkey/tests/unit_tests/monkey_island/cc/services/conftest.py
- pyproject.toml
Updates versions for `flake8`, `dlint`, and `black`
Updates python version in `black` config
Fixes leftover/new issues
> Update `flake8`, `dlint`, `black`

- monkey/monkey_island/cc/services/__init__.py
- monkey/monkey_island/cc/services/aws/__init__.py
- monkey/monkey_island/cc/services/aws/build.py
- monkey/monkey_island/cc/services/initialize.py
Fixes the Island failing to start.
The Island was broken by commit 166424652. This PR fixes it.
> Fix aws instance import

- monkey/common/agent_event_serializers/pydantic_agent_event_serializer.py
> Break PydanticAgentEventSerializer's dependency on common.utils

- envs/monkey_zoo/packer/setup_tunneling_11.yml
- envs/monkey_zoo/packer/setup_tunneling_13.yml
- envs/monkey_zoo/packer/tunneling.pkr.hcl
Adds tunneling 11 and 13 machines to the packer scripts.
> Tested by running the depth_3 and depth_4 tests in the zoo
> BB: Add tunneling 11 and 13 machines to the packer scripts

- envs/monkey_zoo/blackbox/utils/gcp_machine_handlers.py
Fix GCP instance startup in BB tests
> Tested by running appimage and msi EtE tests
> BB: Use threads instead of processes for gcp start/stop

- monkey/agent_plugins/exploiters/ssh/src/ssh_client.py
> Remove SSH exploiter's dependency on common timeouts

- monkey/agent_plugins/exploiters/zerologon/src/zerologon_utils/dc_utils.py
- monkey/agent_plugins/exploiters/zerologon/src/zerologon_utils/dump_secrets.py
- monkey/agent_plugins/exploiters/zerologon/src/zerologon_utils/wmiexec.py
> Remove Zerologon's dependency on common timeouts

- monkey/agent_plugins/payloads/cryptojacker/src/bitcoin_mining_network_traffic_simulator.py
> Remove Cryptojacker's dependency on common timeouts 

- monkey/infection_monkey/i_puppet/target_host.py
- monkey/infection_monkey/island_api_client/configuration_validator_decorator.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/master/propagator.py
- monkey/tests/unit_tests/infection_monkey/i_puppet/test_fingerprint_data.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_configuration_validator_decorator.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_http_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_registry.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_source_extractor.py
- vulture_allowlist.py
Fixes part of #3732 .
Upgrade everything related to the Agent to pydantic V2
More testing needs to be done as this is merged to the base branch.
> 3732 upgrade agent pydantic to v2

- monkey/agent_plugins/payloads/ransomware/src/ransomware_options.py
- monkey/tests/unit_tests/agent_plugins/credentials_collectors/chrome/test_windows_credentials_database_processor.py
- monkey/tests/unit_tests/agent_plugins/credentials_collectors/mimikatz/test_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/powershell/test_powershell_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/powershell/test_powershell_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/rdp/test_rdp_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/rdp/test_rdp_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/smb/test_smb_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/smb/test_smb_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/snmp/test_snmp_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/ssh/test_ssh_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/ssh/test_ssh_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_smb_options.py
- monkey/tests/unit_tests/agent_plugins/exploiters/zerologon/test_zerologon_options.py
- monkey/tests/unit_tests/agent_plugins/payloads/cryptojacker/test_cryptojacker_options.py
- monkey/tests/unit_tests/agent_plugins/payloads/ransomware/test_ransomware_options.py
Fixes part of #3732.
Updates everything related to Agent Plugins to pydantic V2
More testing needs to be done as soon as this is merge to the base branch
> 3732 upgrade agent plugins pydantic to v2

- monkey/monkey_island/cc/services/agent_configuration_service/hard_coded_schemas/hard_coded_fingerprinter_schemas.py
Fixes a part of #3769
> Tested #3792 which is rebased on this branch
> Add http_ports option to HTTP fingerprinter schema

- monkey/monkey_island/cc/ui/src/components/pages/LoginPage.js
- monkey/monkey_island/cc/ui/src/components/pages/RegisterPage.js
> Fix: inconsistent error messages on login page

- envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py
- envs/monkey_zoo/blackbox/test_configurations/utils.py
Fixes failing BB tests
> AppImage and MSI tests pass. Docker fails due to an unrelated issue.
> Fix blackbox tests

- envs/monkey_zoo/packer/island-linux-250.pkr.hcl
- envs/monkey_zoo/packer/setup_island_linux_250.yml
- envs/monkey_zoo/packer/tasks/linux_install_gcloud.yml
- envs/monkey_zoo/packer/tasks/linux_install_python.yml
- envs/monkey_zoo/packer/tasks/linux_setup_docker.yml
Fixes part of #3711.
Since this includes work to update the linux island machine to ubuntu 20.04, I'm linking it to #3711. This PR includes the work to "packerize" the linux island.
> - Tested by manually running BB tests with docker and AppImage
> - Tested in the automated BB test environment with docker and AppImage
> - Tested the NodeJS v20 islands on it as well
> Island linux packer

- README.md
I've fixed some typos made proper capitalization and corrected some grammatical mistakes
> fix: typos in  README.md

- build_scripts/appimage/appimage.sh
- build_scripts/build_package.sh
- deployment_scripts/config.ps1
- deployment_scripts/deploy_linux.sh
- monkey/monkey_island/readme.md
Fixes #3711.
Updates the deployment scripts, linux builds, and documentation. The Windows build was updated by updating the NodeJS installation on the windows island build machine
> Tested by running the Islands in the zoo environment and observing the UI
> 3711 nodejs 20

- monkey/common/agent_events/tcp_scan_event.py
- monkey/common/types/__init__.py
- monkey/monkey_island/cc/agent_event_handlers/scan_event_handler.py
- monkey/monkey_island/cc/services/reporting/report.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_exploit_client.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/powershell/conftest.py
- monkey/tests/unit_tests/agent_plugins/exploiters/powershell/test_powershell_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/rdp/test_rdp_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/smb/test_smb_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/ssh/test_ssh_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_plugin.py
- monkey/tests/unit_tests/common/agent_events/test_tcp_scan_event.py
- monkey/tests/unit_tests/infection_monkey/exploit/conftest.py
- monkey/tests/unit_tests/infection_monkey/exploit/tools/test_exploit_tools_utils.py
- monkey/tests/unit_tests/infection_monkey/i_puppet/test_target_host.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_http_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_mssql_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ssh_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_tcp_scanner.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_scan_event_handler.py
> 3756 monkeytypes portstatus

- monkey/agent_plugins/payloads/cryptojacker/src/cpu_utilizer.py
- monkey/agent_plugins/payloads/cryptojacker/src/cryptojacker_builder.py
- monkey/agent_plugins/payloads/cryptojacker/src/cryptojacker_options.py
- monkey/agent_plugins/payloads/cryptojacker/src/memory_utilizer.py
- monkey/common/types/__init__.py
- monkey/tests/unit_tests/agent_plugins/payloads/cryptojacker/test_memory_utilizer.py
- monkey/tests/unit_tests/common/types/test_percent.py
> 3756 monkeytypes percentlimited

- monkey/common/agent_events/cpu_consumption_event.py
- monkey/common/agent_events/ram_consumption_event.py
- monkey/common/types/__init__.py
- vulture_allowlist.py
> 3756 monkeytypes percent

- monkey/agent_plugins/payloads/cryptojacker/src/cpu_utilizer.py
- monkey/common/types/__init__.py
> 3756 monkeytypes nonnegativefloat

- monkey/agent_plugins/exploiters/mssql/src/plugin.py
- monkey/common/types/__init__.py
- monkey/monkey_island/cc/agent_event_handlers/scan_event_handler.py
- monkey/monkey_island/cc/models/machine.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_exploit_client.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_plugin.py
- monkey/tests/unit_tests/common/agent_events/test_fingerprinting_event.py
- monkey/tests/unit_tests/infection_monkey/exploit/tools/test_exploit_tools_utils.py
- monkey/tests/unit_tests/infection_monkey/i_puppet/test_fingerprint_data.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_http_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_mssql_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ssh_fingerprinter.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_fingerprinting_event_handler.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_scan_event_handler.py
- monkey/tests/unit_tests/monkey_island/cc/models/test_machine.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_mongo_machine_repository.py
> 3756 monkeytypes networkservice

- monkey/common/types/__init__.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_exploit_client.py
- monkey/tests/unit_tests/agent_plugins/exploiters/powershell/conftest.py
- monkey/tests/unit_tests/common/agent_events/test_fingerprinting_event.py
- monkey/tests/unit_tests/infection_monkey/exploit/conftest.py
- monkey/tests/unit_tests/infection_monkey/i_puppet/test_fingerprint_data.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_http_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_mssql_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ssh_fingerprinter.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_fingerprinting_event_handler.py
> 3756 monkeytypes networkprotocol

- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/log_handlers/monkey_logs_downloader.py
- monkey/common/agent_events/abstract_agent_event.py
- monkey/common/types/__init__.py
- monkey/monkey_island/cc/models/__init__.py
- monkey/monkey_island/cc/models/agent.py
- monkey/monkey_island/cc/models/machine.py
- monkey/monkey_island/cc/models/node.py
- monkey/monkey_island/cc/repositories/agent_machine_facade.py
- monkey/monkey_island/cc/repositories/i_machine_repository.py
- monkey/monkey_island/cc/repositories/i_node_repository.py
- monkey/monkey_island/cc/repositories/mongo_machine_repository.py
- monkey/monkey_island/cc/repositories/mongo_node_repository.py
- monkey/monkey_island/cc/repositories/network_model_update_facade.py
- monkey/monkey_island/cc/services/agent_signals_service.py
- monkey/tests/monkey_island/in_memory_machine_repository.py
- monkey/tests/monkey_island/in_memory_node_repository.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_scan_event_handler.py
> 3756 monkeytypes machineid

- envs/monkey_zoo/blackbox/island_client/monkey_island_requests.py
- monkey/common/agent_event_serializers/i_agent_event_serializer.py
- monkey/common/agent_event_serializers/pydantic_agent_event_serializer.py
- monkey/common/types/__init__.py
- monkey/monkey_island/cc/repositories/agent_event_encryption.py
- monkey/monkey_island/cc/repositories/utils/mongo_encoder.py
- monkey/monkey_island/cc/resources/agent_events.py
- monkey/tests/unit_tests/monkey_island/cc/services/agent_configuration_service/flask_resources/test_agent_configuration.py
> 3756 monkeytypes jsonserializable

- monkey/common/agent_registration_data.py
- monkey/common/types/__init__.py
- monkey/common/utils/environment.py
- monkey/monkey_island/cc/models/machine.py
- monkey/monkey_island/cc/repositories/i_machine_repository.py
- monkey/monkey_island/cc/repositories/mongo_machine_repository.py
- monkey/tests/monkey_island/in_memory_machine_repository.py
> 3756 monkeytypes hardwareid

- monkey/common/agent_events/fingerprinting_event.py
- monkey/common/types/__init__.py
- monkey/tests/unit_tests/common/agent_events/test_fingerprinting_event.py
- monkey/tests/unit_tests/infection_monkey/i_puppet/test_fingerprint_data.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_http_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_mssql_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ssh_fingerprinter.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_fingerprinting_event_handler.py
> 3756 monkeytypes discoveredservice

- monkey/common/agent_configuration/__init__.py
- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/tests/common/example_agent_configuration.py
- monkey/tests/unit_tests/common/agent_configuration/test_agent_configuration.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/configuration_validation_constants.py
> Common: Remove unused `PluginConfiguration`

- monkey/monkey_island/monkey_island.spec
> Island: Use relative path for common in spec file

- CHANGELOG.md
- monkey/common/agent_event_serializers/register.py
- monkey/common/agent_events/__init__.py
- monkey/common/agent_events/register.py
> 3684 fix agent event registration

- monkey/common/agent_event_serializers/register.py
- monkey/common/agent_events/register.py
> 2378 automatic event registration

- CHANGELOG.md
- monkey/common/network/network_utils.py
Fixes #3825
> Tested UI
Before:
After:
> Remove link-local IP option in Run Monkey UI

- monkey/monkey_island/cc/services/authentication_service/flask_resources/register.py
- monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_register.py
> 3807 provide useful username constraint

- .travis.yml
> Update Travis config with Slack notifications token

- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/monkey_island/cc/models/machine.py
- monkey/monkey_island/cc/next_ui/server.js
- monkey/monkey_island/cc/next_ui/src/app/consts.tsx
- monkey/monkey_island/cc/resources/agent_events.py
- monkey/monkey_island/cc/server_setup.py
- monkey/monkey_island/cc/server_utils/consts.py
- monkey/monkey_island/cc/services/aws/aws_command_runner.py
- monkey/monkey_island/cc/services/aws/aws_service.py
- monkey/monkey_island/cc/services/aws/build.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/monkey_island/cc/services/run_local_monkey.py
- monkey/monkey_island/cc/setup/nextjs/nextjs_process.py
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunManually/LocalManualRunOptions.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_curl.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_wget.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_windows_powershell.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/utils/ServerUtils.tsx
- monkey/tests/unit_tests/monkey_island/cc/services/aws/test_aws_command_runner.py
- monkey/tests/unit_tests/monkey_island/cc/services/aws/test_aws_service.py
> Make Island work with configurable port

- monkey/monkey_island/cc/ui/src/components/ui-components/EventsTable.js
Fixes #3813.
Fixes sorting by time in EventsTable.
-------------------------
> Add custom sorter for timestamp in EventsTable

- monkey/monkey_island/cc/feature_flags.py
- monkey/monkey_island/cc/next_ui/src/app/consts.tsx
- monkey/monkey_island/cc/server_setup.py
Adds feature flag for next.js UI and node server
> Island: Add next.js feature flag

- build_scripts/appimage/install-infection-monkey-service.sh
> 3873 fix hanging service

- docs/content/reference/operating_systems_support.md
Improves operating system support documentation
> Docs: Improve operating system support documentation

- monkey/monkey_island/cc/next_ui/next.config.js
> UI: Keep error logs on production

- envs/monkey_zoo/packer/setup_mimikatz_15.yml
- envs/monkey_zoo/packer/smb.pkr.hcl
- envs/monkey_zoo/packer/tasks/windows_disable_powershell_remoting.yml
> Disable powershell remoting on mimikatz-15

- envs/monkey_zoo/blackbox/expected_credentials.py
- envs/monkey_zoo/blackbox/gcp_test_machine_list.py
- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/test_configurations/__init__.py
- envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_2_b.py
- envs/monkey_zoo/packer/setup_mimikatz_14.yml
- envs/monkey_zoo/packer/setup_mimikatz_15.yml
- envs/monkey_zoo/packer/tasks/windows_disable_automatic_logon.yml
- envs/monkey_zoo/packer/tasks/windows_disable_powershell_remoting.yml
- envs/monkey_zoo/packer/tasks/windows_disable_rdp_for_user.yml
- envs/monkey_zoo/packer/tasks/windows_disallow_powershell_remoting_on_subnet.yml
- envs/monkey_zoo/packer/tasks/windows_disallow_rdp_for_subnet.yml
- envs/monkey_zoo/packer/tasks/windows_enable_automatic_logon.yml
- envs/monkey_zoo/terraform/monkey_zoo.tf
Fixes part of #3583.
Fixes #3953. 
> 3583 mimikatz machines

- monkey/monkey_island/cc/next_ui/src/_components/Test.tsx
- monkey/monkey_island/cc/next_ui/src/_components/logout-button/LogoutButton.tsx
> UI: Update the logout button component

- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/packer/setup_log4j_logstash_56.yml
- envs/monkey_zoo/packer/setup_log4j_solr_50.yml
> 3583 block powershell rdp on log4j machines

- .travis.yml
Adds travis check for NextJS UI code.
> Project: Add check for NextJS ui in Travis

- monkey/common/utils/environment.py
- monkey/common/utils/file_utils/secure_directory.py
- monkey/common/utils/file_utils/secure_file.py
- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
- monkey/infection_monkey/dropper.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/info.py
- monkey/infection_monkey/network_scanning/ping_scanner.py
- monkey/infection_monkey/utils/signal_handler.py
- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/monkey_island/cc/server_utils/consts.py
- monkey/monkey_island/cc/setup/nextjs/nextjs_process.py
- monkey/tests/monkey_island/utils.py
- monkey/tests/unit_tests/agent_plugins/payloads/ransomware/test_integrated_ransomware.py
- monkey/tests/unit_tests/agent_plugins/payloads/ransomware/test_internal_ransomware_options.py
- monkey/tests/unit_tests/common/utils/test_file_utils.py
- monkey/tests/unit_tests/conftest.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_source_extractor.py
- monkey/tests/unit_tests/monkey_island/cc/repositories/test_local_storage_file_repository.py
- monkey/tests/unit_tests/monkey_island/cc/setup/test_config_setup.py
> 3984 monkeytoolbox get os

- monkey/agent_plugins/build_plugin.sh
- monkey/agent_plugins/payloads/ransomware/config-schema.json
Fixes #4000 .
[Ransomware-payload.tar.zip](https://github.com/guardicore/monkey/files/13876263/Ransomware-payload.tar.zip)
> 4000 target dir schema

- monkey/infection_monkey/agent_plugin_api_imports.py
- monkey/infection_monkey/main.py
- monkey/infection_monkey/monkey.py
> Enable `reset_modules_cache` 

- monkey/agent_plugins/credentials_collectors/mimikatz/src/plugin.py
- monkey/agent_plugins/credentials_collectors/ssh/src/plugin.py
- monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploit_client.py
- monkey/agent_plugins/exploiters/mssql/src/plugin.py
- monkey/agent_plugins/payloads/cryptojacker/src/plugin.py
- monkey/agent_plugins/payloads/ransomware/src/plugin.py
- monkey/infection_monkey/agent_plugin_api_imports.py
- monkey/infection_monkey/i_puppet/__init__.py
- monkey/infection_monkey/i_puppet/i_fingerprinter.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/i_puppet/ping_scan_data.py
- monkey/infection_monkey/master/ip_scan_results.py
- monkey/infection_monkey/master/ip_scanner.py
- monkey/infection_monkey/network_scanning/http_fingerprinter.py
- monkey/infection_monkey/network_scanning/mssql_fingerprinter.py
- monkey/infection_monkey/network_scanning/ping_scanner.py
- monkey/infection_monkey/network_scanning/smb_fingerprinter.py
- monkey/infection_monkey/network_scanning/ssh_fingerprinter.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ping_scanner.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
> 4010 migrate ping scan data

- monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploiter.py
- monkey/agent_plugins/exploiters/log4shell/src/plugin.py
- monkey/agent_plugins/exploiters/mssql/src/plugin.py
- monkey/agent_plugins/exploiters/snmp/src/plugin.py
- monkey/infection_monkey/agent_plugin_api_imports.py
- monkey/infection_monkey/exploit/http_agent_binary_server.py
- monkey/infection_monkey/exploit/http_agent_binary_server_factory.py
- monkey/infection_monkey/network/__init__.py
- monkey/infection_monkey/network/info.py
- monkey/infection_monkey/network/tcp_port_selector.py
- monkey/infection_monkey/plugin/exploiter_plugin_factory.py
- monkey/tests/agent_plugins/exploiter_plugin_runner.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_exploiter.py
- monkey/tests/unit_tests/conftest.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_http_agent_binary_server.py
- monkey/tests/unit_tests/infection_monkey/exploit/tools/test_http_bytes_server.py
- monkey/tests/unit_tests/infection_monkey/network/test_tcp_port_selector.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_registry.py
> 4010 migrate i tcp port selector

- monkey/agent_plugins/payloads/cryptojacker/src/plugin.py
- monkey/agent_plugins/payloads/ransomware/src/plugin.py
- monkey/infection_monkey/agent_plugin_api_imports.py
- monkey/infection_monkey/i_puppet/__init__.py
- monkey/infection_monkey/i_puppet/payload_result.py
- monkey/tests/data_for_tests/payload_plugin/src/plugin.py
> 4010 migrate payload result

- monkey/agent_plugins/credentials_collectors/mimikatz/Pipfile.lock
- monkey/agent_plugins/credentials_collectors/ssh/Pipfile.lock
- monkey/agent_plugins/exploiters/hadoop/Pipfile.lock
- monkey/agent_plugins/exploiters/log4shell/Pipfile.lock
- monkey/agent_plugins/exploiters/mssql/Pipfile.lock
- monkey/agent_plugins/exploiters/powershell/Pipfile.lock
- monkey/agent_plugins/exploiters/rdp/Pipfile.lock
- monkey/agent_plugins/exploiters/smb/Pipfile.lock
- monkey/agent_plugins/exploiters/snmp/Pipfile.lock
- monkey/agent_plugins/exploiters/ssh/Pipfile.lock
- monkey/agent_plugins/exploiters/wmi/Pipfile.lock
- monkey/agent_plugins/exploiters/zerologon/Pipfile.lock
- monkey/agent_plugins/payloads/cryptojacker/Pipfile.lock
- monkey/agent_plugins/payloads/ransomware/Pipfile.lock
Updates plugins' locked dependencies since monkey-agentpluginapi v2 was released
> Update plugins' locked dependencies

- monkey/infection_monkey/Pipfile.lock
> Agent: Update locked dependencies

- monkey/infection_monkey/dropper.py
> Agent: Remove unused argument to dropper

- monkey/monkey_island/cc/next_ui/src/app/(auth)/_lib/useAuthenticatedRedirect.tsx
- monkey/monkey_island/cc/next_ui/src/app/(auth)/layout.tsx
- monkey/monkey_island/cc/next_ui/src/app/(auth)/signin/page.tsx
- monkey/monkey_island/cc/next_ui/src/app/(auth)/signin/useRedirectToRegistration.tsx
- monkey/monkey_island/cc/next_ui/src/app/(auth)/signup/page.tsx
- monkey/monkey_island/cc/next_ui/src/app/(auth)/signup/useRedirectToLogin.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/_lib/useRedirectionOnLogout.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/_lib/useRedirectionWhenUnauthenticated.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/layout.tsx
- monkey/monkey_island/cc/next_ui/src/redux/features/api/authentication/authenticationEndpoints.ts
Fixes redirects between authenticated/protected pages
> going to authentication page when already logged in
> going to protected page when not authenticated
> going to login when registration is needed
> going to registration when already registered
> 3900 authentication redirects

- .travis.yml
- monkey/monkey_island/cc/next_ui/jest.config.js
- monkey/monkey_island/cc/next_ui/jest.config.ts
- monkey/monkey_island/cc/next_ui/package-lock.json
- monkey/monkey_island/cc/next_ui/package.json
- monkey/monkey_island/cc/next_ui/src/lib/authenticationToken.test.ts
- monkey/monkey_island/cc/next_ui/src/lib/authenticationToken.tsx
- monkey/monkey_island/cc/next_ui/src/lib/localStorage.test.ts
- monkey/monkey_island/cc/next_ui/tsconfig.json
Fixes part of #765.
- Add Jest test framework
- Add some unit tests
> 765 add jest

- monkey/monkey_island/cc/next_ui/src/app/(auth)/registration/page.tsx
- monkey/monkey_island/cc/next_ui/src/app/(auth)/registration/style.ts
Finishes up the styling of the registration page.
Once the theming is done it will look like: 
> Tested by navigating
> 3900 registration screen style

- monkey/agent_plugins/exploiters/log4shell/src/log4shell_command_builder.py
- monkey/agent_plugins/exploiters/snmp/src/plugin.py
- monkey/agent_plugins/exploiters/ssh/src/ssh_command_builder.py
- monkey/infection_monkey/command_builders/__init__.py
- monkey/infection_monkey/command_builders/agent_command_builder_factory.py
- monkey/infection_monkey/command_builders/linux_agent_command_builder.py
- monkey/infection_monkey/command_builders/utils.py
- monkey/infection_monkey/command_builders/windows_agent_command_builder.py
- monkey/infection_monkey/dropper.py
- monkey/infection_monkey/utils/commands.py
- monkey/tests/unit_tests/infection_monkey/command_builders/conftest.py
- monkey/tests/unit_tests/infection_monkey/command_builders/test_command_utils.py
- monkey/tests/unit_tests/infection_monkey/command_builders/test_linux_agent_command_builder.py
- monkey/tests/unit_tests/infection_monkey/command_builders/test_windows_agent_command_builder.py
- monkey/tests/unit_tests/infection_monkey/utils/test_commands.py
- vulture_allowlist.py
> 4042 concrete command builders

- monkey/agent_plugins/exploiters/hadoop/src/plugin.py
- monkey/agent_plugins/exploiters/log4shell/src/plugin.py
- monkey/agent_plugins/exploiters/mssql/src/plugin.py
- monkey/agent_plugins/exploiters/powershell/src/plugin.py
- monkey/agent_plugins/exploiters/rdp/src/plugin.py
- monkey/agent_plugins/exploiters/smb/src/plugin.py
- monkey/agent_plugins/exploiters/snmp/src/plugin.py
- monkey/agent_plugins/exploiters/ssh/src/plugin.py
- monkey/agent_plugins/exploiters/wmi/src/plugin.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/plugin/exploiter_plugin_factory.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/mssql/test_mssql_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/powershell/test_powershell_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/rdp/test_rdp_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/smb/test_smb_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/ssh/test_ssh_plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_plugin.py
> 4042 pass command builder factory to plugins

- monkey/monkey_island/cc/next_ui/next.config.js
- monkey/monkey_island/cc/next_ui/src/_components/app-nav/app-menu/AppMenu.tsx
- monkey/monkey_island/cc/next_ui/src/_components/app-nav/app-sidebar/AppSidebar.tsx
- monkey/monkey_island/cc/next_ui/src/_components/app-nav/app-sidebar/SidebarItem.tsx
- monkey/monkey_island/cc/next_ui/src/_components/app-nav/app-sidebar/style.ts
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/available/page.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/installed/page.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/layout.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/page.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/pluginPages.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/pluginSidebar.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/upload/page.tsx
Fixes navigation tab task from #3916
> 3916 plugin nav tabs

- monkey/agent_plugins/credentials_collectors/chrome/Pipfile.lock
- monkey/agent_plugins/credentials_collectors/mimikatz/Pipfile.lock
- monkey/agent_plugins/credentials_collectors/ssh/Pipfile.lock
- monkey/agent_plugins/exploiters/hadoop/Pipfile.lock
- monkey/agent_plugins/exploiters/log4shell/Pipfile.lock
- monkey/agent_plugins/exploiters/mssql/Pipfile.lock
- monkey/agent_plugins/exploiters/powershell/Pipfile.lock
- monkey/agent_plugins/exploiters/rdp/Pipfile.lock
- monkey/agent_plugins/exploiters/smb/Pipfile.lock
- monkey/agent_plugins/exploiters/snmp/Pipfile.lock
- monkey/agent_plugins/exploiters/ssh/Pipfile.lock
- monkey/agent_plugins/exploiters/wmi/Pipfile.lock
- monkey/agent_plugins/exploiters/zerologon/Pipfile.lock
- monkey/agent_plugins/payloads/cryptojacker/Pipfile.lock
- monkey/agent_plugins/payloads/ransomware/Pipfile.lock
- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
> 4011 update plugins agentpluginapi

- monkey/monkey_island/cc/next_ui/.gitignore
- monkey/monkey_island/cc/next_ui/cypress.config.ts
- monkey/monkey_island/cc/next_ui/cypress/cypress.d.ts
- monkey/monkey_island/cc/next_ui/cypress/e2e/spec.cy.ts
- monkey/monkey_island/cc/next_ui/cypress/support/component-index.html
- monkey/monkey_island/cc/next_ui/cypress/support/component.tsx
- monkey/monkey_island/cc/next_ui/cypress/tsconfig.json
- monkey/monkey_island/cc/next_ui/package-lock.json
- monkey/monkey_island/cc/next_ui/package.json
- monkey/monkey_island/cc/next_ui/src/_components/drawer/DrawerMonkeyDrawer.cy.tsx
- monkey/monkey_island/cc/next_ui/src/_components/logout-button/LogoutButton.cy.tsx
Fixes #765.
- Adds E2E tests for registration, login. Note that this requires the Island to be running, and a clean island data dir
- Adds simple "does it render?" component tests for the LogoutButton and MonkeyDrawer components
> 765 add cypress

- monkey/agent_plugins/exploiters/snmp/src/plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/snmp/test_snmp_plugin.py
> SNMP: Add tests for Plugin class

- monkey/agent_plugins/exploiters/hadoop/Pipfile
- monkey/agent_plugins/exploiters/hadoop/Pipfile.lock
- monkey/agent_plugins/exploiters/log4shell/Pipfile
- monkey/agent_plugins/exploiters/log4shell/Pipfile.lock
- monkey/agent_plugins/exploiters/mssql/Pipfile
- monkey/agent_plugins/exploiters/mssql/Pipfile.lock
- monkey/agent_plugins/exploiters/powershell/Pipfile
- monkey/agent_plugins/exploiters/powershell/Pipfile.lock
- monkey/agent_plugins/exploiters/rdp/Pipfile
- monkey/agent_plugins/exploiters/rdp/Pipfile.lock
- monkey/agent_plugins/exploiters/smb/Pipfile
- monkey/agent_plugins/exploiters/smb/Pipfile.lock
- monkey/agent_plugins/exploiters/snmp/Pipfile
- monkey/agent_plugins/exploiters/snmp/Pipfile.lock
- monkey/agent_plugins/exploiters/ssh/Pipfile
- monkey/agent_plugins/exploiters/ssh/Pipfile.lock
- monkey/agent_plugins/exploiters/wmi/Pipfile
- monkey/agent_plugins/exploiters/wmi/Pipfile.lock
- monkey/agent_plugins/payloads/ransomware/Pipfile
- monkey/agent_plugins/payloads/ransomware/Pipfile.lock
> 4011 install plugintoolbox to plugins

- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/available/PluginInstallationButton.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/available/page.tsx
- monkey/monkey_island/cc/next_ui/src/redux/features/api/agentPlugins/agentPluginEndpoints.tsx
- monkey/monkey_island/cc/next_ui/src/redux/features/api/agentPlugins/types.ts
Adds plugin installation button,
Merge #4096 first
> 3916 plugin installation button

- monkey/agent_plugins/exploiters/powershell/src/powershell_remote_access_client_factory.py
- monkey/agent_plugins/exploiters/rdp/src/rdp_remote_access_client_factory.py
- monkey/agent_plugins/exploiters/smb/src/smb_remote_access_client_factory.py
- monkey/agent_plugins/exploiters/ssh/src/ssh_remote_access_client_factory.py
- monkey/agent_plugins/exploiters/wmi/src/wmi_remote_access_client_factory.py
- monkey/infection_monkey/exploit/tools/__init__.py
- monkey/infection_monkey/exploit/tools/i_remote_access_client_factory.py
> 4011 migrate i remote access client factory

- CHANGELOG.md
- monkey/monkey_island/cc/services/run_local_monkey.py
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunManually/LocalManualRunOptions.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_curl.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_wget.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_windows_powershell.js
Fixes #2593 .
> Tested by manually running the commands
> 2593 add servers to run commands

- .travis.yml
- monkey/monkey_island/cc/ui/package-lock.json
- monkey/monkey_island/cc/ui/package.json
Issue #`put issue number here`.
> Project: Travis should use the same eslint version as UI

- monkey/monkey_island/cc/next_ui/package-lock.json
- monkey/monkey_island/cc/next_ui/package.json
- monkey/monkey_island/cc/next_ui/src/_components/alerts/MonkeyAlert.tsx
- monkey/monkey_island/cc/next_ui/src/_components/errors/ErrorList.tsx
- monkey/monkey_island/cc/next_ui/src/_components/file-upload/MonkeyFileUpload.tsx
- monkey/monkey_island/cc/next_ui/src/_components/file-upload/style.ts
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/installed/InstalledPluginFilters.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/installed/page.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/upload/page.tsx
- monkey/monkey_island/cc/next_ui/src/redux/features/api/agentPlugins/agentPluginEndpoints.tsx
- monkey/monkey_island/cc/next_ui/src/redux/features/api/agentPlugins/types.ts
- monkey/monkey_island/cc/next_ui/src/redux/features/api/islandApiSlice.ts
- Adds upload page
- Adds basic installed plugins page
> Tested by manually uploading/removing plugins
> 3916 upload page

- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/installed/InstalledPluginFilters.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/installed/PluginUpgradeButton.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/installed/page.tsx
- monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/upload/page.tsx
- monkey/monkey_island/cc/next_ui/src/redux/features/api/agentPlugins/agentPluginEndpoints.tsx
- monkey/monkey_island/cc/next_ui/src/redux/features/api/agentPlugins/responseParsers.ts
- monkey/monkey_island/cc/next_ui/src/redux/features/api/agentPlugins/types.ts
- monkey/monkey_island/cc/next_ui/src/redux/features/api/islandApiSlice.ts
Issue #3916 
Add plugin update button
> UI: Implement plugin upgrade button

- monkey/agent_plugins/exploiters/snmp/Pipfile.lock
- monkey/agent_plugins/exploiters/snmp/src/plugin.py
- monkey/infection_monkey/Pipfile.lock
- monkey/infection_monkey/command_builders/linux_agent_command_builder.py
- monkey/infection_monkey/command_builders/windows_agent_command_builder.py
- monkey/tests/unit_tests/infection_monkey/command_builders/test_linux_agent_command_builder.py
- monkey/tests/unit_tests/infection_monkey/command_builders/test_windows_agent_command_builder.py
Issue #`put issue number here`.
> 4201 remove otp from bash dropper

- docs/content/FAQ/_index.md
- docs/content/reference/release-artifact-checksums.md
- docs/content/reference/release-artifact-hashes.md
- docs/content/setup/_index.md
Rework release artifact checksums
> Move release artifact checksums

- docs/content/features/polymorphism.md
Improves polymorphism explanation.
> Docs: Improve polymorphism documentation

- docs/content/reference/payloads/cryptojacker.md
This PR removes the "Type" sections in the Cryptojacker reference page since none of the other pages have this.
> Tested with Hugo
> Update Cryptojacker reference page

- monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploiter.py
- monkey/agent_plugins/exploiters/hadoop/src/plugin.py
- monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploiter.py
- monkey/agent_plugins/exploiters/log4shell/src/plugin.py
- monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_exploiter.py
- monkey/tests/unit_tests/agent_plugins/exploiters/zerologon/test_zerologon.py
> Remove infection monkey imports from plugins

- docs/content/features/ransomware-simulation.md
- docs/content/howtos/simulate-ransomware.md
Fixes #4214 
> Tested with Hugo
> Rewrite ransomware docs 

- docs/content/howtos/factory-reset.md
Reformat the steps in the factory reset howto document to make them consistent with the Ransomware howto.
> Docs: Reformat factory reset howto steps

- build_scripts/build_agent_linux.sh
> Build: Modify build_agent_linux to use non-root agent-builder

- README.md
Issue #`put issue number here`.
> Project: Fix map and report images in README

- CHANGELOG.md
- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/infection_monkey/network_scanning/scan_target_generator.py
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/scanTarget.js
- monkey/tests/unit_tests/common/agent_configuration/test_agent_configuration.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_scan_target_generator.py
Fixes #4276
> Tested manually by running the Island and Agent locally
> Support ranges for blocked IPs
