guardicore/monkey

chaos_monkey/__init__.py, chaos_monkey/config.py, chaos_monkey/control.py, chaos_monkey/requirements.txt, chaos_monkey/test/config__test.py, monkey_island/cc/main.py
Instead of crashing if the monkey deserializes an unknown configuration
variable, send an error message to the current monkey server and keep on
working.
fixes #26
=> Don't crash when receiving unknown configuration variables

monkey_island/cc/resources/root.py
Fixed small bug #102 : In navigation, under "Report generated" tick appeared even if map is not done being generated.
=> Bugfix(102) V under report generated after new monkey ran

infection_monkey/exploit/tools.py, infection_monkey/network/info.py
Part of a bite-sized approach to #119
- Define long in Python 3
- The trailing L on numeric literals is no longer required in Python 2 and is a Syntax Error in Python 3
-
=> long was removed in Python 3

.travis.yml
Travis Continuous Integration is free for all open source projects like this one.  This config file would have Travis CI run [flake8](http://flake8.pycqa.org) tests to find Python syntax errors and undefined names in all pull requests _before_ they are reviewed.  To turn Travis CI on, visit https://travis-ci.com/guardicore
- Add Travis CI to do automated testing of pull requests before they are reviewed
-
-
=> Travis CI for automated testing of all pull requests

infection_monkey/transport/ftp.py
__local_ip__ is an __undefined name__ in this context (could raise [__NameError__](https://docs.python.org/3/library/exceptions.html#NameError) at runtime) so this PR recommends the use of __self.local_ip__ instead.  
flake8 testing of https://github.com/guardicore/monkey on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./infection_monkey/transport/ftp.py:86:29: F821 undefined name 'local_ip'
self.servsock.bind((local_ip,0))
^
```
=> ftp.py: Undefined name local_ip --> self.local_ip

infection_monkey/config.py, infection_monkey/example.conf, infection_monkey/exploit/__init__.py, infection_monkey/exploit/struts2.py, infection_monkey/model/__init__.py, monkey_island/cc/resources/monkey_download.py, monkey_island/cc/services/config.py, monkey_island/cc/services/report.py, monkey_island/cc/ui/src/components/pages/ReportPage.js
Struts2 remote code execution exploitation added: <br>
https://cwiki.apache.org/confluence/display/WW/S2-045<br>
Tested on windows 10 and ubuntu(struts2 2.3.15.1 and tomcat 9.0.0.M9)<br>
Monkey can now propagate using above mentioned vulnerability and if it does
so successfully, warnings and recomendations are shown in report
=> Struts2 rce

infection_monkey/exploit/struts2.py, infection_monkey/exploit/tools.py, infection_monkey/exploit/web_rce.py, infection_monkey/model/__init__.py, infection_monkey/network/tcp_scanner.py, infection_monkey/network/tools.py, infection_monkey/transport/__init__.py, infection_monkey/transport/http.py
> Created a framework for web rce implementation. It saves code and makes logging more standard.
>Created a locked http server to avoid race conditions
Tested with struts2 and oracle web logic blind vulnerability. Framework is more or less usefull in both of them
=> Web rce framework

infection_monkey/exploit/web_rce.py
Small fix that sets default monkey path to None in constructor's annotation (now you dont need to pass "None" while creating instance of framework to have default values)
=> Changed constructor to have default paths set to None for convienience

infection_monkey/config.py, infection_monkey/exploit/sambacry.py, infection_monkey/exploit/tools.py, infection_monkey/monkey.spec, infection_monkey/pyinstaller_utils.py, infection_monkey/readme.txt, infection_monkey/system_info/mimikatz_collector.py, infection_monkey/system_info/windows_info_collector.py, infection_monkey/utils.py, monkey_island/cc/services/config.py
> Mimikatz is now inside password protected zip, and extracted only if config says so.
=> Make mimikatz inside zip and extract only if config says so

infection_monkey/exploit/tools.py, infection_monkey/exploit/web_rce.py
> In the case that firewall blocks user from opening http server LOG shows that and web_rce framework does not spit errors.
=> Improved error handling if firewall does not allow to open http server

monkey/infection_monkey/network/tools.py
Fixes the port scanner to not timeout due to typo
=> Fix typo in tcp_scan_ports

monkey/monkey_island/cc/main.py, monkey/monkey_island/cc/resources/monkey_configuration.py, monkey/monkey_island/cc/services/config.py, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
While testing the develop code for version 1.6, two bugs came up:
* Log file wasn't being written on disc
* When trying to submit an outdated configuration file in the monkey island the server would return error 500 and the page would crash.
- Updated the path to the logging json configuration file to be generic relative using os.path
- Added a small and specific error handling for the specific configuration submission endpoint for now.
=> Fix/bugfix for 1.6

monkey/monkey_island/readme.txt
> On windows bit deffender starts deleting files and it's really not obvious as it deletes __init__.py files and you get module not found errors. Tested on multiple 
> Mongo db throws error if there is none db folder
=> Added a few missing steps to monkey_island setup instructions 

monkey/infection_monkey/exploit/rdpgrinder.py, monkey/infection_monkey/utils.py
Bugfix for https://github.com/guardicore/monkey/issues/206
Tested on GCP, with utf -> ascii and ascii -> ascii
=> Fixes the problem of rdp grinder not being able to handle utf encoded credentials.

monkey/monkey_island/cc/ui/src/styles/App.css
Before:
After:
Tests:
Quickly went trough all the pages, but these changes shouldn't target other elements if nav-tabs is aunique class.
=> Makes all tabs of equal height

monkey/infection_monkey/exploit/web_rce.py
> Some services are added to the host.services array without 'name' property. Thus we need to make sure it exists
=> Small bugfix for web_rce get_open_service_ports function

monkey/infection_monkey/exploit/hadoop.py, monkey/infection_monkey/model/__init__.py
> Hadoop windows now uploads and executes on 64 bit windows.
MonkeyZoo tests showed that:
1. Bits admin command doesn't work in hadoop environment.
2. Hadoop runs as a job. It means that if we upload monkey32 this happens:
A. monkey32 spawns monkey64
B. monkey64 starts execution
C. monkey32 shuts down
D. all monkey32 children processes gets terminated (in this case monkey64 is killed mid-execution)
For these reasons upload command was changed to powershell and only monkey64.exe is used in exploitation process.
=> Hadoop windows fixed to be more reliable

README.md, deployment_scripts/README.md, deployment_scripts/config, deployment_scripts/config.ps1, deployment_scripts/deploy_linux.sh, deployment_scripts/deploy_windows.ps1, deployment_scripts/run_script.bat, monkey/infection_monkey/readme.txt, monkey/monkey_island/readme.txt
Added deployment scripts. 
> These scripts are made so that developers could install all of the dependencies for development version of monkey in one go.
=> Deployment scripts

monkey/infection_monkey/exploit/shellshock.py
> Sending requests in shellshock module had no timeout handling.
If timeout happens for any request, we just continue sending other requests. At the end we inform that timeout happened (we don't inform about particular urls because that would trash the log)
=> Shellshock timeout exception handling

monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage.js
After testing the monkey run-line that is generated in the monkey island gui on servral OSs, we saw that curl wasn't installed out of the box while wget was present on all of them already. So we decided to change download methods.
- Changed curl to wget, its available out of the box on more OSs.
=> Changing curl usage to wget on monkey island gui

monkey/monkey_island/cc/ui/src/components/pages/ReportPage.js
When we updated our mocha dependency we fixed the color in the map pane and not in the report.
=> Bugfix - report map colored again

monkey/infection_monkey/exploit/elasticgroovy.py, monkey/infection_monkey/model/__init__.py
> Elastic wouldn't execute on windows because java needed cmd prefix to understand cmd commands. I added the prefix and tested it on MonkeyZoo
=> Elastic windows exploitation bugfix

monkey/infection_monkey/config.py, monkey/infection_monkey/example.conf, monkey/infection_monkey/monkey.py, monkey/infection_monkey/network/network_scanner.py, monkey/infection_monkey/network/ping_scanner.py, monkey/monkey_island/cc/services/config.py, monkey/monkey_island/cc/services/config_schema.py
Lets use our `PingScanner` to scan machines using ICMP and not just port scan.
This is useful for the cross segment analysis, letting us find machines open to ICMP and not just specific ports.
In addition, remove option to pick specific scanner, since now we constantly want to use both.
Still to be done, add it to fingerprinting.
=> Search for new machines using ICMP and not just port scan

monkey/common/network/network_range.py, monkey/infection_monkey/model/host.py, monkey/infection_monkey/network/network_scanner.py, monkey/monkey_island/cc/resources/telemetry.py, monkey/monkey_island/cc/services/config.py, monkey/monkey_island/cc/services/node.py, monkey/monkey_island/cc/services/report.py, monkey/monkey_island/cc/ui/src/components/report-components/BreachedServers.js, monkey/monkey_island/cc/ui/src/components/report-components/ScannedServers.js
> Domain name can now be entered alongside IP's to scan. If domain name gets successfully translated and scanned it's added to corresponding parts of report and map.
=> Domain name to ip translation

monkey/monkey_island/cc/services/wmi_handler.py
Attempts to fix https://github.com/guardicore/monkey/issues/250
=> wmi info handler does not crash if no wmi info is collected

monkey/infection_monkey/exploit/mssqlexec.py
> _config import is handled by parent class constructor (HostExploiter) so we don't need it
=> Fixes the config import on MSSQL exploiter

monkey/monkey_island/cc/resources/telemetry.py
Scanner field was removed (when implementing ICMP scanner) from machines on monkey, but Island still expects to get 'scanner' field on it's telemetry.
=> Fixed a bug where telemetry expects a 'scanner' field

monkey/infection_monkey/exploit/web_rce.py, monkey/infection_monkey/exploit/weblogic.py
Improved the speed of weblogic exploiter by firing all requests virtually at the same time. Downside is that we loose the knowledge which url's are vulnerable and which aren't. 
If any of them are vulnerable the machine is marked as exploited, but monkey only tries to exploit first url in the list.
From my experience all url's we try are standard server url's and if one is exploitable, all of them are.
=> Improved the speed of weblogic exploiter

monkey/monkey_island/cc/services/report.py
> Fixes typo, where instead of node dict we should reference monkey dict
=> Fixed bug (from node['domain_name'] to monkey['domain_name']

monkey/infection_monkey/requirements_linux.txt
Added pymssql and pyftpdlib into monkey's linux requiremets (linux requirements didn't get updated during rebase)
=> Quickfix for requirement separation pr

monkey/infection_monkey/requirements_linux.txt, monkey/infection_monkey/requirements_windows.txt, monkey/monkey_island/cc/environment/__init__.py, monkey/monkey_island/cc/environment/aws.py, monkey/monkey_island/cc/environment/environment.py, monkey/monkey_island/cc/environment/password.py, monkey/monkey_island/cc/ui/package-lock.json, monkey/monkey_island/cc/ui/package.json, monkey/monkey_island/cc/ui/src/server_config/PasswordConfig.js, monkey/monkey_island/cc/ui/src/server_config/ServerConfig.js, monkey/monkey_island/cc/ui/src/services/AuthService.js, monkey/monkey_island/deb-package/monkey_island_pip_requirements.txt, monkey/monkey_island/requirements.txt
> Add option to authenticate with island using password
- Add option to authenticate with island using password
- Replace PyCrypto with Cryptodome (Fixes #234 )
=> Add option for password authentication with island

monkey/infection_monkey/exploit/sambacry.py
> Fixes bug where failed credentials would throw uncaught exception
=> Sambacry now catches NetBIOSError on attempting credentials

monkey/common/utils/exploit_enum.py, monkey/infection_monkey/exploit/__init__.py, monkey/infection_monkey/exploit/mssqlexec.py, monkey/infection_monkey/exploit/rdpgrinder.py, monkey/infection_monkey/exploit/smbexec.py, monkey/infection_monkey/exploit/sshexec.py, monkey/infection_monkey/exploit/wmiexec.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/requirements_linux.txt, monkey/infection_monkey/requirements_windows.txt
> Implemented the ability to add a type to an exploiter (vulnerability/brute-force)
> Exploitation sequence are now determined by type (default is vulnerabilities -> other -> brute-forcers)
> In case of a vulnerable server that has brute-force prevention (like sshguard on ubuntu servers) it now get exploited instead of just blocking communications with island
> Refactored monkey.py host exploitation workflow into functions
Sanity test on local machine
=> Exploitation order + tiny monkey.py refactor

monkey/monkey_island/linux/create_certificate.sh
deb package creates a key of length 1024 by default and and since the release of openssl 1.1.1 the default openssl.conf file at /etc/ssl/openssl.conf  has CipherString = DEFAULT@SECLEVEL=2 , resulting in the key length to be small.  In order to adhere to SECLEVEL=2 the key length was increased from 1024 to 2048.
=> Updated Create_certificate to key of length 2048

monkey/infection_monkey/exploit/mssqlexec.py, monkey/infection_monkey/exploit/mssqlexec_utils.py
> MSSQL exploiter now uploads and executes a payload.
Fixed: 
FTP server now listens to incoming remote connections
FTP server now opens in the dir where payload is, rather than in monkey dir (and remote host can access 
and download the payload)
Fixed race condition.
Exploiter still doesn't execute monkey on remote host. Instead it executes dummy command, that does nothing. 
So we still need to:
1. Choose the monkey binary
2. Upload it and execute it.
For now, this fix at least shows users that their server is vulnerable.
=> MSSQL now is able to upload a payload

monkey/monkey_island/cc/ui/src/components/pages/ReportPage.js
Fix for issue #213
> Fix for Domain related recommendations showing up even if it is empty
Insted of just doing 
`<h3>
Domain related recommendations
</h3>`
we check if the object is not empty before printing the heading.
`{Object.keys(this.state.report.recommendations.domain_issues).length !=0 ? <h3>Domain related recommendations</h3> : null }`
=> Updated ReportPage.js

monkey/infection_monkey/exploit/sshexec.py
> Paramiko might throw various exceptions while trying to connect to host. It's hard to enumerate them all, so it's more stable to handle them all.
=> Reverted ssh exception handling changes.

monkey/infection_monkey/exploit/struts2.py, monkey/monkey_island/cc/services/config_schema.py
> Fixes this issue: https://github.com/guardicore/monkey/issues/306
> Struts2 ignores invalid certificates
> Improved configuration description, stating that user can input host names.
=> Struts2 ignores certificate errors, updated schema

monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> After import you can change to attack config without warnings.
> After import you are not thrown into a different configuration tab.
=> Import made compatible with attack config

monkey/monkey_island/cc/database.py, monkey/monkey_island/cc/main.py
Also refactored a bit to make the main shorter.
Fixes #337 
> `sudo+ssh://shay@10.15.1.115:22/usr/bin/python -u /home/shay/monkey/monkey/monkey_island.py
2019-06-05 19:24:37,119 - environment.py:46 -   <module>() - INFO - Monkey's env is: StandardEnvironment
2019-06-05 19:24:38,104 - main.py:60 - wait_for_mongo_db_server() - INFO - Waiting for MongoDB server on mongodb://localhost:27017/monkeyisland
2019-06-05 19:24:39,608 - main.py:60 - wait_for_mongo_db_server() - INFO - Waiting for MongoDB server on mongodb://localhost:27017/monkeyisland
2019-06-05 19:24:41,113 - main.py:60 - wait_for_mongo_db_server() - INFO - Waiting for MongoDB server on mongodb://localhost:27017/monkeyisland
2019-06-05 …
=> [DONE] Added assertion of mongo db version.

monkey/infection_monkey/config.py, monkey/infection_monkey/example.conf, monkey/infection_monkey/exploit/mssqlexec.py, monkey/infection_monkey/utils.py, monkey/monkey_island/cc/services/config_schema.py
Instead of predetermined tmp paths.
Fixes #348 .
After running the monkey locally...
```
C:\users\shay~1.neh\appdata\local\temp>dir | findstr monkey_dir
12/06/2019  17:51    <DIR>          monkey_dir
```
- Now using tempfile to create monkey directory
=> [CR] Use tempfile to create monkey directory

monkey/infection_monkey/transport/http.py
For some reason the previous bugfix stopped working (it was setting `closed_connection = 1` on http server object, not on request handler).
=> HTTP servers' bugfix

monkey/infection_monkey/post_breach/pba.py, monkey/monkey_island/cc/resources/telemetry_feed.py
> PBA doesn't crash if hostname lookup fails [360](https://github.com/guardicore/monkey/issues/360)
=> PBA handles hostname lookup failure

monkey/monkey_island/cc/services/config_schema.py
The monkey will delete itself after going down by default. 
=> self_delete_in_cleanup default is now True

monkey/monkey_island/requirements.txt
Fix missing requirement dpath in Island
@ShayNehmad what ideas did you have about making sure this never happens?
=> Add missing requirement

monkey/infection_monkey/system_info/windows_info_collector.py, monkey/monkey_island/cc/services/attack/technique_reports/T1145.py
> Mimikatz logs successful credential gathering
> Private key attack technique query fixed according to changed telemetry type
=> Attack: private key query fix, mimikatz: log message.

monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> Fixes a bug where you can't submit changed config after import.
Refactored config import not to change current section on import.
Refactored 'onReadFile' to 'setConfigOnImport'
=> Bugfix: can't submit on import

monkey/infection_monkey/exploit/__init__.py, monkey/infection_monkey/exploit/shellshock.py
> Fixes for #199. Create a locking mechanism to avoid 2 monkeys downloading exploit binaries at the same time. The lock is implemented by checking if a file exists on the target machine
=> Enter lock in Shellshock exploit

monkey/infection_monkey/monkey.py
> Fixes monkey sending wrong telemetry on cleanup which results in monkey not reporting it's death
=> Bugfix for monkey not reporting being dead

monkey/infection_monkey/exploit/weblogic.py
> Weblogic exploiter made more reliable with delay that fixes race condition between saving monkey binary and launching it.
=> Delay in weblogic to make exploiter more reliable

monkey/monkey_island/cc/models/monkey.py, monkey/monkey_island/cc/models/test_monkey.py, monkey/monkey_island/cc/services/attack/technique_reports/technique_report_tools.py, monkey/monkey_island/cc/services/edge.py, monkey/monkey_island/cc/services/node.py, monkey/monkey_island/cc/services/reporting/report.py, monkey/monkey_island/cc/services/telemetry/processing/system_info.py, monkey/monkey_island/cc/utils.py, monkey/monkey_island/requirements.txt
Fixes #441.
From: 
To (Middle of progress): 
To (final):
- Improved runtime of the `get_displayed_node_by_id` function via caching
- Improved runtime of the `get_scanned` function via algorithmic improvments
- Other small optimisations in EdgeService and NodeService via caching mostly.
=> [WIP] 441/bugfix/slow report generation with plenty of machines

monkey/monkey_island/cc/resources/telemetry_feed.py
> Telemetries that don't require briefs no longer throws errors in island.
=> Fixed bug in telemetry feed

envs/monkey_zoo/blackbox/tests/basic_test.py, monkey/infection_monkey/exploit/__init__.py, monkey/infection_monkey/exploit/mssqlexec.py, monkey/infection_monkey/monkey.py, monkey/monkey_island/cc/ui/src/components/pages/MapPage.js
Note:
With the latest changes we can improve exploiter code in following way:
Before:
``` 
def exploit_host(host):
result = brute_force(host)
if not result:
return False
def brute_force(host):
try:
try_brute_force(host)
except Exception:
Log.debug("Brute force failed)
return False
```
Now:
``` 
def exploit_host(host):
result = brute_force(host)
def brute_force(host):
try:
try_brute_force(host)
except Exception:
raise FailedExploitationError("Brute force failed)
```
Note that FailedExploitationError allows us to remove `if not some_func(): return False` statements and makes code cleaner.
=> Py3 logging improvements

monkey/infection_monkey/post_breach/actions/communicate_as_new_user.py, monkey/infection_monkey/requirements.txt, monkey/infection_monkey/utils/windows/users.py
Fixes #515. 
* * [x] Windows - works
* * [x] Windows - fails
* * [x] Linux - works with curl x wget
* * [x] Linux - fails with curl x wget
* * [x] Linux - fails - one or both missing
```
2019-12-24 19:09:28,876 [25444:22012:DEBUG] base_telem.send.25: Sending post_breach telemetry. Data: {"command": "", "result": ["Created process 'powershell.exe -command \"Invoke-WebRequest https://infectiokjl;adfkjl;dsfjklsdfkj;ladfjkl;adfsjkldsfnmonkey.com/\" -UseBasicParsing' as user 'somenewuservfulk', but the process failed (exit status 1:0x1).", false], "name": "Communicate as new user", "hostname": "gc-pc-169", "ip": "10.15.1.75"}
```
```
2019-12-24 19:11:28,905 [30116:12880:DEBUG] base_telem.send.25: Sending post_breach telemetry. Data: {"command": "", "result": ["Created process 'powershell.exe …
```
=> Replaced ping with curl/wget and Invoke-WebRequest

monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
Fixes #355 
Altered the warning to be displayed even after monkeys stop running. 
It's a possible scenario, that user will want to run again with more aggressive configuration after first run went fine. Now he will be noted that to change configuration he needs to "start over"
=> Added config won't change warning

monkey/infection_monkey/pyinstaller_hooks/hook-infection_monkey.system_info.collectors.py, monkey/infection_monkey/system_info/__init__.py
Fixes the lack of pyinstaller hooks for the new systeminfo collector plugin system.
=> Add pyinstaller hook for systeminfo plugins

monkey/infection_monkey/monkey.spec
Simplifying any build process out there so the binary names generated match what the Island expects.
=> Fix names to match island naming conventions

monkey/infection_monkey/monkey.spec
The tuple is from source file to dst folder. https://stackoverflow.com/a/59710336/4119906
Hotfix for the #543 pr.
=> Hotfix pyinstaller spec file - datas paths

monkey/monkey_island/linux/install_mongo.sh
This PR adds entry for ubuntu 19.10. mongodb does not provide the download for 19.10 version yet. But the 18.04 version download works fine. The entry will have to be replaced if and when the mongodb download for 19.10 becomes available
Closes https://github.com/guardicore/monkey/issues/563
Fixes https://github.com/guardicore/monkey/issues/563
If applicable, add screenshots or log transcripts of the feature working
=> install_mongo.sh: Add entry for ubuntu 19.10

monkey/infection_monkey/readme.md, monkey/monkey_island/readme.md
This PR sets replaces windows style path separator with linux style path separator for linux dev setup guide. It also adds chmod command for ./monkey_island/linux/run.sh in  monkey_island/readme.md
Closes https://github.com/guardicore/monkey/issues/561
Fixes https://github.com/guardicore/monkey/issues/561
If applicable, add screenshots or log transcripts of the feature working
=> dev-setup: Fix minor issues in dev-setup readme

monkey/monkey_island/cc/ui/src/components/pages/MapPage.js, monkey/monkey_island/cc/ui/src/styles/App.css
Fixes #538 
Currently, the telemetry console stays at the top even when there are updates. Seeing the new content requires user action.
This makes sure that it scrolls to the last line when there are new updates.
TODO:
1. don't scroll if the user has scrolled up
2. show line number
=> Autoscroll to last line in telemetry console

monkey/monkey_island/cc/services/bootloader.py
Pyinstaller seems to launch bootloader two times. The second launch seems to error on command launching function/functions and thus gives less information about the machine.
Changes code to only store the first bootloader telem instead of overriding it with the incomplete second one.
=> Bootlaoder reliability

monkey/infection_monkey/exploit/vsftpd.py
=> VSFTPD byte string mixup fixes

monkey/common/version.py, monkey/monkey_island/cc/environment/__init__.py, monkey/monkey_island/cc/environment/test_aws.py
Fix encoding bug in AWS env secret hashing
Commit messages.
=> Python 3 hashing requires bytes, not string

monkey/monkey_island/cc/services/attack/attack_report.py, monkey/monkey_island/cc/services/attack/attack_schema.py, monkey/monkey_island/cc/services/attack/technique_reports/T1136.py, monkey/monkey_island/cc/services/config_schema.py, monkey/monkey_island/cc/ui/src/components/attack/techniques/T1136.js, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
Fixes #579 
~Implemented changes 1, 2, 4 from the following (mentioned in the issue):~
Implemented all changes mentioned in the issue:
> Let's add this PBA to the matrix as Create Account attack technique.
>1. The "Create Account" technique should be present in attack matrix and user should be able to toggle it.
>2. On hover a brief with information about this particular attack technique should appear.
>3. This technique should be mapped with "Back door user" post breach action. This means that when "Create Account" is turned off, "Back door user" should turn off and vice versa.
>4. After exploitation, "Create Account" technique should be present on the ATT&CK report page.
~TODO: 3~
=> Map create user PBA to ATT&CK matrix

.travis.yml, monkey/infection_monkey/monkey.py
=> Fixed monkey ignoring depth restrictions

envs/monkey_zoo/blackbox/README.md, envs/monkey_zoo/blackbox/tests/performance/endpoint_performance_test.py, envs/monkey_zoo/blackbox/tests/performance/telemetry_performance_test_workflow.py, monkey/infection_monkey/exploit/smbexec.py, monkey/monkey_island/cc/services/edge.py, monkey/monkey_island/cc/services/telemetry/processing/scan.py
Fixes SMB exploiter not passing vulnerable port (thus causing redundant exploitations)
```
2020-05-26 11:41:07,787 [1160:10408:INFO] smbexec._exploit_host.163: Executed monkey 'C:\Windows\temp\monkey32.exe' on remote victim VictimHost('3.1.1.1') (cmdline='cmd.exe /c start cmd /c C:\\Windows\\temp\\monkey32.exe m0nk3y -p 268308375968634 -t 1.1.1.1:42614 -s 1.1.1.1:5000 -d 1 -vp 445')
=> SMB vulnerable port fix

monkey/monkey_island/cc/main.py
Changed minimum mongodb version required to 4.2.0
=> Changed minimum mongodb version required

monkey/common/utils/wmi_utils.py, monkey/infection_monkey/requirements.txt
WMI package upgraded and required pywin32.
because we have this package imported but not used in linux machines
we downgraded
After `pip install -r monkey\infection_monkey\requirements.txt`:
```
Collecting pywin32 (from wmi==1.5.1->-r monkey\infection_monkey\requirements.txt (line 16))
Downloading https://files.pythonhosted.org/packages/96/51/d46eb277182e0989a81cdc0933e97924b68b12519dfe62ae0ea5dec198dd/pywin32-228-cp37-cp37m-win_amd64.whl (9.1MB)
100% |████████████████████████████████| 9.1MB 2.9MB/s
```
=> pywin32 is missing from the Monkey

monkey/monkey_island/cc/app.py
Fixes #752 
Preserves the ATT&CK schema configuration order by setting Flask config variable `JSON_SORT_KEYS` to false.
By default, this variable is set to true and Flask sorts keys of JSON objects alphabetically (see [this](https://flask.palletsprojects.com/en/1.1.x/config/#JSON_SORT_KEYS)).
Proof it works:
=> Preserves ATT&CK config order on clicking 'Reset to defaults'

monkey/infection_monkey/post_breach/actions/modify_shell_startup_files.py, monkey/infection_monkey/post_breach/shell_startup_files/windows/modify_powershell_startup_file.ps1, monkey/infection_monkey/post_breach/shell_startup_files/windows/shell_startup_files_modification.py
Fixes #759
(1) ~~TODO~~ Runs a powershell script that creates a new folder and file if `profile.ps1` doesn't exist already.
(2) Removes "Public" from `USERS` in windows modify shell startup PBA file so it doesn't look for a `profile.ps1` file in the Public folder too.
=> Windows' "modify shell startup files" PBA fix

monkey/monkey_island/cc/ui/src/components/report-components/security/PostBreachParser.js
If the post-breach results have no changes, nothing is returned from `aggregateShellStartupPba()` which causes a rendering issue (te replicate, try running only the `trap` command PBA).
This makes sure the results are returned back as it is if there are no changes.
=> Fix rendering bug in security report generation due to PBA section

monkey/monkey_island/cc/services/attack/attack_schema.py
Links ".bash_profile and .bashrc" and "PowerShell profile" techniques, and "Local Job Scheduling" and "Scheduled Task" techniques, in the ATT&CK configuration (i.e. both are enabled/disabled together).
=> Link ATT&CK techniques of the same PBA in the config

README.md
Retargeted links in README.md to direct to documentation framework
=> Retargeted links in README.md to direct to documentation framework

monkey/infection_monkey/monkey.py, monkey/infection_monkey/post_breach/post_breach_handler.py
=> Run post-breach phase in separate thread

monkey/monkey_island/cc/resources/pba_file_upload.py, monkey/monkey_island/cc/services/post_breach_files.py
Fixed a bug where PBA file upload shows that file didn't get uploaded (PBA file path mixup).
=> Fixed post breach file upload bug

envs/monkey_zoo/docs/fullDocs.md, envs/monkey_zoo/terraform/images.tf, envs/monkey_zoo/terraform/monkey_zoo.tf, monkey/infection_monkey/network/windowsserver_fingerprint.py, monkey/infection_monkey/requirements.txt, monkey/monkey_island/cc/services/config_schema/definitions/finger_classes.py, monkey/monkey_island/cc/services/config_schema/internal.py
Fixes #845 
Implementation from https://github.com/SecuraBV/CVE-2020-1472
=> Zerologon Fingerprinter

monkey/common/cloud/azure/azure_instance.py, monkey/common/cloud/gcp/gcp_instance.py, monkey/common/common_consts/timeouts.py, monkey/infection_monkey/control.py, monkey/infection_monkey/exploit/drupal.py, monkey/infection_monkey/exploit/hadoop.py, monkey/infection_monkey/network/windowsserver_fingerprint.py, monkey/infection_monkey/transport/http.py, monkey/monkey_island/cc/bootloader_server.py
Fixes requests not having timeouts, which causes a delay in monkey executions or make it hang.
Also removed unused imports in one of the fingerprinters
> Tested by running sanity test
=> Added request timeouts

monkey/monkey_island/requirements.txt
**What this fixes**
Our Travis CI builds were failing because of [this](https://github.com/guardicore/monkey/blob/5ba1bf1db8a87fe5793b015aa4c8770d7165dafb/monkey/monkey_island/cc/models/test_monkey.py#L52) line.
**How**
The [latest mongoengine release](https://github.com/MongoEngine/mongoengine/blob/v0.21.0/docs/changelog.rst#changes-in-0210) has some changes in "Cursor.count" which throw an AttributeError on calling "QuerySet.count()", which is being used in `is_dead()` in `test_monkey.py`. The AttributeError is [caught by the except statement](https://github.com/guardicore/monkey/blob/5ba1bf1db8a87fe5793b015aa4c8770d7165dafb/monkey/monkey_island/cc/models/monkey.py#L84-L91) which marks the monkey as dead. 
There's no workaround yet either (see …
=> Fix mongoengine version to 0.20.0

monkey/infection_monkey/monkey.py
This guards against errors in our fingerprinters that may cause fingerprinting to fail but should not crash monkey
Closes #897 
=> Monkey: Guard against exceptions while fingerprinting

monkey/common/utils/exceptions.py, monkey/infection_monkey/control.py, monkey/infection_monkey/post_breach/actions/schedule_jobs.py, monkey/infection_monkey/post_breach/job_scheduling/windows_job_scheduling.py, monkey/infection_monkey/post_breach/post_breach_handler.py, monkey/monkey_island/cc/services/version_update.py
Fixed 2 issues: 
- Scheduled job gets created, but never deleted
- If scheduled job is already present when monkey wants to create it, schtasks prompts a question and monkey hangs indefinitelly
> Tested what happens if monkey job is already present
> Tested if job is created and deleted afterwards
=> Schedule jobs bugfix

deployment_scripts/README.md, deployment_scripts/config, deployment_scripts/deploy_linux.sh
Fixes a number of issues with `deployment_scripts/deploy_linux.sh`. 
The `deployment_scripts/deploy_linux.sh` is not often used. As such, it has fallen into a state of disrepair. These commits fix a number of installation failures, as well as update some documentation to improve the overall experience of using the linux deployment script.
> Tested by running the `deploy_linux.sh` script on an Ubuntu 18.04 VM
=> Linux deployment scripts tweaks

docs/content/usage/reports/zero-trust.md
Makes "Unexecuted" visible [here](https://www.guardicore.com/infectionmonkey/docs/usage/reports/zero-trust/#summary).
Changes this  
to this
=> Documentation fix

monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunManually/LocalManualRunOptions.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_curl.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_wget.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_windows_cmd.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_windows_powershell.js
Fixes #830 
**UPDATE:**
Added checkbox for "Run as user"
=> Add option to run as a certain user on the Run Monkey page

monkey/monkey_island/cc/resources/local_run.py
Fixes a bug, where anyone could run the monkey on island without authorization.
=> Added jwt_required decorator to the "local_run" endpoint

monkey/monkey_island.py, monkey/monkey_island/cc/arg_parser.py, monkey/monkey_island/cc/consts.py, monkey/monkey_island/cc/island_logger.py, monkey/monkey_island/cc/main.py, monkey/monkey_island/cc/test_island_logger.py, monkey/monkey_island/cc/testing/logger_config.json
Allows the logger configuration to be specified at runtime.
=> Select logger config at runtime

monkey/monkey_island/cc/services/config_schema/config_schema.py, monkey/monkey_island/cc/ui/src/components/configuration-components/UnsafeOptionsConfirmationModal.js, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js, monkey/monkey_island/cc/ui/src/components/ui-components/AdvancedMultiSelect.js, monkey/monkey_island/cc/ui/src/components/utils/SafeOptionValidator.js
Adds a modal dialog warning the user when unsafe options are selected. This prevents users from accidentally selecting unsafe options.
> Tested locally by submitting, exporting, and importing configs.
=> Unsafe options confirmation

monkey/monkey_island/cc/ui/src/components/configuration-components/UnsafeOptionsWarningModal.js, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
Adds a warning when a user submits an ATT&CK config that could be unsafe.
The ATT&CK configuration screen could allow users to unknowingly submit a potentially unsafe configuration.
**Example**
1. Go to `Exploits` and enable an unsafe exploiter.
2. Submit config -- you are warned that this config may be unsafe.
3. Go to the `ATT&CK` configuration screen and click submit -- You are not warned that the config may be unsafe
4. Export the configuration
5. Open the exported configuration and verify that the unsafe exploiter is present in the configuration.
**Solution**
When ATT&CK configurations are submitted, the workflow is: 
1. ATT&CK configuration is submitted to the back-end.
2. The back-end converts the ATT&CK configuration into a regular configuration
3. The front-end pulls the new, …
=> Attack config unsafe warning

docs/content/reference/exploiters/Zerologon.md, monkey/common/utils/exceptions.py, monkey/infection_monkey/exploit/HostExploiter.py, monkey/infection_monkey/exploit/tests/zerologon_utils/test_vuln_assessment.py, monkey/infection_monkey/exploit/zerologon.py, monkey/infection_monkey/exploit/zerologon_utils/vuln_assessment.py, monkey/monkey_island/cc/services/config_schema/definitions/exploiter_classes.py, monkey/monkey_island/cc/services/reporting/report.py, monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js, monkey/monkey_island/cc/ui/src/styles/pages/report/ReportPage.scss
=> Zerologon password reset warning

monkey/monkey_island/cc/services/tests/test_config.py, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOptions.js
Fixes #953
Only configured Island Server's IPs appear on the Run Monkey -> Manual page.
=> Show only configured IPs for Run Monkey -> Manual page

monkey/infection_monkey/requirements.txt
Fixes cryptography requirement to version 2.5, which has a built wheel available for Linux 32 bit, so we can build the agent.
=> Fixed cryptography requirement

envs/monkey_zoo/blackbox/island_configs/ssh.py, envs/monkey_zoo/blackbox/island_configs/struts2.py, envs/monkey_zoo/blackbox/island_configs/tunneling.py, envs/monkey_zoo/blackbox/island_configs/weblogic.py, envs/monkey_zoo/blackbox/island_configs/wmi_mimikatz.py, envs/monkey_zoo/blackbox/island_configs/wmi_pth.py, envs/monkey_zoo/blackbox/test_blackbox.py
Fixed a bug related to incorrect references in configuration generation and changed the default logging level to `INFO`
=> Configuration generation for BB tests bugfix

monkey/infection_monkey/post_breach/actions/users_custom_pba.py, monkey/infection_monkey/post_breach/tests/actions/test_users_custom_pba.py, monkey/monkey_island/cc/services/config_schema/monkey.py
=> Rephrase custom PBA file descriptions in configuration

monkey/monkey_island.py, monkey/monkey_island/cc/encryptor.py, monkey/monkey_island/cc/environment/environment_config.py, monkey/monkey_island/cc/environment/environment_singleton.py, monkey/monkey_island/cc/environment/test_environment_config.py, monkey/monkey_island/cc/main.py, monkey/monkey_island/cc/resources/local_run.py, monkey/monkey_island/cc/test_encryptor.py, monkey/monkey_island/cc/testing/environment/server_config_with_data_dir_home.json
Uses the runtime-configurable `data_dir` to store the monkey agent executable when the monkey is run from the island.
> Tested by building an appimage and running
=> Local run data dir

docs/content/_index.md
Fixes #1035 
1. Establishes lingo used throughout the documentation
2. Explains how monkey works architecturally
3. Explains the results you'll get and answers to the question "what's the point of using this".
The purpose of these changes is to avoid trivial tech questions and improve the high-level overview of the tool.
=> Improved home page documentation

docs/content/setup/debian.md
Adds a note about distro compatibility and Ubuntu Focal installation instructions to documentation.
=> docs: add distro compatibility and focal instructions do debian setup

monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
Fixes #1086 
> Tested by running Shellshock exploiter in mokeyzoo.
I changed exploiter's issue datastructure to contain all of the fields, so all of the issues now contained credential info, though for most of them it was `null`. Now we deem that "exploit is a credential exploit IF it contains credential info AND credential info is not null"
=> Shellshock UI bugfix

monkey/monkey_island/cc/resources/pba_file_upload.py
Fixes:
`os.remove(file_path)` in `monkey_island/cc/resources/pba_file_upload.py` attempts to delete a directory which throws an error when the PBA_linux_filename/PBA_windows_filename field in the database is empty.
To reproduce:
1. Start Monkey Island.
2. Go to the configuration page.
3. Make sure that nothing is uploaded in the custom PBA file field.
4. Reset the config.
=> Fix error when removing uploaded post breach file on config reset

.travis.yml
Fixes #1111
Install Node v12 instead of latest in travis script.
=> travis: install node v12.x, instead of latest

CHANGELOG.md, appimage/README.md, appimage/build_appimage.sh, appimage/clean.sh
Modifies the AppImage build script so that AppImage packages can be easily build locally by developers or by Jenkins.
Closes #1103
> Tested by building locally and running on my local network. Then I built a package with Jenkins and ran blackbox tests.
=> Appimage automated build

CHANGELOG.md, monkey/infection_monkey/exploit/zerologon.py, monkey/infection_monkey/exploit/zerologon_utils/remote_shell.py, monkey/infection_monkey/exploit/zerologon_utils/wmiexec.py
Zerologon exploiter writes runtime artifacts to a secure temporary directory instead of $HOME
This PR is in support of #1133.
> Tested by running the zerologon blackbox test.
=> Create a temporary directory for zerologon artifacts

CHANGELOG.md, monkey/monkey_island/Pipfile, monkey/monkey_island/Pipfile.lock, monkey/monkey_island/cc/environment/environment_config.py, monkey/monkey_island/cc/environment/standard.py, monkey/monkey_island/cc/environment/user_creds.py, monkey/monkey_island/cc/resources/auth/auth.py, monkey/monkey_island/cc/resources/auth/password_utils.py, monkey/monkey_island/cc/resources/auth/registration.py, monkey/monkey_island/cc/ui/src/services/AuthService.js, monkey/tests/monkey_island/cc/environment/test_environment.py, monkey/tests/monkey_island/cc/environment/test_user_creds.py
Fixes #969
Uses bcrypt to salt and hash the password on the server side before storing it.
> Tested by running Island locally. Network traffic shows plaintext password. `server_config.json` stores salted and hashed password. Correct password results in authentication. Incorrect is denied.
=> Hash login password on server side with bcrypt

docs/content/setup/docker.md
Improves documentation by stating why monkey docker containers can't be deployed in windows/mac os x.
=> Improved docker container support documentation

CHANGELOG.md, appimage/build_appimage.sh, appimage/run_appimage.sh, appimage/server_config.json.standard, monkey/monkey_island.py, monkey/monkey_island/cc/environment/environment_config.py, monkey/monkey_island/cc/main.py, monkey/monkey_island/cc/server_config.json.develop, monkey/tests/conftest.py, monkey/tests/monkey_island/cc/environment/test_environment_config.py, monkey/tests/resources/environment/server_config_no_credentials.json, monkey/tests/resources/environment/server_config_partial_credentials.json, monkey/tests/resources/environment/server_config_standard_env.json, monkey/tests/resources/environment/server_config_standard_with_credentials.json, monkey/tests/resources/environment/server_config_with_credentials.json, monkey/tests/resources/environment/server_config_with_data_dir.json, monkey/tests/resources/environment/server_config_with_data_dir_home.json
Issue #1146 
Creates an "environment" section in the config to separate the environment config from the non-environment config options.
> Tested by running the monkey locally
=> Environment config section

.swm/tbxb2cGgUiJQ8Btma0fp.swm, CHANGELOG.md, monkey/infection_monkey/config.py, monkey/infection_monkey/example.conf, monkey/infection_monkey/exploit/win_ms08_067.py, monkey/infection_monkey/post_breach/actions/add_user.py, monkey/infection_monkey/utils/random_password_generator.py, monkey/monkey_island/cc/services/config_schema/internal.py, monkey/tests/infection_monkey/utils/test_random_password_generator.py
Fixes #1169 
> Ran the Island, configuration page loads properly. Swimm units work.
=> Create new user with a random password

CHANGELOG.md, envs/monkey_zoo/blackbox/island_client/monkey_island_requests.py, envs/monkey_zoo/blackbox/test_blackbox.py
EtE tests deploy the island, but island prompts a registration screen, which BB can't handle. 
This PR solves that problem by selecting a passwordless option.
> Tested with an unregistred island (registration successful)
> Tested with a registered island (authentication error is thrown, tests don't run)
> Tested with unreachable island ("can't reach island" error message is displayed, tests don't run)
=> BB tests: automatic registration

monkey/monkey_island/cc/ui/src/components/configuration-components/ExportConfigModal.tsx, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js, monkey/monkey_island/cc/ui/src/styles/components/configuration-components/ExportConfigModal.scss
Creates a modal window/popup for configuration export.
Mockup:
Results:
> Tested manually, by using all of the functionality in the popup: close modal, enter password, switch to plaintext, switch back to password, etc.
=> Config export modal

monkey/monkey_island/setup/island_config_options.py, monkey/tests/unit_tests/monkey_island/setup/test_island_config_options.py
1. Expand environment variables if they are in `data_dir`
2. Adds unit tests to ensure that "~" and "$HOME" are expanded if they are in `data_dir`
> Tested by running unit test suite
=> Test data dir expand user env

docs/content/setup/docker.md, docs/content/setup/linux.md, monkey/common/utils/exceptions.py, monkey/monkey_island/cc/server_utils/file_utils.py, monkey/monkey_island/cc/setup/island_config_options_validator.py, monkey/monkey_island/linux/create_certificate.sh, monkey/tests/unit_tests/monkey_island/cc/server_utils/test_file_utils.py, monkey/tests/unit_tests/monkey_island/cc/setup/test_island_config_options_validator.py
Because the Docker container provides its own user, which may not match the host user, the permissions on certificates (particularly the default certificate) must be more open than the SSL certificate permission checks allow. As this was just a _nice to have_ functionality, this PR removes it.
> Tested by running an AppImage and Docker
=> Remove ssl perms checks

monkey/monkey_island/cc/services/post_breach_files.py, monkey/tests/monkey_island/utils.py, monkey/tests/unit_tests/monkey_island/cc/server_utils/test_file_utils.py, monkey/tests/unit_tests/monkey_island/cc/services/test_post_breach_files.py
Fixes #1196 
> Tested by running Monkey Island locally with no data directory so it creates everything by default. Uploaded custom PBA files on both Linux and Windows and made sure they ran.
=> Create secure custom PBA directory on Windows

monkey/infection_monkey/pyinstaller_hooks/hook-infection_monkey.ransomware.py, monkey/infection_monkey/ransomware/ransomware_payload.py, monkey/infection_monkey/ransomware/ransomware_readme.txt, monkey/monkey_island/cc/services/config_schema/ransomware.py, monkey/tests/unit_tests/infection_monkey/ransomware/test_ransomware_payload.py
Issue #1244
Adds functionality to the ransomware payload that leaves a README.txt file in the ransomware target directory after encryption has finished.
> Tested by running unit tests, running from source, and building and running an agent binary
=> Ransomware readme behavior

monkey/infection_monkey/ransomware/ransomware_readme.txt
Issue #1244 
Replaces the placeholder content in the ransomware README.txt file with cool ASCII art and useful information.
=> Agent: Add content to ransomware README.txt file

monkey/infection_monkey/control.py, monkey/infection_monkey/main.py
When monkey agent logs its default/new configuration, format the output so it is more easily readable.
> See screenshot
=> Agent: Format config log messages so they are readable

monkey/monkey_island/cc/ui/src/components/configuration-components/UISchemaManipulators.tsx, monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- Fixes part of #1239
- Allows to change UI schema display based on user input in the form itself
> Tested manually, by selecting/deselecting/changing tabs/resetting the config/exporting etc...
=> Ransomware: hide directory fields if encryption is disabled

monkey/monkey_island/cc/services/config_schema/ransomware.py, monkey/monkey_island/cc/ui/src/components/configuration-components/HtmlFieldDescription.js, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
Adds a description and link to documentation to the ransomware configuration UI.
Issue #1239
> See screenshot
=> Ransomware config UI description

CHANGELOG.md, monkey/monkey_island/cc/server_setup.py, monkey/monkey_island/cc/server_utils/consts.py, monkey/monkey_island/cc/setup/gevent_hub_error_handler.py, vulture_allowlist.py
Fixes #859
The gevent hub has 2 mechanisms for controlling how errors (tracebacks) are handled.
1. The `exception_stream` controls where tracebacks are written (default=stderr): https://www.gevent.org/api/gevent.hub.html#gevent.hub.Hub.exception_stream
2. The `handle_error()` method controls what happens when an error is encountered: https://www.gevent.org/api/gevent.hub.html#gevent.hub.Hub.handle_error
If `exception_stream` is set, the user may not get any indication that a gevent error occurred. To solve this, the `handle_error()` functionality is wrapped and the exception (not traceback) is logged to WARNING. 
> Tested by running monkey island
=> Gevent ssl traceback

CHANGELOG.md, monkey/monkey_island/cc/app.py, monkey/monkey_island/cc/resources/ransomware_report.py
#1240  
> Ran Island and added a log statement in `ReportPage.js` to make sure it worked.
=> Add API endpoint for ransomware report

monkey/monkey_island/windows/create_certificate.bat
Fixes delimiter problem in `windows\create_certificate.bat`. 
=> island: Add delimiter to windows create_certificate

monkey/common/common_consts/validation_formats.py, monkey/monkey_island/cc/services/config_schema/ransomware.py, monkey/monkey_island/cc/ui/src/components/configuration-components/ValidationErrorMessages.js, monkey/monkey_island/cc/ui/src/components/configuration-components/ValidationFormats.js
#1239  
> Ran and tested on Island (see video below). 
https://user-images.githubusercontent.com/44770317/124090136-2cf03a00-da72-11eb-8995-5001255e9dc1.mp4
=> Validate ransomware target directories

monkey/monkey_island/cc/ui/src/components/Main.js, monkey/monkey_island/cc/ui/src/components/pages/ReportPage.js, monkey/monkey_island/cc/ui/src/components/report-components/RansomwareReport.js, monkey/monkey_island/cc/ui/src/components/report-components/common/ReportHeader.js
Fixes #1240 
~**Ransomware tab is not hidden if no ransomware options are enabled**~
=> Add ransomware report tab

monkey/tests/unit_tests/infection_monkey/ransomware/test_ransomware_payload.py
Add a UT to test if ransomware payload tries to encrypt files if "linux_target_dir" and "windows_target_dir" inputs are empty.
We have empty "linux_target_dir" and "windows_target_dir" by default so it's important that ransomware payload doesn't try to encrypt files by default, without users' knowledge.
> Tested by Running the UT, seeing it fail.
=> Add file encryption UT for ransomware payload: test no ecryption when no directory specified

monkey/common/utils/file_utils.py, monkey/infection_monkey/ransomware/ransomware_payload.py, monkey/tests/unit_tests/common/utils/test_common_file_utils.py, monkey/tests/unit_tests/infection_monkey/ransomware/test_ransomware_payload.py
Fixes ransomware encrypting CWD by default, when no directory is specified
Improves readability in ransomware payload
Changes `expand_path` in `monkey/common/utils/file_utils.py` to raise an exception if empty path is specified.
=> Ransomeware bugfix: cwd encryption by default

monkey/tests/unit_tests/infection_monkey/ransomware/test_ransomware_payload.py
The old implementation tightly coupled the test to the specific
implementation of the ransomware payload. Since the ransomware payload
provides insight into its actions in the form of telemetry, it should be
sufficient to test whether or not any telemetries were sent in order to
determine whether or not encryption was skipped. This way, the test can
remain decoupled from the internal workings of the ransomware payload.
=> Island: Refactor test_encryption_skipped_if_no_directory()

monkey/infection_monkey/monkey.py, monkey/infection_monkey/ransomware/ransomware_payload.py, monkey/tests/unit_tests/infection_monkey/ransomware/test_ransomware_payload.py
Adds a check to prevent the ransomware payload from overwriting an existing README.txt.
Adds a `copy_file` callable to the RansomwarePayload constructor to decouple RansomwarePayload from the specific file copy implementation. See f0e9109f6 for more information.
=> Ransomware README improvements

monkey/infection_monkey/ransomware/ransomware_payload.py, monkey/monkey_island/cc/services/config_schema/ransomware.py, monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js, monkey/tests/unit_tests/infection_monkey/ransomware/test_ransomware_payload.py
Fixes first task of #1287 . If we don't specify a directory, the readme should not be left.
=> Ransomware README with configurable directories

monkey/monkey_island/cc/resources/island_mode.py, monkey/monkey_island/cc/services/mode/island_mode_service.py, monkey/tests/unit_tests/monkey_island/cc/resources/test_island_mode.py
Fixes unset mode for ransomware quickstart start-over task. 
=> Ransomware quickstart unset mode to get method in island mode

monkey/monkey_island/cc/ui/src/components/Main.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunMonkeyPage.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOptions.js
Fixes hides scoutsuite run option in ransomware mode. 
=> Ransomware quickstart - Hide scoutsuite run options in ransomware mode

monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
Fixes #1293  . 
Note: I didn't do the test on Network or Ransomware. Check the fix in #1330 .
=> Fix bug where we can't change tab from attack to another tab in Configure

.gitattributes, monkey/common/utils/file_utils.py, monkey/infection_monkey/ransomware/consts.py, monkey/infection_monkey/ransomware/file_selectors.py, monkey/infection_monkey/ransomware/ransomware_payload.py, monkey/tests/conftest.py, monkey/tests/data_for_tests/stable_file.txt, monkey/tests/unit_tests/common/utils/test_common_file_utils.py, monkey/tests/unit_tests/infection_monkey/ransomware/test_file_selectors.py, monkey/tests/unit_tests/infection_monkey/ransomware/test_in_place_file_encryptor.py, monkey/tests/unit_tests/infection_monkey/ransomware/test_ransomware_payload.py, monkey/tests/unit_tests/infection_monkey/ransomware/test_readme_dropper.py, monkey/tests/utils.py
Fixes #1304
> Tested by running unit tests on windows and linux
> Tested by building monkey agents on jenkins and running on both windows and linux
=> Ransomware skip encrypt readme

monkey/monkey_island/cc/ui/src/components/Main.tsx
Fixes #1339 
Setting the island mode in `Main.tsx`'s constructor ensures that no bugs (such as #1339) arise because the island mode hasn't been correctly set yet. 
> Tested by running Monkey Island and playing around with it.
https://user-images.githubusercontent.com/44770317/126481939-3a409add-8993-43b6-807c-c8b6f14d9dfd.mp4
=> Set island mode in `Main.tsx`'s constructor

appimage/build_appimage.sh
Improves the process of AppImage building by:
1. Giving an indication of what happens if you try to build appImage from development environment (`cp` command takes forever due to node modules and other submodules)
2. Disables the autoclrf line ending conversion, so if you build appImage on WSL, the monkey branch checked out doesn't have dos style line endings which fail the script
> Tested by building appImage on WSL, timeout tested by trying to build appImage from development directory
=> appImage improvements

envs/monkey_zoo/blackbox/config_templates/base_template.py
Fixes #1371 . 
Disabling `internal.monkey.internet_services` is skipping connectivity check making the bb tests faster.
There where done multiple checks on  ssh exploit tests.
With connectivity check: 
Without connectivity check:
=> Skip connectivity check in BB tests

build_scripts/appimage/appimage.sh, build_scripts/appimage/clean.sh, build_scripts/appimage/infection-monkey.desktop, build_scripts/docker/clean.sh
Fixes #1355
Fixes #1362
> Tested by  running on Ubuntu Bionic, Ubuntu Focal, and Rocky 8
=> Package appimage with linuxdeploy

CHANGELOG.md, monkey/infection_monkey/post_breach/actions/communicate_as_new_user.py
Fixes linux Communicate as new user PBA. 
The post breach action was failing previously because it relays on `shell=True`.
I was replaced with a check for the executables.
=> Agent: Fix linux command line for http request

CHANGELOG.md, monkey/infection_monkey/network/ping_scanner.py
Fixes #1175. 
Add encoding cp850 to subprocess of ping scanner.
This adds the ability for the monkey to work on other system languages that use DOS-Latin-1 as encoding.
> Tested by running the Monkey locally on a system using the german (and english of course) system language
=> Fix breaking monkey on german system language by adding cp850 encoding to ping scanner

CHANGELOG.md, envs/monkey_zoo/blackbox/config_templates/base_template.py, monkey/infection_monkey/config.py, monkey/infection_monkey/control.py, monkey/infection_monkey/example.conf, monkey/infection_monkey/network/info.py, monkey/monkey_island/cc/models/monkey.py, monkey/monkey_island/cc/services/config_schema/internal.py, monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json
Fixes #1402
> Tested by running blackbox tests and a custom test to verify reports render correctly.
=> Remove internet access check

CHANGELOG.md, monkey/infection_monkey/post_breach/shell_startup_files/windows/shell_startup_files_modification.py, monkey/infection_monkey/post_breach/timestomping/windows/timestomping.py, monkey/infection_monkey/pyinstaller_hooks/hook-infection_monkey.post_breach.py
Fixes #1405
Fixes #1419
> Tested by building an agent binary and running it.
...
=> Post breach pyinstaller hook

.swm/afMu3y3ny5lnrYFWl3EI.swm, .travis.yml
#1410 
Since we removed the BackdoorUser PBA in #1433, the existing PBA Swimm unit was removed. This PR adds a Swimm unit for a different PBA.
> Tested by running Swimm 
* [] ~If applicable, add screenshots or log transcripts of the feature working~
=> Add Swimm unit for adding a PBA

CHANGELOG.md, monkey/infection_monkey/post_breach/actions/use_trap_command.py, monkey/infection_monkey/post_breach/trap_command/linux_trap_command.py, monkey/monkey_island/cc/services/config_schema/definitions/post_breach_actions.py
Fixes #1406 .
Trap command was showing no output when run from Island because the kill command never sends it.
As the technique allows for any kind of interrupt signals ( check [this](https://attack.mitre.org/techniques/T1546/005/) and [this](https://github.com/Kirtar22/Litmus_Test/blob/master/Persistence/T1154/T1154.md) ) I have changed the INT with TERM.
=> Agent: Change trap command signal to TERM

envs/monkey_zoo/blackbox/island_client/monkey_island_requests.py
=> Zoo: Change island to use credentials

build_scripts/appimage/appimage.sh, build_scripts/build_package.sh, build_scripts/common.sh, build_scripts/docker/docker.sh
=> Add deployment type to the build_scripts

monkey/infection_monkey/Pipfile, monkey/infection_monkey/Pipfile.lock, monkey/monkey_island/Pipfile, monkey/monkey_island/Pipfile.lock
Fixes #1476 . 
For the agent, I think that at the moment what we can do is a hack where we have multiple solutions on how to install different version of `cryptography` and `pyopenssl` needed for 32bit linux agent.  Another solution will be to possibly somehow add `-32` or `-64` to the python version that we are using for the agent. There is no implementation yet on this.
Some resource: [Pipenv Issue](https://github.com/pypa/pipenv/issues/2397) , 
> Tested by running both the Agent and the Island:
Agent has successfully exploited a vulnerable machines.
Island has updated `awscli`, `boto3` and `botocore` . For this case I have run the Island on AWS instance and
generated a report which triggered the Island to send finding to AWS security hub. There were not any issues
with updating the …
=> Update Python dependencies

monkey/infection_monkey/system_info/windows_info_collector.py, monkey/monkey_island/cc/models/telemetries/telemetry_dal.py
Removes the unnecessary "mimikatz" info from telemetry data since the exact same data is stored under "credentials" key
Couldn't find any usages or reason for duplicating credentials into "mimikatz" key
> Tested by building monkey, gathering credentials, testing the report
=> Duplicate credentials in system info telem

CHANGELOG.md, docs/content/FAQ/_index.md, monkey/monkey_island/cc/resources/auth/auth.py, monkey/monkey_island/cc/resources/auth/registration.py, monkey/monkey_island/cc/server_setup.py, monkey/monkey_island/cc/services/database.py, monkey/monkey_island/cc/setup/mongo/database_initializer.py, monkey/monkey_island/cc/ui/src/components/pages/RegisterPage.js, monkey/monkey_island/cc/ui/src/styles/pages/AuthPage.scss
#1463 
> Tested by running the Island (deleted data dir, deleted DB, deleted server config, deleted creds)
> Tested by running Hugo.
=> Delay mongo init to after registration

CHANGELOG.md, monkey/monkey_island/cc/server_utils/encryption/encryptors/key_based_encryptor.py, monkey/tests/unit_tests/monkey_island/cc/server_utils/encryption/test_key_based_encryptor.py
Fixes #1490
> Tested by running the Island and changing the configuration.
=> Change KeyBasedEncryptor's padding

CHANGELOG.md, monkey/infection_monkey/post_breach/actions/modify_shell_startup_files.py
Fixes #1507 and #1055 . 
In docker container `/etc/passwd` doesn't have any regular users. The modify shell script searches for those kind of users and if it doesn't find it return empty list which then we send telemetry without any result making the post breach action to fail.
Here we check if we have empty result from the running of command and send failed result with explanation.
=> Check for empty result in Modify shell files

CHANGELOG.md, monkey/infection_monkey/config.py, monkey/infection_monkey/example.conf, monkey/infection_monkey/main.py, monkey/monkey_island/cc/services/config_schema/internal.py, monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json
Fixes #1537 always use file logging. 
=> 1537 use file logging

CHANGELOG.md, monkey/infection_monkey/config.py, monkey/infection_monkey/main.py, monkey/monkey_island/cc/services/config_schema/internal.py, monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json
Fixes #1537 remove serialize config. 
=> 1537 remove serialize config

CHANGELOG.md, monkey/infection_monkey/config.py, monkey/infection_monkey/dropper.py, monkey/infection_monkey/example.conf, monkey/monkey_island/cc/services/config_schema/internal.py, monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json
Fixes #1537 always try to move dropper first. 
=> 1537 try to move dropper file first

CHANGELOG.md, monkey/infection_monkey/config.py, monkey/infection_monkey/example.conf, monkey/infection_monkey/system_singleton.py, monkey/monkey_island/cc/services/config_schema/internal.py, monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json
=> Remove custom singleton mutex name option

CHANGELOG.md, monkey/infection_monkey/config.py, monkey/infection_monkey/example.conf, monkey/infection_monkey/utils/monkey_dir.py, monkey/monkey_island/cc/services/config_schema/internal.py, monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json
Fixes # 1537 constant monkey dir name. 
=> 1537 constant monkey dir

monkey/infection_monkey/monkey.py, monkey/infection_monkey/utils/signal_handler.py
Agent will now handle interrupt and break signals on linux and windows
Fixes #1594
Handles SIGINT and SIGTERM for Linux
Handles SIGBREAK and window close event for Windows
> Tested by stopping agent with ctrl+c and `kill -15` on Linux
> Tested by stopping agent with ctrl+c and by closing window on Windows
=> Agent: register signal handlers

monkey/infection_monkey/i_puppet.py, monkey/infection_monkey/master/__init__.py, monkey/infection_monkey/master/automated_master.py, monkey/infection_monkey/master/exploiter.py, monkey/infection_monkey/master/ip_scanner.py, monkey/infection_monkey/master/propagator.py, monkey/infection_monkey/master/threading_utils.py, monkey/infection_monkey/model/__init__.py, monkey/infection_monkey/model/victim_host_factory.py, monkey/infection_monkey/puppet/mock_puppet.py, monkey/monkey_island/cc/services/config.py, monkey/tests/data_for_tests/monkey_configs/flat_config.json, monkey/tests/unit_tests/infection_monkey/master/test_automated_master.py, monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py, monkey/tests/unit_tests/infection_monkey/master/test_propagator.py, monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Calls the exploiters from the AutomatedMaster for issue #1597
> Tested by running AutomatedMaster in isolation
=> 1597 implement exploitation

monkey/common/network/network_range.py, monkey/infection_monkey/network/network_scanner.py, monkey/infection_monkey/network/scan_target_generator.py, monkey/tests/unit_tests/common/network/test_network_range.py, monkey/tests/unit_tests/infection_monkey/model/test_victim_host_generator.py, monkey/tests/unit_tests/infection_monkey/network/test_scan_target_generator.py
Implements scan target generator. These changes extract the step of scan target generation into a method that takes inputs like scan targets, local interfaces, segmentation test targets, blocked IP's etc. and produces a list of IP's that agent needs to scan.
=> 1597 implement scan target generator

CHANGELOG.md, monkey/monkey_island/cc/server_setup.py
Two users contacted me (coincidentally on the same day) and were confused when Monkey Island started. They thought it had frozen when the agent binary hashes were printed to the screen. The instructions for accessing the island are buried in the Island's output and it may be difficult for users to find the appropriate messages.
By changing the order and content of the log statements, I hope to alleviate this confusion.
=> Island: Change the order of log messages on startup to improve UX

monkey/infection_monkey/monkey.py, monkey/infection_monkey/utils/signal_handler.py
After the Master terminates, this resets the signal handlers to the
default handlers provided by Python.
> Tested by running on Windows and Linux and sending all applicable signals
=> Reset signal handlers after the Master is cleaned up

monkey/infection_monkey/i_puppet/i_puppet.py, monkey/infection_monkey/master/ip_scanner.py, monkey/infection_monkey/master/mock_master.py, monkey/infection_monkey/puppet/mock_puppet.py, monkey/infection_monkey/puppet/puppet.py, monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py
Fixes first task of #1601. 
Instead of using scan_tcp_port and scan each port seperately
we can use scan_tcp_ports which will recieve list of ports
for the specific host and return dictionary of port:PortScanData
items. There was no point of scanning each port seperately.
=> Agent, UT: Change puppet interface to use scan_tcp_ports

monkey/infection_monkey/network/__init__.py, monkey/infection_monkey/network/tcp_scanner.py, monkey/infection_monkey/network/tools.py, monkey/infection_monkey/puppet/puppet.py
Fixes second task of #1601 . 
TcpScanner class is not needed now. `check_tcp_ports` is moved to `tcp_scanner.py` as it is used only there.
=> Agent: Implement scan_tcp_ports in tcp_scanner

monkey/infection_monkey/master/automated_master.py, monkey/infection_monkey/master/control_channel.py, monkey/infection_monkey/master/exploiter.py, monkey/infection_monkey/utils/decorators.py, monkey/tests/unit_tests/infection_monkey/master/test_automated_master.py, monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py, monkey/tests/unit_tests/infection_monkey/utils/test_decorators.py
Enables the `AutomatedMaster` to periodically check for new propagation credentials during the exploitation phase of the attack.
Issue #1605 
> Tested by running unit test
> Tested by running with modified source code to verify the behavior of the `ControlClient`
=> 1605 get updated credentials

monkey/infection_monkey/master/exploiter.py, monkey/monkey_island/cc/services/config.py, monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py, monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Pass wormconfig options, related to #1605 . 
=> 1605 pass wormconfig options

monkey/infection_monkey/credential_collectors/ssh_collector/ssh_handler.py, monkey/infection_monkey/exploit/HostExploiter.py, monkey/infection_monkey/i_puppet/i_puppet.py, monkey/infection_monkey/master/exploiter.py, monkey/infection_monkey/master/mock_master.py, monkey/infection_monkey/master/propagator.py, monkey/infection_monkey/puppet/mock_puppet.py, monkey/infection_monkey/telemetry/exploit_telem.py, monkey/monkey_island/cc/services/edge/edge.py, monkey/monkey_island/cc/services/telemetry/processing/exploit.py, monkey/tests/unit_tests/infection_monkey/master/test_propagator.py, monkey/tests/unit_tests/infection_monkey/telemetry/test_exploit_telem.py
=> Modify ExploiterResultData

monkey/infection_monkey/exploit/HostExploiter.py, monkey/infection_monkey/exploit/sshexec.py, monkey/infection_monkey/i_puppet/i_puppet.py, monkey/infection_monkey/master/exploiter.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/puppet/mock_puppet.py, monkey/infection_monkey/puppet/puppet.py, monkey/infection_monkey/telemetry/exploit_telem.py, monkey/monkey_island/cc/services/attack/technique_reports/T1210.py, monkey/monkey_island/cc/services/reporting/exploitations/monkey_exploitation.py, monkey/monkey_island/cc/services/telemetry/processing/exploit.py, monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py, monkey/tests/unit_tests/monkey_island/cc/services/reporting/test_report.py
Modify SSH exploiter, related to #1605. 
=> Modify SSH exploit

monkey/infection_monkey/exploit/__init__.py, monkey/infection_monkey/exploit/exploiter_wrapper.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/puppet/puppet.py, monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Adds ExploiterWrapper for issue #1605
> Tested by running ssh exploiter locally
=> Agent: Add ExploiterWrapper

monkey/infection_monkey/config.py, monkey/infection_monkey/example.conf, monkey/infection_monkey/exploit/tools/helpers.py, monkey/infection_monkey/exploit/web_rce.py, monkey/monkey_island/cc/services/config.py, monkey/monkey_island/cc/services/config_schema/internal.py, monkey/tests/data_for_tests/monkey_configs/flat_config.json, monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json, monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py, monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Removes dropper_target_path_win_32 from config. Related to #1675 .
=> Remove dropper_target_path_win_32 bit config option

monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunManually/LocalManualRunOptions.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOptions.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_curl.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_wget.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_windows_powershell.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/utils/OsTypes.js, monkey/monkey_island/cc/ui/src/components/report-components/security/PostBreachParser.js
Remove 32bit manual run options. Related #1675 .
=> Island: Remove 32bit manual run options

monkey/infection_monkey/exploit/tools/helpers.py, monkey/infection_monkey/exploit/web_rce.py, monkey/infection_monkey/model/host.py, monkey/monkey_island/cc/resources/monkey_download.py, monkey/monkey_island/cc/services/run_local_monkey.py, monkey/tests/unit_tests/infection_monkey/telemetry/test_exploit_telem.py, monkey/tests/unit_tests/infection_monkey/telemetry/test_scan_telem.py
=> Remove 32-bit references from Hadoop

monkey/infection_monkey/control.py, monkey/monkey_island/cc/models/monkey.py, monkey/monkey_island/cc/services/reporting/report.py
Network information is required for segmentation reports, that's why it gets sent in the wakeup telemetry. It could be joined with "ip_addresses", but that would require a bigger refactoring on the island side
Fixes part of #1695 
> Tested by running unit tests, monkey
=> Agent, Island: send network information in monkey wakeup telemetry

CHANGELOG.md, docs/content/FAQ/_index.md, monkey/infection_monkey/utils/monkey_log_path.py
Reorders the components of the agent log so that the timestamp comes before the random component. This allows agent logs to be sorted by timestamp more easily.
> Tested by building agent binaries and running SMB exploiter
=> Agent log timestamp ordering

monkey/infection_monkey/monkey.py
Prevent the agent from opening/closing a tunnel if `depth < 1`. Since agents with `depth < 1` will not propagate, there's no need for them to open a tunnel. This greatly speeds up testing since agents that don't open a tunnel don't need to wait for the tunnel to close before exiting (60 seconds by default).
> Tested by running from source
> Tested by building binaries and running
The below GIF shows the map during the entire run. It's a little slow to get started. You'll notice that the victims are only displayed as green for a very short period. This is because they don't have to start/stop tunnels.
=> Agent: Only start/stop tunnel if the agent is able to propagate

monkey/infection_monkey/network_scanning/ping_scanner.py, monkey/infection_monkey/post_breach/job_scheduling/job_scheduling.py, monkey/infection_monkey/post_breach/job_scheduling/linux_job_scheduling.py, monkey/infection_monkey/post_breach/job_scheduling/windows_job_scheduling.py, monkey/tests/unit_tests/infection_monkey/network_scanning/test_ping.py
Fixes part of #1650 .
Also one commit for older version of ping that doesn't support float for `-W`
> Tested by running Schedule Jobs on Linux and Windows
=> 1650 job scheduling timeouts

monkey/infection_monkey/config.py, monkey/infection_monkey/exploit/sshexec.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/network/firewall.py, monkey/infection_monkey/transport/base.py, monkey/infection_monkey/transport/http.py, monkey/infection_monkey/transport/tcp.py, monkey/monkey_island/cc/services/config_schema/internal.py
Fixes part of  #1613
Improves logging
Fixes firewall rule handling
Changes `keep_tunnel_open` time to 30s from 60s
Max time for agent shutdown:
tunnel timeout = 30
closing http/tcp proxy = 2.5
closing firewall = 1.5
sending log = 5
state telem = 5
quit tunnel = 10
**Total 54s**
> Tested by running locally, couldn't test tunneling properly due to the bugs in the agent
=> 1613 agent timeouts

monkey/infection_monkey/credential_collectors/mimikatz_collector/pypykatz_handler.py
Fixes #1771 
> Tested by exploiting Zerologon and checking the Island
=> Don't gather kerberos creds in pypykatz

CHANGELOG.md, envs/os_compatibility/README.md, envs/os_compatibility/terraform/instances.tf, monkey/infection_monkey/control.py, monkey/infection_monkey/exploit/caching_agent_repository.py, monkey/infection_monkey/master/control_channel.py, monkey/monkey_island/cc/app.py, monkey/monkey_island/cc/resources/monkey.py, monkey/monkey_island/cc/services/remote_run_aws.py, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_curl.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_wget.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_windows_powershell.js
Fixes #1888 .
Renames `api/monkey` to `api/agent`
> Tested by running on AWS, running manual commands, ssh exploit and some manual tests
=> 1888 rename monkey endpoint

CHANGELOG.md, monkey/infection_monkey/consts.py, monkey/infection_monkey/credential_collectors/mimikatz_collector/mimikatz_credential_collector.py, monkey/infection_monkey/model/__init__.py, monkey/infection_monkey/post_breach/actions/communicate_as_backdoor_user.py
Fixes #1860 
> Tested by running on Windows
=> Fix fake user addition to the config because of Mimikatz

monkey/monkey_island/cc/services/edge/edge.py
Fixes #1917 
> Tested by running the Agent and Island as described in the issue.
Scanning and exploiting happen in parallel and the telemetries for both were being sent too close to each other which was causing a race condition during edge creation.
When `get_or_create_edge()` in `EdgeService` is called the first time, it has to _create_ an edge, but before that is done, it gets called a second time. It can't _get_ the edge the second time either since an edge hasn't been created yet from the first time it was called. So it decides that it needs to _create_ an edge the second time as well and two edges end up being created.
=> Bugfix for 2 edges being created

CHANGELOG.md, docs/content/FAQ/_index.md, envs/os_compatibility/README.md, envs/os_compatibility/terraform/instances.tf, monkey/infection_monkey/exploit/caching_agent_repository.py, monkey/monkey_island/cc/resources/agent_binaries.py, monkey/monkey_island/cc/services/aws/aws_command_runner.py, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_curl.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_wget.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_windows_powershell.js
Fixes a part of #1974 
> Tested by testing the endpoint manually on Windows.
=> Change AgentBinaries URL

monkey/monkey_island/Pipfile, monkey/monkey_island/Pipfile.lock
They are used in pyinstaller and without them frozen island doesn't work
Fixes part of #1959
> Tested by building and running the island exe
=> Island: Add pywin32 requirements for island

build_scripts/appimage/appimage.sh
Fixes #1993
> Tested by building locally and modifying config through the UI
> Tested by running end-to-end tests
=> 1993 fix pip platform appimage

monkey/infection_monkey/config.py, monkey/infection_monkey/control.py, monkey/infection_monkey/master/control_channel.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/post_breach/custom_pba/custom_pba.py, monkey/infection_monkey/telemetry/base_telem.py, monkey/infection_monkey/telemetry/tunnel_telem.py, monkey/tests/unit_tests/infection_monkey/post_breach/actions/test_users_custom_pba.py, monkey/tests/unit_tests/infection_monkey/telemetry/conftest.py, monkey/tests/unit_tests/infection_monkey/telemetry/test_tunnel_telem.py, monkey/tests/unit_tests/infection_monkey/test_control.py
Mitigates the coupling of agent codebase to `current_server` property in worm config, by using server address from control channel and control client #1996
> Tested by running manual test, infecting machines
=> 1996 agent worm config decouple

monkey/common/di_container.py, monkey/monkey_island/cc/services/initialize.py, monkey/tests/unit_tests/common/test_di_container.py, vulture_allowlist.py
Adds simple "conventions" to the `DIContainer` to address [this TODO](https://github.com/guardicore/monkey/blob/ac172dc81f3593f7337f56d79ccb2d50b4b76e3f/monkey/monkey_island/cc/services/initialize.py#L30-L32).
See https://blog.ploeh.dk/2012/07/02/PrimitiveDependencies/ for inspiration.
> Tested by running an agent from the Island.
=> Register di conventions

CHANGELOG.md, monkey/common/utils/argparse_types.py, monkey/infection_monkey/config.py, monkey/infection_monkey/dropper.py, monkey/infection_monkey/exploit/hadoop.py, monkey/infection_monkey/exploit/log4shell.py, monkey/infection_monkey/exploit/mssqlexec.py, monkey/infection_monkey/exploit/powershell.py, monkey/infection_monkey/exploit/smbexec.py, monkey/infection_monkey/exploit/sshexec.py, monkey/infection_monkey/exploit/web_rce.py, monkey/infection_monkey/exploit/wmiexec.py, monkey/infection_monkey/master/automated_master.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/utils/commands.py, monkey/infection_monkey/utils/propagation.py, monkey/tests/unit_tests/infection_monkey/utils/test_commands.py, monkey/tests/unit_tests/infection_monkey/utils/test_propagation.py
Based on the previous logic the depth parameter represented hops remaining, not current depth.
Fixes incorrect depth logic on the agent side. Based on the previous logic the depth parameter represented hops remaining, not current depth. This is misleading and might result in a situation where max depth is 3 in the configuration, so the user runs the agent with `-d 2` expecting the agent to do one more hop. In reality, the agent will make 2 hops, because `--depth` was countdown to zero, not count to maximum depth.
> Tested by running agent manually with max depth
=> Agent: Change the logic of depth to represent current depth

monkey/monkey_island/cc/ui/package-lock.json, monkey/monkey_island/cc/ui/package.json, monkey/monkey_island/cc/ui/src/components/configuration-components/ExportConfigModal.tsx, monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js, monkey/monkey_island/cc/ui/src/components/utils/PasswordBasedEncryptor.tsx
Fixes #2002
> Tested by running these cases and more:
UNSAFE_ENCRYPTED.conf
UNSAFE_UNENCRYPTED.conf
SAFE_UNENCRYPTED_OUTDATED.conf.bak
SAFE_UNENCRYPTED.conf
SAFE_ENCRYPTED.conf
SAFE_ENCRYPTED_MALFORMED.conf
SAFE_UNENCRYPTED_MALFORMED.conf
SAFE_UNENCRYPTED_OUTDATED.conf
=> 2002 config encryption in UI

docs/content/FAQ/_index.md
Fixes #1954.
Fixes broken TOC links, adds missing links in the log section and matches TOC title names to their corresponding headers.
> Tested by running Hugo locally and checking that when clicking on the links it jumps to the correct header.
=> Docs: Fix TOC links in FAQ

monkey/monkey_island/cc/resources/agent_configuration.py, monkey/monkey_island/cc/ui/src/components/configuration-components/ExportConfigModal.tsx, monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx, monkey/monkey_island/cc/ui/src/components/configuration-components/ReformatHook.js, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js, monkey/monkey_island/cc/ui/src/components/ui-components/AdvancedMultiSelect.js
Fixes part of #2003
Enables submit, import, export and reset buttons in the configuration page
> Tested by manually running import, export, submit, reset, refreshing the page, changing tabs, importing malformed configs, etc.
=> 2003 retrieve submit config

monkey/common/config_value_paths.py, monkey/monkey_island/cc/resources/telemetry.py, monkey/monkey_island/cc/services/configuration/utils.py, monkey/monkey_island/cc/services/reporting/report.py, monkey/monkey_island/cc/services/telemetry/processing/aws_info.py, monkey/monkey_island/cc/services/telemetry/processing/exploit.py, monkey/monkey_island/cc/services/telemetry/processing/post_breach.py, monkey/monkey_island/cc/services/telemetry/processing/processing.py, monkey/monkey_island/cc/services/telemetry/processing/scan.py, monkey/monkey_island/cc/services/telemetry/processing/state.py, monkey/monkey_island/cc/services/telemetry/processing/tunnel.py, monkey/monkey_island/cc/services/telemetry/zero_trust_checks/segmentation.py, monkey/tests/unit_tests/monkey_island/cc/services/telemetry/processing/test_post_breach.py
Merge after #2088
Fixes a part of #1662
For `services/reporting/report.py`, the agent configuration repository has been added as a dependency in #2088, which is used to fetch the required data.
For `services/telemetry/zero_trust_checks/segmentation.py`, the agent configuration repository is added as a dependency of the `Telemetry` resource which then passes the agent configuration through the telemetry processing functions which is then used to fetch the required data. Not sure if there's a better way.
=> Remove `services/configuration/utils.py`, use AgentConfiguration

monkey/common/agent_configuration/agent_sub_configuration_schemas.py, monkey/common/agent_configuration/agent_sub_configurations.py, monkey/tests/unit_tests/common/configuration/test_agent_configuration.py
There are no constraints except that the timeout should be of type `float` which marshmallow handles.
=> ICMPScanConfiguration docstring

monkey/common/agent_configuration/agent_sub_configuration_schemas.py, monkey/common/agent_configuration/agent_sub_configurations.py, monkey/monkey_island/cc/ui/src/services/configuration/propagation/propagation.js, monkey/tests/unit_tests/common/configuration/test_agent_configuration.py
=> PropagationConfiguration docstring + validation

CHANGELOG.md, monkey/monkey_island/cc/app.py, monkey/monkey_island/cc/resources/auth/register.py, monkey/monkey_island/cc/resources/auth/registration_status.py, monkey/monkey_island/cc/ui/src/services/AuthService.js, monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_register.py, monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_registration_status.py
=> New API endpoint for registration status

monkey/common/__init__.py, monkey/common/di_container.py, monkey/tests/common/stub_di_container.py
- Renames `UnregiseredTypeError` to `UnresolvableDependnecyError`
- Adds exceptions to `DIContainer`'s docstrings.
Resolves https://github.com/guardicore/monkey/pull/2167#issuecomment-1205381256
* [x} Have you added an explanation of what your changes do and why you'd like to include them?
=> Di container quality improvements

monkey/monkey_island/cc/app.py, monkey/monkey_island/cc/resources/propagation_credentials.py, monkey/tests/unit_tests/monkey_island/cc/resources/test_propagation_credentials.py, monkey/tests/unit_tests/monkey_island/cc/test_app.py
Strict slashes seems to not handle a case when URL is defined with a trailing slash, but request is sent without one. Removing trailing slashes before registering a URL will solve the burden of remembering to register URLS without slashes
Fixes the 404 in  #2191
> Tested by running the Agent
=> Island: Remove trailing slashes before registering a URL

monkey/infection_monkey/credential_repository/aggregating_propagation_credentials_repository.py, monkey/tests/unit_tests/infection_monkey/credential_store/test_aggregating_propagation_credentials_repository.py
The AggregatingPropagationCredentialsRepository would clear the repository and return None if it failed to get credentials from the Island. It has been updated so that the repository is no longer cleared, and it will return its stored credentials even if it fails to retrieve any from the Island.
Added a unit test, which also prompted a change to the way that the repository caches its results.
=> 2191 fix credentials repository get

monkey/monkey_island/cc/services/database.py
Also fix one type annotation because of mypy
Fixes #2210 
We have condition where we check which collections should be dropped. That condition was causing configured credentials to be deleted. I added another condition that it will not drop anything that starts with "config"
=> Island: Don't drop collections that starts with "config"

.pre-commit-config.yaml, monkey/infection_monkey/master/automated_master.py, monkey/infection_monkey/master/propagator.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/network/__init__.py, monkey/infection_monkey/network/info.py, monkey/infection_monkey/network_scanning/scan_target_generator.py, monkey/infection_monkey/network_scanning/tcp_scanner.py, monkey/tests/unit_tests/infection_monkey/master/test_propagator.py, monkey/tests/unit_tests/infection_monkey/network_scanning/test_scan_target_generator.py, vulture_allowlist.py
Addresses #2135.
Updates `NetworkInterface` to use `IPv4Interface` instead of the named tuple.
*Note:* This branch is based off of [`add-mypy-precommit-hook`](https://github.com/guardicore/monkey/pull/2220).
> I have only run the unit tests
=> 2135 use ipaddress

monkey/infection_monkey/master/automated_master.py, monkey/infection_monkey/master/control_channel.py, monkey/infection_monkey/master/ip_scanner.py, monkey/infection_monkey/master/propagator.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/network/info.py
Fixes #2218.
Renames `get_local_network_interfaces()` to `get_network_interfaces()` and adds it to the `AgentRegistrationData`.
> I tested the call on Windows to ensure that it runs correctly
=> 2218 get network interfaces

CHANGELOG.md, monkey/infection_monkey/dropper.py, monkey/infection_monkey/monkey.py
Removes tunnel argument
Fixes part of #2216 .
This PR removes tunnel command line argument and accepts list of servers.
Note: This PR breaks the agent.
=> Agent: Modify command line arguments to accept list of servers

monkey/infection_monkey/monkey.py, monkey/infection_monkey/network/relay/__init__.py, monkey/infection_monkey/network/relay/utils.py
Sends the notification upstream to tell the agent's relay that it is disconnecting.
=> 2216 notify relay when finished

monkey/infection_monkey/monkey.py
The exploited machines need to be given the relay connection details in case they can't communicate with the server.
> Tested by running the Monkey in the zoo and verifying that the server list is updated
=> Agent: Add relay to servers list for exploited hosts

monkey/infection_monkey/network/info.py, monkey/tests/unit_tests/infection_monkey/network/test_info.py
Resolves race condition where well-known ports can be returned as "free" in multiple threads.
=> Agent: Add TCPPortSelector

monkey/monkey_island/cc/repository/__init__.py, monkey/monkey_island/cc/repository/mongo_event_repository.py, monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_event_repository.py, vulture_allowlist.py
Fixes part of  #2180.
Add a repository for storing events in MongoDB.
> Just ran the unit tests
=> 2180 mongo event repository

monkey/infection_monkey/payload/ransomware/ransomware_builder.py, monkey/tests/integration_tests/infection_monkey/payload/ransomware/test_integrated_ransomware.py
The ransomware integration tests were sometimes painfully slow because they were waiting for the BatchingTelemetryMessenger to stop its internal thread. This commit surfaces the sleep period parameter to the `build_ransomware()` function so that the unit tests can set it to a very small value. This is somewhat of a hack, but
BatchingTelemetryMessenger is going away very soon, as Telemetry is being replaced by Events.
> Tested by running integration tests
=> Agent: Make BatchingTelemetryMessenger sleep period configurable

monkey/infection_monkey/control.py, monkey/infection_monkey/island_api_client/http_island_api_client.py, monkey/infection_monkey/island_api_client/i_island_api_client.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/post_breach/custom_pba/custom_pba.py, monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py, vulture_allowlist.py
Fixes a part of #2292 
Adds a decorator to handle Island API exceptions which can be used for all HTTPIslandAPIClient functions. Alternatively, we could do this [using a metaclass ](https://stackoverflow.com/a/6307917) or using [`inspect` at the end of the class](https://stackoverflow.com/a/3467879).
> UTs pass
=> Use HTTPIslandAPIClient in ControlClient

monkey/monkey_island/cc/repository/i_agent_repository.py, monkey/monkey_island/cc/repository/mongo_agent_repository.py, monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_agent_repository.py, vulture_allowlist.py
=> 2261 get progenitor

monkey/monkey_island/cc/services/__init__.py, monkey/monkey_island/cc/services/agent_signals_service.py, monkey/monkey_island/cc/services/initialize.py, monkey/monkey_island/cc/setup/island_event_handlers.py, monkey/tests/unit_tests/monkey_island/cc/services/test_agent_signals_service.py
Fixes part of #2261.
Implements on_terminate_agents_signal, and connects the AgentSignalsService to the event.
=> 2261 on terminate agents signal

monkey/common/types.py, monkey/infection_monkey/island_api_client/http_island_api_client.py, monkey/infection_monkey/island_api_client/i_island_api_client.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/network/relay/utils.py, monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py, monkey/tests/unit_tests/infection_monkey/network/relay/test_utils.py
Fixes part of #2323. Follows [2350](https://github.com/guardicore/monkey/pull/2350).
Add any further explanations here. Updates the IslandAPIClient to use a SocketAddress. One effect of this is that IslandAPISearchResults can no longer be a dict because SocketAddress is not hashable. `find_available_island_apis` was updated to output the results in the same order as the servers that are passed in, in order to make it easier to use.
=> 2323 update iislandapiclient with socketaddress

envs/monkey_zoo/blackbox/test_configurations/noop.py, monkey/common/agent_configuration/agent_sub_configurations.py, monkey/common/agent_configuration/default_agent_configuration.py, monkey/common/network/network_range.py, monkey/infection_monkey/master/propagator.py, monkey/infection_monkey/network/info.py, monkey/infection_monkey/network_scanning/scan_target_generator.py, monkey/monkey_island/cc/services/reporting/report.py, monkey/monkey_island/cc/ui/src/services/configuration/propagation/propagation.js, monkey/monkey_island/cc/ui/src/services/configuration/propagation/scanTarget.js, monkey/tests/common/example_agent_configuration.py, monkey/tests/unit_tests/common/agent_configuration/test_agent_configuration.py, monkey/tests/unit_tests/infection_monkey/master/test_propagator.py, monkey/tests/unit_tests/infection_monkey/network_scanning/test_scan_target_generator.py
Fixes part of #2299.
Renames local_network_scan -> scan_local_interfaces
> The unit tests still pass
=> Island: Rename local_network_scan

monkey/infection_monkey/control.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/network/tools.py, monkey/infection_monkey/post_breach/custom_pba/custom_pba.py, monkey/infection_monkey/post_breach/pba.py
Fixes part of #2323. Follows [2351](https://github.com/guardicore/monkey/pull/2351)
Updates `ControlClient` to use `SocketAddress`, enabling `_running_on_island()` to be refactored as well.
=> 2323 use socketaddress in running on island

docs/content/usage/configuration/basic-network.md, docs/content/usage/scenarios/custom-scenario/credential-leak.md, docs/content/usage/scenarios/custom-scenario/network-breach.md, docs/content/usage/scenarios/custom-scenario/network-segmentation.md, docs/content/usage/scenarios/custom-scenario/other.md, docs/content/usage/scenarios/custom-scenario/zero-trust.md
Fixes part of #2299.
Updates the documentation for the "Scan Agent's networks" option.
=> Docs: Update network scanning documentation

monkey/infection_monkey/network_scanning/tcp_scanner.py, monkey/infection_monkey/puppet/puppet.py, monkey/tests/unit_tests/infection_monkey/network_scanning/conftest.py, monkey/tests/unit_tests/infection_monkey/network_scanning/test_ping_scanner.py, monkey/tests/unit_tests/infection_monkey/network_scanning/test_tcp_scanner.py
Modify `scan_tcp_ports()` to accept an `IAgentEventQueue`
Issue #2267
=> 2267 tcp scanner accept iagenteventqueue

monkey/common/event_queue/__init__.py, monkey/common/event_queue/locking_agent_event_queue_decorator.py, monkey/monkey_island/cc/event_queue/__init__.py, monkey/monkey_island/cc/event_queue/locking_island_event_queue_decorator.py, monkey/monkey_island/cc/event_queue/pypubsub_island_event_queue.py, monkey/monkey_island/cc/services/initialize.py
Makes Island and Agent event queues in the Island thread-safe.
Issue #2267
> Local smoke test
> ETE tests
=> 2267 island event queue threadsafe

monkey/common/agent_events/__init__.py, monkey/common/agent_events/agent_event_registry.py, monkey/common/agent_events/register.py, monkey/monkey_island/cc/services/initialize.py, monkey/tests/unit_tests/common/agent_events/test_agent_event_registry.py
This PR supports issue #2429 and may also support #2378.
In order to filter events by type, the endpoint needs to be able to translate from event type name to a Type.
* [] ~Was the documentation framework updated to reflect the changes?~
=> 2429 agent event registry

monkey/monkey_island/cc/ui/src/components/types/MapNode.tsx
Fixes part of #2334 .
MapNode is a class without a constructor which we can easily set the attributes. 
```
class MapNode {
machine_id!: number
operating_system!: string
network_interfaces!: object
parent_id!: string
}
let map_node = new MapNode();
map_node.machine_id = 2
map_node.operating_system = "Linux"
map_node.network_interfaces = {"bla": "bla"}
console.log(map_node)
```
=> UI: Add MapNode type

monkey/infection_monkey/exploit/smbexec.py, monkey/monkey_island/cc/services/telemetry/processing/state.py
Fixes #2426
On the Island side, also fixes `process_state_telemetry()`'s arguments which was causing an error since an extra argument was being passed from `processing.py`.
> Tested by running Zerologon
=> Fix SMB exploiter bug

monkey/monkey_island/cc/resources/exploitations/monkey_exploitation.py, monkey/monkey_island/cc/resources/ransomware_report.py, monkey/monkey_island/cc/services/ransomware/ransomware_report.py, monkey/monkey_island/cc/services/reporting/exploitations/monkey_exploitation.py, monkey/monkey_island/cc/services/reporting/report.py, monkey/tests/unit_tests/monkey_island/cc/services/ransomware/test_ransomware_report.py, monkey/tests/unit_tests/monkey_island/cc/services/reporting/exploitations/test_monkey_exploitation.py
This addresses the parts of the report that use get_monkey_exploited(). This affects the following:
- The Security report:
- Which info/warning message is displayed just below Overview
-  The number of breached machines and the %Exploited in the "The Network from the Monkey's Eyes"
- The number of breached servers listed above Breached Servers table
- The Ransomware report:
- The number of breached servers listed in the Lateral Movement section
> ![Screen Shot 2022-10-13 at 12 25 27 PM](https://user-images.githubusercontent.com/11077625/195657302-953f3da7-10b9-4def-a747-02176005010f.jpg)
> ![Screen Shot 2022-10-13 at 12 21 22 PM](https://user-images.githubusercontent.com/11077625/195657347-bafd8697-2c20-4875-895e-f0455b066c58. …
=> 2269 use repositories for get monkey exploited

monkey/infection_monkey/agent_event_handlers/agent_event_forwarder.py, monkey/infection_monkey/monkey.py
Logs are sent to the Island even if the singleton couldn't be acquired. 
> Tested by running an agent and ensuring logs get uploaded to the Island.
=> Fix send logs on singleton failure

envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py, monkey/infection_monkey/exploit/hadoop.py
Fixes #2464.
Addresses depth 1 blackbox test failure due to unhandled exception in the Hadoop exploiter. The exception is now handled, and a failed propagation event sent. Note that the depth 1 blackbox test still fails -- it appears that not all of the machines are able to be exploited in the given timeframe.
> Tested by running the depth 1 blackbox test
=> 2464 fix depth 1 bb test

monkey/monkey_island/cc/models/monkey.py, monkey/monkey_island/cc/resources/local_run.py, monkey/monkey_island/cc/services/node.py, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOnIslandButton.js, vulture_allowlist.py
- Use /api/machines and /api/agents instead of /api/local-monkey to determine if Agents are currently running on the Island.
- Remove `GET /api/local-monkey`
Resolves #2506
> Tested by manipulating stop times in the database and verifying the UI
=> 2506 remove get api local monkey

monkey/monkey_island/cc/ui/src/components/types/MapNode.tsx
Fixes #2530 
Previously, if a node was only scanned, the map would still show the wrench icon. This PR fixes that.
> Tested by running on GCP and checking the map
=> Fix MapNode group logic

monkey/common/agent_events/__init__.py, monkey/common/agent_events/os_discovery_event.py, monkey/common/agent_events/register.py, monkey/tests/unit_tests/common/agent_events/test_os_discovery_event.py
Fixes part of #2562.
Adds `OSDiscoveryEvent`, an agent event for OS information.
=> Add OS discovery agent event

monkey/monkey_island/cc/agent_event_handlers/__init__.py, monkey/monkey_island/cc/agent_event_handlers/update_machine_os.py, monkey/monkey_island/cc/repository/__init__.py, monkey/monkey_island/cc/repository/agent_machine_facade.py, monkey/monkey_island/cc/repository/network_model_update_facade.py, monkey/monkey_island/cc/services/initialize.py, monkey/monkey_island/cc/setup/agent_event_handlers.py, monkey/monkey_island/cc/setup/island_event_handlers.py, monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_scan_event_handler.py, monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_update_machine_os.py, monkey/tests/unit_tests/monkey_island/cc/repository/test_agent_machine_facade.py, monkey/tests/unit_tests/monkey_island/cc/repository/test_network_model_update_facade.py
Fixes part of #2562.
Should be merged after #2572.
Update the Island to handle `OSDiscoveryEvent`s.
> ![Screen Shot 2022-11-11 at 4 04 13 PM](https://user-images.githubusercontent.com/11077625/201430596-0f420f9f-1805-40c1-917d-51a4088e1fca.jpg)
=> 2562 handle agent os event

envs/monkey_zoo/blackbox/test_blackbox.py
Fixes #2601.
Arranges the blackbox tests so that the credentials reuse test happens first.
> Tested by running the blackbox tests in the zoo
Observe that the credentials reuse test runs first:
```
20:19:49 [INFO] gcp_machine_handlers.start_machines.49: GCP machines successfully started.
20:20:19 [INFO] test_blackbox.delete_logs.58: Deleting monkey logs before new tests.
----------------------------------------------------------------------------------- live log call -----------------------------------------------------------------------------------
20:20:20 [INFO] monkey_island_client._set_island_mode.47: Setting island mode to Custom.
20:20:20 [INFO] monkey_island_client._import_config.59: Configuration is imported.
20:20:20 [INFO] monkey_island_client._import_credentials.74: Credentials …
```
=> BB: Make credentials reuse the first test

CHANGELOG.md, monkey/monkey_island/cc/app.py, monkey/monkey_island/cc/resources/__init__.py, monkey/monkey_island/cc/resources/agent_plugins.py, monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_plugins.py
Fixes #2578.
Adds the `/api/agent-plugins` resource.
=> 2578 stub agent plugins endpoint

monkey/common/agent_plugins/__init__.py, monkey/common/agent_plugins/agent_plugin_type.py, monkey/common/plugins/plugin_type.py, monkey/common/types.py, monkey/infection_monkey/i_puppet/i_puppet.py, monkey/infection_monkey/island_api_client/http_island_api_client.py, monkey/infection_monkey/island_api_client/i_island_api_client.py, monkey/infection_monkey/master/plugin_registry.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/puppet/puppet.py, monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py, monkey/tests/unit_tests/infection_monkey/master/test_plugin_registry.py, monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Moves PluginType enum. `types.py` has an unclear purpose. I think it's better to define plugin types close to other, related plugin infrastructure (currently being developed)
=> Common: Move PluginType enum from types.py to plugin/plugin_type.py

monkey/infection_monkey/agent_event_handlers/agent_event_forwarder.py, monkey/tests/unit_tests/infection_monkey/agent_event_handlers/test_agent_event_forwarder.py
Prevents events from being dropped if the island is temporarily not able to be contacted.
Merge after #2649 
=> Agent: Fix unsent events getting dropped on exception

monkey/common/agent_events/abstract_agent_event.py, monkey/tests/unit_tests/common/agent_events/test_file_encryption_event.py, monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_events.py, vulture_allowlist.py
Fixes #2534 .
Adding `smart_union` to the config of AbstractAgentEvent validates the order of types. Changing the order of the target field and adding smart_union fixes this thing.
Why did we need to change the order? IPv4Address can use strings and integers to parse it.
Example:
IPv4Address(1) will be IPv4Addres("0.0.0.1")
=> 2534 fix machine id serialization

monkey/monkey_island/cc/ui/src/styles/components/Map.scss
Fixes part of #2590.
Overlays the legend on the map.
> Ran the island and viewed the webpage
Observe that the legend is displayed over the map
> ![Screen Shot 2022-12-13 at 11 11 44 AM](https://user-images.githubusercontent.com/11077625/207385112-17dd0b36-f387-47f8-a68a-c13101dd3728.jpg)
=> UI: Overlay the map legend on the map

monkey/monkey_island/cc/ui/src/components/map/MapOptions.js, monkey/monkey_island/cc/ui/src/components/pages/MapPage.js, monkey/monkey_island/cc/ui/src/components/reactive-graph/ReactiveGraph.tsx, monkey/monkey_island/cc/ui/src/styles/App.css, monkey/monkey_island/cc/ui/src/styles/components/Map.scss, monkey/monkey_island/cc/ui/src/styles/components/PreviewPane.scss
Fixes #2590.
Expands the map width and overlays the preview pane on top of the map.
> Tested by running the island and viewing the webpage (Chrome, Firefox, Safari)
> https://user-images.githubusercontent.com/11077625/207447471-b8f92776-9d2b-43c3-8e4c-555059fca372.mov
=> UI: Overlay preview pane on top of the map

monkey/monkey_island/cc/ui/src/styles/pages/ConfigurationPage.scss
Fixes part of #2694.
Hides the error summary on the configuration page.
Note: It appears that the errors have been placed in the `card` class. I'm not sure if this card is being reused for other messages. We could hide the `danger-border` class instead.
> Tested by running the island and viewing the webpage
Observe that the error list is not being displayed when field(s) have invalid inputs
> ![Screen Shot 2022-12-15 at 10 46 21 AM](https://user-images.githubusercontent.com/11077625/207904913-4f6a2a49-8c57-454b-ad1e-015b05a92920.jpg)
=> UI: Hide the configuration page error summary

monkey/common/utils/file_utils/__init__.py, monkey/common/utils/file_utils/file_utils.py, monkey/infection_monkey/main.py, monkey/infection_monkey/master/plugin_registry.py, monkey/infection_monkey/monkey.py, monkey/tests/unit_tests/common/utils/test_common_file_utils.py, monkey/tests/unit_tests/infection_monkey/master/test_plugin_registry.py, monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Fixes part of #2692.
Adds serpentarium.PluginLoader to the PluginRegistry.
=> 2692 add pluginloader to pluginregistry

monkey/monkey_island/cc/ui/src/components/ui-components/ErrorModal.tsx, monkey/monkey_island/cc/ui/src/styles/components/ErrorModal.scss
UI couldn't be built because of inline style in ErrorModal
=> UI: Add ErrorModal stylesheet

monkey/monkey_island/cc/services/__init__.py, monkey/monkey_island/cc/services/config_schema_service.py, monkey/monkey_island/cc/services/initialize.py, monkey/tests/unit_tests/common/agent_plugins/test_agent_plugin_manifest.py, monkey/tests/unit_tests/monkey_island/cc/fake_agent_plugin_data.py, monkey/tests/unit_tests/monkey_island/cc/repositories/test_agent_plugin_repository_caching_decorator.py, monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_plugins.py, monkey/tests/unit_tests/monkey_island/cc/services/test_config_schema_service.py, vulture_allowlist.py
Fixes part of #2710.
Adds the ConfigSchemaService, which provides the get_schema() method for retrieving the configuration schema.
We need to change the AgentConfguration to include the title and description the proper way so this PR is a draft PR until we have fixed that.
The result schema looks like:
[schema.zip](https://github.com/guardicore/monkey/files/10287302/schema.zip)
=> 2710 config schema service

monkey/infection_monkey/agent_event_handlers/agent_event_forwarder.py, monkey/infection_monkey/monkey.py
Fixes an exception that is raised when the agent shuts down because it can't acquire the system singleton.
=> Fix plugin event forwarder exception

envs/monkey_zoo/blackbox/test_configurations/credentials_reuse_ssh_key.py, envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py, envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py, envs/monkey_zoo/blackbox/test_configurations/depth_3_a.py, envs/monkey_zoo/blackbox/test_configurations/depth_4_a.py, envs/monkey_zoo/blackbox/test_configurations/noop.py, envs/monkey_zoo/blackbox/test_configurations/smb_pth.py, envs/monkey_zoo/blackbox/test_configurations/utils.py, envs/monkey_zoo/blackbox/test_configurations/wmi_mimikatz.py, envs/monkey_zoo/blackbox/test_configurations/zerologon.py, monkey/common/agent_configuration/agent_sub_configurations.py, monkey/common/agent_configuration/default_agent_configuration.py, monkey/infection_monkey/master/exploiter.py, monkey/monkey_island/cc/repositories/utils/agent_configuration_schema_compiler.py, monkey/monkey_island/cc/services/reporting/report.py, monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js, monkey/monkey_island/cc/ui/src/components/utils/SafeOptionValidator.js, monkey/monkey_island/cc/ui/src/services/configuration/exploiterClasses.js, monkey/monkey_island/cc/ui/src/services/configuration/propagation/exploitation.js, monkey/tests/common/example_agent_configuration.py, monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
Fixes #2787.
> Tested by running the island and agent
=> 2787 merge vulnerability and brute force exploiter config

monkey/common/agent_configuration/agent_sub_configurations.py
This is done to make the structure of hard-coded exploiters' options to match the options of exploiter plugins
=> Island: Switch exploiters in schema type to dict

monkey/tests/data_for_tests/agent_plugin/mock1/src/plugin.py, monkey/tests/data_for_tests/agent_plugin/mock2/src/plugin.py
Fixes #2773.
Updated the mock plugins to print the credentials from the credentials repo.
> [2023-01-06T16.32.16.530Z-island-linux-250.log](https://github.com/guardicore/monkey/files/10361603/2023-01-06T16.32.16.530Z-island-linux-250.log)
=> UT: Update mock plugins to use credentials repo

monkey/monkey_island/cc/repositories/utils/agent_configuration_schema_compiler.py, monkey/monkey_island/cc/repositories/utils/hard_coded_exploiters.py, monkey/tests/unit_tests/monkey_island/cc/services/test_agent_configuration_schema_service.py
Exploiter plugins and hard-coded plugins must be merged to create a cohesive configuration schema
Fixes part of #2785
=> Island: Change schema compiler to merge plugins and exploiters

monkey/common/agent_configuration/default_agent_configuration.py, monkey/infection_monkey/master/exploiter.py, monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
Addresses #2785 (changes agent to be compatible with configuration changes)
Improved naming a bit 
> Tested by exploiting hadoop, looking at the logs
=> Agent: Change the Agent to use the modified exploiter config

CHANGELOG.md, monkey/infection_monkey/exploit/log4shell_utils/ldap_server.py, monkey/infection_monkey/main.py, monkey/infection_monkey/monkey.py
Fixes #2820
* [x} Have you checked that you haven't introduced any duplicate code?
=> 2820 fix hanging child process

monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx, monkey/monkey_island/cc/ui/src/components/configuration-components/PropagationConfig.tsx, monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js, monkey/monkey_island/cc/ui/src/components/ui-components/AdvancedMultiSelect.js
Part of #2698
Implements the core of plugin selection logic. 
Enables selection/deselection of plugins and changes to their configuration options. On submit/export configuration state contains the changes
> Tested manually (changing the configuration options and making sure the submitted configuration state represents the state of the UI)
=> 2698 plugin selector core

monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx, monkey/monkey_island/cc/ui/src/components/configuration-components/PropagationConfig.tsx, monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
Fixes #2700
Disables the options for unselected exploiters
Minor renaming in PluginSelectorTemplate
The solution is quite messy. I've tried to modify the UiSchema before passing it down to the children, but that seems to not be supported: https://github.com/rjsf-team/react-jsonschema-form/issues/1589
It's possible to do it with CSS, but in that case we would need to style all possible option elements, like inputs, buttons, checkboxes, selects, etc. 
> Tested by running the UI, selecting/unselecting
=> UI: Disable the options of unselected exploiters

monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx
Bug happened because some components were not changed to account for selectedExploiters being a Set instead of an array
Fixes part of #2702
> Tested by clicking on master checkbox, submitting
=> UI: Fix a bug in master checkbox of PluginSelectorTemplate.tsx

monkey/monkey_island/cc/resources/exploitations/monkey_exploitation.py, monkey/monkey_island/cc/resources/ransomware_report.py, monkey/monkey_island/cc/services/initialize.py, monkey/monkey_island/cc/services/ransomware/ransomware_report.py, monkey/monkey_island/cc/services/reporting/exploitations/monkey_exploitation.py, monkey/monkey_island/cc/services/reporting/report.py, monkey/tests/unit_tests/monkey_island/cc/services/ransomware/test_ransomware_report.py, monkey/tests/unit_tests/monkey_island/cc/services/reporting/exploitations/test_monkey_exploitation.py, monkey/tests/unit_tests/monkey_island/cc/services/reporting/test_report.py
Fixes part of #2857 
Fix reporting UTs is the only thing left
=> 2857 security report get exploit on node fix

monkey/agent_plugins/exploiters/hadoop/config-schema.json, monkey/agent_plugins/exploiters/hadoop/manifest.yaml, monkey/monkey_island/cc/ui/src/components/configuration-components/MarkdownDescriptionTemplate.tsx, monkey/monkey_island/cc/ui/src/components/configuration-components/PluginSelectorTemplate.tsx, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js, monkey/monkey_island/cc/ui/src/styles/pages/ConfigurationPage.scss
Fixes #2857 
Renders plugin descriptions in configuration in markdown
> Tested manually:
=> 2857 markdown plugin descriptions

monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploit_client.py
Fixes #2921 
The `name` in the manifest of an exploiter plugin and the `exploiter_name` being sent as part of the `ExploitationEvent` need to be the same.
The plugin registry, when asked for all plugin manifests, returns `Dict[AgentPluginType, Dict[str, AgentPluginManifest]]` where the `str` is whatever is in the `name` field in that plugin's manifest. When the report is being generated, `monkey_island.cc.services.reporting.exploitations.monkey_exploitation.get_monkey_exploited()` requests the plugin registry for all the manifests, and then, in `get_exploits_used_on_node()`, tries to get the manifest that it wants by using whatever is in the exploitation event's `exploiter_name` field as the key. No such key is found in the dictionary which is why the respective field is left empty in the …
=> Change 'name' in Hadoop manifest

envs/monkey_zoo/blackbox/conftest.py
Each test `name` is overwritten when parameterizing tests. However, `originalname` will keep the original test's name. This change will allow the use of pytest-repeat, enabling something like the following:
> `pytest -k test_depth_3_a --count 1000 -x`
Which will run the `test_depth_3_a` test 1000 times or until it fails.
* [c] Have you checked that you haven't introduced any duplicate code?
> Tested by running the blackbox tests using the `--count` flag
```
kkaaikal@localhost:~/infection_monkey/monkey$ python -m pytest -k test_depth_3_a --count=1000 -x -s --no-gcp --island=34.89.161.57:5000 ../envs/monkey_zoo/blackbox/test_blackbox.py
================================================== test session starts ===================================================
platform linux -- Python 3.7.13, …
```
=> BB: Allow tests to be parameterized

monkey/common/agent_configuration/default_agent_configuration.py
Disables credential collectors by default in the ransomware simulation.
Since the configuration UI hides these settings when ransomware is selected, they should be disabled. 
=> Common: Disable credential collectors in ransomware configuration

envs/monkey_zoo/blackbox/utils/gcp_machine_handlers.py
The BB tests proceeded even if there was no gcloud installed and no machines were started. There were no error logs in the output as well
The BB tests proceeded even if there was no gcloud installed and no machines were started. There were no error logs in the output as well
=> BB: Improve error handling in gcp_machine_handler

monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py, monkey/tests/utils.py
Fixes the [broken build](https://app.travis-ci.com/github/guardicore/monkey/jobs/596020735) caused by the use of MagicMock, which is not thread-safe.
=> UT: Use a thread-safe MagicMock implementation in test_ip_scanner.py

CHANGELOG.md, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js, monkey/monkey_island/cc/ui/src/services/configuration/credentialCollectors.js
Fixes #1301
> Tested manually (see gif)
=> 1301 disable submit button

monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploiter.py, monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_exploiter.py
Fixes part of #2136
Updates Hadoop to skip configured ports if they are closed
=> 2136 update hadoop to skip closed ports

build_scripts/appimage/AppRun, build_scripts/appimage/appimage.sh
Fixes part of #2705.
Updates the app image script to 
=> 2705 appimage script

monkey/tests/unit_tests/common/utils/test_common_file_utils.py, monkey/tests/unit_tests/conftest.py, monkey/tests/unit_tests/infection_monkey/payload/ransomware/conftest.py, monkey/tests/unit_tests/infection_monkey/payload/ransomware/test_ransomware_options.py, monkey/tests/unit_tests/monkey_island/cc/setup/test_island_config_options.py
Fixes a part of #2705
`expanduser()`'s functionality was changed in Python 3.8 to not allow "$HOME" on Windows anymore. See [this](https://docs.python.org/3/whatsnew/3.8.html#os-path).
> `expanduser()` UTs pass
=> Fix Windows `expanduser()` UTs after Python upgrade

monkey/agent_plugins/exploiters/hadoop/Pipfile, monkey/agent_plugins/exploiters/hadoop/Pipfile.lock, monkey/agent_plugins/exploiters/hadoop/build.sh, monkey/agent_plugins/exploiters/hadoop/build_plugin.sh
Issue #2705
- Upgrade Hadoop to depend on Python3.11
- Create a single-touch build script to build the Hadoop plugin in the same container as the Agent
=> 2705 upgrade python version hadoop

monkey/monkey_island/cc/island_event_handlers/handle_agent_registration.py, monkey/monkey_island/cc/models/agent.py, monkey/tests/unit_tests/monkey_island/cc/island_event_handlers/test_handle_agent_registration.py, monkey/tests/unit_tests/monkey_island/cc/models/test_agent.py, vulture_allowlist.py
Fixes part of #2817.
Adds Agent.registration_time field
Sets registration_time when an agent registers
> Tested by {Running the unit tests}
=> 2817 add agent registration time field

monkey/monkey_island/cc/services/agent_signals_service.py, monkey/tests/unit_tests/monkey_island/cc/services/test_agent_signals_service.py
Fixes part of #2817.
If more than one agent is running on a given machine, the first agent shall be allowed to run, and the rest shall be given a terminate signal.
=> Island: Set terminate signal for duplicate agents

monkey/monkey_island/cc/app.py, monkey/monkey_island/cc/resources/auth/__init__.py, monkey/monkey_island/cc/resources/auth/login.py, monkey/monkey_island/cc/resources/auth/logout.py, monkey/monkey_island/cc/resources/auth/register.py
Disables the default login, logout, and register endpoints provided by flask-security
> Tested by sending cURL commands to the endpoints
=> Island: Disable default flask-security endpoints

docs/content/FAQ/_index.md
Updates the documentation concerning password resets to say that the data directory must be removed.
=> Docs: Update island password reset documentation

monkey/agent_plugins/exploiters/smb/Pipfile, monkey/agent_plugins/exploiters/smb/Pipfile.lock
Fixes part of #2952.
Adds a pipfile with the dependencies for SMB exploiter. The only dependency is impacket
=> SMB: Add pipfile for dependencies

monkey/agent_plugins/exploiters/smb/src/smb_options.py, monkey/tests/unit_tests/agent_plugins/exploiters/smb/test_smb_options.py, vulture_allowlist.py
Issue: #2952
Fixes part of #2952 
=> SMB: Add SMBOptions to SMBPlugin

monkey/infection_monkey/island_api_client/configuration_validator_decorator.py, monkey/infection_monkey/island_api_client/http_island_api_client.py, monkey/infection_monkey/island_api_client/i_island_api_client.py, monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py, vulture_allowlist.py
=> Agent: Add OTP fetching to the island api client

monkey/monkey_island/cc/services/authentication_service/configure_flask_security.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/register.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_register.py
This check is moved from a validator, because flask-security-too ignores email validators if generic responses are enabled
=> Island: Do manual "is user already registered" check

monkey/monkey_island/cc/ui/src/components/configuration-components/HtmlFieldDescription.js, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
Related to #3081.
Deletion of the HtmlFieldDescription function and its usages due to XSS vulnerability.
=> Deletion of the HtmlFieldDescription function

monkey/common/types/otp.py, monkey/common/utils/i_secret_variable.py, monkey/common/utils/secret_variable.py, monkey/infection_monkey/island_api_client/http_island_api_client.py, monkey/infection_monkey/main.py, monkey/infection_monkey/monkey.py, monkey/tests/data_for_tests/otp.py, monkey/tests/unit_tests/common/utils/test_secret_variable.py, monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py, monkey/tests/unit_tests/infection_monkey/test_monkey.py
Fixes a part of #3077
> Added dummy logs and checked that they were correctly formatted
=> Don't leak OTP in logs

monkey/tests/unit_tests/monkey_island/cc/services/aws/test_aws_command_runner.py
Issue: #3096
Sleep precision depends on the OS, that's why we can't reproduce locally. Based on the logic, the increase in timeout should fix it. The bigger the timeout, the more requests will be made. The timeout size is irrelevant for the failing test as long as it's long enough for the client to send at least 3 requests (the responses are mocked, so the third response will be a success). 
> Tested by running travis
=> UT: Fix AWS unit tests

monkey/agent_plugins/exploiters/smb/src/plugin.py, monkey/infection_monkey/i_puppet/__init__.py, monkey/infection_monkey/i_puppet/i_puppet.py, monkey/infection_monkey/i_puppet/target_host.py, monkey/infection_monkey/master/ip_scan_results.py, monkey/infection_monkey/master/ip_scanner.py, monkey/infection_monkey/network_scanning/tcp_scanner.py, monkey/infection_monkey/puppet/puppet.py, monkey/tests/unit_tests/agent_plugins/exploiters/hadoop/test_hadoop_exploiter.py, monkey/tests/unit_tests/agent_plugins/exploiters/smb/test_smb_plugin.py, monkey/tests/unit_tests/infection_monkey/i_puppet/test_target_host.py, monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
Fixes part of #2952.
Adds the following checks before running the exploiter:
- Check that the target has SMB ports open
=> SMB: Check for SMB ports before running exploiter

monkey/monkey_island/cc/app.py, monkey/monkey_island/cc/services/__init__.py, monkey/monkey_island/cc/services/authentication_service/__init__.py, monkey/monkey_island/cc/services/authentication_service/authentication_facade.py, monkey/monkey_island/cc/services/authentication_service/configure_flask_security.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/logout.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/register_resources.py, monkey/monkey_island/cc/services/authentication_service/setup.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_logout.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/test_authentication_service.py
=> 3138 revoke tokens on logout

monkey/infection_monkey/monkey.py, monkey/infection_monkey/network_scanning/ping_scanner.py, monkey/infection_monkey/network_scanning/tcp_scanner.py, monkey/infection_monkey/puppet/puppet.py, monkey/tests/unit_tests/infection_monkey/network_scanning/test_ping_scanner.py, monkey/tests/unit_tests/infection_monkey/network_scanning/test_tcp_scanner.py, monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Fixes part of #3119 by passing Agent ID to the ping and TCP scanners.
=> Agent: Pass Agent ID to the scanners

monkey/infection_monkey/credential_collectors/mimikatz_collector/mimikatz_credential_collector.py, monkey/infection_monkey/credential_collectors/ssh_collector/ssh_credential_collector.py, monkey/infection_monkey/credential_collectors/ssh_collector/ssh_handler.py, monkey/infection_monkey/monkey.py, monkey/tests/unit_tests/infection_monkey/credential_collectors/test_mimikatz_collector.py, monkey/tests/unit_tests/infection_monkey/credential_collectors/test_ssh_credentials_collector.py
Fixes part of #3119 by passing Agent ID to the mimikatz and SSH credential collectors.
=> Agent: Pass Agent ID to credentials collectors

monkey/infection_monkey/monkey.py, monkey/infection_monkey/puppet/plugin_registry.py, monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_registry.py, monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Fixes part of #3119 by passing Agent ID to the plugin registry
=> Agent: Pass Agent ID to PluginRegistry

monkey/infection_monkey/heart.py, monkey/infection_monkey/island_api_client/configuration_validator_decorator.py, monkey/infection_monkey/island_api_client/http_island_api_client.py, monkey/infection_monkey/island_api_client/http_island_api_client_factory.py, monkey/infection_monkey/island_api_client/i_island_api_client.py, monkey/infection_monkey/master/control_channel.py, monkey/infection_monkey/monkey.py, monkey/tests/unit_tests/infection_monkey/base_island_api_client.py, monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py, monkey/tests/unit_tests/infection_monkey/master/test_control_channel.py
Fixes part of #3119 by passing Agent ID to the `HTTPIslandAPIClient`
=> 3119 heart

monkey/agent_plugins/exploiters/smb/src/smb_client.py, monkey/infection_monkey/exploit/mssqlexec.py, monkey/infection_monkey/exploit/sshexec.py, monkey/infection_monkey/exploit/tools/brute_force_exploiter.py, monkey/infection_monkey/exploit/web_rce.py, monkey/infection_monkey/exploit/wmiexec.py, monkey/infection_monkey/exploit/zerologon.py, monkey/infection_monkey/master/propagator.py, monkey/infection_monkey/puppet/puppet.py, monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
Fixes #3150.
Instead of logging the whole TragetHost object, it logs only the host IP.
=> 3150 log target host ip

monkey/monkey_island/cc/app.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/login.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/register.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/utils.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/conftest.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_login.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_register.py
Fixes part of #3137.
Login and registration should respond with a token pair
> Tested by validating the output of cURL commands to the endpoints 
> ```
> $ curl -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data '{"username": "test", "password": "testtest"}' -k ${ISLAND}/api/register
> {"meta": {"code": 200}, "response": {"user": {"authentication_token": "WyJmOGMxZTc0YzBkNWM0MjQzYWI4NTE0NDY3MGYzNzRhYiJd.ZCW59Q.RHLJsim5y-SvYb8Nppe1qy_p0UY", "refresh_token": "ImY4YzFlNzRjMGQ1YzQyNDNhYjg1MTQ0NjcwZjM3NGFiIg.ZCW59Q.GaWzjz9XpCu50VItcHp8OYhgk6o"}, "csrf_token": "IjFhMzJmNDdlMzEyYmM1NDNjM2EwOGJlYzBmYWY2ZjI2OGFiZmE2MmIi.ZCW59Q.aPp670PyIpbjDa21IggSRVC1Zic"}}
>```
>```
> $ curl -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data …
```
=> Island: Include refresh token into responses

monkey/monkey_island/cc/services/authentication_service/configure_flask_security.py
This change means that the user will be able to be AFK for at most 17 minutes 59 seconds before getting logged out. Refresh token being 3 minutes means that the user has to be AFK at least 3 minutes to get logged out.
Issue: #3137
=> Island: Change access token lifetime to 15 minutes

monkey/monkey_island/cc/app.py
Related to #3078 
> Island starts with no errors
=> Build AuthenticationFacade with MongoOTPRepository

monkey/monkey_island/cc/app.py, monkey/monkey_island/cc/services/authentication_service/setup.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/test_authentication_service.py
=> Island: Move construction of AuthenicationFacade

monkey/monkey_island/cc/services/authentication_service/authentication_facade.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/agent_otp_login.py, monkey/monkey_island/cc/services/authentication_service/i_otp_repository.py, monkey/monkey_island/cc/services/authentication_service/mongo_otp_repository.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_agent_otp_login.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/test_authentication_service.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/test_mongo_otp_repository.py, monkey/tests/unit_tests/monkey_island/cc/services/test_agent_signals_service.py
=> OTP validation

monkey/monkey_island/cc/ui/package-lock.json, monkey/monkey_island/cc/ui/package.json, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunManually/LocalManualRunOptions.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/utils/CommandExpirationTimer.tsx
Fixes part of #3078 by displaying a countdown timer for the OTP expiration.
- Displays a countdown timer for command expiration
=> 3078 otp expiration timer

monkey/monkey_island/cc/services/authentication_service/mongo_otp_repository.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/test_mongo_otp_repository.py
Fixes a bug in MongoOTPRepository
The encryption algorithm is not deterministic, making searching impossible. Salted SHA256 is considered to be secure enough for one-time passwords with a 2-minute TTL.
> Tested locally with a hard-coded OTP and Postman
=> Island: Use SHA256 to hash OTPs

envs/monkey_zoo/blackbox/test_blackbox.py, monkey/monkey_island/cc/event_queue/i_island_event_queue.py, monkey/monkey_island/cc/island_event_handlers/agent_heartbeat_monitor.py, monkey/monkey_island/cc/services/authentication_service/authentication_facade.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/logout.py, monkey/monkey_island/cc/services/authentication_service/register_event_handlers.py, monkey/monkey_island/cc/services/authentication_service/setup.py, monkey/tests/unit_tests/monkey_island/cc/island_event_handlers/test_agent_heartbeat_monitor.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_logout.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/test_authentication_service.py
Fixes part of #3078 by removing users for agents that have shut down or timed out.
> Manually tested agent user removed after agent shutdown and when agent times out
> Ran the logout BB test to test that the agent user is removed after agent logs out
=> 3078 revoke agent tokens

monkey/monkey_island/cc/services/authentication_service/authentication_facade.py, monkey/monkey_island/cc/services/authentication_service/setup.py, monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/test_authentication_service.py
Fixes part of #3078 by invalidating OTPs on Island startup.
=> 3078 invalidate tokens on startup

monkey/infection_monkey/island_api_client/configuration_validator_decorator.py, monkey/infection_monkey/island_api_client/http_island_api_client.py, monkey/infection_monkey/island_api_client/i_island_api_client.py, monkey/infection_monkey/monkey.py, monkey/tests/unit_tests/infection_monkey/base_island_api_client.py
Fixes part of #3078 by logging agents out when they are finished.
> Tested by running the agent manually
=> 3078 logout agent

monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py, monkey/infection_monkey/exploit/sshexec.py, monkey/infection_monkey/model/__init__.py, monkey/infection_monkey/monkey.py, monkey/tests/unit_tests/infection_monkey/test_monkey.py
=> 3078 remove feature flag

envs/monkey_zoo/blackbox/test_blackbox.py, monkey/infection_monkey/island_api_client/http_client.py, monkey/infection_monkey/island_api_client/http_island_api_client.py, monkey/monkey_island/cc/services/authentication_service/authentication_facade.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/agent_otp.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/agent_otp_login.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/login.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/refresh_authentication_token.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/register_resources.py, monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_client.py, monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
Issue #3078
Adds rate limiting to authentication-related endpoints
=> 3078 rate limit login

envs/monkey_zoo/blackbox/test_blackbox.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/agent_otp.py, monkey/monkey_island/cc/services/authentication_service/flask_resources/refresh_authentication_token.py
Fixes part of #3078 by rate limiting endpoints by user instead of IP.
- Added a BB test
> Tested by running the BB test testing the OTP endpoint
=> 3078 rate limit users

CHANGELOG.md, monkey/agent_plugins/exploiters/hadoop/manifest.yaml, monkey/agent_plugins/exploiters/hadoop/src/hadoop_exploiter.py, monkey/infection_monkey/i_puppet/target_host.py, monkey/tests/unit_tests/infection_monkey/i_puppet/test_target_host.py
Adds `open` property to `PortScanDataDict`
Reimplements some Hadoop methods using the `open` and `closed` properties from `PortScanDataDict`
=> Hadoop port filtering improvements

monkey/common/utils/windows_permissions.py, monkey/monkey_island/.gitignore, monkey/monkey_island/cc/setup/data_dir.py, monkey/tests/monkey_island/utils.py, monkey/tests/unit_tests/monkey_island/cc/setup/test_data_dir.py
Prevents plugins in the `data_dir` from being overwritten on Island startup
=> Fix data dir plugin overwrite

envs/monkey_zoo/docs/zoo_network.md, envs/monkey_zoo/packer/setup_tunneling_10.yml, envs/monkey_zoo/packer/setup_tunneling_9.yml, envs/monkey_zoo/packer/tunneling.pkr.hcl, envs/monkey_zoo/terraform/monkey_zoo.tf
Fixes #3198.
Adds packer scripts for the tunneling-9 and tunneling-10 machines.
> Tested by running the depth-4 test in the test1 zoo using the generated images
=> 3198 Packerize the tunneling 9, 10 images

monkey/monkey_island/cc/services/agent_binary_service/agent_binary_repository.py, monkey/monkey_island/cc/services/agent_binary_service/agent_binary_service.py, monkey/monkey_island/cc/services/agent_binary_service/build.py, monkey/monkey_island/cc/services/agent_binary_service/flask_resources/agent_binaries.py, monkey/monkey_island/cc/services/agent_binary_service/i_agent_binary_repository.py, monkey/monkey_island/cc/services/agent_binary_service/i_agent_binary_service.py, monkey/monkey_island/cc/services/agent_binary_service/masquerade_agent_binary_repository_decorator.py, monkey/monkey_island/cc/services/run_local_monkey.py, monkey/tests/monkey_island/__init__.py, monkey/tests/monkey_island/in_memory_agent_binary_repository.py, monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/test_agent_binary_repository.py, monkey/tests/unit_tests/monkey_island/cc/services/agent_binary_service/test_masquerade_agent_binary_repository_decorator.py
Issue #3241
Change the interface of `IAgentBinaryService` to provide `get_agent_binary()`
=> 3241 refactor get agent binary methods

monkey/infection_monkey/monkey.py, monkey/infection_monkey/plugin/credentials_collector_plugin_factory.py, monkey/infection_monkey/plugin/exploiter_plugin_factory.py, monkey/infection_monkey/plugin/i_plugin_factory.py, monkey/infection_monkey/plugin/multiprocessing_plugin_wrapper.py, monkey/infection_monkey/puppet/plugin_registry.py, monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_registry.py, monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Fixes part of #3167.
Adds loading of Credentials Collectors to the PluginRegistry
=> 3167 load credential collector plugins

envs/monkey_zoo/README.md, envs/monkey_zoo/docs/zoo_setup.md, envs/monkey_zoo/packer/setup_tunneling_10.yml, envs/monkey_zoo/packer/setup_tunneling_9.yml
Fixes #3198.
Removes sshguard, which was preventing brute-forcing over SSH, and causing our depth_4 test to fail.
=> 3198 remove sshguard

monkey/agent_plugins/credentials_collectors/mimikatz/config-schema.json, monkey/agent_plugins/credentials_collectors/mimikatz/manifest.yaml, monkey/agent_plugins/credentials_collectors/mimikatz/src/mimikatz_options.py, vulture_allowlist.py
=> 3168 mimikatz collector settings

monkey/agent_plugins/exploiters/smb/src/plugin.py, monkey/agent_plugins/exploiters/wmi/src/plugin.py, monkey/infection_monkey/exploit/tools/__init__.py, monkey/infection_monkey/exploit/tools/brute_force_credentials_generator.py, monkey/tests/unit_tests/infection_monkey/exploit/tools/test_brute_force_credentials_generator.py, vulture_allowlist.py
Adds identity type filtering to SMB and WMI plugins
It's conceivable that different types of Identities are added, such as email addresses. This PR adds identity type filtering to brute-force exploiter plugins so that they don't crash if new identities are ever added.
ETE tests should be run before this is merged.
=> 3163 add identity filtering

CHANGELOG.md, monkey/common/utils/environment.py, monkey/infection_monkey/i_puppet/__init__.py, monkey/infection_monkey/i_puppet/i_puppet.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/puppet/plugin_compatability_verifier.py, monkey/infection_monkey/puppet/puppet.py, monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py, monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_compatability_verifier.py, monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Issue #3168
Add the ability to verify supported operating system compatability.
=> 3168 verify supported operating system

monkey/agent_plugins/exploiters/wmi/src/plugin.py, monkey/agent_plugins/exploiters/wmi/src/smb_client.py, monkey/agent_plugins/exploiters/wmi/src/smb_options.py, monkey/agent_plugins/exploiters/wmi/src/smb_remote_access_client.py, monkey/agent_plugins/exploiters/wmi/src/wmi_client.py, monkey/agent_plugins/exploiters/wmi/src/wmi_options.py, monkey/agent_plugins/exploiters/wmi/src/wmi_remote_access_client.py, monkey/agent_plugins/exploiters/wmi/src/wmi_remote_access_client_factory.py, monkey/tests/agent_plugins/exploiter_plugin_runner.py, monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_client.py, monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_options.py, monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_remote_access_client.py, monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_smb_client.py, monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_smb_options.py, monkey/tests/unit_tests/agent_plugins/exploiters/wmi/test_wmi_smb_remote_access_client.py
Fixes #3163.
Adds the WMIRemoteAccessClient
> Tested by running the exploiter_plugin_runner
```
$ python tests/agent_plugins/exploiter_plugin_runner.py
ExploiterResultData(exploitation_success=True, propagation_success=True, os='', info=None, error_message='')
```
=> 3163 wmi exploit client

monkey/common/__init__.py, monkey/common/hard_coded_manifests/__init__.py, monkey/infection_monkey/master/automated_master.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/puppet/plugin_compatibility_verifier.py, monkey/infection_monkey/puppet/puppet.py, monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Issue #3168
Adds OS compatibility verification for credentials collectors
> Tested by running manually on Linux.
*  [x] If applicable, add screenshots or log transcripts of the feature working
```
2023-04-28 16:51:19,030 [33260:CredentialsCollectorThread:INFO] automated_master._run_plugins.175: Running credentials collectors
2023-04-28 16:51:19,030 [33260:CredentialsCollectorThread:DEBUG] automated_master._run_plugins.176: Found 2 credentials collector(s) to run
2023-04-28 16:51:19,030 [33260:CredentialsCollectorThread:INFO] automated_master._run_plugins.181: Trying to run plugin "MimikatzCollector" of type "credentials collector"
2023-04-28 16:51:19,030 [33260:CredentialsCollectorThread:INFO] automated_master._run_plugins.184: Skipping plugin MimikatzCollector of type credentials …
```
=> 3168 verify credentials collectors os compatibility

monkey/agent_plugins/exploiters/snmp/manifest.yaml
- Adds a plugin manifest for the SNMP plugin
=> SNMP: Add plugin manifest

monkey/monkey_island/cc/ui/src/components/IslandHttpClient.tsx, monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js, monkey/monkey_island/cc/ui/src/components/pages/LandingPage.tsx
Fixes part of #3242 .
Things left to do:
https://user-images.githubusercontent.com/15820737/236820737-7b95f7ad-3968-4c4c-9c0d-bebd1ec3dd84.mov
=> Submit masquerade strings

monkey/agent_plugins/exploiters/snmp/src/community_string_generator.py, monkey/common/credentials/__init__.py, monkey/common/credentials/credentials.py, monkey/tests/unit_tests/agent_plugins/exploiters/snmp/test_community_string_generator.py
Add a class to generate community strings from credentials
=> SNMP: Add class to generate community strings

monkey/monkey_island/cc/ui/src/utils/sanitizers/uriSanitizer/uriSanitizer.js
Removal of the global flag from the regex.
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex
=> UI: Fix uri sanitizer function

monkey/tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_agent_otp_login.py
Fixes a broken UT
```
FAILED tests/unit_tests/monkey_island/cc/services/authentication_service/flask_resources/test_agent_otp_login.py::test_invalid_json - assert 415 == <HTTPStatus.BAD_REQUEST: 400>
```
=> Fix broken UT on Flask upgrade

CHANGELOG.md, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunManually/LocalManualRunOptions.js, monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunMonkeyPage.js
=> Update manual run page

envs/monkey_zoo/blackbox/gcp_test_machine_list.py, envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
Fixes part of #3234 .
Merge after the exploiter plugin is done and tested.
=> BB: Add SNMP configuration to depth_1_a grouped tests

docs/content/reference/exploiters/SNMP.md, monkey/agent_plugins/exploiters/snmp/manifest.yaml
Add documentation for the SNMP exploiter
=> Docs: Add documentation for the SNMP exploiter

monkey/common/utils/file_utils/__init__.py, monkey/common/utils/file_utils/file_utils.py, monkey/infection_monkey/exploit/__init__.py, monkey/infection_monkey/exploit/polymorphic_agent_binary_repository_decorator.py, monkey/monkey_island/cc/services/agent_binary_service/masquerade_agent_binary_repository_decorator.py, monkey/tests/unit_tests/common/utils/test_file_utils.py, monkey/tests/unit_tests/infection_monkey/exploit/test_polymorphic_agent_binary_repository_decorator.py
Issue #3224 
Add PolymorphicAgentBinaryRepositoryDecorator
=> 3244 agent binary repository decorator

envs/monkey_zoo/blackbox/test_configurations/noop.py, monkey/common/agent_configuration/__init__.py, monkey/common/agent_configuration/agent_sub_configurations.py, monkey/common/agent_configuration/default_agent_configuration.py, monkey/infection_monkey/monkey.py, monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js, monkey/monkey_island/cc/ui/src/services/configuration/polymorphism.js, monkey/tests/common/example_agent_configuration.py, monkey/tests/unit_tests/infection_monkey/island_api_client/configuration_validation_constants.py
Issue #3244
Enables randomized binary hash in the agent.
> Tested by manually by running a single BB test and checking the hashes of the binaries.
=> 3244 enable random hash in agent

monkey/monkey_island/cc/island_event_handlers/handle_agent_registration.py, monkey/monkey_island/cc/models/agent.py, monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_scan_event_handler.py, monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_update_agent_shutdown_status.py, monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_update_machine_hostname.py, monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_update_machine_os.py, monkey/tests/unit_tests/monkey_island/cc/island_event_handlers/test_agent_heartbeat_monitor.py, monkey/tests/unit_tests/monkey_island/cc/island_event_handlers/test_handle_agent_registration.py, monkey/tests/unit_tests/monkey_island/cc/models/test_agent.py, monkey/tests/unit_tests/monkey_island/cc/repositories/test_agent_machine_facade.py, monkey/tests/unit_tests/monkey_island/cc/repositories/test_mongo_agent_repository.py, monkey/tests/unit_tests/monkey_island/cc/repositories/test_network_model_update_facade.py, monkey/tests/unit_tests/monkey_island/cc/resources/test_agents.py, monkey/tests/unit_tests/monkey_island/cc/services/reporting/test_report.py, monkey/tests/unit_tests/monkey_island/cc/services/test_agent_signals_service.py
Fixes part of #3244.
Merge after #3346.
Adds sha256 to Agent model
Sets the Agent sha256 on agent registration
=> 3244 agent sha256

monkey/agent_plugins/exploiters/snmp/src/plugin.py, monkey/agent_plugins/exploiters/snmp/src/snmp_command_builder.py, monkey/agent_plugins/exploiters/snmp/src/snmp_exploiter.py, monkey/infection_monkey/dropper.py, monkey/infection_monkey/exploit/tools/helpers.py, monkey/infection_monkey/exploit/tools/http_agent_binary_server.py, monkey/infection_monkey/utils/__init__.py, monkey/infection_monkey/utils/commands.py, monkey/infection_monkey/utils/script_dropper.py, monkey/tests/unit_tests/agent_plugins/exploiters/snmp/test_snmp_command_builder.py, monkey/tests/unit_tests/agent_plugins/exploiters/snmp/test_snmp_exploiter.py, monkey/tests/unit_tests/infection_monkey/exploit/tools/test_helpers.py, monkey/tests/unit_tests/infection_monkey/utils/test_commands.py, monkey/tests/unit_tests/infection_monkey/utils/test_script_dropper.py, vulture_allowlist.py
Fixes #3234.
> Tested by running manually on Linux and Windows, as well as using the exploiter_plugin_runner
=> 3234 script dropper

CHANGELOG.md, monkey/common/credentials/__init__.py, monkey/common/credentials/credentials.py, monkey/common/credentials/email_address.py, monkey/infection_monkey/Pipfile, monkey/infection_monkey/Pipfile.lock, monkey/monkey_island/Pipfile, monkey/monkey_island/Pipfile.lock, monkey/monkey_island/cc/ui/package-lock.json, monkey/monkey_island/cc/ui/package.json, monkey/monkey_island/cc/ui/src/components/configuration-components/CredentialsConfig.tsx, monkey/monkey_island/cc/ui/src/components/configuration-components/PropagationConfig.tsx, monkey/monkey_island/cc/ui/src/components/configuration-components/ReformatHook.js, monkey/monkey_island/cc/ui/src/components/configuration-components/ValidationErrorMessages.js, monkey/monkey_island/cc/ui/src/components/configuration-components/ValidationFormats.js, monkey/monkey_island/cc/ui/src/components/report-components/credentialParsing.tsx, monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx, monkey/monkey_island/cc/ui/src/components/utils/CredentialTitle.tsx, monkey/monkey_island/cc/ui/src/services/configuration/propagation/credentials.js, monkey/tests/data_for_tests/propagation_credentials.py, monkey/tests/unit_tests/common/credentials/test_email_address.py, monkey/tests/unit_tests/infection_monkey/exploit/tools/test_brute_force_credentials_generator.py
Fixes #3270
> Tested configuration manually
=> Add email address identity type

monkey/agent_plugins/exploiters/snmp/src/snmp_client.py, monkey/agent_plugins/exploiters/snmp/src/snmp_exploit_client.py, monkey/tests/unit_tests/agent_plugins/exploiters/snmp/test_snmp_client.py, monkey/tests/unit_tests/agent_plugins/exploiters/snmp/test_snmp_exploit_client.py
Fixes #3234.
- Adds additional logging to SNMP
- Switches from using createAndGo to createAndWait, which proved to be more robust in testing
> Tested by running an abridged depth_1 test ~300 times without issue
=> 3234 fix inconsistent value error

monkey/agent_plugins/exploiters/powershell/src/credentials_generator.py, monkey/tests/unit_tests/agent_plugins/exploiters/powershell/test_credentials_generator.py
Issue #3165
Adds a credentials generator for powershell plugin
=> 3165 credentials generator

monkey/agent_plugins/exploiters/log4shell/src/log4shell_options.py, monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_options.py, vulture_allowlist.py
=> Log4Shell: Add options

monkey/agent_plugins/exploiters/log4shell/config-schema.json
=> Log4Shell: Add config schema

monkey/agent_plugins/exploiters/ssh/src/plugin.py, monkey/tests/unit_tests/agent_plugins/exploiters/ssh/test_ssh_plugin.py
=> SSH exploiter plugin.py

monkey/monkey_island/cc/repositories/plugin_archive_parser.py, monkey/tests/unit_tests/infection_monkey/puppet/test_plugin_source_extractor.py, monkey/tests/unit_tests/monkey_island/cc/repositories/test_file_agent_plugin_repository.py, monkey/tests/unit_tests/monkey_island/cc/repositories/test_plugin_archive_parser.py
Compressing plugins can be slow. This resulted in some failures in the end-to-end testing, as the Island was blocked while compressing plugins. This PR reduces the compression level in order to improve performance.
=> Fix slow compression

monkey/infection_monkey/network/info.py, monkey/tests/unit_tests/infection_monkey/network/test_info.py
Fixes part of #3410.
Allows preferred ports to be provided to TCPPortSelector.get_free_tcp_port.
=> Agent: Add preferred_ports to TCPPortSelector.get_free_tcp_port

monkey/agent_plugins/exploiters/log4shell/manifest.yml, monkey/agent_plugins/exploiters/log4shell/src/log4shell_exploiter.py, monkey/agent_plugins/exploiters/log4shell/src/plugin.py, monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_exploiter.py, monkey/tests/unit_tests/agent_plugins/exploiters/log4shell/test_log4shell_plugin.py
Fixes part of #3410.
Updates the Log4Shell exploiter to use the `HTTPAgentBinaryServer`
> Tested by running log4shell exploiter in the zoo environment
=> Log4Shell: Use HTTPAgentBinaryServerRegistrar

monkey/agent_plugins/exploiters/snmp/manifest.yaml, monkey/agent_plugins/exploiters/snmp/src/plugin.py, monkey/agent_plugins/exploiters/snmp/src/snmp_exploiter.py, monkey/infection_monkey/exploit/tools/http_agent_binary_server.py, monkey/tests/unit_tests/agent_plugins/exploiters/snmp/test_snmp_exploiter.py
Fixes part of #3410.
Updates SNMP exploiter to use the `HTTPAgentBinaryServer`
=> 3410 use shared http server snmp

monkey/monkey_island/cc/resources/exploitations/monkey_exploitation.py, monkey/monkey_island/cc/resources/ransomware_report.py, monkey/monkey_island/cc/services/agent_configuration_service/agent_configuration_schema_compiler.py, monkey/monkey_island/cc/services/initialize.py, monkey/monkey_island/cc/services/ransomware/ransomware_report.py, monkey/monkey_island/cc/services/reporting/exploitations/monkey_exploitation.py, monkey/monkey_island/cc/services/reporting/report.py, monkey/tests/unit_tests/monkey_island/cc/services/agent_configuration_service/test_agent_configuration_schema_compiler.py, monkey/tests/unit_tests/monkey_island/cc/services/ransomware/test_ransomware_report.py, monkey/tests/unit_tests/monkey_island/cc/services/reporting/test_report.py
Fixes part of #3415.
Updates users of `IAgentPluginRepository` to instead use `IAgentPluginService`.
=> 3415 use agent plugin service

monkey/agent_plugins/payloads/ransomware/Pipfile, monkey/agent_plugins/payloads/ransomware/Pipfile.lock, monkey/agent_plugins/payloads/ransomware/config-schema.json, monkey/agent_plugins/payloads/ransomware/manifest.yaml, monkey/agent_plugins/payloads/ransomware/src/ransomware_options.py, monkey/tests/unit_tests/agent_plugins/payloads/ransomware/test_ransomware_options.py, vulture_allowlist.py
This PR creates the options, config schema, manifest, and dependency files for the ransomware payload plugin.
There's a TODO in `ransomware_options.py` about a flake8 complaint that needs to be addressed.
Fixes a part of #3391
=> Ransomware plugin skeleton

monkey/agent_plugins/payloads/ransomware/src/internal_ransomware_options.py, monkey/tests/unit_tests/agent_plugins/payloads/ransomware/test_internal_ransomware_options.py
Adds an internal representation of the Ransomware configuration that can be used by the ransomware plugin.
Issue #3391
=> Ransomware: Add InternalRansomwareOptions object

CHANGELOG.md, monkey/common/agent_events/__init__.py, monkey/common/agent_events/cpu_consumption_event.py, monkey/common/agent_events/http_request_event.py, monkey/common/agent_events/ram_consumption_event.py, monkey/tests/unit_tests/common/agent_events/test_cpu_consumption_event.py, monkey/tests/unit_tests/common/agent_events/test_http_request_event.py, monkey/tests/unit_tests/common/agent_events/test_ram_consumption_event.py, vulture_allowlist.py
Adds events that will be used by the cryptojacker.
Issue #3411
=> 3411 define events

envs/monkey_zoo/packer/setup_rdp_64.yml
Fixes part of #3425.
Allow incoming traffic over port 8080 on rdp-64
> Tested by running RDP exploiter with an rdp-64 instance generated with this change
=> BB: Allow port 8080 on rdp-64

monkey/agent_plugins/payloads/cryptojacker/src/bitcoin_mining_network_traffic_simulator.py, monkey/agent_plugins/payloads/cryptojacker/src/cpu_utilizer.py, monkey/agent_plugins/payloads/cryptojacker/src/cryptojacker.py, monkey/agent_plugins/payloads/cryptojacker/src/cryptojacker_builder.py, monkey/agent_plugins/payloads/cryptojacker/src/memory_utilizer.py, monkey/agent_plugins/payloads/cryptojacker/src/plugin.py
- Fixes the Cryptojacker payload where `IAgentEventQueue` was expected when it should've been `IAgentEventPublisher`
- ~Removes `cpu_number` from `CPUConsumptionEvent` since [it isn't possible to find the CPU on which a process is running in Windows](https://psutil.readthedocs.io/en/latest/index.html#psutil.Process.cpu_num)~
Issue #3411 
=> Cryptojacker fixes

monkey/agent_plugins/exploiters/rdp/Pipfile, monkey/agent_plugins/exploiters/rdp/Pipfile.lock, monkey/agent_plugins/exploiters/rdp/src/plugin.py, monkey/agent_plugins/exploiters/rdp/src/rdp_credentials_generator.py, monkey/tests/unit_tests/agent_plugins/exploiters/rdp/test_rdp_credentials_generator.py
Fixes part of #3425.
Considers local domains when generating credentials.
=> 3425 rdp domain logic

monkey/agent_plugins/exploiters/rdp/src/rdp_client.py
Issue #3425 .
By default Copy/Paste via shortcuts it is not enabled in Windows Server 2012 and some other versions of Windows. We need to interactively paste the command in the Command Prompt using Alt+Space,e,p.
=> 3425 win 2012

monkey/agent_plugins/payloads/cryptojacker/src/memory_utilizer.py, monkey/tests/unit_tests/agent_plugins/payloads/cryptojacker/test_memory_utilizer.py
Implements MemoryUtilizer
Issue #3411
> Ran manually on my local machine using a test harness
=> 3411 memory utilization component

envs/monkey_zoo/blackbox/gcp_test_machine_list.py, envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py, envs/monkey_zoo/terraform/firewalls.tf
Fixes #3425 .
RDP machines are added to depth_2 grouped test.
=> 3425 rdp ete test

monkey/monkey_island/cc/ui/src/components/configuration-components/ReformatHook.js
Bug happens when secret is null, so Object.entries can't process null parameter
Fixes a bug:
> Tested by adding empty secrets, reloading the webpage
=> UI: Fix a credential formatting bug in UI

monkey/agent_plugins/payloads/cryptojacker/src/bitcoin_mining_network_traffic_simulator.py
Fixes the getblocktemplate request sent out by cryptojacker
Issue #3411
=> 3411 fix getblocktemplate request

CHANGELOG.md, monkey/monkey_island/cc/flask_utils/responses.py, monkey/monkey_island/cc/services/agent_plugin_service/agent_plugin_service.py, monkey/monkey_island/cc/services/agent_plugin_service/errors.py, monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/__init__.py, monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/register.py, monkey/monkey_island/cc/services/agent_plugin_service/flask_resources/uninstall_agent_plugin.py, monkey/monkey_island/cc/services/agent_plugin_service/i_agent_plugin_service.py, monkey/tests/monkey_island/in_memory_agent_plugin_repository.py, monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/flask_resources/test_uninstall_agent_plugin.py, monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/test_agent_plugin_service.py, vulture_allowlist.py
Fixes #3422 .
Adda RPC styled endpont to uninstall agent plugins based on type and name.
One TODO remaining in UTs to discuss
=> 3422 add uninstall agent plugin

monkey/common/base_models.py, monkey/monkey_island/cc/services/agent_plugin_service/mongo_agent_plugin_repository.py, monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/test_mongo_agent_plugin_repository.py
Fixes the issue in which an error was raised because the agent plugins were too large for Mongo, causing the server to crash.
=> Fix mongo agent plugin document too large

monkey/monkey_island/cc/ui/src/components/ui-components/MonkeyToggle.js
Fixes part of #3418 
- Add custom Toggle component
=> UI Add custom Toggle component

monkey/monkey_island/cc/services/agent_plugin_service/i_agent_plugin_repository.py, monkey/monkey_island/cc/services/agent_plugin_service/mongo_agent_plugin_repository.py, monkey/tests/unit_tests/monkey_island/cc/services/agent_plugin_service/test_mongo_agent_plugin_repository.py
Fixes a bug in storing agent plugins.
=> Island: Preserve stored binaries when storing plugin

monkey/monkey_island/cc/agent_event_handlers/scan_event_handler.py, monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_scan_event_handler.py
Prevents discovered services from being overwritten by the agent `ScanEventHandler`.
=> 3000 fix tcp scan service overwrite

monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.tsx, monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/BasePlugins.tsx, monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/InstalledPlugins.tsx, monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/PluginTable.tsx
Make plugin type values human readable in plugin grid (removes underscores)
#3418
> Tested UI
=> Fix plugin type value in grid

monkey/monkey_island/cc/ui/src/components/IslandHttpClient.tsx, monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.tsx, monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/InstalledPlugins.tsx
Uses IslandHttpClient for API requests
Issue #3418
> Tested the Island manually
=> Use IslandHttpClient for plugin-related API requests

monkey/monkey_island/cc/ui/src/components/contexts/plugins/PluginsContext.tsx, monkey/monkey_island/cc/ui/src/components/ui-components/plugins-marketplace/AvailablePlugins.tsx, monkey/monkey_island/cc/ui/src/components/ui-components/utils/useInterval.tsx, monkey/monkey_island/cc/ui/src/utils/timeConsts.js
- Add an hourly interval to force refresh plugins
=> UI: refresh plugins interval

CHANGELOG.md, monkey/common/agent_events/abstract_agent_event.py
The MITRE ATT&CK framework identifies subtechniques by using a '.' to separate the technique ID from the subtechnique ID. For example, the technique "Defacement" has the ID T1491, whereas the subtechnique "Internal Defacement" has the ID T1491.001.
=> Common: Allow '.' characters in Event tags

monkey/agent_plugins/credentials_collectors/chrome/src/linux_credentials_database_selector.py, monkey/tests/unit_tests/agent_plugins/credentials_collectors/chrome/test_linux_credentials_database_selector.py
=> 3426 linux chrome credentials collector

monkey/monkey_island/cc/ui/src/components/ui-components/IslandResetModal.tsx
Updates UI to mentions that plugins won't be uninstalled even if you reset the Island completely.
> Tested by running UI
=> Update text in reset data modal in UI

monkey/agent_plugins/build_windows_vendor_directory.ps1
When building vendor-windows dir for each plugin we forgot to remove the vendor-windows directory which meant that if some plugin is rebuild, some of the dependencies may still be left out.
=> Remove vendor-windows dir after building the zip

monkey/monkey_island/cc/ui/src/components/report-components/ransomware/FileEncryptionTable.tsx
Fixes issue with column widths not maximizing available space for the "file path" column:
> ![Screenshot 2023-09-18 at 5 41 31 PM](https://github.com/guardicore/monkey/assets/11077625/302677da-6517-445e-8428-6d6a78883e96)
=> Fix encrypted files table

CHANGELOG.md, monkey/agent_plugins/exploiters/hadoop/config-schema.json, monkey/agent_plugins/exploiters/hadoop/manifest.yml, monkey/agent_plugins/exploiters/log4shell/config-schema.json, monkey/agent_plugins/exploiters/log4shell/manifest.yml, monkey/agent_plugins/exploiters/mssql/config-schema.json, monkey/agent_plugins/exploiters/mssql/manifest.yaml
Hadoop, MSSQL, and Log4Shell would allow floating-point numbers for network ports. This PR fixes these three exploiters to allow only integer ports.
> Ran depth 1 tests
=> Plugin ports as integers

build_scripts/appimage/appimage.sh
Fixes the appimage build. The download link changed: https://github.com/niess/python-appimage/releases/tag/python3.11
=> Build: Update python appimage to 3.11.6

monkey/infection_monkey/monkey.py, monkey/infection_monkey/plugin/exploiter_plugin_factory.py
Passes the Agent OTP environment variable to ExploiterPluginFactory and then to plugins when they're built
Fixes a part of #3741
* [c] Have you added an explanation of what your changes do and why you'd like to include them?
=> Pass Agent OTP env var to exploiters

monkey/agent_plugins/exploiters/hadoop/src/plugin.py, monkey/agent_plugins/exploiters/log4shell/src/plugin.py, monkey/agent_plugins/exploiters/mssql/src/plugin.py, monkey/agent_plugins/exploiters/powershell/src/plugin.py, monkey/agent_plugins/exploiters/rdp/src/plugin.py, monkey/agent_plugins/exploiters/smb/src/plugin.py, monkey/agent_plugins/exploiters/snmp/src/plugin.py, monkey/agent_plugins/exploiters/ssh/src/plugin.py, monkey/agent_plugins/exploiters/wmi/src/plugin.py, monkey/agent_plugins/exploiters/zerologon/src/plugin.py, monkey/agent_plugins/payloads/cryptojacker/src/plugin.py, monkey/agent_plugins/payloads/ransomware/src/plugin.py
Fixes a part of #3769 
> All exploiters pass at least once (~2 tunneling machines didn't communicate back in depth_4_a, probably due to speed issues~ everything passed the second time)
=> Remove logic to delete http_ports option in plugins

monkey/common/agent_plugins/agent_plugin.py
Typehint is useful because developers will know before runtime that invalid config schema was passed. Due to a limitation/bug in pydantic we can't use self-referencing version, but this should be good enough and catch the majority of cases
=> Agent: Add a typehint for config schema in AgentPlugin

monkey/agent_plugins/exploiters/smb/config-schema.json
Required is not needed, because we have reasonable defaults that will be used to fill in the values in case the fields are missing
Fixes part of #3839
=> SMB: Remove required field from config-schema

monkey/agent_plugins/exploiters/hadoop/config-schema.json
Required is not needed, because we have reasonable defaults that will be used to fill in the values in case the fields are missing
Fixes part of #3839
=> Hadoop: Remove required field from config-schema

monkey/infection_monkey/Pipfile, monkey/infection_monkey/Pipfile.lock
Removes paramiko dependency (and sub-dependencies) from the Agent. This was missed in #3170
> SSH-related tests pass
=> Agent: Remove disused paramiko dependency

build_scripts/appimage/appimage.sh
Fixes broken build due to 3.11.6 appimage no longer being available
=> Python patch version update (3.11.7)

monkey/infection_monkey/exploit/http_agent_binary_server.py, monkey/infection_monkey/exploit/http_agent_binary_server_factory.py, monkey/infection_monkey/local_machine_info.py, monkey/infection_monkey/monkey.py, monkey/infection_monkey/network/tools.py, monkey/tests/unit_tests/infection_monkey/exploit/test_http_agent_binary_server.py, monkey/tests/unit_tests/infection_monkey/network/test_tools.py
Reimplements `get_interface_to_target()`
Issue #3751
=> 3751 reimplement get interface to target

envs/monkey_zoo/blackbox/test_blackbox.py
Fixes part of #3583.
Since the test contains only Windows machine the assertion is not needed. We will have two hashes when running from Linux/ Docker and one when running from MSI.
=> Remove hash length assert in depth 2B

CHANGELOG.md, monkey/infection_monkey/network/relay/relay_connection_handler.py, monkey/infection_monkey/network/relay/relay_user_handler.py, monkey/infection_monkey/network/relay/sockets_pipe.py, monkey/infection_monkey/network/relay/tcp_connection_handler.py, monkey/infection_monkey/network/relay/tcp_pipe_spawner.py, monkey/infection_monkey/network/relay/tcp_relay.py, monkey/tests/unit_tests/infection_monkey/network/relay/test_relay_connection_handler.py, monkey/tests/unit_tests/infection_monkey/network/relay/test_relay_user_handler.py, monkey/tests/unit_tests/infection_monkey/network/relay/test_sockets_pipe.py
Fixes #3945.
Refreshes the RelayUser timeout whenever traffic comes from that relay user.
> Tested by running the depth_3 tunneling test, and verifying that the relay remains open for new connections longer than the original timeout would have allowed
> 2023-12-12 19:24:51,774 [2863:TCPConnectionHandler:DEBUG] tcp_connection_handler.run.44: New connection received from: ('10.2.1.10', 43068)
2023-12-12 19:24:51,777 [2863:TCPConnectionHandler:DEBUG] relay_user_handler.add_relay_user.64: Added relay user RelayUser(address='10.2.1.10', time_remaining=20.000)
2023-12-12 19:24:51,826 [2863:SocketsPipeThread-1:DEBUG] tcp_pipe_spawner._handle_pipe_closed.65: Closing pipe <SocketsPipe(SocketsPipeThread-1, started daemon 139867111532288)>
2023-12-12 19:24:52,226 [2863:AutomatedMasterThread:DEBUG] …
=> 3945 keep relay open for descendants

monkey/agent_plugins/exploiters/rdp/Pipfile, monkey/agent_plugins/exploiters/rdp/Pipfile.lock
Fixes part of #3583 .
Oscrypto has not yet released with fix to this [issue](https://github.com/wbond/oscrypto/issues/78) so we need to lock the commit until oscrypto releases. 
=> Lock oscrypto to fix libcrypto issue with RDP

envs/monkey_zoo/docs/zoo_network.md, envs/monkey_zoo/packer/rdp.pkr.hcl, envs/monkey_zoo/packer/setup_rdp_64.yml, envs/monkey_zoo/packer/setup_rdp_65.yml
Fixes #3583 .
Disables PowerShell Remoting on the RDP machines and uses custom Windows Server 2012 R2 for .65
Things left to do:
=> 3583 rdp machines

build_scripts/docker/docker.sh
Fixes #3964 
Running of docker with feature flags:
```bash
sudo docker run \   
--tty \
--interactive \
--name monkey-island \
--network=host \
--env FEATURE_FLAGS="NEXT_JS_UI" \
infectionmonkey/monkey-island:614b9f658
```
Or for multiple environments check [this](https://docs.docker.com/engine/reference/commandline/run/#env)
=> 3964 docker feature flags

monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
=> UI: Add more descriptive message upon submitting invalid credentials

monkey/infection_monkey/agent_plugin_api_imports.py, monkey/infection_monkey/i_puppet/__init__.py, monkey/infection_monkey/i_puppet/fingerprint_data.py, monkey/infection_monkey/i_puppet/i_fingerprinter.py, monkey/infection_monkey/i_puppet/i_puppet.py, monkey/infection_monkey/master/ip_scan_results.py, monkey/infection_monkey/master/ip_scanner.py, monkey/infection_monkey/master/propagator.py, monkey/infection_monkey/network_scanning/http_fingerprinter.py, monkey/infection_monkey/network_scanning/mssql_fingerprinter.py, monkey/infection_monkey/network_scanning/smb_fingerprinter.py, monkey/infection_monkey/network_scanning/ssh_fingerprinter.py, monkey/infection_monkey/puppet/puppet.py, monkey/tests/unit_tests/infection_monkey/i_puppet/test_fingerprint_data.py, monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py, monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py, monkey/tests/unit_tests/infection_monkey/master/test_propagator.py, monkey/tests/unit_tests/infection_monkey/network_scanning/test_ssh_fingerprinter.py
=> 4010 migrate fingerprint data

monkey/monkey_island/cc/next_ui/src/app/(auth)/login/page.tsx, monkey/monkey_island/cc/next_ui/src/app/(auth)/login/useRedirectToRegistration.tsx, monkey/monkey_island/cc/next_ui/src/app/(auth)/registration/page.tsx, monkey/monkey_island/cc/next_ui/src/app/(auth)/registration/useRedirectToLogin.tsx, monkey/monkey_island/cc/next_ui/src/app/(protected)/_lib/useRedirectionOnLogout.tsx, monkey/monkey_island/cc/next_ui/src/app/(protected)/_lib/useRedirectionWhenUnauthenticated.tsx, monkey/monkey_island/cc/next_ui/src/constants/paths.constants.tsx
Fixes authentication page names.
Login and registration are easier to comprehend for non-native speakers.
> Tested by navigating to the pages, doing basic auth flow
=> UI: Rename sign[in/up] into registration/login

monkey/infection_monkey/Pipfile, monkey/monkey_island/Pipfile
Updates the Island and Agent pipfiles to use markers instead of setting sys_platform directly. This enables selective package upgrades `pipenv upgrade <package>` on more recent versions of pipenv.
=> Enable selective package upgrades

monkey/monkey_island/cc/mongo_consts.py, monkey/monkey_island/cc/services/authentication_service/configure_flask_security.py
Addresses the issue by parsing MONGO_URL into its constituent parts and using them to set the values provided to flask-security.
Issue #4170.
> Tested by running monkey-island and mongo in a docker-compose script, setting the MONKEY_MONGO_URL using the mongo service name
=> Island: Use MONGO_URL instead of hard-coded values for flask-security

monkey/monkey_island/cc/next_ui/src/_components/icons/MonkeyLoadingIcon.tsx, monkey/monkey_island/cc/next_ui/src/_components/icons/MonkeyRefreshIcon.tsx, monkey/monkey_island/cc/next_ui/src/_components/icons/loading-icon/LoadingIcon.tsx, monkey/monkey_island/cc/next_ui/src/_components/icons/style.ts, monkey/monkey_island/cc/next_ui/src/app/(auth)/login/page.tsx, monkey/monkey_island/cc/next_ui/src/app/(auth)/registration/page.tsx, monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/_lib/InstallAllSafePluginsButton.tsx, monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/_lib/PluginTable.tsx, monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/available/PluginInstallationButton.tsx, monkey/monkey_island/cc/next_ui/src/app/(protected)/plugins/available/page.tsx, monkey/monkey_island/cc/next_ui/src/redux/features/api/agentPlugins/agentPluginEndpoints.tsx
Fixes part of #3916
- After this is merged, don't forget to add an issue to remove the force-refectch option from the island API as we no longer need it.
=> 3916 refresh plugins button

monkey/infection_monkey/Pipfile, monkey/infection_monkey/Pipfile.lock, monkey/infection_monkey/exploit/http_agent_binary_server.py, monkey/tests/unit_tests/infection_monkey/exploit/test_http_agent_binary_request_handler.py, monkey/tests/unit_tests/infection_monkey/exploit/test_http_agent_binary_server.py
Per Issue #4187, there are cases when download strings must be shorter. In order to achieve this, random strings from a set of 62 characters are generated. Using 5 characters gives something like 916M possible values, which is more than enough for any single agent.
Issue #4187.
=> Agent: Shorten reservation ID

monkey/monkey_island/cc/services/authentication_service/authentication_facade.py
Part of  #4187 
7 chars (alphanumeric + 3 special characters) gives total of 4,764,996,883,946 combinations (based on [this](https://www.omnicalculator.com/statistics/password-combination)
The current throttle is 0.001, so the result is that you're able to check 120 000 passwords per 2 minutes. 
This means that you chance of guessing the OTP is 1 in 39,708,307. In practice it's much higher if you account for network latency. I think this is sufficient security for a problem whose real solution is NAC.
=> Island: Add a small throttle to shorten the OTP

docs/content/FAQ/_index.md, docs/content/howtos/_index.md, docs/content/reference/_index.md, docs/content/reference/credentials_collectors/_index.md, docs/content/reference/exploiters/_index.md, docs/content/reports/_index.md, docs/content/setup/_index.md, docs/content/setup/linux.md, docs/content/setup/windows.md, docs/content/tutorials/_index.md, docs/content/usage/configuration/_index.md, docs/content/usage/integrations/_index.md, docs/content/usage/plugins/_index.md, docs/content/usage/scenarios/_index.md
I'm stuck using a newer version of Hugo (v0.123.1) than is mentioned as supported in the docs (v0.92.0). These changes allow the documentation to be compiled with more recent versions of Hugo (tested on v0.123.1 and v0.127.0).
=> Support newer hugo versions

monkey/agent_plugins/exploiters/hadoop/src/hadoop_command_builder.py, monkey/agent_plugins/exploiters/log4shell/src/log4shell_command_builder.py, monkey/agent_plugins/exploiters/snmp/src/snmp_command_builder.py, monkey/infection_monkey/Pipfile.lock, monkey/infection_monkey/command_builders/linux_agent_command_builder.py, monkey/tests/unit_tests/infection_monkey/command_builders/test_linux_agent_command_builder.py, vulture_allowlist.py
=> 4187 use permission change command

monkey/monkey_island/cc/setup/mongo/mongo_setup.py
Since the upgrade to pymongo 4.6.3 (commit 8fe2603c7), the pymongo client has been dumping copious debug logs. Most of these are of no interest to us. Logs with level WARNING or higher maybe of interest.
=> Island: Suppress pymongo logging

monkey/tests/unit_tests/agent_plugins/payloads/ransomware/test_ransomware.py
`AgentEventPublisherSpy` implements `IAgentEventPublisher`, meaning it only needs to provide `publish()`. For some reason, it provides NOOP implementations for other methods from `IAgentEventQueue`, which is unnecessary.
=> Ransomware: Remove unnecessary methods from AgentEventPublisherSpy
