- chaos_monkey/exploit/rdpgrinder.py
- chaos_monkey/exploit/smbexec.py
- chaos_monkey/exploit/sshexec.py
- chaos_monkey/exploit/win_ms08_067.py
- chaos_monkey/network/sshfinger.py
- chaos_monkey/network/tcp_scanner.py
- chaos_monkey/network/tools.py
- chaos_monkey/tunnel.py
> Revert "Feature/async scan"

- infection_monkey/config.py
Fix bug when converting unicode to binary
> fix unicode bug

- .github/ISSUE_TEMPLATE/Bug_report.md
- CONTRIBUTING.md
- infection_monkey/config.py
- infection_monkey/exploit/rdpgrinder.py
- infection_monkey/network/smbfinger.py
- infection_monkey/system_info/mimikatz_collector.py
- infection_monkey/transport/ftp.py
- infection_monkey/transport/http.py
- infection_monkey/transport/tcp.py
- monkey_island/cc/resources/monkey_configuration.py
- monkey_island/cc/resources/telemetry.py
Part of a bite-sized approach to #119
- Old style exceptions to new style for Python 3
- Drop the use of the deprecated __.has_key()__
- Change __types.ClassType__ to __type__ for Python 3
> New style exceptions, has_key(), and types

- common/network/network_range.py
- infection_monkey/monkey.py
- infection_monkey/requirements.txt
- monkey_island/cc/services/config.py
- monkey_island/cc/services/report.py
Part of a bite-sized approach to #119
- Use the six module to make the code support both Python 2 and Python 3.
-
-
> from six import string_types, text_type, xrange

- infection_monkey/config.py
- infection_monkey/example.conf
> 2 default config values on infection monkey didn't make sense
- Changed default values of subnet_scan_list and blocked_ips.
> Fix default config values

- infection_monkey/dropper.py
> Fixes checking if source and destination files are the same on windows.
* Tested with console locally.
> Dropper bug fix

- infection_monkey/exploit/struts2.py
Implemented struts2 vulnerability according to web_rce framework
> Struts2 vulnerability with framework

- monkey/infection_monkey/exploit/tools.py
Fix two imports you missed in the refactor
> Fix relative imports

- infection_monkey/exploit/tools.py
- infection_monkey/exploit/web_rce.py
- infection_monkey/transport/http.py
> Exported vuln_url filter to function
>Exported running backup commands to a function
>Exported monkey path's retrieval to a funciton
> Other minor changes
> Added functions get_monkey_paths and run_backup_commands

- infection_monkey/exploit/struts2.py
> Struts2 refactored for the lasted web_rce framework changes
> Struts2 with framework

- infection_monkey/config.py
- infection_monkey/example.conf
- infection_monkey/exploit/__init__.py
- infection_monkey/exploit/weblogic.py
- monkey_island/cc/services/config.py
- monkey_island/cc/services/report.py
- monkey_island/cc/ui/src/components/pages/ReportPage.js
> Oracle Weblogic server's vulnerability implemented, tested and CR'd
> Web logic with framework

- infection_monkey/config.py
- infection_monkey/example.conf
- infection_monkey/exploit/__init__.py
- infection_monkey/exploit/hadoop.py
- infection_monkey/network/mssql_fingerprint.py
- infection_monkey/transport/http.py
- monkey_island/cc/services/config.py
- monkey_island/cc/services/report.py
- monkey_island/cc/ui/src/components/pages/ReportPage.js
> Implemented hadoop/yarn exploitation of default config using web_rce framework
> Hadoop with web_rce framework

- infection_monkey/network/tools.py
Improve scanning time to reduce to worst case of timeout rather than constant case. Should improve scanning times by a lot since most computers reply quickly.
> Opportunistic waiting, make get_tcp_ports O(timeout)

- monkey/infection_monkey/config.py
- monkey/infection_monkey/control.py
- monkey/infection_monkey/main.py
- monkey/infection_monkey/network/network_scanner.py
Rewrite the horrible configuration parsing code. Nuff said.
No more parse by example or tricky circular imports.
The code now dynamically loads modules from the appropriate network and exploit modules.
Yes but no end to end tests have been done.
> Rewrote config parsing

- monkey/monkey_island/cc/app.py
See https://stackoverflow.com/questions/27287391/why-not-generate-the-secret-key-every-time-flask-starts
> Make flask session key consistent between sessions

- monkey/infection_monkey/network/tools.py
Add a traceroute feature built on top of OS available tools.
On windows we utilise tracert and on Linux, ping.
> Implement traceroute for Linux and Windows over existing tools.

- monkey/monkey_island/cc/main.py
Because we changed the project's folder tree I had to change the log configuration file path.
Changed the log configuration path to point at the right file.
> Fixed logger configuration file path

- monkey/infection_monkey/exploit/shellshock.py
Fix bug in shellshock activation to fit dropper semantics, this wasn't properly tested.
> Shellshock dropper now works

- monkey/infection_monkey/network/tools.py
> Fix traceroute

- monkey/monkey_island/cc/app.py
Fix SECRET_KEY to be a string object for Flask-JWT
> Bugfix JWT expects input of string

- monkey/monkey_island/cc/services/config.py
> Add support for strings to be encrypted
> Add support for strings to be encrypted

- monkey/common/cloud/__init__.py
- monkey/common/cloud/aws.py
- monkey/infection_monkey/system_info/__init__.py
- monkey/infection_monkey/system_info/aws_collector.py
- monkey/infection_monkey/system_info/linux_info_collector.py
- monkey/infection_monkey/system_info/windows_info_collector.py
- monkey/monkey_island/cc/environment/aws.py
- monkey/monkey_island/cc/ui/package-lock.json
- monkey/monkey_island/cc/ui/package.json
> Add AWS instance-id collector
- Moved AWS logic to common
- Add aws instance-id to system-info
> Add AWS instance id collector

- monkey/infection_monkey/system_info/__init__.py
- monkey/infection_monkey/system_info/netstat_collector.py
- monkey/infection_monkey/system_info/windows_info_collector.py
> Add netstat

- monkey/infection_monkey/example.conf
- monkey/infection_monkey/system_info/windows_info_collector.py
We never actually checked the mimikatz collection variable
> Actually use mimikatz configuration variable

- deployment_scripts/deploy_linux.sh
> We need to update node.js in order to generate front end
> We need pip for python to install all of the requirements
> Node updates and pip installation added

- monkey/infection_monkey/exploit/hadoop.py
> Uploads only 64 bit monkey to windows
> Hadoop quicfix

- monkey/infection_monkey/config.py
- monkey/infection_monkey/example.conf
- monkey/infection_monkey/network/network_scanner.py
- monkey/monkey_island/cc/services/config_schema.py
Lets actually use the `tcp_scan_timeout` configuration value and stick to it.
> Sleep between scans

- monkey/infection_monkey/network/network_scanner.py
> TCP scanner sleep bugfix

- monkey/monkey_island/cc/auth.py
- monkey/monkey_island/cc/environment/__init__.py
- monkey/monkey_island/cc/environment/aws.py
- monkey/monkey_island/cc/environment/password.py
- monkey/monkey_island/cc/environment/standard.py
- monkey/monkey_island/cc/ui/src/components/Main.js
- monkey/monkey_island/cc/ui/src/components/pages/LoginPage.js
- monkey/monkey_island/cc/ui/src/index.js
- monkey/monkey_island/cc/ui/src/services/AuthService.js
> UI now checks with server whether authentication is on
- UI checks with server whether auth is on
- Auth is technically always on. No auth - default credentials the UI will try
> Checking with server if auth enabled

- monkey/monkey_island/cc/ui/src/components/Main.js
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> Some unecessary set states removed to prevent refreshing of config page

- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> Fixed bug where config reset followed by update failed
> Fixed bug where config reset followed by update failed

- monkey/infection_monkey/exploit/mssqlexec.py
> default payload path is now chosen correctly on MSSQL exploit
> fix expanding of env variables

- monkey/infection_monkey/config.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/utils.py
- monkey/monkey_island/cc/services/config_schema.py
> New directory to store monkey and it's files is created.
> New directory for monkey and it's files

- monkey/infection_monkey/example.conf
Added monkey directory paths to example.conf
> Added monkey directories to example.conf

- monkey/common/utils/attack_status_enum.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/transport/attack_telems/__init__.py
- monkey/infection_monkey/transport/attack_telems/base_telem.py
- monkey/infection_monkey/transport/attack_telems/victim_host_telem.py
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/attack_telem.py
- monkey/monkey_island/cc/services/attack/__init__.py
- monkey/monkey_island/cc/services/attack/attack_telem.py
> Implemented ability to send ATT&CK telemetry from monkey to island.
* Example telemetry data:
> Attack telemetry

- monkey/infection_monkey/exploit/elasticgroovy.py
> Elastic exploiter sent get request and waited for response indefinitely.
> Added request timeout to elastic exploiter

- monkey/monkey_island/cc/ui/src/components/report-components/PostBreach.js
> Class name typo fixed on pba
> Minor ui fix

- monkey/monkey_island/requirements.txt
Fixed https://github.com/guardicore/monkey/issues/291
> Updated requirements file

- monkey/infection_monkey/exploit/tools.py
> get_interface_to_target(dst) method now chooses IP based on connection, not string
> Refactored get_interface_to_target fix

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/consts.py
- monkey/monkey_island/cc/encryptor.py
- monkey/monkey_island/cc/environment/environment.py
- monkey/monkey_island/cc/main.py
- monkey/monkey_island/cc/resources/local_run.py
- monkey/monkey_island/cc/resources/monkey_download.py
> Downloading binaries from island is fixed
> All 'monkey_island' dir references are now absolute
> all monkey_island references are now absolute

- monkey/infection_monkey/exploit/sshexec.py
> Exception is handled better in SSH exploiter
> SSH exploiter handles exception better

- envs/monkey_zoo/docs/fullDocs.md
> Added vulnerable MsSQL image credentials
> MonkeyZoo: MsSQL docs improved

- monkey/monkey_island/cc/ui/package-lock.json
- monkey/monkey_island/cc/ui/package.json
> update bootstrap to 3.4.1

- deployment_scripts/deploy_linux.sh
> Added `install_mongo.sh` to deployment script
> MongoDB installation script added to deployment

- monkey/infection_monkey/control.py
- monkey/infection_monkey/network/info.py
> Change internet check to use HTTPS instead of ICMP
> internet check now uses https instead of icmp

- monkey/infection_monkey/transport/http.py
> HTTP servers didn't close the connection after the file was downloaded.
> HTTP server bugfix

- monkey/infection_monkey/example.conf
- monkey/infection_monkey/exploit/__init__.py
- monkey/infection_monkey/exploit/vsftpd.py
- monkey/monkey_island/cc/services/config_schema.py
- monkey/monkey_island/cc/services/report.py
- monkey/monkey_island/cc/ui/src/components/pages/ReportPage.js
A new exploit has been added to the infection_monkey for the following vulnerability
https://www.rapid7.com/db/modules/exploit/unix/ftp/vsftpd_234_backdoor
> Added a new exploit 

- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> Configuration gets submitted on import.
> Configuration gets submitted on import.

- monkey/infection_monkey/post_breach/pba.py
> Telemetry feed expected ip and hostname with PBA telem. to show where the PBA was executed.
> Hotfixed telemetry feed for post breach actions

- monkey/infection_monkey/exploit/web_rce.py
> Fixed the problem of not adding vulnerable url's in web_rce
> bug in web_rce fixed

- monkey/infection_monkey/exploit/win_ms08_067.py
> Added necessary _EXPLOITED_SERVICE prop to win_ms08_067 exploiter
> _EXPLOITED_SERVICE prop added to win_ms08_067 exploiter

- monkey/infection_monkey/control.py
- monkey/infection_monkey/telemetry/attack/attack_telem.py
- monkey/infection_monkey/telemetry/attack/test_victim_host_telem.py
- monkey/infection_monkey/telemetry/base_telem.py
- monkey/monkey_island/cc/resources/monkey.py
- monkey/monkey_island/cc/resources/telemetry.py
- monkey/monkey_island/cc/resources/telemetry_feed.py
- monkey/monkey_island/cc/services/attack/attack_report.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1197.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1210.py
- monkey/monkey_island/cc/services/attack/technique_reports/__init__.py
- monkey/monkey_island/cc/services/report.py
> fix variable name 'catagory' -> 'category'
> fix variable name 'catagory' -> 'category'

- monkey/infection_monkey/exploit/__init__.py
> exploit_host returns '_exploit_host''s return value
> exploit_host returns '_exploit_host''s return value

- monkey/infection_monkey/exploit/weblogic.py
- monkey/monkey_island/cc/services/config_schema.py
- monkey/monkey_island/cc/ui/src/components/pages/ReportPage.js
> Implements [CVE-2019-2725](https://www.oracle.com/technetwork/security-advisory/alert-cve-2019-2725-5466295.html) in weblogic exploiter.
> WebLogic CVE-2019-2725 implemented

- monkey/monkey_island/cc/ui/package-lock.json
- monkey/monkey_island/cc/ui/package.json
- monkey/monkey_island/cc/ui/server.js
> Removes the 'open' dependency
> Remove open dependency

- monkey/monkey_island/cc/services/attack/attack_report.py
- monkey/monkey_island/cc/services/attack/attack_schema.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1065.py
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1065.js
- monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js
> Implements T1065 Uncommonly used port attack technique
> T1065 Uncommonly used port

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/network_scanner.py
#Fixes
> Fixed tunneling bug where local machine gets set as island.
> Tunneling bugfix

- monkey/infection_monkey/exploit/weblogic.py
>Renames exploit_host to _exploit_host in weblogic exploiter
> Renames exploit_host to _exploit_host in weblogic exploiter

- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/services/report.py
> Commit 1. Fixes recommendation duplication in report:
> Commit 2. Fixes tunneling bug:
> Tunneling and report recommendation bugfixes

- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage.js
> Added  target="_blank to link so it opens in a new window

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/telemetry/attack/t1107_telem.py
- monkey/infection_monkey/utils.py
- monkey/monkey_island/cc/services/attack/attack_report.py
- monkey/monkey_island/cc/services/attack/attack_schema.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1107.py
- monkey/monkey_island/cc/services/attack/technique_reports/__init__.py
- monkey/monkey_island/cc/ui/src/components/attack/techniques/Helpers.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1003.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1059.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1075.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1082.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1086.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1107.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1110.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1145.js
- monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js
> Implements T1107 File Deletion attack technique.
> T1107 File Deletion

- .travis.yml
> Remove python 3 build from travis
> remove python 3 build from travis

- monkey/infection_monkey/config.py
- monkey/infection_monkey/control.py
- monkey/infection_monkey/exploit/mssqlexec.py
- monkey/infection_monkey/exploit/rdpgrinder.py
- monkey/infection_monkey/exploit/smbexec.py
- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/exploit/wmiexec.py
- monkey/infection_monkey/main.py
Fixes #395 .
- Added a filtering func
- Filtered config where we log it
> Filtering sensitive info when logging running config

- monkey/infection_monkey/exploit/smbexec.py
- monkey/infection_monkey/telemetry/attack/t1035_telem.py
- monkey/monkey_island/cc/services/attack/attack_report.py
- monkey/monkey_island/cc/services/attack/attack_schema.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1003.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1035.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1059.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1065.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1075.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1082.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1086.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1110.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1145.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1210.py
- monkey/monkey_island/cc/services/attack/technique_reports/__init__.py
- monkey/monkey_island/cc/services/config_schema.py
- monkey/monkey_island/cc/ui/src/components/attack/techniques/Helpers.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1035.js
- monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js
> Implements T1035 Service Execution
> T1035 Service Execution

- monkey/common/utils/attack_utils.py
- monkey/infection_monkey/exploit/smbexec.py
- monkey/infection_monkey/system_info/mimikatz_collector.py
- monkey/infection_monkey/telemetry/attack/t1035_telem.py
- monkey/infection_monkey/telemetry/attack/t1129_telem.py
- monkey/infection_monkey/telemetry/attack/usage_telem.py
- monkey/monkey_island/cc/services/attack/attack_report.py
- monkey/monkey_island/cc/services/attack/attack_schema.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1035.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1129.py
- monkey/monkey_island/cc/services/attack/technique_reports/__init__.py
- monkey/monkey_island/cc/services/config_schema.py
- monkey/monkey_island/cc/ui/src/components/attack/techniques/Helpers.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1035.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1129.js
- monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js
> Implemented attack technique T1129 Execution through module load
> T1129 Execution through module load

- monkey/common/utils/attack_utils.py
- monkey/infection_monkey/control.py
- monkey/infection_monkey/dropper.py
- monkey/infection_monkey/system_info/mimikatz_collector.py
- monkey/infection_monkey/system_singleton.py
- monkey/infection_monkey/telemetry/attack/t1106_telem.py
- monkey/monkey_island/cc/services/attack/attack_report.py
- monkey/monkey_island/cc/services/attack/attack_schema.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1035.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1106.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1129.py
- monkey/monkey_island/cc/services/attack/technique_reports/__init__.py
- monkey/monkey_island/cc/services/config_schema.py
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1106.js
- monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js
> Implements T1106 Execution through API
> T1106 Execution through API

- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/models/test_monkey.py
- monkey/monkey_island/cc/services/attack/attack_report.py
- monkey/monkey_island/cc/services/attack/attack_schema.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1090.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1188.py
- monkey/monkey_island/cc/ui/src/components/attack/techniques/Helpers.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1090.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1188.js
- monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js
> T1188 Multi-hop proxy attack technique:
> T1090 Connection proxy attack technique:
Test's topography:
> T1188 Multi-hop proxy and T1090 Connection proxy

- monkey/monkey_island/cc/models/__init__.py
- monkey/monkey_island/cc/models/c2_info.py
- monkey/monkey_island/cc/models/command_control_channel.py
- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/resources/telemetry.py
- monkey/monkey_island/cc/services/attack/attack_report.py
- monkey/monkey_island/cc/services/attack/attack_schema.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1041.py
- monkey/monkey_island/cc/services/node.py
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1041.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1090.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1188.js
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js
- monkey/monkey_island/cc/ui/src/styles/App.css
> T1041 Exfiltration Over Command and Control Channel attack technique implemented:
> T1041 Exfiltration Over Command and Control Channel 

- monkey/infection_monkey/monkey.py
> Fixes bug where monkey crashes if default server flag is not passed
> Bugfix for monkey without -s flag

- monkey/monkey_island/cc/services/attack/technique_reports/T1090.py
> Made T1090 connection proxy more descriptive
> Improved description of T1090 connection proxy

- monkey/monkey_island/cc/models/monkey.py
> Added aws_instance_id field to monkey model

- envs/monkey_zoo/docs/fullDocs.md
- envs/monkey_zoo/terraform/config.tf
- envs/monkey_zoo/terraform/firewalls.tf
- envs/monkey_zoo/terraform/images.tf
- envs/monkey_zoo/terraform/monkey_zoo.tf
- envs/monkey_zoo/terraform/templates.tf
> Adds tunneling-11 machine and updates other images
> Adds the ability to add prefix to resources and deploy two zoo's in the same project
> Improved default config and docs
> Updated monkeyzoo images and added tunneling-11

- monkey/infection_monkey/post_breach/actions/users_custom_pba.py
- monkey/infection_monkey/post_breach/pba.py
- monkey/monkey_island/cc/services/config_schema.py
- monkey/monkey_island/cc/ui/src/components/report-components/PostBreach.js
> Fixes empty pba output as shown below (first two entries from unfixed monkey, two following them from fixed monkey):
> Fixes #429 
> Other minor improvements
> Small bugfixes for attack and pba modules.

- monkey/infection_monkey/exploit/mssqlexec.py
- monkey/infection_monkey/exploit/tools/exceptions.py
- monkey/infection_monkey/exploit/tools/helpers.py
- monkey/infection_monkey/exploit/tools/http_tools.py
- monkey/infection_monkey/exploit/tools/payload_parsing.py
- monkey/infection_monkey/exploit/tools/payload_parsing_test.py
- monkey/infection_monkey/monkey.py
> Makes mssql exploiter more stable and fixes a bug
> Adds a class that defines payload and allows for some basic parsing
> MSSQL bugs fixed, refactored to be more stable

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/system_singleton.py
> Moved sending WinAPI attack telem to where monkey already has server established and can send the telem. Fixes:
> WinAPI attack telem fix.

- monkey/infection_monkey/exploit/smbexec.py
- monkey/infection_monkey/exploit/tools/smb_tools.py
- monkey/infection_monkey/exploit/wmiexec.py
> Hashing lm+ntlm hashes to make sure we don't log them plaintext

- monkey/infection_monkey/config.py
- monkey/infection_monkey/example.conf
- monkey/infection_monkey/main.py
- monkey/infection_monkey/model/host.py
- monkey/infection_monkey/model/victim_host_generator.py
- monkey/infection_monkey/model/victim_host_generator_test.py
- monkey/infection_monkey/network/network_scanner.py
- monkey/monkey_island/cc/services/config_schema.py
Add localized multiprocessing to network scanning to generate new victim machines faster.
Relates to #436 
- Add MP support to the Monkey (main.py)
- Scan victims in parallel to save time. In Windows done using multithreading, in Linux multiprocessing.
- Fix network scanner logger.
> Feature/scan hosts fast [WIP]

- monkey/infection_monkey/network/network_scanner.py
- monkey/monkey_island/cc/services/attack/attack_schema.py
> Bugfix unused attack technique 
> Bugfix invalid import statement of is_windows_os
> Bugfix unused attack technique and bad import of is_windows_os

- monkey/infection_monkey/network/network_scanner.py
Fixes #451.
Make both OSes use MT and not MP to avoid pickling issues.
I'll do more tests and upload with benchmarks
> Bugfix for 451

- monkey/infection_monkey/build_windows.bat
> Removed accidental changes to build_windows.bat
> Reverted accidental changes to build_windows.bat

- monkey/monkey_island/cc/resources/telemetry_feed.py
> You no longer have to add briefs to all telemetries
> Added ability to disable telemetry briefs for certain telemetries.

- monkey/common/cloud/aws_instance.py
- monkey/infection_monkey/system_info/__init__.py
- monkey/monkey_island/cc/environment/aws.py
- monkey/monkey_island/cc/services/remote_run_aws.py
- monkey/monkey_island/cc/services/reporting/aws_exporter.py
- monkey/monkey_island/cc/services/reporting/exporter_init.py
merge hotfix to master as well (see #464).
> 463/hotfix/exception on aws network error -> master

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
Makes the issue/pr templates looks nicer and without formatting issues. 
Can't provide until merged.
> Updated the issue templates to look a bit nicer.

- monkey/monkey_island/cc/models/monkey.py
- Remove `Monkey.__ring_key__` which was required by old version of ring bug
@ShayNehmad
> Remove Monkey.__ring_key__

- monkey/infection_monkey/requirements_linux.txt
- monkey/infection_monkey/requirements_windows.txt
Fixes #492. 
Screenshots in comments
> https://github.com/pymssql/pymssql/issues/668

- monkey/infection_monkey/config.py
Fixes a bug in config, where methods are included into config.
> Monkey config to dict. bugfix

- monkey/monkey_island/cc/ui/src/components/Main.js
- monkey/monkey_island/cc/ui/src/components/pages/ZeroTrustReportPage.js
Less auto-refreshing for higher responsiveness.
Fixes server load issues in demos (for now) by lowering the refresh rate.
> Updated the refresh intervals to lower server load.

- monkey/infection_monkey/post_breach/actions/communicate_as_new_user.py
Make sure the PBA will work on old Windows servers
https://somoit.net/powershell/could-not-create-ssltls-secure-channel
Tested manually
> Added TLS version to powershell command.

- monkey/monkey_island/cc/services/config.py
- monkey/monkey_island/cc/services/telemetry/processing/system_info.py
> Refactored credential saving to check if credentials already exist

- monkey/infection_monkey/config.py
> Plaintext ssh keys in logs

- deployment_scripts/deploy_linux.sh
- monkey/monkey_island/linux/install_mongo.sh
Fixes #503 by adding option to use wget or curl as long as one is installed.
Also took the time to cleanup the script.
None yet
> Bugfix/handle missing curl wget fixes #503

- monkey/monkey_island/deb-package/DEBIAN/control
- monkey/monkey_island/deb-package/DEBIAN/postinst
- monkey/monkey_island/deb-package/DEBIAN_MONGO/postinst
- monkey/monkey_island/linux/install.sh
- monkey/monkey_island/linux/monkey.sh
- monkey/monkey_island/linux/run.sh
Change python2 to Python3 in a debian installation package.
> Update debian installation to use python3

- monkey/monkey_island/cc/ui/src/components/pages/StartOverPage.js
- monkey/monkey_island/cc/ui/src/components/ui-components/StartOverModal.js
- monkey/monkey_island/cc/ui/src/styles/StartOverPage.scss
Fixes #417 
- Adds loading component that indicates monkey resetting
- Fixes yellow checkmarks on the side menu that previously took time to refresh
> Start over page loading fix

- monkey/infection_monkey/monkey.spec
This handles cases where we run 32b python on 64b machines
> Bugfix, installer should go according to Python bitnes

- monkey/monkey_island/cc/ui/src/components/Main.js
> Bugfix: notification wrong route

- monkey/monkey_island/deb-package/DEBIAN/control
Updates homepage and email reference
> Change DEB package homepage to be InfectionMonkey

- deployment_scripts/deploy_linux.sh
> Fix typo in deployment script for linux

- README.md
> Update codecov badge branch to develop

- envs/monkey_zoo/blackbox/analyzers/analyzer.py
- envs/monkey_zoo/blackbox/analyzers/communication_analyzer.py
- envs/monkey_zoo/blackbox/analyzers/performance_analyzer.py
- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/island_client/monkey_island_requests.py
- envs/monkey_zoo/blackbox/island_configs/PERFORMANCE.conf
- envs/monkey_zoo/blackbox/island_configs/STRUTS2.conf
- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/tests/basic_test.py
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/test/__init__.py
- monkey/monkey_island/cc/resources/test/clear_caches.py
- monkey/monkey_island/cc/services/attack/attack_report.py
- monkey/monkey_island/cc/services/reporting/report.py
Fixes #547. 
See issue, and also: 
- Added post_exec analyzers for analyzers which need to wait for all monkeys to finish before running
- Small fixes to BB code
> Calculate response time for testing

- monkey/monkey_island/cc/services/attack/technique_reports/T1003.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1016.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1082.py
- monkey/monkey_island/cc/ui/src/components/attack/techniques/Helpers.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1003.js
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1082.js
> Mitre bugfixes

- .gitmodules
Retargets CTI submodule to our fork.
> Mitre cti retarget

- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/BreachedServers.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/PostBreach.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/ScannedServers.js
Fixes #635. 
See commit messages.
> Added a short summary sentence over each table in the security report

- monkey/monkey_island/cc/services/attack/attack_schema.py
- monkey/monkey_island/cc/services/attack/technique_reports/T1136.py
- monkey/monkey_island/cc/ui/src/components/attack/techniques/T1136.js
> Smallfixes on persistance/create user attack technique

- monkey/monkey_island/cc/ui/src/components/map/MapOptions.js
- monkey/monkey_island/cc/ui/src/components/pages/MapPage.js
Fixes map jitter that happens with a full-mesh networ.
Fixes UI errors, that happened because front end sends multiple requests before island manages to respond to one of them. In the end island responds to all of them with the same telemetries and because of this duplication react starts throwing tens of thousands of "duplicate component keys" errors.
> UI performance fixes

- envs/monkey_zoo/blackbox/README.md
- envs/monkey_zoo/blackbox/tests/performance/endpoint_performance_test.py
- envs/monkey_zoo/blackbox/tests/performance/telemetry_performance_test_workflow.py
- monkey/monkey_island/cc/services/edge.py
- monkey/monkey_island/cc/services/telemetry/processing/scan.py
Improves edge label creation performance
Minor BB test fixes
Before 
After
> Edge label creation performance fixes

- monkey/monkey_island/cc/ui/src/components/ui-components/StartOverModal.js
😈
Fixes #665. Thanks for reporting @ophirharpazg 
> Fix reset env state bug

- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
UI bugfix: non-existent PTH map include
> UI bugfix: non-existent PTH map include

- docs/content/usage/accounts-and-security.md
> Added accounts and security page

- docs/content/_index.md
Emphasise Guardicore in homepage and sidebar
> Tiny fix in docs site

- monkey/monkey_island/cc/services/attack/technique_reports/T1136.py
Use mongo search for T1136's report data, as is the case with all other techniques
> Use mongo search for T1136's report data

- deployment_scripts/config
- deployment_scripts/config.ps1
Fixes #623. 
If applicable, add screenshots or log transcripts of the feature working
> 623/get version from GitHub api

- monkey/common/data/zero_trust_consts.py
- monkey/common/utils/mongo_utils.py
- monkey/infection_monkey/exploit/shellshock.py
- monkey/infection_monkey/exploit/sshexec.py
- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/services/config_schema.py
Fixes a bunch of text only typos.
> Fix a bunch of typos

- monkey/monkey_island/cc/ui/src/index.js
> Removed core-js/fn/object/assign import

- monkey/monkey_island/cc/ui/src/styles/Checkbox.scss
> Fixed broken attack matrix checkbox UI in config

- monkey/monkey_island/cc/ui/src/components/SideNavComponent.js
- monkey/monkey_island/cc/ui/src/components/pages/MapPage.js
- monkey/monkey_island/cc/ui/src/components/pages/ReportPage.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage.js
- monkey/monkey_island/cc/ui/src/components/pages/RunServerPage.js
- monkey/monkey_island/cc/ui/src/components/pages/TelemetryPage.js
- monkey/monkey_island/cc/ui/src/styles/components/SideNav.scss
- monkey/monkey_island/cc/ui/src/styles/pages/RunServerPage.scss
Small UI improvements:
* Update homepage look and feel
* Add links to documentation
* Declutter NavBar
> Improve island homepage layout

- docs/content/usage/file-checksums.md
> Doc hash update

- .gitmodules
We moved the theme URL from my personal account to GuardiCode.
> Changed submodule URL to new fork

- docs/content/setup/_index.md
- docs/content/usage/getting-started.md
- docs/content/usage/use-cases/_index.md
- docs/content/usage/use-cases/credential-leak.md
- docs/content/usage/use-cases/ids-test.md
- docs/content/usage/use-cases/network-breach.md
- docs/content/usage/use-cases/network-segmentation.md
- docs/content/usage/use-cases/other.md
Fixes small issues with the new use cases documentation.
* Draft true -> false
* added page descriptions
* replaced manual list with shortcode
* fix image paths
> hugo server
> Use cases documentation fixes

- monkey/infection_monkey/exploit/win_ms08_067.py
Added windows XP support for win_ms08_067 and fixed exploited/not exploited logic
> Tested by running on exploitable windows XP machine (SP2) and non exploitable (updated SP3)
> Added windows XP support for win_ms08_067

- monkey/infection_monkey/post_breach/actions/hide_files.py
> Bugfix - missing import

- .travis.yml
- monkey/infection_monkey/exploit/drupal.py
Deletes unused code where Drupal ports are defined.
* The exploit was tested as part from [this PR](https://github.com/guardicore/monkey/pull/808).
Trivial to understand.
> minor fixes

- monkey/monkey_island/requirements.txt
Fixes conflicting pip packages. 
> Only minor package upgrades, no testing
> Locking the AWS requirements to avoid conflicts

- docs/content/reference/mitre_techniques.md
Adds a list of all current MITRE techniques.
> Document MITRE techniques

- docs/content/usage/integrations/aws-security-hub.md
> docs: Fix image url for integration page

- docs/content/reference/mitre_techniques.md
- docs/content/usage/reports/mitre.md
Add some tweaks to mitre documentation
> docs: Add final tweaks to mitre techniques page.

- docs/content/usage/configuration/_index.md
- docs/content/usage/integrations/_index.md
- docs/content/usage/use-cases/_index.md
Fixes #866 
Fixes list style a bit
> Fixed list style so that link and description is on the same line

- deployment_scripts/config
In deployment_scripts/config, put exports on the same line as definitions for easier reading. 
> Tested by running deploy_linux.sh
> deployment_scripts/config: Consolidate exports

- docs/content/FAQ/_index.md
Fixes #841 
Adds password reset tutorial to FAQ
> Added password reset tutorial to FAQ

- monkey/monkey_island.py
- monkey/monkey_island/cc/main.py
- monkey/monkey_island/cc/services/reporting/report_generation_synchronisation.py
- monkey/monkey_island/cc/ui/webpack.config.js
- monkey/monkey_island/requirements.txt
Revent gevent refactoring, which is causing bugs in production.
> Revert "Gevent refactoring" for ransomeware

- envs/monkey_zoo/docs/fullDocs.md
minor fixes to monkey_zoo docs
> monkey_zoo: minor fixes to monkey_zoo docs

- monkey/monkey_island/cc/ui/src/styles/App.css
Fixes #612
> Tested by running the monkey locally and comparing screenshots
> ui: fix centering of guardicore logo

- monkey/monkey_island/cc/resources/pba_file_download.py
- monkey/monkey_island/cc/resources/pba_file_upload.py
- monkey/monkey_island/cc/services/post_breach_files.py
Fixes custom PBA upload path, which was broken in production due to flask having different cwd in production than in dev.
> Tested by uploading and downloading custom PBA file
> Bugfix: custom PBA upload path

- monkey/infection_monkey/utils/linux/test_users.py
- monkey/infection_monkey/utils/test_auto_new_user_factory.py
Adds unit tests for `auto_new_user_factory.create_auto_new_user()`
Adds unit tests for `monkey/infection_monkey/utils/linux/user.py`
> Only unit test code was changed. All tests run and pass.
> New user tests

- monkey/infection_monkey/telemetry/tests/attack/test_attack_telem.py
- monkey/infection_monkey/telemetry/tests/attack/test_t1005_telem.py
- monkey/infection_monkey/telemetry/tests/attack/test_t1035_telem.py
- monkey/infection_monkey/telemetry/tests/attack/test_t1064_telem.py
- monkey/infection_monkey/telemetry/tests/attack/test_t1105_telem.py
- monkey/infection_monkey/telemetry/tests/attack/test_t1106_telem.py
- monkey/infection_monkey/telemetry/tests/attack/test_t1107_telem.py
- monkey/infection_monkey/telemetry/tests/attack/test_t1129_telem.py
- monkey/infection_monkey/telemetry/tests/attack/test_t1197_telem.py
- monkey/infection_monkey/telemetry/tests/attack/test_t1222_telem.py
- monkey/infection_monkey/telemetry/tests/attack/test_usage_telem.py
- monkey/infection_monkey/telemetry/tests/attack/test_victim_host_telem.py
- monkey/infection_monkey/telemetry/tests/test_exploit_telem.py
- monkey/infection_monkey/telemetry/tests/test_post_breach_telem.py
- monkey/infection_monkey/telemetry/tests/test_scan_telem.py
- monkey/infection_monkey/telemetry/tests/test_state_telem.py
- monkey/infection_monkey/telemetry/tests/test_system_info_telem.py
- monkey/infection_monkey/telemetry/tests/test_trace_telem.py
- monkey/infection_monkey/telemetry/tests/test_tunnel_telem.py
Fixes broken telemetry UT's by refactoring them to compare json data to json instead of json to dict.
> Fix: broken telemetry UT's

- docs/content/development/_index.md
- docs/content/development/add-zero-trust-test.md
- docs/content/development/adding-post-breach-actions.md
- docs/content/development/adding-system-info-collectors.md
- docs/content/development/contribute-documentation.md
- docs/content/development/setup-development-environment.md
- docs/content/development/swimm.md
- docs/content/reports/mitre.md
- docs/content/reports/security.md
- docs/content/reports/zero-trust.md
- docs/content/setup/accounts-and-security.md
- docs/content/usage/_index.md
- docs/content/usage/configuration/_index.md
- docs/content/usage/configuration/basic-credentials.md
- docs/content/usage/configuration/basic-network.md
- docs/content/usage/getting-started.md
- docs/content/usage/integrations/aws-run-on-ec2-machine.md
- docs/content/usage/integrations/aws-security-hub.md
- docs/content/usage/use-cases/_index.md
- docs/content/usage/use-cases/attack.md
- docs/content/usage/use-cases/credential-leak.md
- docs/content/usage/use-cases/network-breach.md
- docs/content/usage/use-cases/network-segmentation.md
- docs/content/usage/use-cases/other.md
- docs/content/usage/use-cases/zero-trust.md
> Copyedits for usage sections

- monkey/monkey_island.py
- monkey/monkey_island/cc/arg_parser.py
- monkey/monkey_island/cc/test_island_logger.py
> Logger config at runtime refactor

- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/styles/pages/report/ReportPage.scss
> Zerologon overview section

- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
Improves ZL PR by making code more consistent and fixing report style a bit:
> Zerologon report improvements

- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/services/tests/reporting/test_report.py
> Show exploited machine name under "Stolen From" in stolen credentials section

- monkey/monkey_island/cc/ui/src/components/ui-components/AdvancedMultiSelect.js
Fixes #1018. 
> Tested by reproducing #1018 before and after code changes
> Fix master checkbox rendering

- envs/monkey_zoo/blackbox/README.md
- envs/monkey_zoo/blackbox/island_configs/drupal.py
- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/terraform/images.tf
- envs/monkey_zoo/terraform/monkey_zoo.tf
Adds blackbox test for drupal exploiter
> Tested by running `python3 -m pytest -s --island=34.107.109.84:5000  -k test_drupal_exploiter ../envs/monkey_zoo/blackbox/test_blackbox.py`
> Drupal blackbox test

- envs/monkey_zoo/blackbox/config_templates/elastic.py
- envs/monkey_zoo/blackbox/config_templates/wmi_pth.py
- envs/monkey_zoo/blackbox/utils/README.md
Fixes config templates for BB tests and improves readme of config file generation script.
> Config template fixes

- monkey/infection_monkey/dropper.py
- monkey/infection_monkey/exploit/drupal.py
Fixes #1026 
> Tested by running the blackbox tests on GCP
> Fix drupal exploit failure

- monkey/monkey_island/requirements.txt
Fixes errors in authentication, caused by outdated pyjwt dependency
> Island requirements fix

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/system_info/windows_info_collector.py
> Handle UnicodeDecodeError in Windows info collector

- deployment_scripts/deploy_linux.sh
- monkey/infection_monkey/monkey.spec
Removes outdated ScoutSuite setup from deployment scripts
Removes unnecessary code from monkey.spec
> Minor ScoutSuite related fixes

- monkey/infection_monkey/requirements.txt
> Added simplejson requirements to monkey requirements

- monkey/common/version.py
- monkey/monkey_island/cc/ui/package.json
Bumps numbers for the next version
> Version number bump

- docs/content/setup/vmware.md
Fixes #1051
> Tested by running hugo and viewing the documentation pages
NOTE: These instructions need to be tested on the v1.10 VM once it's been built.
EDIT: While the above instructions work for v1.9, the below instructions work for v1.10
> docs: update vmware OVA static IP configuration instructions

- docs/content/usage/file-checksums.md
Updated checksums page to match 1.10.0 release binaries
> Updated checksums page

- docs/content/setup/docker.md
Adds a troubleshooting section. Related to #1032.
> Update Docker docs

- deployment_scripts/deploy_windows.ps1
Adds  pre-commit installation in windows deployment scripts
> Tested by running the added function
> Added pre-commit installation to windows deployment script

- .pre-commit-config.yaml
- .travis.yml
- deployment_scripts/README.md
- deployment_scripts/deploy_linux.sh
- deployment_scripts/deploy_windows.ps1
- pyproject.toml
Adds pre-commit config. Resolves #974.
Includes pre-commit hooks for black, flake8, and isort.
> Tested by running `git commit`
> Add pre-commit hooks

- .swm/AzD8XysWg1BBXCjCDkfq.swm
- .swm/JFXftJml8DpmuCPBA9rL.swm
- .swm/OwcKMnALpn7tuBaJY1US.swm
- .swm/VW4rf3AxRslfT7lwaug7.swm
- .swm/tbxb2cGgUiJQ8Btma0fp.swm
- .travis.yml
Updates swim units and adds `swim verify` to travis.yml
Fixes #1012 
> Tested by checking the output of the travis build.
> Swimm verify

- docs/content/FAQ/_index.md
- docs/content/reference/_index.md
- docs/content/reference/exploiters/Drupal.md
- docs/content/reference/exploiters/ElasticGroovy.md
- docs/content/reference/exploiters/Hadoop.md
- docs/content/reference/exploiters/MS08-067.md
- docs/content/reference/exploiters/MsSQL.md
- docs/content/reference/exploiters/SMBExec.md
- docs/content/reference/exploiters/SSHExec.md
- docs/content/reference/exploiters/Sambacry.md
- docs/content/reference/exploiters/Struts2.md
- docs/content/reference/exploiters/VSFTPD.md
- docs/content/reference/exploiters/WMIExec.md
- docs/content/reference/exploiters/WebLogic.md
- docs/content/reference/exploiters/_index.md
- docs/content/reference/exploiters/shellshock.md
- docs/content/reference/mitre_techniques.md
- docs/content/reference/operating_systems_support.md
- docs/content/reference/scanners/_index.md
Copyedits for the reference section of the docs.
This PR supersedes #1003
> Copyedits reference section

- .pre-commit-config.yaml
- .travis.yml
- docs/content/development/setup-development-environment.md
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOnAWS/AWSRunOptions.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOptions.js
- monkey/monkey_island/cc/ui/src/components/reactive-graph/ReactiveGraph.js
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/IssueDescriptor.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/issues/SharedPasswordsIssue.js
- monkey/monkey_island/cc/ui/src/components/report-components/zerotrust/PrinciplesStatusTable.js
> Add eslint

- monkey/monkey_island/cc/models/attack/mitigation.py
Fixes a broken import in mitigation.py
> Fixed a broken import in mitigation.py

- monkey/monkey_island/cc/models/exported_telem.py
- monkey/monkey_island/cc/resources/blackbox/utils/telem_store.py
- monkey/monkey_island/cc/resources/log.py
- monkey/monkey_island/cc/resources/monkey.py
- monkey/monkey_island/cc/resources/telemetry.py
- monkey/monkey_island/cc/services/infection_lifecycle.py
Refactored `test_telems` to `exported_telems` and moved them back to production from test folder, because they're used in production
> Refactored test_telems to exported_telems 

- CHANGELOG.md
- envs/monkey_zoo/blackbox/conftest.py
- envs/monkey_zoo/blackbox/test_blackbox.py
Adds a `--no-performance-tests` flag to BB tests, which allows to skip performance tests.
> Tested by running BB tests with the flag
> Blackbox: --run-performance-tests

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_windows_cmd.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_windows_powershell.js
Fixes #1153
> Tested by copying the command from the browser into powershell
> island: Remove errant space in manual run windows command

- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/utils/gcp_machine_handlers.py
Fixes #1150
> Tested by with/without key files. Without key file the whole test suite is aborted. With key file it works fine, even from different cwd
> BlackBox test GCP handling fixes

- docs/config/staging/config.toml
Fixes part of  #1096 
> Tested by staging the documentation
> Updated documentation root link in documentation config.toml

- envs/monkey_zoo/blackbox/README.md
- envs/monkey_zoo/blackbox/test_blackbox.py
Does small improvements in BB test readme and connection to island checking
> Small bb improvements

- docs/content/FAQ/_index.md
- docs/content/reference/data_directory.md
- docs/content/setup/accounts-and-security.md
Partial fix for #1146 
> Built and checked with Hugo.
> Update docs around server_config changes

- monkey/monkey_island.py
- monkey/monkey_island/monkey_island.spec
- monkey/monkey_island/startup.py
Refactored monkey island startup files to the old structure which was compatible with our build scripts.
Fixes #1198
> Tested by Building MSI with jenkins and testing
> MSI build fix

- docs/content/setup/docker.md
Adds instructions to documentation that describe how users can provide the Docker container with their own certificate.
> Tested by building documentation with hugo.
> Docs docker signed certs

- monkey/monkey_island/cc/environment/linux_permissions.py
- monkey/monkey_island/cc/environment/utils.py
- monkey/tests/unit_tests/monkey_island/cc/environment/test_utils.py
> Fixed a race condition for linux secure directory creation

- docs/content/setup/windows.md
> Added a support section for Windows docs

- monkey/monkey_island/cc/environment/utils.py
- monkey/monkey_island/cc/environment/windows_permissions.py
- monkey/monkey_island/cc/setup/config_setup.py
- monkey/monkey_island/cc/setup/mongo/mongo_setup.py
- monkey/tests/unit_tests/monkey_island/cc/environment/test_utils.py
Fixes #1193 
> Tested by starting monkey island
> Fix data dir race condition on Windows

- docs/content/setup/windows.md
Adds instructions for user-provided certs to windows setup
> Tested by building an MSI and running through the steps
> docs: Add instructions for user-provided certs to windows setup

- deployment_scripts/README.md
Fixes #1229  Documentation of deployment scripts
> Update README.md in deployment _scripts

- deployment_scripts/README.md
> Replaced starting tilda with home directory. Related #1108.

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
> Added altpgraph to the Pipfile.

- monkey/infection_monkey/readme.md
- monkey/monkey_island/readme.md
> Added documentation about installing python dependencies.

- monkey/monkey_island/cc/server_utils/windows_permissions.py
- monkey/tests/unit_tests/monkey_island/cc/server_utils/test_file_utils.py
> island: Add inheritance when setting Windows file or dir permissions

- .swm/OwcKMnALpn7tuBaJY1US.swm
Run `swimm verify` to fix the travis build
> Swimm: update exercise Add a new System Info Collector (id: OwcKMnALpn7tuBaJY1US)

- monkey/monkey_island/cc/server_utils/encryptor.py
- monkey/monkey_island/cc/server_utils/file_utils.py
- monkey/tests/unit_tests/monkey_island/cc/server_utils/test_file_utils.py
Fixes #1252
> Tested by running on Windows and running unit tests
> Secure file permissions contextmanager

- monkey/infection_monkey/ransomware/ransomware_payload.py
- monkey/infection_monkey/utils/dir_utils.py
- monkey/tests/unit_tests/infection_monkey/utils/test_dir_utils.py
- monkey/tests/utils.py
Explicitly ignore and do not encrypt symlinks and shortcuts in ransomware simulation.
> Ransomware ignore links

- monkey/common/common_consts/telem_categories.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/ransomware/ransomware_payload.py
- monkey/infection_monkey/telemetry/base_telem.py
- monkey/infection_monkey/telemetry/i_telem.py
- monkey/infection_monkey/telemetry/messengers/i_telemetry_messenger.py
- monkey/infection_monkey/telemetry/messengers/telemetry_messenger_wrapper.py
- monkey/infection_monkey/telemetry/ransomware_telem.py
- monkey/tests/unit_tests/infection_monkey/ransomware/test_ransomware_payload.py
- monkey/tests/unit_tests/infection_monkey/telemetry/test_ransomware_telem.py
- vulture_allowlist.py
Fixes #`put issue number here`. 
> Tested by running locally and running unit tests
> Ransomware telemetry

- docs/content/reference/ransomware.md
Partial fix for #1238 
> Ran hugo
> Add documentation for ransomware

- monkey/monkey_island/cc/services/config_schema/ransomware.py
> Tested by running monkey island
> Add readme to ransomware section of configuration schema

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/ransomware/ransomware_payload.py
Adds logging and exception handling to the ransomware payload.
> Tested by running the agent locally from source
> Ransomware logging

- docs/content/reference/ransomware.md
Addresses part of #1244 
> Ran Hugo
> Ransomware documentation modifications for README.txt

- monkey/infection_monkey/ransomware/ransomware_payload.py
- monkey/monkey_island/cc/services/config_schema/ransomware.py
- monkey/tests/unit_tests/infection_monkey/ransomware/test_ransomware_payload.py
Addresses part of #1239  
> Tested by running the Island (see screenshot below). Enabled/disabled encryption and ran ransomware to check it works.
> Add encryption checkbox to ransomware config page

- docs/content/reference/ransomware.md
- monkey/infection_monkey/ransomware/ransomware_payload.py
- monkey/infection_monkey/ransomware/targeted_file_extensions.py
Describe ransomware extensions as "targeted", rather than valid (which implies invalid). Make language consistent between the documentation and the code.
> Tested by running Hugo and unit tests
> Ransomware targeted files

- monkey/infection_monkey/dropper.py
- monkey/infection_monkey/exploit/hadoop.py
- monkey/infection_monkey/exploit/mssqlexec.py
- monkey/infection_monkey/exploit/sambacry.py
- monkey/infection_monkey/exploit/shellshock.py
- monkey/infection_monkey/exploit/smbexec.py
- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/exploit/tools/helpers.py
- monkey/infection_monkey/exploit/vsftpd.py
- monkey/infection_monkey/exploit/web_rce.py
- monkey/infection_monkey/exploit/win_ms08_067.py
- monkey/infection_monkey/exploit/wmiexec.py
- monkey/infection_monkey/model/__init__.py
- monkey/infection_monkey/utils/commands.py
- monkey/infection_monkey/windows_upgrader.py
- monkey/tests/unit_tests/infection_monkey/utils/test_commands.py
Fixes TODOs in infection_monkey/dropper.py. 
> Added string templating functions for infection monkey dropper.

- monkey/monkey_island/cc/ui/src/components/report-components/RansomwareReport.js
> Generate exploitation stats for ransomware report

- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/monkey_island/cc/resources/ransomware_report.py
- monkey/monkey_island/cc/services/ransomware/ransomware_report.py
- monkey/monkey_island/cc/ui/src/components/pages/ReportPage.js
- monkey/tests/data_for_tests/mongo_documents/edges.py
- monkey/tests/data_for_tests/mongo_documents/monkeys.py
- monkey/tests/data_for_tests/mongo_documents/telemetries/file_encryption.py
- monkey/tests/unit_tests/monkey_island/cc/services/ransomware/test_ransomware_report.py
Fixes  part of #1240
> Tested by running manually
> Ransomware encryption table data

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/models/island_mode_model.py
- monkey/monkey_island/cc/resources/island_mode.py
- monkey/monkey_island/cc/services/mode/island_mode_service.py
- monkey/monkey_island/cc/services/mode/mode_enum.py
- monkey/tests/unit_tests/monkey_island/cc/resources/conftest.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_island_mode.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_post_breach_files.py
- monkey/tests/utils.py
- vulture_allowlist.py
Fixes #1241  Add API endpoint for setting the island mode. 
> Ransomware quickstart endpoint

- monkey/monkey_island/cc/resources/island_mode.py
- monkey/monkey_island/cc/services/mode/island_mode_service.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_island_mode.py
Fixes #1241 get mode endpoint. 
> Ransomware quickstart - Add get method for island mode

- monkey/monkey_island/cc/ui/src/components/Main.js
- monkey/monkey_island/cc/ui/src/components/configuration-components/ConfigurationTabs.js
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
#1241  
> Tested by running the Island.
> Display relevant configuration tabs in ransomware mode

- monkey/monkey_island/cc/services/config_schema/basic_network.py
- monkey/monkey_island/cc/services/config_schema/ransomware.py
- monkey/monkey_island/cc/ui/src/components/configuration-components/TextBox.js
- monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> Fix submit config when nothing is changed on Ransomware and Network

- monkey/monkey_island/cc/ui/src/components/Main.tsx
- monkey/monkey_island/cc/ui/src/components/SideNavComponent.tsx
- monkey/monkey_island/cc/ui/src/components/layouts/SidebarLayoutComponent.tsx
- monkey/monkey_island/cc/ui/src/components/pages/ReportPage.js
> Sort report tabs according to scenario

- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
Fixes #1294
> Tested by manually fiddling with the UI
> Island UI: fix config import UI bug

- monkey/monkey_island/cc/ui/src/components/Main.tsx
- monkey/monkey_island/cc/ui/src/components/SideNavComponent.tsx
- monkey/monkey_island/cc/ui/src/components/layouts/SidebarLayoutComponent.tsx
Fixes side navigation part of #1241
> Tested by setting different modes
> Island UI: add island scenario/mode to side navigation

- monkey/monkey_island/cc/ui/src/components/pages/LandingPage.tsx
Fixes #1338. 
> Tested by manual, added timeouts on the island to 100% reproduce the bug
> Bugfix: race condition while setting Island mode

- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/NumberedReportSection.tsx
- monkey/monkey_island/cc/ui/src/styles/pages/report/RansomwareReport.scss
Adds a NumberedReportSection component in support of #1350
> Tested by building and viewing the UI with test data
> UI: Use CSS instead of style for FontAwesomeIcon in Reports

- monkey/monkey_island/cc/services/reporting/aws_exporter.py
Fixes #1341
> Tested by running locally with changed code, tested on AWS with AppImage
> Bugfix: AWS exporter 

- monkey/monkey_island/cc/ui/src/components/report-components/RansomwareReport.js
- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/LateralMovement.tsx
Adds Lateral Movement section to ransomware report
> See screenshot
> UI: Add lateral movement section to ransomware report

- monkey/monkey_island/cc/ui/src/styles/pages/LandingPage.scss
#1349 
> Tested by running Monkey Island.
> Make scenarios buttons on landing page of equal size

- CHANGELOG.md
- appimage/README.md
- docker/DOCKER_README.md
- docker/Dockerfile
- docker/README.md
- docker/build_docker.sh
- docker/clean.sh
- docker/entrypoint.sh
- docker/server_config.json
Adds a script that builds a docker image locally (so you don't need jenkins).
This PR duplicates a lot of code from `appimage/build_appimage.sh`. Duplicate code will be unified in a future PR.
> Tested by building a docker image locally and verifying that a monkey agent can be run from the UI.
> Local docker build

- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
> Config reset after refresh

- monkey/monkey_island/cc/ui/src/components/SideNavComponent.tsx
- monkey/monkey_island/cc/ui/src/components/pages/LandingPage.tsx
- monkey/monkey_island/cc/ui/src/styles/App.css
- monkey/monkey_island/cc/ui/src/styles/pages/LandingPage.scss
Adds a banner to the landing page
> Landing page banner

- monkey/monkey_island/cc/ui/src/components/pages/RegisterPage.js
Fixes #910. 
We just forgot to not show it, if we get good response.
> Fix brief red alert on register.

- .swm/AzD8XysWg1BBXCjCDkfq.swm
- CHANGELOG.md
- monkey/infection_monkey/control.py
- monkey/infection_monkey/monkey.py
Fixes #1374
> Tested by running with `max_depth == 1` and `max_depth == 2`
> Skip propagation only if max depth reached

- .gitignore
- envs/monkey_zoo/.gitignore
- envs/monkey_zoo/blackbox/README.md
- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/tests/performance/telem_sample_parsing/sample_file_parser.py
- envs/monkey_zoo/blackbox/tests/performance/telem_sample_parsing/sample_multiplier/sample_multiplier.py
- envs/monkey_zoo/blackbox/tests/performance/telemetry_performance_test.py
Improves the documentation and does other small changes to the BB tests, especially performance
> BB performance tests: small improvements

- monkey/monkey_island/cc/ui/src/components/attack/techniques/Helpers.js
Fixes #1370  
> Tested by running the Island.
> Fix ATT&CK report bug which wasn't showing IP addresses in PBAs

- docs/content/development/_index.md
- docs/content/development/adding-exploits.md
- docs/content/development/adding-post-breach-actions.md
- docs/content/development/adding-system-info-collectors.md
- docs/content/development/setup-development-environment.md
Fixes #1383  
> Tested by running hugo
---
---
> Add 'Adding Exploits' page to docs

- monkey/monkey_island/cc/ui/src/components/pages/RegisterPage.js
Fixes #1386  
> Tested by running the Island. 
https://user-images.githubusercontent.com/44770317/128145434-cbacfb0f-cc40-4ded-affb-5546266d4a10.mp4
> Redirect to landing page after registration

- monkey/infection_monkey/post_breach/signed_script_proxy/windows/signed_script_proxy.py
Fixes #`put issue number here`. 
> Fix T1216 PBA filename

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js
> Hide description that messed up the list in the UI

- monkey/infection_monkey/network/ping_scanner.py
Removes some duplicate code to clean up the ping scanner.
> Tested by running a subset of blackbox tests
> Ping scanner cleanup

- CHANGELOG.md
- deployment_scripts/config
- deployment_scripts/config.ps1
- deployment_scripts/deploy_linux.sh
- monkey/infection_monkey/monkey.spec
- monkey/infection_monkey/readme.md
Remove traceroute binaries.
Fixes #1397
> Tested by running a subset of blackbox tests.
> Remove traceroute binaries

- CHANGELOG.md
- monkey/infection_monkey/post_breach/actions/communicate_as_new_user.py
- monkey/tests/unit_tests/infection_monkey/post_breach/actions/test_communicate_as_backdoor_user.py
**Merge this before #1433 to avoid messy merge conflicts!**
---
#1410 
> Tested by running the PBA on Windows
> Use random password for CommunicateAsNewUser PBA

- monkey/infection_monkey/utils/windows/users.py
- monkey/tests/unit_tests/infection_monkey/utils/windows/test_windows_users.py
> Add unit test for deactivate and delete new auto windows user

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/powershell_utils/auth_options.py
- monkey/infection_monkey/exploit/powershell_utils/credential_generation.py
- monkey/infection_monkey/exploit/powershell_utils/utils.py
- monkey/tests/unit_tests/infection_monkey/exploit/powershell_utils/test_utils.py
Adds the capability to exploit powershell remoting via HTTP
> Tested by running with credentials over HTTP
> Running with credentials over HTTPS
> Adds the capability to exploit powershell remoting via HTTP

- envs/monkey_zoo/blackbox/config_templates/powershell.py
- envs/monkey_zoo/blackbox/gcp_test_machine_list.py
- envs/monkey_zoo/docs/fullDocs.md
- envs/monkey_zoo/terraform/images.tf
- envs/monkey_zoo/terraform/monkey_zoo.tf
> Zoo: Add new machine for powershell exploiter

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/pages/LandingPage.tsx
- monkey/monkey_island/cc/ui/src/styles/pages/LandingPage.scss
Fixes #1441 :
> Tested by Navigating pages
> Fix the Guardicore logo overlap

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/report-components/security/PostBreach.js
Fixes #1423
> Tested by running Monkey Island
> Don't collapse PBA table in security report on data change

- monkey/monkey_island/cc/resources/pba_file_upload.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_pba_file_upload.py
> UT: Add unit tests for pba_upload

- docs/content/FAQ/_index.md
- docs/content/setup/windows.md
- monkey/monkey_island/cc/ui/src/components/ui-components/IslandMonkeyRunErrorModal.js
> UI: Add AV explanation if binaries are missing

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/powershell_utils/auth_options.py
- monkey/tests/unit_tests/infection_monkey/exploit/powershell_utils/test_auth_options.py
Fixes #1456
> Tested by running bb tests from a Windows and Linux host
> Powershell pth on windows

- monkey/tests/unit_tests/monkey_island/cc/resources/test_pba_file_upload.py
> Fix breaking PBA file upload unit tests on windows.

- monkey/infection_monkey/control.py
Fixes the tunneling test (At least to the old state ).
> Changed proxy schema for the agent

- CHANGELOG.md
- monkey/infection_monkey/config.py
- monkey/infection_monkey/example.conf
- monkey/infection_monkey/main.py
- monkey/monkey_island/cc/services/config_schema/internal.py
- monkey/monkey_island/cc/ui/src/components/configuration-components/InternalConfig.js
- monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json
Fixes #1536  
> Tested by running Monkey Island to make sure nothing breaks.
> Remove "Kill file" config option

- docs/content/FAQ/_index.md
Fixes #1555
> Tested by running hugo
> Docs: Add system resources section to FAQ

- CHANGELOG.md
- monkey/infection_monkey/post_breach/actions/communicate_as_backdoor_user.py
- monkey/infection_monkey/utils/windows/users.py
Fixes #1577 
> Tested by running the modified commands manually.
> Modify "Communicate as Backdoor User" PBA's HTTP requests

- CHANGELOG.md
- monkey/infection_monkey/post_breach/signed_script_proxy/windows/signed_script_proxy.py
Fixes #1557 
> Tested by running the Agent manually, making sure the exe isn't downloaded on Linux, and that it runs on Windows as it should.
> Signed script PBA: don't download exe on Linux

- CHANGELOG.md
- monkey/infection_monkey/config.py
- monkey/infection_monkey/example.conf
- monkey/infection_monkey/monkey.py
- monkey/monkey_island/cc/services/config_schema/internal.py
- monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json
Fixes #1537 Always delete on cleanup. 
> 1537 delete on cleanup

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
Remove unused python package.. 
> Remove unused simplejson python package

- .swm/AzD8XysWg1BBXCjCDkfq.swm
- CHANGELOG.md
- monkey/infection_monkey/config.py
- monkey/infection_monkey/example.conf
- monkey/infection_monkey/monkey.py
- monkey/monkey_island/cc/services/config_schema/monkey.py
- monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json
> Remove max iterations and timeout between iterations options

- monkey/infection_monkey/i_puppet.py
- monkey/infection_monkey/puppet/mock_puppet.py
- vulture_allowlist.py
> Create IPuppet interface

- monkey/infection_monkey/control_channel.py
- monkey/infection_monkey/i_control_channel.py
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/monkey_control/stop_agent_check.py
- monkey/monkey_island/cc/resources/propagation_credentials.py
- monkey/monkey_island/cc/services/config.py
- vulture_allowlist.py
> Implement ControlChannel

- monkey/infection_monkey/i_master.py
- monkey/infection_monkey/i_puppet.py
- monkey/infection_monkey/master/mock_master.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/puppet/mock_puppet.py
- monkey/infection_monkey/telemetry/exploit_telem.py
- monkey/infection_monkey/telemetry/post_breach_telem.py
- monkey/infection_monkey/utils/signal_handler.py
- monkey/tests/unit_tests/infection_monkey/telemetry/test_exploit_telem.py
- monkey/tests/unit_tests/infection_monkey/telemetry/test_post_breach_telem.py
- vulture_allowlist.py
> Add IMaster and MockMaster

- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/telemetry/messengers/batching_telemetry_messenger.py
- monkey/infection_monkey/tunnel.py
- monkey/infection_monkey/utils/timer.py
- monkey/tests/unit_tests/infection_monkey/master/test_automated_master.py
- monkey/tests/unit_tests/infection_monkey/utils/test_timer.py
Partially addresses #1597
This is a preliminary pull request that implements the basic infrastructure required by AutomatedMaster.
This PR:
1. Creates a master thread that can be killed by the user or the Island.
2. Implements a "simulation" thread that calls a number of stub functions/threads
3. Implements running system info collectors
> More unit tests may be added as implementation progresses
> Tested by running the AutomatedMaster in isolation and killing it by calling `terminate()` and signaling from the island.
> 1597 implement automated master - Part 1

- monkey/infection_monkey/master/automated_master.py
- monkey/monkey_island/cc/resources/monkey.py
- monkey/monkey_island/cc/services/config.py
- monkey/tests/data_for_tests/monkey_configs/flat_config.json
- monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Implements the PBA and Payload stubs for AutomatedMaster (#1597)
> Tested by running `AutomatedMaster` in isolation
> 1597 implement stubs in automated master

- CHANGELOG.md
- monkey/infection_monkey/master/control_channel.py
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/propagation_credentials.py
- monkey/monkey_island/cc/services/config.py
- monkey/tests/data_for_tests/monkey_configs/flat_config.json
- monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Implements the `/api/propagation-credentials` endpoint (#1538)
> Tested by adding the endpoint to the `develop` branch and testing with `curl`.
> Implement propagation credentials endpoint

- monkey/monkey_island/cc/services/infection_lifecycle.py
- monkey/tests/requirements.txt
- monkey/tests/unit_tests/monkey_island/cc/services/test_infection_lifecycle.py
Fixes a bug in "is agent dead" endpoint
Adds requirements file for unit tests
> Monkey killing fix

- monkey/infection_monkey/example.conf
- monkey/infection_monkey/i_puppet.py
- monkey/infection_monkey/master/__init__.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/master/control_channel.py
- monkey/infection_monkey/master/ip_scanner.py
- monkey/infection_monkey/master/mock_master.py
- monkey/infection_monkey/master/propagator.py
- monkey/infection_monkey/master/threading_utils.py
- monkey/infection_monkey/puppet/mock_puppet.py
- monkey/monkey_island/cc/services/config.py
- monkey/monkey_island/cc/services/config_schema/definitions/finger_classes.py
- monkey/monkey_island/cc/services/config_schema/internal.py
- monkey/tests/data_for_tests/monkey_configs/flat_config.json
- monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json
- monkey/tests/unit_tests/infection_monkey/master/test_automated_master.py
- monkey/tests/unit_tests/infection_monkey/master/test_network_scanner.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Implements the framework for propagation in `AutomatedMaster`.
Implements TCP and Ping scanning in `AutomatedMaster`. 
> Tested by running the AutomatedMaster in isolation
> 1597 implement propagation scanning

- monkey/infection_monkey/i_puppet.py
- monkey/infection_monkey/puppet/mock_puppet.py
- monkey/infection_monkey/puppet/plugin_type.py
- monkey/infection_monkey/puppet/puppet.py
Resolves the first two tasks of #1598.
> Add `load_plugin` functions and create a concrete puppet class

- monkey/infection_monkey/ransomware/ransomware_payload.py
- monkey/tests/unit_tests/infection_monkey/ransomware/test_ransomware_payload.py
> 1646 remove ransomware cleanup

- monkey/infection_monkey/i_master.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/master/mock_master.py
- monkey/infection_monkey/utils/exceptions/planned_shutdown_error.py
- monkey/infection_monkey/utils/signal_handler.py
Improves Windows signal handling for #1597 and gives the `AutomatedMaster` the opportunity to gracefully shut down on window close events.
> Tested by running on Windows and Linux and sending the necessary signals
> 1597 signal handling

- monkey/common/utils/exceptions.py
- monkey/infection_monkey/i_control_channel.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/master/control_channel.py
- monkey/tests/data_for_tests/monkey_configs/automated_master_config.json
- monkey/tests/unit_tests/conftest.py
- monkey/tests/unit_tests/infection_monkey/conftest.py
- monkey/tests/unit_tests/infection_monkey/master/test_automated_master.py
- monkey/tests/unit_tests/monkey_island/cc/conftest.py
- monkey/tests/unit_tests/monkey_island/cc/server_utils/encryption/test_password_based_encryption.py
Handle ControlClient exceptions. Related to #1597 . 
> Handle ControlClient exceptions in AutomatedMaster

- monkey/monkey_island/cc/server_utils/consts.py
- monkey/monkey_island/cc/setup/island_config_options.py
- monkey/tests/unit_tests/monkey_island/cc/setup/test_island_config_options.py
Fixes the logic that updates the Island config options from the package and user-specified config files.
> Tested by running blackbox tests for Docker package
> Island: Fix updating logic for IslandConfigOptions

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
Fixed dev requirments for windows agents
> Tested by running pipenv install --dev
> Project: add windows dev requirements for agent

- monkey/infection_monkey/network/__init__.py
- monkey/infection_monkey/network/ping_scanner.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/network/test_ping.py
Fixes #1602
Implements ping scanning in the Puppet.
> Tested by running the puppet
> 1602 implement ping scanning

- CHANGELOG.md
- monkey/infection_monkey/monkey.spec
Fixes #1693 . 
Some remains referencing sambacry binaries.
> Agent: Remove sambacry binaries from monkey spec

- monkey/infection_monkey/i_puppet/__init__.py
- monkey/infection_monkey/i_puppet/i_fingerprinter.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/master/ip_scanner.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/http_fingerprinter.py
- monkey/infection_monkey/network/httpfinger.py
- monkey/infection_monkey/puppet/mock_puppet.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/monkey_island/cc/services/config.py
- monkey/tests/unit_tests/infection_monkey/master/test_ip_scanner.py
- monkey/tests/unit_tests/infection_monkey/network/test_http_fingerprinter.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Implements HTTP fingerprinting in the Puppet for issue #1603
> Enable http fingerprinting

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
Fixes #1690 
> Tested by building windows island
> Tested by building and running linux and windows agents
> 1690 investigate pyinstaller versions

- monkey/infection_monkey/master/exploiter.py
- monkey/monkey_island/cc/services/config.py
- monkey/tests/data_for_tests/monkey_configs/automated_master_config.json
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Fixes #1605 removing propagator boolean. 
> Agent, Island: Modify config to remove boolean propagator field

- monkey/infection_monkey/utils/brute_force.py
- monkey/tests/unit_tests/infection_monkey/utils/test_brute_force.py
Copies identity/key generation code from `WormConfig` to a new `infection_monkey.utils.brute_force` module so that exploiters can be decoupled from the WormConfig.
> 1605 brute force utils

- monkey/infection_monkey/exploit/HostExploiter.py
Modifies `HostExploiter` so that it no longer inherits from `Plugin`
> Agent: Remove HostExploiter's dependency on Plugin

- monkey/monkey_island/cc/services/telemetry/processing/credentials/__init__.py
- monkey/monkey_island/cc/services/telemetry/processing/credentials/credentials.py
- monkey/monkey_island/cc/services/telemetry/processing/credentials/credentials_parser.py
- monkey/monkey_island/cc/services/telemetry/processing/credentials/identities/username_processor.py
- monkey/monkey_island/cc/services/telemetry/processing/credentials/secrets/lm_hash_processor.py
- monkey/monkey_island/cc/services/telemetry/processing/credentials/secrets/nt_hash_processor.py
- monkey/monkey_island/cc/services/telemetry/processing/credentials/secrets/password_processor.py
- monkey/monkey_island/cc/services/telemetry/processing/credentials/secrets/ssh_key_processor.py
- monkey/monkey_island/cc/services/telemetry/processing/processing.py
- monkey/tests/unit_tests/monkey_island/cc/services/telemetry/processing/credentials/conftest.py
- monkey/tests/unit_tests/monkey_island/cc/services/telemetry/processing/credentials/test_credential_processing.py
- monkey/tests/unit_tests/monkey_island/cc/services/telemetry/processing/credentials/test_ssh_key_processing.py
> 1695 ssh keys processing

- monkey/infection_monkey/exploit/hadoop.py
- monkey/infection_monkey/exploit/web_rce.py
- monkey/infection_monkey/exploit/weblogic.py
- monkey/infection_monkey/model/__init__.py
- monkey/infection_monkey/monkey.py
- monkey/monkey_island/cc/resources/telemetry_feed.py
- monkey/monkey_island/cc/services/config.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
> Modify Hadoop exploiter

- docs/content/development/setup-development-environment.md
- docs/content/usage/getting-started.md
- monkey/infection_monkey/readme.md
- monkey/monkey_island/readme.md
Fixes a part of #1675 
> Tested by running Hugo
> Modify docs to remove 32-bit mentions

- CHANGELOG.md
- envs/monkey_zoo/blackbox/config_templates/base_template.py
- envs/monkey_zoo/blackbox/config_templates/drupal.py
- envs/monkey_zoo/blackbox/config_templates/mssql.py
- envs/monkey_zoo/blackbox/config_templates/powershell.py
- envs/monkey_zoo/blackbox/config_templates/powershell_credentials_reuse.py
- envs/monkey_zoo/blackbox/config_templates/smb_mimikatz.py
- envs/monkey_zoo/blackbox/config_templates/smb_pth.py
- envs/monkey_zoo/blackbox/config_templates/ssh.py
- envs/monkey_zoo/blackbox/config_templates/tunneling.py
- envs/monkey_zoo/blackbox/config_templates/wmi_pth.py
- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/exploit/tools/helpers.py
Removes 32-bit logic from SSHExploiter
Fixes bug in monkey download/propagation
Removes PingScanner from BB config templates
Issue #1675.
> Tested by running SSH blackbox test
> 1675 remove 32 bit from ssh

- monkey/infection_monkey/control.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/telemetry/messengers/exploit_intercepting_telemetry_messenger.py
- monkey/infection_monkey/tunnel.py
- monkey/tests/unit_tests/infection_monkey/telemetry/messengers/test_exploit_intercepting_telemetry_messenger.py
Adds logic to keep tunnel open until exploited machines connect. This preserves the existing logic and makes no attempts to improve upon it. 
> Tested by running locally from source
> Keep tunnel open

- monkey/infection_monkey/dropper.py
- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/log4shell_utils/exploit_class_http_server.py
- monkey/infection_monkey/exploit/log4shell_utils/ldap_server.py
- monkey/infection_monkey/exploit/web_rce.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network_scanning/http_fingerprinter.py
- monkey/infection_monkey/telemetry/attack/t1107_telem.py
- monkey/infection_monkey/utils/monkey_dir.py
- monkey/monkey_island/cc/resources/monkey_download.py
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_curl.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_wget.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_windows_powershell.js
- monkey/tests/unit_tests/infection_monkey/exploit/log4shell_utils/test_exploit_class_http_server.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_http_fingerprinter.py
- monkey/tests/unit_tests/infection_monkey/telemetry/attack/test_t1107_telem.py
> Add Log4Shell to puppet

- monkey/infection_monkey/model/__init__.py
Fixes #1755 .
Because hadoop is re-requesting agents, we don't get the
agent if it already there, if it has size 0 and if it exists
we remove it.
> Agent: Prevent overwriting hadoop linux agent

- monkey/infection_monkey/config.py
- monkey/infection_monkey/exploit/HostExploiter.py
- monkey/infection_monkey/exploit/exploiter_wrapper.py
- monkey/infection_monkey/exploit/hadoop.py
- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/web_rce.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/master/exploiter.py
- monkey/infection_monkey/master/mock_master.py
- monkey/infection_monkey/master/propagator.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/puppet/mock_puppet.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_automated_master.py
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
Reintroduces the logic to skip propagation if the scan depth is 0
Some function calls are starting to have a lot of parameters. I haven't found the best way to solve it yet. I think, as the code evolves, ways to group some of these parameters will become more apparent.
> Tested by running log4shell
> Scan depth

- CHANGELOG.md
- monkey/infection_monkey/config.py
- monkey/infection_monkey/exploit/smbexec.py
- monkey/infection_monkey/exploit/tools/smb_tools.py
- monkey/infection_monkey/exploit/tools/wmi_tools.py
- monkey/infection_monkey/exploit/wmiexec.py
- monkey/infection_monkey/main.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/master/exploiter.py
- monkey/infection_monkey/master/ip_scanner.py
- monkey/infection_monkey/master/propagator.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/tunnel.py
- monkey/infection_monkey/utils/aws_environment_check.py
- monkey/infection_monkey/utils/brute_force.py
- monkey/infection_monkey/utils/threading.py
- monkey/monkey_island/cc/services/config.py
- monkey/monkey_island/cc/services/config_schema/internal.py
- monkey/tests/unit_tests/infection_monkey/utils/test_threading.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Fixes #1742 
> Tested by running 6 wmi threads/machines at a time
> 1742 add wmi exploiter to puppet

- monkey/monkey_island/cc/resources/monkey.py
- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/services/telemetry/processing/exploit.py
> 1770 exploiter issue in security report

- envs/monkey_zoo/docs/fullDocs.md
- monkey/infection_monkey/exploit/caching_agent_repository.py
- monkey/infection_monkey/exploit/consts.py
- monkey/infection_monkey/exploit/hadoop.py
- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/powershell_utils/powershell_client.py
- monkey/infection_monkey/exploit/tools/helpers.py
- monkey/infection_monkey/exploit/tools/http_tools.py
- monkey/infection_monkey/model/__init__.py
- monkey/infection_monkey/monkey.py
- monkey/monkey_island/cc/services/run_local_monkey.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py
Fixes #1740 .
> Tested by running the exploit on gcp machines both on Linux and Windows islands
> 1740 add powershell to puppet

- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/resources/client_run.py
- monkey/monkey_island/cc/resources/local_run.py
- monkey/monkey_island/cc/resources/monkey.py
- monkey/monkey_island/cc/services/node.py
> Remove `keepalive`

- monkey/infection_monkey/config.py
- monkey/infection_monkey/example.conf
- monkey/infection_monkey/exploit/HostExploiter.py
- monkey/infection_monkey/exploit/exploiter_wrapper.py
- monkey/infection_monkey/exploit/tools/wmi_tools.py
- monkey/infection_monkey/exploit/wmiexec.py
- monkey/infection_monkey/puppet/plugin_registry.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/monkey_island/cc/models/config.py
- monkey/monkey_island/cc/services/config_schema/internal.py
- monkey/monkey_island/cc/services/infection_lifecycle.py
- monkey/monkey_island/cc/services/node.py
- monkey/monkey_island/cc/ui/src/components/pages/MapPage.js
- monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_infection_lifecycle.py
> 1611 interruptable exploiters

- monkey/infection_monkey/exploit/HostExploiter.py
- monkey/infection_monkey/exploit/mssqlexec.py
- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/wmiexec.py
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/puppet/mock_puppet.py
- monkey/infection_monkey/telemetry/exploit_telem.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
- monkey/tests/unit_tests/infection_monkey/telemetry/test_exploit_telem.py
Makes powershell exploiter interruptable
> Tested by shutting down powershell machine, killing all monkeys
> 1611 Make powershell exploiter interruptable

- monkey/infection_monkey/exploit/sshexec.py
Adds interrupts to SSH exploit. Related #1611 
> Tested by running SSH exploit and checking timeouts locally.
> 1611 interruptable ssh exploit

- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/log4shell_utils/service_exploiters/logstash.py
- monkey/infection_monkey/exploit/log4shell_utils/service_exploiters/solr.py
- monkey/infection_monkey/exploit/log4shell_utils/service_exploiters/tomcat.py
Makes log4shell interuptable
> Tested by running on all log4shell machines in zoo
> Killing monkey in the middle of log4shell exploit
> Agent: Make log4shell interruptable

- monkey/infection_monkey/exploit/smbexec.py
Make SMBExploiter interruptible.
> Tested by running from source on GCP
> Agent: Make SMBExploiter interruptible

- monkey/infection_monkey/exploit/hadoop.py
- monkey/infection_monkey/exploit/web_rce.py
Makes Hadoop interuptable #1611.
> Agent: Make Hadoop interruptable

- monkey/infection_monkey/exploit/zerologon.py
- monkey/infection_monkey/exploit/zerologon_utils/remote_shell.py
- monkey/infection_monkey/exploit/zerologon_utils/vuln_assessment.py
> Agent: Make ZeroLogon interruptibale

- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/powershell_utils/powershell_client.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py
Fixes powershell part of #1782
> Tested by exploiting powershell in GCP
> Agent: Upload binary with random string when using powershell

- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/telemetry/attack/t1105_telem.py
- monkey/tests/unit_tests/infection_monkey/telemetry/attack/test_t1105_telem.py
> Agent: Use random destination path for SSH

- monkey/infection_monkey/exploit/mssqlexec.py
Fixes #1782.
> Tested by mssql exploit on GCP
> Agent: User random binary destination path for MSSQL Exploit

- monkey/infection_monkey/exploit/smbexec.py
- monkey/infection_monkey/exploit/tools/smb_tools.py
Fixes smb part of #1782 
> Tested by running in GCP, seeing the exploitation
> Agent: Convert destination path to string in SMB exploiter

- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/powershell_utils/auth_options.py
- monkey/monkey_island/cc/services/config_schema/internal.py
- monkey/tests/unit_tests/infection_monkey/exploit/conftest.py
- monkey/tests/unit_tests/infection_monkey/exploit/powershell_utils/test_auth_options.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py
Fixes #1788 
> Tested by running the Monkey and being able to exploit a machine, and removing the ports from the config and not being able to exploit it.
> PowerShell SSL detection

- monkey/infection_monkey/exploit/wmiexec.py
Fixes wmi part of #1782
> Tested by running wmi exploitation, looking at telems/report
> Agent: Change WMI exploiter to use random agent name

- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/mssqlexec.py
- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/powershell_utils/powershell_client.py
- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/exploit/tools/helpers.py
- monkey/infection_monkey/exploit/tools/smb_tools.py
Fixes log4shell part of #1782
Fixes a bug in destination path helper
Fixes incorrect propagation state toggle in log4shell
> Tested by exploiting machines in GCP
> 1782 log4shell

- monkey/infection_monkey/telemetry/messengers/exploit_intercepting_telemetry_messenger.py
- monkey/tests/unit_tests/infection_monkey/telemetry/messengers/test_exploit_intercepting_telemetry_messenger.py
Improves logic in `ExploitInterceptingTelemetryMessenger`
#1801
> Agent: Fix unnecessary waiting in MonkeyTunnel

- envs/monkey_zoo/docs/fullDocs.md
- envs/monkey_zoo/terraform/images.tf
- envs/monkey_zoo/terraform/monkey_zoo.tf
Fixes part of #1801 (removes smb-20 machine)
> BB: Remove smb-20 machine

- monkey/infection_monkey/exploit/hadoop.py
Fixes #1782.
> Tested by running hadoop in GCP
> Agent: Use random binary destination path for Hadoop

- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/master/mock_master.py
- monkey/infection_monkey/post_breach/pba.py
- monkey/infection_monkey/puppet/mock_puppet.py
Fixes #1604 
> Tested by running the Island, running the Agent, and making sure the report shows the display name.
> Remove PBA's Plugin dependency + add display_name to PostBreachData

- envs/monkey_zoo/blackbox/config_templates/powershell.py
- envs/monkey_zoo/blackbox/config_templates/powershell_credentials_reuse.py
- envs/monkey_zoo/blackbox/config_templates/tunneling.py
- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/tests/exploitation.py
Fixes the blackbox tests so that they run.
Issue #1801
> Tested by running all blackbox tests (except zerologon) in GCP
> 1801 fix blackbox tests

- monkey/infection_monkey/monkey.py
Fixes part of #1604 
> Tested by running agent, seeing PBA telemetries
> Agent: Load PBA's into puppet

- monkey/infection_monkey/payload/ransomware/file_selectors.py
- monkey/infection_monkey/payload/ransomware/ransomware.py
- monkey/infection_monkey/utils/dir_utils.py
- monkey/infection_monkey/utils/threading.py
- monkey/tests/unit_tests/infection_monkey/payload/ransomware/test_file_selectors.py
- monkey/tests/unit_tests/infection_monkey/payload/ransomware/test_ransomware.py
- monkey/tests/unit_tests/infection_monkey/utils/test_dir_utils.py
- monkey/tests/unit_tests/infection_monkey/utils/test_threading.py
Improves mechanisms for interrupting the ransomware payload.
Use iterators instead of lists for filtering files.
Fixes #1612
> Running locally on Linux
> 1612 interruptible ransomware

- monkey/common/common_consts/timeouts.py
- monkey/infection_monkey/network/tools.py
- monkey/infection_monkey/puppet/puppet.py
Creates a const to be used for connection timeout
> CONNECTION_TIMEOUT const

- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/telemetry/post_breach_telem.py
Fixes part of #1064, changes telemetries accept post breach data
> 1604 post breach telems accept post breach data

- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/post_breach/actions/clear_command_history.py
- monkey/infection_monkey/post_breach/actions/collect_processes_list.py
- monkey/infection_monkey/post_breach/actions/communicate_as_backdoor_user.py
- monkey/infection_monkey/post_breach/actions/hide_files.py
- monkey/infection_monkey/post_breach/actions/modify_shell_startup_files.py
- monkey/infection_monkey/post_breach/actions/schedule_jobs.py
- monkey/infection_monkey/post_breach/actions/use_signed_scripts.py
- monkey/infection_monkey/post_breach/pba.py
- monkey/infection_monkey/puppet/mock_puppet.py
- vulture_allowlist.py
Fixes a part of #1604 
> Tested with 2 PBAs enabled on Windows. There's a separate task for testing so the rest can be done and any bugs found then should be miniscule. 
> Modify PBAs to return PostBreachData

- monkey/infection_monkey/exploit/HostExploiter.py
- monkey/infection_monkey/exploit/drupal.py
- monkey/infection_monkey/exploit/hadoop.py
- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/mssqlexec.py
- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/smbexec.py
- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/exploit/struts2.py
- monkey/infection_monkey/exploit/weblogic.py
- monkey/infection_monkey/exploit/wmiexec.py
- monkey/infection_monkey/exploit/zerologon.py
- monkey/infection_monkey/master/exploiter.py
- monkey/infection_monkey/puppet/mock_puppet.py
- monkey/monkey_island/cc/services/config.py
- monkey/tests/data_for_tests/monkey_configs/automated_master_config.json
- monkey/tests/data_for_tests/monkey_configs/flat_config.json
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Don't run an exploiter if the victim runs an unsupported OS
> Check supported os for exploiters

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/post_breach/actions/change_file_privileges.py
- monkey/infection_monkey/post_breach/actions/clear_command_history.py
- monkey/infection_monkey/post_breach/actions/collect_processes_list.py
- monkey/infection_monkey/post_breach/actions/communicate_as_backdoor_user.py
- monkey/infection_monkey/post_breach/actions/discover_accounts.py
- monkey/infection_monkey/post_breach/actions/hide_files.py
- monkey/infection_monkey/post_breach/actions/modify_shell_startup_files.py
- monkey/infection_monkey/post_breach/actions/schedule_jobs.py
- monkey/infection_monkey/post_breach/actions/timestomping.py
- monkey/infection_monkey/post_breach/actions/use_signed_scripts.py
- monkey/infection_monkey/post_breach/actions/use_trap_command.py
- monkey/infection_monkey/post_breach/actions/users_custom_pba.py
- monkey/infection_monkey/post_breach/pba.py
> Telemetry messenger in PBAs

- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/post_breach/actions/clear_command_history.py
- monkey/infection_monkey/post_breach/actions/collect_processes_list.py
- monkey/infection_monkey/post_breach/actions/communicate_as_backdoor_user.py
- monkey/infection_monkey/post_breach/actions/hide_files.py
- monkey/infection_monkey/post_breach/actions/modify_shell_startup_files.py
- monkey/infection_monkey/post_breach/actions/schedule_jobs.py
- monkey/infection_monkey/post_breach/actions/use_signed_scripts.py
- monkey/infection_monkey/post_breach/pba.py
- monkey/infection_monkey/puppet/puppet.py
Fixes #1604 
> Tested that PBAs run without any errors on Windows
> PBA modifications so they run

- monkey/infection_monkey/post_breach/actions/modify_shell_startup_files.py
- monkey/infection_monkey/post_breach/shell_startup_files/linux/shell_startup_files_modification.py
- monkey/infection_monkey/post_breach/shell_startup_files/windows/shell_startup_files_modification.py
> Agent: Add timeouts in shell startup modification PBA's

- monkey/infection_monkey/post_breach/actions/clear_command_history.py
- monkey/infection_monkey/post_breach/clear_command_history/linux_clear_command_history.py
Related to #1650.
Inspected timeouts in Clear command history PBA.
> Tested by running Clear Command History PBA 
> Agent: Add long timeout to clear command history PBA

- monkey/monkey_island/cc/ui/src/components/pages/MapPage.js
- monkey/monkey_island/cc/ui/src/components/report-components/attack/ReportMatrixComponent.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/PostBreachParser.js
Fixes #1836 
> Travis build passes
> Fix eslint errors

- monkey/infection_monkey/utils/linux/users.py
- monkey/infection_monkey/utils/windows/users.py
- monkey/tests/unit_tests/infection_monkey/utils/linux/test_users.py
- monkey/tests/unit_tests/infection_monkey/utils/windows/test_windows_users.py
> Add timeout to new user creation

- monkey/infection_monkey/exploit/log4shell_utils/exploit_class_http_server.py
- monkey/monkey_island/cc/setup/mongo/database_initializer.py
- monkey/tests/unit_tests/monkey_island/cc/services/reporting/test_stolen_credentials.py
Fixes part of #1826 .
Also small deprecation warning to use `count_documents({})` instead of `count()`
> Tested by running log4shell bb test
> 1826 resolve exploit class http server todo

- monkey/monkey_island/cc/ui/package-lock.json
- monkey/monkey_island/cc/ui/package.json
Fixes #1875
Removes snyk and snyk scripts from npm
> Tested by running `npm ci`
> UI: Remove snyk

- monkey/monkey_island/cc/server_utils/encryption/__init__.py
- monkey/monkey_island/cc/server_utils/encryption/field_encryptors/__init__.py
- monkey/monkey_island/cc/server_utils/encryption/field_encryptors/string_encryptor.py
- monkey/monkey_island/cc/services/config.py
- monkey/monkey_island/cc/services/telemetry/processing/credentials/secrets/ssh_key_processor.py
- monkey/tests/unit_tests/monkey_island/cc/server_utils/encryption/test_string_encryptor.py
- monkey/tests/unit_tests/monkey_island/cc/services/telemetry/processing/credentials/test_ssh_key_processing.py
Fixes part of #1826.
Username and ip are totally not needed for processing of ssh_keypairs, but there was a catch. The username and the ip were used as identifier for the ssh key. One user and ip to a single ssh key which is wrong. This PR fixes that along with encryption/ decryption of dictionaries which was needed for encrypting/decrypting the ssh key dictionaries.
> 1826 ssh key todo

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
Fixes #1863.
> Tested by running SSH BB test from windows island
> Agent: Update the forked paramiko with a patch for ssh_windows

- monkey/infection_monkey/telemetry/messengers/batching_telemetry_messenger.py
- monkey/infection_monkey/tunnel.py
- monkey/infection_monkey/utils/timer.py
Fixes a part of #1826 
> All UTs pass
> Resolve `Timer` TODOs

- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/commands/local_linux_wget.js
The wget command was just outputing the binary to `linux`
> UI: Add output to the wget manual run command

- CHANGELOG.md
- deployment_scripts/install-infection-monkey-service.sh
Fixes #1552 
Deployment script to install systemd unit service that runs infection monkey appimage on boot
> Deploy: Script to install appimage sysd service that runs on boot

- .travis.yml
Takes the lessons learned from #1832 and apply them to the travis build.
> Reduce travis build time

- CHANGELOG.md
- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- monkey/infection_monkey/master/control_channel.py
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/components/pages/MapPage.js
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/tests/unit_tests/monkey_island/cc/resources/test_pba_file_upload.py
Fixes part of #1888 .
Fix endpoints naming
> Tested by locally by running agent and Island
> Fix endpoints urls

- monkey/monkey_island/cc/ui/src/components/map/preview-pane/PreviewPane.js
> UI: Add logs' download buttons to Island node in the map

- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
> Island: Fix immediate threats indentation

- monkey/monkey_island/cc/ui/src/styles/components/Map.scss
> Fix telemetry overview line counter position

- CHANGELOG.md
- monkey/infection_monkey/model/__init__.py
- monkey/infection_monkey/monkey.py
Fixes #1763 
Couple issues, first was that we had infinite loop where we waited to deleted the executable and second
monkey name with spaces like 'monkey-windows-64 - Copy.exe' was not deleted because the spaces.
> Tested by running locally and running the Hadoop BB test
> Agent: Change windows removal command

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/map/TelemetryLog.tsx
> Fix line number in telemetry overview window

- monkey/monkey_island/cc/resources/telemetry_feed.py
Fixes a part of #1850 
> There is some duplication when checking the scan telemetry for whether the machine responded or not (similar code is present in `monkey_island/cc/services/telemetry/processing/scan.py`). I don't see a good way to get rid of this duplication.
> Tested by running the Island.
> Filter scan telemetry before showing in telemetry overview

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/map/TelemetryLog.tsx
Fixes #1850.
> Tested by locally by running Monkey Island
https://user-images.githubusercontent.com/15820737/164467253-1a109fc0-8b7f-4c09-bf68-fee8859b39da.mov
> Fix automatic jumping in telemetry feed

- envs/monkey_zoo/blackbox/test_blackbox.py
- monkey/infection_monkey/exploit/tools/smb_tools.py
Fixes #1903.
Zerologon takes more then 150s.
> Tested by running Jenkins bunch and bunch of times.
> Zoo: Add timeout to zerologon bb test

- .gitignore
- monkey/common/__init__.py
- monkey/common/di_container.py
- monkey/common/utils/file_utils.py
- monkey/infection_monkey/payload/ransomware/file_selectors.py
- monkey/infection_monkey/utils/dir_utils.py
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/pba_file_download.py
- monkey/monkey_island/cc/resources/pba_file_upload.py
- monkey/monkey_island/cc/server_setup.py
- monkey/monkey_island/cc/services/__init__.py
- monkey/monkey_island/cc/services/authentication/authentication_service.py
- monkey/monkey_island/cc/services/directory_file_storage_service.py
- monkey/monkey_island/cc/services/i_file_storage_service.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/monkey_island/cc/services/post_breach_files.py
- monkey/monkey_island/cc/services/run_local_monkey.py
- monkey/tests/monkey_island/utils.py
- monkey/tests/unit_tests/common/test_di_container.py
- monkey/tests/unit_tests/common/utils/test_common_file_utils.py
- monkey/tests/unit_tests/infection_monkey/utils/test_dir_utils.py
- monkey/tests/unit_tests/monkey_island/cc/resources/conftest.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_pba_file_download.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_pba_file_upload.py
- monkey/tests/unit_tests/monkey_island/cc/server_utils/test_file_utils.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_directory_file_storage_service.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_post_breach_files.py
- monkey/tests/utils.py
Added:
* IFileStorageService
* DirectoryFileStorageService
* DIContainer
Changed:
* the custom PBA resources to accept an IFileStorageService in their constructors
* the functions that build the Flask API to use the new DIContainer.
Removed:
* Most of the meat and potatoes from PostBreachFilesService
Resolves #1904
> Tested by running a custom PBA locally
> 1904 service resource dependency injection

- monkey/common/config_value_paths.py
- monkey/monkey_island/cc/resources/pba_file_upload.py
- monkey/monkey_island/cc/services/directory_file_storage_service.py
Resolves #1904
> Tested by running a custom PBA locally
> 1904 pba file upload resource improvements

- CHANGELOG.md
- build_scripts/build_package.sh
- monkey/common/version.py
Fixes #1553.
> Tested by building all three packages both release and development
> Change BUILD file to include commit hash on dev builds

- monkey/monkey_island/cc/server_utils/file_utils.py
- monkey/monkey_island/cc/setup/data_dir.py
- monkey/monkey_island/cc/setup/mongo/mongo_setup.py
- monkey/tests/unit_tests/monkey_island/cc/server_utils/test_file_utils.py
Related to #1921 .
> Tested by running msi EtE
> Island: Fix file_utils paths

- monkey/monkey_island/cc/services/__init__.py
- monkey/monkey_island/cc/services/aws_service.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_aws_service.py
Create a stateful AWSService. Compose and register it in the composition root.
Part of issue #1928
> Tested by running the Island and ensuring there were no exceptions when it starts.
> 1928 stateful aws service

- docs/content/setup/linux.md
Fixes a part of #1883.
> Tested by running Hugo
> Add documentation to run IM as service on boot

- .pre-commit-config.yaml
- .travis.yml
- monkey/monkey_island/cc/models/networkmap.py
- monkey/monkey_island/cc/repository/ILogRepository.py
- monkey/monkey_island/cc/repository/IMachineRepository.py
- monkey/monkey_island/cc/repository/INetworkMapRepository.py
- monkey/monkey_island/cc/repository/ISimulationRepository.py
- monkey/monkey_island/cc/repository/ITelemetryRepository.py
- monkey/monkey_island/cc/resources/blackbox/utils/telem_store.py
- monkey/monkey_island/cc/services/node.py
- pyproject.toml
> Project: Fix travis build

- monkey/infection_monkey/config.py
- monkey/monkey_island/cc/models/config.py
- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/services/config_schema/internal.py
- monkey/monkey_island/cc/services/infection_lifecycle.py
- monkey/monkey_island/cc/services/node.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_infection_lifecycle.py
Fixes #1962 
> Tested by running a single monkey locally and killing it before the simulation thread starts and while the simulation is running. Tested on GCP with multiple monkeys running on different machines.
> Move `should_stop` out of the config

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/agent_binaries.py
- monkey/monkey_island/cc/server_setup.py
- monkey/monkey_island/cc/services/run_local_monkey.py
> Rename MonkeyDownload to AgentBinaries

- build_scripts/docker/docker.sh
Fixes part of #1959 .
> Tested by building the island and checking the docker images
> Build: Cleanup dangling docker images after build

- build_scripts/appimage/appimage.sh
- build_scripts/build_package.sh
- build_scripts/docker/docker.sh
> Build: Remove squashfs-root folder after appimage build

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/monkey_island/cc/server_setup.py
> Island: Add AgentBinaries to monkey_island.cc.resources package

- monkey/monkey_island/cc/repository/__init__.py
- monkey/monkey_island/cc/repository/i_agent_binary_repository.py
Adds IAgentBinaryRepository. Related to #1974 
> Island: Add IAgentBinaryRepository

- monkey/monkey_island/cc/repository/__init__.py
- monkey/monkey_island/cc/repository/agent_binary_repository.py
- monkey/monkey_island/cc/repository/i_agent_binary_repository.py
- monkey/monkey_island/cc/services/initialize.py
Implements concrete AgentBinaryReposiotyr, #1974 .
> vulture failing until the Agent-binaries resource is refactored
> Island: Add concrete AgentBinaryRepository

- monkey/common/utils/file_utils.py
- monkey/monkey_island/cc/repository/__init__.py
- monkey/monkey_island/cc/repository/agent_binary_repository.py
- monkey/monkey_island/cc/repository/i_agent_binary_repository.py
- monkey/monkey_island/cc/resources/agent_binaries.py
- monkey/monkey_island/cc/server_setup.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/tests/unit_tests/common/utils/test_common_file_utils.py
Fixes part of #1974 .
> Tested by running from source
> 1974 log hashes on initialize

- monkey/infection_monkey/control.py
- monkey/infection_monkey/master/control_channel.py
- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/resources/island_configuration.py
- monkey/monkey_island/cc/resources/monkey.py
- monkey/monkey_island/cc/resources/propagation_credentials.py
- monkey/monkey_island/cc/services/config.py
- monkey/monkey_island/cc/services/reporting/report.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Fixes #1968
> Tested by ETE tests
> 1968 global agent config

- monkey/monkey_island/cc/resources/agent_binaries.py
- monkey/monkey_island/cc/resources/local_run.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/monkey_island/cc/services/run_local_monkey.py
- monkey/monkey_island/cc/ui/src/components/configuration-components/InternalConfig.js
Fixes #1974 
> Tested by running locally and exploiting a machine
> Island: Refactor agent-binaries resource

- monkey/monkey_island/cc/services/config.py
- monkey/monkey_island/cc/services/config_schema/internal.py
- monkey/tests/data_for_tests/monkey_configs/flat_config.json
- monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
Fixes #1995 
> Need to test on GCP
> Remove smb_download_timeout

- monkey/common/config_value_paths.py
- monkey/infection_monkey/config.py
- monkey/monkey_island/cc/services/config.py
- monkey/monkey_island/cc/services/config_schema/internal.py
- monkey/tests/data_for_tests/monkey_configs/flat_config.json
- monkey/tests/data_for_tests/monkey_configs/monkey_config_standard.json
> Remove unused AWS config fields

- monkey/infection_monkey/config.py
- monkey/infection_monkey/control.py
- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/resources/monkey.py
Fixes #1999 .
> Tested by running EtE
> 1999 remove send config error

- CHANGELOG.md
- monkey/infection_monkey/exploit/mssqlexec.py
Fixes #2019
> Tested by running manually in GCP
> 2019 mssql batch cleanup

- monkey/infection_monkey/exploit/mssqlexec.py
Improves code quality of methods in `MSSQLExploiter`
> Tested by running manually in GCP
> MSSQL method improvements

- monkey/infection_monkey/exploit/mssqlexec.py
Fixes #2019
> Tested by running manually in GCP
> Remove temporary "payload" file in MSSQL exploiter

- CHANGELOG.md
- monkey/monkey_island/cc/services/config.py
> Island: Remove HTTP_PORTS from top-level agent configuration

- monkey/monkey_island/cc/services/config.py
- monkey/monkey_island/cc/services/representations.py
- monkey/tests/data_for_tests/monkey_configs/flat_config.json
- monkey/tests/unit_tests/monkey_island/cc/services/test_config.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_representations.py
Fixes a part of #1960 
Changes the json encoder to parse Enum objects to their name value
> Tested manually by creating an AgentConfiguration object
> Change config flattening logic to return new schema

- monkey/monkey_island/cc/repository/__init__.py
- monkey/monkey_island/cc/repository/errors.py
- monkey/monkey_island/cc/repository/file_storage/i_file_repository.py
- monkey/monkey_island/cc/repository/file_storage/local_storage_file_repository.py
Standardizes `RemovalError`, `RetrievalError`, and `StorageError` for repositories
> Repository errors

- monkey/common/configuration/__init__.py
- monkey/common/configuration/default_agent_configuration.py
- monkey/monkey_island/cc/repository/file_agent_configuration_repository.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/tests/unit_tests/common/test_agent_configuration.py
- monkey/tests/unit_tests/conftest.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_file_agent_configuration_repository.py
- pyproject.toml
Passes the default agent configuration to the constructor of `FileAgentConfigurationRepository`
> Tested by running the Island manually
> Default agent config di

- monkey/infection_monkey/exploit/hadoop.py
- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/tools/helpers.py
- monkey/infection_monkey/exploit/web_rce.py
- monkey/infection_monkey/model/host.py
- monkey/infection_monkey/network_scanning/ping_scanner.py
- monkey/infection_monkey/network_scanning/smb_fingerprinter.py
- monkey/infection_monkey/network_scanning/ssh_fingerprinter.py
- monkey/infection_monkey/telemetry/base_telem.py
- monkey/infection_monkey/telemetry/telem_encoder.py
- monkey/tests/unit_tests/infection_monkey/master/mock_puppet.py
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ping_scanner.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ssh_fingerprinter.py
Uses OperatingSystems const in agent
Adds json encoder for telemetries to encode OperatingSystems enum values
> Tests can't be done as 1960 doesn't work either, due to incompatible config format
> 1960 use operating systems

- monkey/common/configuration/__init__.py
- monkey/common/configuration/agent_sub_configuration_schemas.py
- monkey/common/configuration/agent_sub_configurations.py
- monkey/common/configuration/default_agent_configuration.py
- monkey/infection_monkey/master/exploiter.py
- monkey/tests/unit_tests/common/configuration/test_agent_configuration.py
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
Fixes last task in #1960
Merge after #2043 
> 1960 ExploiterConfig to PluginConfig

- monkey/monkey_island/cc/repository/file_agent_configuration_repository.py
- monkey/monkey_island/cc/repository/i_agent_configuration_repository.py
- monkey/tests/monkey_island/in_memory_agent_configuration_repository.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_file_agent_configuration_repository.py
Adds `IAgentConfigurationRepository.reset_to_default()`
> 2036 reset repository

- monkey/monkey_island/cc/ui/src/components/ui-components/IslandResetModal.tsx
Modifies the UI to use the new reset endpoints
> Tested by clicking buttons in the UI and verifying functionality
> 2036 use new reset endpoints

- monkey/monkey_island/cc/resources/root.py
Fixes #2036 
A lot of the other logic will be removed in other PRs.
> Remove old logic for resetting config

- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/monkey_island/cc/repository/__init__.py
- monkey/monkey_island/cc/repository/file_repository_caching_decorator.py
- monkey/monkey_island/cc/repository/file_repository_locking_decorator.py
- monkey/monkey_island/cc/repository/file_repository_logging_decorator.py
- monkey/monkey_island/cc/repository/i_file_repository.py
- monkey/monkey_island/cc/repository/local_storage_file_repository.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_file_repository_caching_decorator.py
Adds decorators for `IFileRepository`
* Logging decorator
* Locking decorator
* Caching decorator
> Tested by switching the island's mode and verifying repository contents
> File repository decorators

- monkey/monkey_island/cc/services/representations.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_representations.py
Fixes inconvenience to manually jsonify data in same ways on flask responses
> Tested by previous and new unit tests
> Fix json representations

- monkey/monkey_island/cc/services/authentication_service.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_authentication_service.py
Reset the repository encryptor on registration, unlock it on login
> Tested authentication and registration
> 1965 reset repository encryptor

- monkey/monkey_island/cc/repository/mongo_credentials_repository.py
- monkey/monkey_island/cc/server_utils/encryption/repository_encryptor.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_credentials_repository.py
Encrypt credentials in `MongoCredentialsRepository`
> 1965 encrypt credentials

- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/components/ui-components/IslandResetModal.tsx
> Use DELETE /api/propagation-credentials/configured-credentials

- monkey/monkey_island/cc/resources/clear_simulation_data.py
- monkey/monkey_island/cc/services/repository_service.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_repository_service.py
Merge #2085 first.
Implement `RepositoryService.clear_simulation_data()`
> Repository service clear simulation data

- monkey/monkey_island/cc/resources/pba_file_upload.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_pba_file_upload.py
Merge #2085 first.
Remove` PBAFileUpload`'s dependency on `ConfigService`
> 1662 remove configservice from pba resource

- monkey/infection_monkey/credential_store/aggregating_credentials_store.py
- monkey/infection_monkey/i_control_channel.py
- monkey/infection_monkey/master/control_channel.py
- monkey/tests/unit_tests/infection_monkey/credential_store/test_aggregating_credentials_store.py
Modifies the `AggregatingCredentialsStore` to use the new Credentials objects returned by the API.
> Tested by running unit tests. Will delay further testing until #2092
> 2072 credentials store fix

- monkey/infection_monkey/master/control_channel.py
- monkey/monkey_island/cc/repository/mongo_credentials_repository.py
- monkey/monkey_island/cc/resources/propagation_credentials.py
- monkey/monkey_island/cc/ui/package.json
- monkey/monkey_island/cc/ui/src/components/configuration-components/CredentialsConfig.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/ExportConfigModal.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/PropagationConfig.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/ReformatHook.js
- monkey/monkey_island/cc/ui/src/components/configuration-components/UiSchema.js
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/components/report-components/credentialParsing.js
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/credentials.js
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/exploitation.js
- monkey/monkey_island/cc/ui/src/services/configuration/propagation/fingerprinterClasses.js
Fixes part of #1965 submit/reset.
> Tested by exploiting a machine 🥳
> 1965 credentials in config

- monkey/common/configuration/agent_configuration.py
- monkey/tests/unit_tests/common/configuration/test_agent_configuration.py
Adds `AgentConfiguration.to_mapping()`
> 2092 add agent configuration to mapping

- monkey/monkey_island/cc/ui/package-lock.json
- monkey/monkey_island/cc/ui/package.json
- monkey/monkey_island/cc/ui/src/components/configuration-components/CredentialsConfig.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/ExportConfigModal.tsx
- monkey/monkey_island/cc/ui/src/components/configuration-components/PropagationConfig.tsx
Bumps terser + does typescript error fixes
> Tested by building and checking the UI
> Terser upgrade + typescript fixes

- monkey/common/agent_configuration/agent_configuration.py
- monkey/common/agent_configuration/agent_sub_configuration_schemas.py
- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/common/agent_configuration/default_agent_configuration.py
- monkey/common/agent_configuration/utils.py
- monkey/common/utils/code_utils.py
- monkey/tests/unit_tests/common/configuration/test_agent_configuration.py
- vulture_allowlist.py
Freezes lists in configuration object  #2004
> 2004 freeze lists

- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/log_handlers/monkey_log.py
- envs/monkey_zoo/blackbox/log_handlers/test_logs_handler.py
- envs/monkey_zoo/blackbox/test_configurations/smb_pth.py
- envs/monkey_zoo/blackbox/test_configurations/test_configuration.py
- envs/monkey_zoo/blackbox/tests/exploitation.py
- monkey/monkey_island/cc/services/utils/node_states.py
> 2092 fix bb tests

- monkey/common/agent_configuration/agent_sub_configuration_schemas.py
- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/tests/unit_tests/common/configuration/test_agent_configuration.py
- vulture_allowlist.py
We may want to discuss the regex.
> UTs pass
> Custom PBA configuration validation

- monkey/common/agent_configuration/agent_sub_configurations.py
> NetworkScanConfiguration docstring

- monkey/common/agent_configuration/agent_sub_configurations.py
> PluginConfiguration docstring

- monkey/common/agent_configuration/agent_sub_configuration_schemas.py
- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/tests/unit_tests/common/configuration/test_agent_configuration.py
> TCPScanConfiguration docstring + validation

- monkey/common/agent_configuration/agent_sub_configuration_schemas.py
- monkey/common/agent_configuration/agent_sub_configurations.py
- monkey/tests/unit_tests/common/configuration/test_agent_configuration.py
> ExploitationOptionsConfiguration docstring + validation

- monkey/common/agent_configuration/agent_sub_configurations.py
> ExploitationConfiguration docstring

- monkey/common/agent_configuration/agent_configuration.py
- monkey/tests/unit_tests/common/configuration/test_agent_configuration.py
> AgentConfiguration docstring + validation

- monkey/monkey_island/cc/resources/propagation_credentials.py
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/monkey_island/cc/ui/src/components/ui-components/IslandResetModal.tsx
- monkey/tests/unit_tests/monkey_island/cc/resources/test_propagation_credentials.py
Fixes #2104 
> Running manual tests
> 2104 propagation credential endpoint

- envs/monkey_zoo/blackbox/analyzers/zerologon_analyzer.py
- envs/monkey_zoo/blackbox/conftest.py
- envs/monkey_zoo/blackbox/gcp_test_machine_list.py
- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_3_a.py
- envs/monkey_zoo/blackbox/test_configurations/powershell_credentials_reuse.py
- envs/monkey_zoo/blackbox/test_configurations/smb_pth.py
- envs/monkey_zoo/blackbox/test_configurations/utils.py
- envs/monkey_zoo/blackbox/test_configurations/wmi_mimikatz.py
- envs/monkey_zoo/blackbox/test_configurations/zerologon.py
- monkey/infection_monkey/exploit/zerologon.py
- monkey/infection_monkey/master/propagator.py
- monkey/monkey_island/cc/services/attack/technique_reports/technique_report_tools.py
- monkey/monkey_island/cc/services/representations.py
- monkey/monkey_island/cc/services/telemetry/processing/exploit.py
Fixes big part of #2092.
Depth 3
Depth 2
Depth 1
WMI and mimikatz exploiters
Zerologon
Powershell credentials reuse
SMB Pth
Final touch:
> 2092 bb tests

- CHANGELOG.md
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/version.py
- monkey/monkey_island/cc/resources/version_update.py
- monkey/monkey_island/cc/ui/src/components/logo/VersionComponent.js
> Rename VersionUpdate to Version

- monkey/monkey_island/cc/resources/auth/authenticate.py
> Remove unnecessary error in Authenticate

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/auth/authenticate.py
- monkey/monkey_island/cc/resources/auth/register.py
- monkey/monkey_island/cc/services/authentication_service.py
- monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_register.py
> Add docstrings to auth endpoints

- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- monkey/monkey_island/cc/resources/island_mode.py
- monkey/monkey_island/cc/ui/src/components/IslandHttpClient.tsx
- monkey/monkey_island/cc/ui/src/components/Main.tsx
- monkey/monkey_island/cc/ui/src/components/pages/LandingPage.tsx
- monkey/monkey_island/cc/ui/src/components/ui-components/IslandResetModal.tsx
- monkey/tests/unit_tests/monkey_island/cc/resources/test_island_mode.py
> 2106 remove mode keyword

- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/monkey_island/cc/deployment.py
- monkey/monkey_island/cc/version.py
- vulture_allowlist.py
Implement Version object. Related to #2109
> 2109 version object

- monkey/monkey_island/cc/resources/agent_configuration.py
- monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_configuration.py
Fixes #2071
Also adds an error message in the UI for when a configuration file with the wrong configuration schema is uploaded (see screenshot).
> Change POST to PUT in /api/agent-configuration

- monkey/common/version.py
- monkey/monkey_island/cc/resources/version.py
- monkey/monkey_island/cc/services/initialize.py
Adds `Version` to DI container. Related to #2109.
> 2109 add version object to di

- CHANGELOG.md
- monkey/monkey_island/cc/resources/version.py
- monkey/monkey_island/cc/ui/src/components/logo/VersionComponent.js
> 2109 auth island version

- CHANGELOG.md
- monkey/monkey_island/cc/__init__.py
- monkey/monkey_island/cc/resources/version.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/monkey_island/cc/ui/package-lock.json
- monkey/monkey_island/cc/ui/package.json
- monkey/monkey_island/cc/ui/src/components/logo/VersionComponent.js
- monkey/monkey_island/cc/version.py
Compare Version numbers in UI. Related to #2109.
> 2109 compare versions UI

- monkey/common/di_container.py
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/monkey_island/cc/resources/ip_addresses.py
- monkey/monkey_island/cc/resources/root.py
- monkey/monkey_island/cc/server_setup.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/monkey_island/cc/services/node.py
- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/services/run_local_monkey.py
- monkey/monkey_island/cc/services/utils/network_utils.py
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOnAWS/AWSRunOptions.js
- monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOptions.js
- monkey/tests/common/stub_di_container.py
Fixes #2108
The last commit is a workaround to get the tests passing for now. There's probably a better way to do it which I don't see right now.
> Refactor IPAddresses resource

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/auth/__init__.py
- monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_authenticate.py
- monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_register.py
- monkey/tests/unit_tests/monkey_island/cc/resources/auth/test_registration_status.py
- monkey/tests/unit_tests/monkey_island/cc/resources/conftest.py
> 2152 refactor auth resource

- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_configuration.py
> Island: Export AgentConfiguration resource from __init__

- CHANGELOG.md
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/monkey_island/cc/resources/pba_file_upload.py
- monkey/monkey_island/cc/ui/src/components/pages/ConfigurePage.js
- monkey/tests/unit_tests/monkey_island/cc/resources/test_pba_file_download.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_pba_file_upload.py
> 2154 refactor pba file upload

- monkey/infection_monkey/credential_repository/__init__.py
- monkey/infection_monkey/credential_repository/aggregating_propagation_credentials_repository.py
- monkey/infection_monkey/credential_repository/i_propagation_credentials_repository.py
- monkey/infection_monkey/credential_store/__init__.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/telemetry/messengers/credentials_intercepting_telemetry_messenger.py
- monkey/monkey_island/cc/services/representations.py
- monkey/tests/unit_tests/infection_monkey/credential_store/test_aggregating_propagation_credentials_repository.py
- monkey/tests/unit_tests/infection_monkey/telemetry/messengers/test_credentials_intercepting_telemetry_messenger.py
Fixes #2169
> Tested by running UT's and passing
> 2169 ICredentialStore renaming

- docs/config/production/config.toml
- docs/config/staging/config.toml
> Docs: Change baseURL for production and staging

- .github/ISSUE_TEMPLATE/config.yml
- README.md
- docs/content/FAQ/_index.md
- docs/content/_index.md
- docs/content/usage/_index.md
- docs/content/usage/file-checksums.md
- docs/content/usage/scenarios/custom-scenario/credential-leak.md
- docs/content/usage/scenarios/custom-scenario/network-breach.md
- docs/content/usage/scenarios/custom-scenario/network-segmentation.md
- monkey/infection_monkey/payload/ransomware/ransomware_readme.txt
- monkey/monkey_island/cc/ui/src/components/logo/LogoComponent.js
- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/AttackSection.tsx
- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/BreachSection.tsx
- monkey/monkey_island/cc/ui/src/components/report-components/ransomware/LateralMovement.tsx
- monkey/monkey_island/docs/source/index.rst
> 2146 replace guardicore links

- CHANGELOG.md
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/monkey_island/cc/resources/events.py
> 2155 events endpoint

- monkey/common/events/__init__.py
- monkey/common/events/credentials_stolen_events.py
- monkey/common/events/stolen_credentials_event.py
- vulture_allowlist.py
> 2176 define stolen credentials event

- monkey/infection_monkey/monkey.py
- vulture_allowlist.py
> Initialize IEventQueue

- monkey/infection_monkey/credential_repository/__init__.py
- monkey/infection_monkey/credential_repository/add_credentials_from_event.py
- monkey/infection_monkey/monkey.py
- monkey/tests/unit_tests/infection_monkey/credential_store/test_add_credentials_from_event.py
- vulture_allowlist.py
Fixes part of #2176 .
The name of the class comes from [PEP8](https://peps.python.org/pep-0008/). Any better names that don't include `subscriber` into it are good:
> 2176 stolen credentials subscriber

- monkey/monkey_island/cc/server_setup.py
- monkey/monkey_island/cc/services/initialize.py
Refactors pars of the Island boot process to separate concerns between collecting system information and initializing services/repositories/resources.
> Tested by starting the Island, logging in, downloading Island Log files
> Refactor island boot

- monkey/infection_monkey/exploit/HostExploiter.py
- monkey/infection_monkey/exploit/exploiter_wrapper.py
- monkey/infection_monkey/exploit/zerologon.py
- monkey/infection_monkey/monkey.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py
> 2176 modify zerologon to publish events

- build_scripts/appimage/appimage.sh
- build_scripts/docker/Dockerfile
> Build: Downgrade pipenv to use 2022.7.4

- vulture_allowlist.py
Fixes #2176 
Merge after all other PRs for #2176 are merged.
> Remove outdated Vulture allowlist entries

- monkey/common/event_serializers/__init__.py
- monkey/common/event_serializers/event_serializer_registry.py
- monkey/common/event_serializers/i_event_serialize.py
- monkey/tests/unit_tests/common/event_serializers/test_event_serializer_registry.py
- vulture_allowlist.py
> Event serializer

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/payload/ransomware/ransomware_builder.py
- monkey/infection_monkey/payload/ransomware/ransomware_payload.py
- monkey/tests/integration_tests/infection_monkey/payload/ransomware/test_integrated_ransomware.py
Addresses an issue with in which an exception is thrown in the ransomware integration tests when attempting to send telemetry.
Pass an ITelemetryMessenger to the ransomware builder, and mock in in the tests.
> Agent: Pass ITelemetryMessenger to Ransomware

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/payload/ransomware/ransomware_builder.py
- monkey/infection_monkey/telemetry/messengers/batching_telemetry_messenger.py
BatchingTelemetryMessenger failed to shutdown its thread, causing the agent to hang.
> Fix batching telemetry thread shutdown

- .pre-commit-config.yaml
Adds mypy to the pre-commit hooks.
> Project: Add mypy pre-commit check

- .pre-commit-config.yaml
Fixes #2122.
Adds ShellCheck to the pre-commit hooks.
> Tested by using the [gallery of bad code](https://github.com/koalaman/shellcheck#gallery-of-bad-code) to verify that bad code in shell scripts are caught
> 2122: Add ShellCheck to pre-commit hooks

- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/test_configurations/depth_1_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_2_a.py
- envs/monkey_zoo/blackbox/test_configurations/depth_3_a.py
- envs/monkey_zoo/blackbox/test_configurations/noop.py
- envs/monkey_zoo/blackbox/test_configurations/powershell_credentials_reuse.py
- envs/monkey_zoo/blackbox/test_configurations/smb_pth.py
- envs/monkey_zoo/blackbox/test_configurations/utils.py
- envs/monkey_zoo/blackbox/test_configurations/wmi_mimikatz.py
- envs/monkey_zoo/blackbox/test_configurations/zerologon.py
Fixes a part of #2217 
Merge after #2229 
> NOT tested yet. BB tests need to be run.
> Update BB tests' configurations' code

- monkey/infection_monkey/utils/commands.py
- monkey/tests/unit_tests/infection_monkey/utils/test_commands.py
Powershell unit tests fails but that will be address in other PR.
> 2216 modify agent build commands

- monkey/infection_monkey/master/control_channel.py
- monkey/monkey_island/cc/models/__init__.py
- monkey/monkey_island/cc/models/agent.py
- monkey/monkey_island/cc/repository/__init__.py
- monkey/monkey_island/cc/repository/i_agent_repository.py
- monkey/monkey_island/cc/repository/mongo_agent_repository.py
- monkey/tests/unit_tests/monkey_island/cc/models/test_agent.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_agent_repository.py
- vulture_allowlist.py
- Refactor/redefine `IAgentRepository`
- Add `AgentID` type alias
- Implement `MongoAgentRepository`
> Agent repository

- monkey/infection_monkey/exploit/HostExploiter.py
- monkey/infection_monkey/exploit/exploiter_wrapper.py
- monkey/infection_monkey/exploit/hadoop.py
- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/exploit/mssqlexec.py
- monkey/infection_monkey/exploit/powershell.py
- monkey/infection_monkey/exploit/smbexec.py
- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/exploit/web_rce.py
- monkey/infection_monkey/exploit/wmiexec.py
- monkey/infection_monkey/master/automated_master.py
- monkey/infection_monkey/master/exploiter.py
- monkey/infection_monkey/master/propagator.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/infection_monkey/exploit/test_powershell.py
- monkey/tests/unit_tests/infection_monkey/master/test_automated_master.py
- monkey/tests/unit_tests/infection_monkey/master/test_exploiter.py
- monkey/tests/unit_tests/infection_monkey/master/test_propagator.py
Fixes part of #2216..
> Tested by running agent locally and by running unit tests
> 2216 pass servers to exploiters

- envs/monkey_zoo/blackbox/test_configurations/noop.py
- envs/monkey_zoo/blackbox/test_configurations/utils.py
Fixes BB tests.
> Tested by BB tests and confirm correct configuration is being imported to the island
> 2217 fix bb tests

- monkey/infection_monkey/network/relay/relay_user_handler.py
- monkey/infection_monkey/network/relay/tcp_relay.py
- monkey/tests/unit_tests/infection_monkey/network/relay/test_relay_user_handler.py
Updates TCPRelay to wait for relay users to disconnect.
> Agent: Wait for relay users to disconnect

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/monkey_island/cc/models/__init__.py
- monkey/monkey_island/cc/models/simulation.py
- monkey/monkey_island/cc/repository/file_simulation_repository.py
- monkey/tests/monkey_island/in_memory_simulation_configuration.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_file_simulation_repository.py
> 2217 remove marshmallow

- monkey/infection_monkey/control.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/relay/__init__.py
- monkey/infection_monkey/network/relay/relay_connection_handler.py
- monkey/infection_monkey/network/relay/utils.py
- monkey/tests/unit_tests/infection_monkey/network/relay/test_relay_connection_handler.py
- monkey/tests/unit_tests/infection_monkey/network/relay/test_utils.py
- monkey/tests/unit_tests/infection_monkey/test_control.py
Paired with @shreyamalviya  on modifing the find_server to accept list of servers. 
> 2216 modify controlclient find server

- monkey/monkey_island/cc/resources/clear_simulation_data.py
- monkey/monkey_island/cc/setup/island_event_handlers.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_clear_simulation_data.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_reset_agent_configuration.py
- vulture_allowlist.py
Fixes part of #2234 
Refactors ClearSimulationData
Merge after #2276
> Tested by running locally and inspecting logs to see that all of the expected functions are called
> 2234 refactor clear simulation data

- monkey/common/event_serializers/__init__.py
- monkey/common/event_serializers/i_event_serialize.py
- monkey/common/event_serializers/pydantic_event_serializer.py
- monkey/tests/unit_tests/common/event_serializers/test_pydantic_event_serializer.py
- vulture_allowlist.py
> 2179 implement pydantic event serializer

- monkey/monkey_island/cc/models/node.py
- monkey/monkey_island/cc/repository/__init__.py
- monkey/monkey_island/cc/repository/i_node_repository.py
- monkey/monkey_island/cc/repository/mongo_agent_repository.py
- monkey/monkey_island/cc/repository/mongo_credentials_repository.py
- monkey/monkey_island/cc/repository/mongo_machine_repository.py
- monkey/monkey_island/cc/repository/mongo_node_repository.py
- monkey/tests/unit_tests/monkey_island/cc/models/test_node.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_node_repository.py
- vulture_allowlist.py
> 2255 mongo node repository

- monkey/monkey_island/cc/repository/__init__.py
- monkey/monkey_island/cc/repository/i_event_repository.py
- vulture_allowlist.py
> Island: Add IEventRepository

- monkey/monkey_island/cc/resources/events.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_events.py
> Island: Refactor api/events to publish list of events

- monkey/monkey_island/cc/agent_event_subscribers/__init__.py
- monkey/monkey_island/cc/agent_event_subscribers/save_event_to_event_repository.py
- monkey/monkey_island/cc/repository/__init__.py
- monkey/monkey_island/cc/repository/stubbed_event_repository.py
- monkey/monkey_island/cc/server_setup.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/monkey_island/cc/setup/__init__.py
- monkey/monkey_island/cc/setup/agent_event_handlers.py
- vulture_allowlist.py
Fixes part of #2180.
Merge after #2180 `MongoEventRepository` is implemented and registered
> 2180 save event to repository

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
> Lock cryptography and bcrypt

- envs/monkey_zoo/blackbox/gcp_test_machine_list.py
- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/test_configurations/__init__.py
- envs/monkey_zoo/blackbox/test_configurations/depth_4_a.py
- envs/monkey_zoo/docs/fullDocs.md
Fix BB tests!
> Tested by running AppImage BB tests
> Fix bb tests

- monkey/monkey_island/cc/repository/__init__.py
- monkey/monkey_island/cc/repository/mongo_agent_event_repository.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_agent_event_repository.py
- vulture_allowlist.py
Rename MongoEventRepository -> MongoAgentEventRepository
> Rename mongo event repository

- envs/monkey_zoo/blackbox/analyzers/zerologon_analyzer.py
- monkey/monkey_island/cc/agent_event_handlers/save_stolen_credentials_to_repository.py
Fixes Zerologon BB test.
> Tested by running BB tests
> Fix zerologon

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/relay/utils.py
- monkey/tests/unit_tests/infection_monkey/network/relay/test_utils.py
Fixes `find_server` task from #2292 .
> Tested by unit tests and local run
> Agent: Modify find_server to use IslandApiClient

- monkey/monkey_island/cc/server_setup.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/monkey_island/cc/setup/island_event_handlers.py
Fixes #2294
> UTs pass + manually tested that the reset functions are called when the CLEAR_SIMULATION_DATA event is published
> Clear repositories on CLEAR_SIMULATION_DATA event

- monkey/infection_monkey/exploit/__init__.py
- monkey/infection_monkey/exploit/caching_agent_binary_repository.py
- monkey/infection_monkey/exploit/i_agent_binary_repository.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/island_api_client/i_island_api_client.py
- monkey/infection_monkey/monkey.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
> HTTPIslandAPIClient in CachingAgentBinaryRepository

- monkey/infection_monkey/agent_event_forwarder.py
- monkey/infection_monkey/island_api_client/__init__.py
- monkey/infection_monkey/island_api_client/abstract_island_api_client_factory.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/island_api_client/i_island_api_client.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/relay/utils.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/network/relay/test_utils.py
- monkey/tests/unit_tests/infection_monkey/test_agent_event_forwarder.py
Fixes part of #2292.
It will need rebase when we merge #2319
> Tested by running UTs,
> 2292 modify agent forwarder

- monkey/infection_monkey/i_control_channel.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/island_api_client/i_island_api_client.py
- monkey/infection_monkey/master/control_channel.py
- monkey/infection_monkey/monkey.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/master/test_control_channel.py
Fixes #2292.
Moves functionality from `ControlClient` to `HTTPIslandAPIClient`.
> 2292 control channel client api client

- envs/monkey_zoo/blackbox/gcp_test_machine_list.py
- envs/monkey_zoo/blackbox/test_blackbox.py
- envs/monkey_zoo/blackbox/test_configurations/__init__.py
- envs/monkey_zoo/blackbox/test_configurations/credential_reuse_ssh_key.py
- envs/monkey_zoo/blackbox/test_configurations/credentials_reuse_ssh_key.py
- envs/monkey_zoo/docs/fullDocs.md
- envs/monkey_zoo/terraform/images.tf
- envs/monkey_zoo/terraform/monkey_zoo.tf
Fixes #2181 .
> Tested by running EtE
> 2181 credential reuse ete

- monkey/monkey_island/cc/ui/src/components/ui-components/AdvancedMultiSelect.js
Fixes #2290 .
https://user-images.githubusercontent.com/15820737/191537433-4cd0cece-9c5e-44ce-9b63-0731629259f0.mov
> UI: Get derived state from props in AdvancedMultiSelect

- monkey/monkey_island/cc/services/agent_signals_service.py
- monkey/tests/unit_tests/monkey_island/cc/services/test_agent_signals_service.py
Implement `AgentSignalsService.get_signals()`
Issue #2261
> Island: Implement AgentSignalsService.get_signals()

- monkey/common/network/network_utils.py
- monkey/infection_monkey/control.py
- monkey/infection_monkey/monkey.py
- monkey/monkey_island/cc/models/monkey.py
- monkey/monkey_island/cc/server_setup.py
- monkey/monkey_island/cc/services/node.py
- monkey/monkey_island/cc/services/reporting/report.py
> Agent, Island: Rename get_my_ip_address to legacy

- monkey/infection_monkey/Pipfile
- monkey/infection_monkey/Pipfile.lock
- monkey/infection_monkey/i_puppet/i_puppet.py
- monkey/infection_monkey/master/ip_scanner.py
- monkey/infection_monkey/master/propagator.py
- monkey/infection_monkey/network/relay/utils.py
- monkey/infection_monkey/network_scanning/scan_target_generator.py
- monkey/infection_monkey/network_scanning/tcp_scanner.py
- monkey/infection_monkey/payload/ransomware/ransomware.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/infection_monkey/telemetry/file_encryption_telem.py
- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/tests/integration_tests/infection_monkey/payload/ransomware/test_integrated_ransomware.py
- monkey/tests/unit_tests/infection_monkey/network/relay/test_relay_connection_handler.py
- monkey/tests/unit_tests/infection_monkey/network/relay/test_relay_user_handler.py
- monkey/tests/unit_tests/infection_monkey/network/relay/test_sockets_pipe.py
- monkey/tests/unit_tests/infection_monkey/telemetry/test_exploit_telem.py
Fixes #2260 
> Did a smoke test with built agent to make sure that removed __init__ file didn't cause any build issues
> 2260 more mypy fixes

- monkey/common/network/network_utils.py
Add `get_my_ip_addresses() -> Sequence[IPv4Address]`
#2325
> Common: Add get_my_ip_addresses() -> Sequence[IPv4Address]

- monkey/common/types.py
- vulture_allowlist.py
> Common: Add SocketAddress type

- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/island_api_client/i_island_api_client.py
- monkey/infection_monkey/master/control_channel.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
- monkey/tests/unit_tests/infection_monkey/master/test_control_channel.py
> 2261 modify agent to use signals

- monkey/infection_monkey/monkey.py
Fixes part of #2325.
Updates monkey.py to use `get_my_ip_address()`
> Agent: Use get_my_ip_address() to build master

- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/relay/tcp_pipe_spawner.py
- monkey/infection_monkey/network/relay/tcp_relay.py
- monkey/infection_monkey/network/relay/utils.py
- vulture_allowlist.py
Fixes a part of #2323 
> UTs pass
> SocketAddress in TCPRelay

- monkey/common/agent_registration_data.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/relay/utils.py
- monkey/monkey_island/cc/island_event_handlers/handle_agent_registration.py
- monkey/monkey_island/cc/models/agent.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
- monkey/tests/unit_tests/monkey_island/cc/island_event_handlers/test_handle_agent_registration.py
- monkey/tests/unit_tests/monkey_island/cc/models/test_agent.py
- monkey/tests/unit_tests/monkey_island/cc/models/test_agent_registration_message.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_agent_repository.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agents.py
Fixes a part of #2323 
> UTs pass
> SocketAddress in AgentRegistrationData

- monkey/monkey_island/cc/models/agent.py
- monkey/tests/unit_tests/monkey_island/cc/models/test_agent.py
> Island: Remove `log_contents` from Agent model

- CHANGELOG.md
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/monkey_island/cc/resources/agent_logs.py
- monkey/monkey_island/cc/resources/agent_signals/agent_signals.py
- monkey/tests/monkey_island/__init__.py
- monkey/tests/monkey_island/in_memory_agent_log_repository.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_logs.py
> 2274 implement new agent logs endpoint

- monkey/infection_monkey/control.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/infection_monkey/island_api_client/i_island_api_client.py
- monkey/infection_monkey/monkey.py
- monkey/tests/unit_tests/infection_monkey/island_api_client/test_http_island_api_client.py
Fixes a part of #2274 
Merge after the third task of #2274 is done so that nothing breaks
> UTs pass
> Use new agent logs endpoint

- monkey/common/agent_events/abstract_agent_event.py
- monkey/common/agent_events/ping_scan_event.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network_scanning/ping_scanner.py
- monkey/infection_monkey/puppet/puppet.py
- monkey/tests/unit_tests/common/agent_events/test_ping_scan_event.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_ping_scanner.py
- monkey/tests/unit_tests/infection_monkey/puppet/test_puppet.py
Fixes part of #2268 .
Fixes #2361.
> 2268 modify ping scanner with agent queue

- monkey/common/agent_events/__init__.py
- monkey/common/agent_events/tcp_scan_event.py
- monkey/common/types.py
- monkey/tests/unit_tests/common/agent_events/test_tcp_scan_event.py
- vulture_allowlist.py
Adds TCPScanEvent.
Issue #2267
> 2267 tcp scan event

- monkey/infection_monkey/network_scanning/tcp_scanner.py
- monkey/tests/unit_tests/infection_monkey/network_scanning/test_tcp_scanner.py
> Publish TCPScanEvent

- CHANGELOG.md
- monkey/monkey_island/cc/repository/i_agent_repository.py
- monkey/monkey_island/cc/repository/mongo_agent_repository.py
- monkey/monkey_island/cc/resources/agents.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_agent_repository.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agents.py
- Adds `IAgentRepository.get_agents()`
- Adds `GET /api/agents`
Issue #2362
> Smoke tested the island
> 2362 get agents

- CHANGELOG.md
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/repository/i_machine_repository.py
- monkey/monkey_island/cc/repository/mongo_machine_repository.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/monkey_island/cc/resources/machines.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_machine_repository.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_machines.py
- monkey/tests/unit_tests/monkey_island/conftest.py
Fixes part of #2362.
Adds the `/api/machines` endpoint
> 2362 add machines endpoint

- monkey/common/agent_event_serializers/register.py
- monkey/infection_monkey/agent_event_forwarder.py
- monkey/monkey_island/cc/models/machine.py
- monkey/monkey_island/cc/repository/i_machine_repository.py
- monkey/monkey_island/cc/repository/mongo_machine_repository.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
- monkey/monkey_island/cc/ui/src/components/report-components/common/RenderArrays.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/ScannedServers.js
- monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_machine_repository.py
- monkey/tests/unit_tests/monkey_island/cc/services/reporting/test_report.py
Fixes part of #2268.
Updates reporting to use the repositories when building the scan list.
> 2268 update reporting

- monkey/common/agent_event_serializers/__init__.py
- monkey/common/agent_event_serializers/i_agent_event_serializer.py
- monkey/common/agent_event_serializers/pydantic_agent_event_serializer.py
- monkey/common/types.py
- monkey/infection_monkey/island_api_client/http_island_api_client.py
- monkey/monkey_island/cc/repository/agent_event_encryption.py
Move `JSONSerializable` to `common.types`
> Tested by running BB tests
> Common: Move JSONSerializable to common.types

- monkey/common/agent_events/__init__.py
- monkey/common/agent_events/exploitation_event.py
- monkey/common/agent_events/propagation_event.py
- monkey/common/agent_events/tcp_scan_event.py
- monkey/tests/unit_tests/common/agent_events/test_exploitation_event.py
- monkey/tests/unit_tests/common/agent_events/test_propagation_event.py
- vulture_allowlist.py
> 2269 exploitation event

- monkey/common/agent_events/__init__.py
- monkey/common/agent_events/password_restoration_event.py
- monkey/tests/unit_tests/common/agent_events/test_password_restoration_event.py
- vulture_allowlist.py
> 2269 password restoration event

- monkey/infection_monkey/exploit/sshexec.py
- monkey/infection_monkey/network/tools.py
Update sshexec exploiter to publish propagation and exploitation events.
> 2269 publish events from sshexec exploiter

- monkey/infection_monkey/exploit/log4shell.py
- monkey/infection_monkey/utils/commands.py
Update log4shell exploiter to publish propagation and exploitation events.
> 2269 publish events from log4shell exploiter

- monkey/monkey_island/cc/agent_event_handlers/scan_event_handler.py
- monkey/monkey_island/cc/models/node.py
- monkey/monkey_island/cc/repository/i_node_repository.py
- monkey/monkey_island/cc/repository/mongo_node_repository.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_scan_event_handler.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_node_repository.py
Adds TCP connections to the Node model #2267
> Tested by UT's
> 2267 add tcp connections

- monkey/infection_monkey/exploit/hadoop.py
Update Hadoop exploiter to publish propagation and exploitation events.
> 2269 publish events from hadoop exploiter

- monkey/infection_monkey/exploit/wmiexec.py
> 2269 publish events from wmi

- CHANGELOG.md
- monkey/monkey_island/cc/resources/agent_events.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_events.py
> GET api/agent-events

- envs/monkey_zoo/blackbox/analyzers/zerologon_analyzer.py
- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
Fixes #2405 .
> Tested by running zerologon BB test
> 2405 modify zerologon analyzer

- monkey/monkey_island/cc/agent_event_handlers/scan_event_handler.py
- monkey/monkey_island/cc/models/machine.py
- monkey/monkey_island/cc/models/node.py
- monkey/monkey_island/cc/models/report/report_dal.py
- monkey/monkey_island/cc/repository/i_machine_repository.py
- monkey/monkey_island/cc/repository/i_node_repository.py
- monkey/monkey_island/cc/repository/mongo_machine_repository.py
- monkey/monkey_island/cc/repository/mongo_node_repository.py
- monkey/monkey_island/cc/repository/utils.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_scan_event_handler.py
- monkey/tests/unit_tests/monkey_island/cc/models/test_utils.py
- monkey/tests/unit_tests/monkey_island/cc/repository/test_mongo_machine_repository.py
> 2267 add services to machine

- monkey/monkey_island/cc/agent_event_handlers/__init__.py
- monkey/monkey_island/cc/agent_event_handlers/update_agent_shutdown_status.py
- monkey/monkey_island/cc/setup/agent_event_handlers.py
- monkey/tests/monkey_island/__init__.py
- monkey/tests/monkey_island/in_memory_agent_repository.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_update_agent_shutdown_status.py
> AgentShutdownEvent in Island

- monkey/monkey_island/cc/agent_event_handlers/__init__.py
- monkey/monkey_island/cc/agent_event_handlers/update_nodes_on_exploitation.py
- monkey/monkey_island/cc/setup/agent_event_handlers.py
- monkey/tests/unit_tests/monkey_island/cc/agent_event_handlers/test_update_nodes_on_exploitation.py
Adds a subscriber that updates the nodes on exploit events
#2269
> Tested by running a simple simulation and verifying the contents of the database
> 2269 handle exploitation events

- CHANGELOG.md
- monkey/monkey_island/cc/resources/node.py
- monkey/monkey_island/cc/ui/src/components/report-components/security/ScannedServers.js
- vulture_allowlist.py
Fixes service display in UI #2267
> Tested by running manually
> 2267 add service reporting

- monkey/monkey_island/cc/ui/src/components/configuration-components/ReformatHook.js
Fixes #2329
> Tested by playing with the Island
https://user-images.githubusercontent.com/44770317/195370479-ec33ce22-95e3-43ef-ba84-1b82f0937347.mp4
> Bugfix: erase credentials on configuration reset in UI

- envs/monkey_zoo/blackbox/test_configurations/zerologon.py
- monkey/infection_monkey/monkey.py
- monkey/infection_monkey/network/relay/utils.py
Fixes #2369
Fixes #2371
> Tested by running blackbox tests
> 2369 fix depth 2 test

- envs/monkey_zoo/blackbox/island_client/monkey_island_requests.py
Before this commit, the BB tests reauthenticated before every single request. Now, the token is only refreshed when its close to expiring.
Fixes # 2383
> Tested by running BB tests
> BB: Cache the JWT token

- CHANGELOG.md
- monkey/monkey_island/cc/app.py
- monkey/monkey_island/cc/resources/__init__.py
- monkey/monkey_island/cc/resources/nodes.py
- monkey/tests/monkey_island/__init__.py
- monkey/tests/monkey_island/in_memory_node_repository.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_nodes.py
- vulture_allowlist.py
> 2334 get nodes endpoint

- CHANGELOG.md
- monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
> Remove Node Map from the Security Report

- monkey/monkey_island/cc/resources/agent_events.py
- monkey/tests/unit_tests/monkey_island/cc/resources/test_agent_events.py
Add filtering to `/api/agent-events` endpoint.
Resolves #2429 
> Tested by running `curl` with filter parameters
> 2429 event filtering

- monkey/common/network/segmentation_utils.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/monkey_island/cc/services/reporting/report.py
- monkey/monkey_island/cc/ui/src/components/report-components/security/issues/CrossSegmentIssue.js
- monkey/tests/unit_tests/common/network/test_segmentation_utils.py
Updates the cross-segmentation report sections to use the repositories.
> ![Screen Shot 2022-10-13 at 2 54 35 PM](https://user-images.githubusercontent.com/11077625/195682541-d8d1364b-e6ce-40a5-99da-6a3190219955.jpg)
Observe the Segmentation Issues section exists:
Observe that expanding the Segmentation Issues items gives more detailed information:
> ![Screen Shot 2022-10-13 at 2 53 44 PM](https://user-images.githubusercontent.com/11077625/195682729-369201a2-1ab6-49ea-9d34-ec85f0bd724c.jpg)
> 2269 use repositories for cross segmentation issues

- monkey/common/base_models.py
- monkey/monkey_island/cc/services/initialize.py
- monkey/monkey_island/cc/services/reporting/report.py
- Fixes a 500 when report is called, but no agents were ran
- Improve pydantic logging to show erroneous fields in the model
> Tested by going to the report page without running any agents
> Fix bugs in report

- monkey/monkey_island/cc/ui/src/components/IslandHttpClient.tsx
- monkey/monkey_island/cc/ui/src/components/Main.tsx
- monkey/monkey_island/cc/ui/src/components/pages/ReportPage.js
- monkey/monkey_island/cc/ui/src/components/report-components/security/ScannedServers.js
- monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx
Fixes infrastructure of UI code that will be required for #2334 to fetch all map nodes.
> Tested manually
> 2334 infrastructure

- CHANGELOG.md
- monkey/monkey_island/cc/services/node.py
- monkey/monkey_island/cc/ui/src/components/map/preview-pane/PreviewPane.js
Fixes a part of #2430 
> Tested by checking the preview pane in the UI
> Remove stuff from preview pane

- monkey/monkey_island/cc/ui/src/components/IslandHttpClient.tsx
- monkey/monkey_island/cc/ui/src/components/Main.tsx
- monkey/monkey_island/cc/ui/src/components/map/MapPageWrapper.tsx
- monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx
Fetches data from the back end for  #2334
> Tested by viewing the UI, seeing the console logs
> 2334 map page wrapper

- monkey/monkey_island/Pipfile
- monkey/monkey_island/Pipfile.lock
- monkey/monkey_island/cc/resources/root.py
Fixes the run of the blackbox tests.
> Tested by running jenkins and confirming that blackbox tests run
> Fix run of blackbox tests

- envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
- envs/monkey_zoo/blackbox/log_handlers/monkey_logs_downloader.py
- monkey/monkey_island/cc/resources/agent_logs.py
Fixes #2386 
> Tested by running bb tests
> 2386 handle empty logs in bb
